### ISSUE TITLE
Several modules use mcrypt which was removed from PHP 7.2.x

### ISSUE THREAD

**Issue by notbasetwo** [boxbilling/boxbilling#1010]
mcrypt was removed in PHP 7.2.x, this project uses it in several places. These are mostly in libraries from other people and most of these have been updated as the code for each of these is quite old.

**Spamchecker**
src/bb-modules/Spamchecker/recaptchalib.php 

This is likely as this library (recaptchalib) in this repo is from 2007 and is super out of date. 

This has been updated since, but I think an update would require more than just a drop in replacement. 

https://github.com/google/recaptcha

**OpenSRS**
src/bb-library/Registrar/includes/opensrs/openSRS_crypt.php uses mcrypt;

This is likely as the OpenSRS module has not been updated since at least 2013, as this was removed from the official OpenSRS toolkit.

There is likely a stopgap to make this work with newer versions of PHP (they did remove this dependency in 2013) -- but they have significantly updated their "PHP toolkit" since then, so in the future looking at migrating the module entirely to the new thing may be on the cards.

https://github.com/OpenSRS/osrs-toolkit-php

**Comment by BenNottelling** [comment]
> This is likely as this library (recaptchalib) in this repo is from 2007 and is super out of date.
> 
> This has been updated since, but I think an update would require more than just a drop in replacement.

Yeah, looking at it, I think it may be recaptcha v1, and there is v3 now


The OpenSRS says it needs PEAR which as far as I can tell is totally abandoned these days, do you know if that's a "requirement" for an easy install?

**Comment by notbasetwo** [comment]
> > This is likely as this library (recaptchalib) in this repo is from 2007 and is super out of date.
> > This has been updated since, but I think an update would require more than just a drop in replacement.
> 
> Yeah, looking at it, I think it may be recaptcha v1, and there is v3 now
> 
> The OpenSRS says it needs PEAR which as far as I can tell is totally abandoned these days, do you know if that's a "requirement" for an easy install?

I don't think it is.

**Comment by notbasetwo** [comment]
@BenNottelling May it be easier to remove the OpenSRS lib as I can't see them being used by any registrar adapters? 

If we decide to add the adapter in the future, we can just add the library with composer.

**Comment by notbasetwo** [comment]
Closed in favour of #1013.
