### ISSUE TITLE
Installation Documentation is confusing; would like some clarification please

### ISSUE THREAD

**Issue by partridge420x** [boxbilling/boxbilling#1028]
### What happened?

The installation guide is rather lacking in specific detail on where to put things.
Ive been trying for the better of 6 hours and haven't gotten anywhere

Ive tried installing it several different ways all with a 404 error while trying to access the web installer

### BoxBilling Version

v4.22-beta.1

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment]
Where you put things are kinda up to you and where you want it.
It's pretty straightforward, assuming you uploaded it to the root of your server, you should only have to go to https://example.com/install/index.php

**Comment by partridge420x** [comment]
i have uploaded it to var/www/billing

**Comment by partridge420x** [comment]
![image](https://user-images.githubusercontent.com/26298829/132774212-344bf5f7-83f7-4ccf-8651-19fd38876655.png)

**Comment by partridge420x** [comment]
![image](https://user-images.githubusercontent.com/26298829/132774272-5cb53f9d-bbb0-4aab-91e5-ddad136631df.png)

**Comment by timothygwebb** [comment]
Your install path is invalid should be boxbilling/install/install.php or boxbilling/src/install/install.php

**Comment by partridge420x** [comment]
Changed everything to boxbilling (installed with zip & ftp and not source) Still file not found

**Comment by partridge420x** [comment]
if anyone has possibly 5-10 minutes and would like to help me out on a call,
You can reach me on discord here: Chronic-Reflexes#9251

**Comment by BenNottelling** [comment]
You did ~~var/www/billing~~  not ~~var/www/public_html/billing~~?

Also, it doesn't matter what the folder is named.. as long as you are trying to access the right what. Timothy meant something else, but it wasn't the most obvious

**Comment by partridge420x** [comment]
public_html was nonexistant
ill try making it and sticking it there. Will report back what happens

**Comment by partridge420x** [comment]
Still apparently is doing the same thing after moving to public_html
also restarted nginx

**Comment by BenNottelling** [comment]
Do you have experience with webservers? I suspect you haven't configured it correctly or don't fully understand what you're doing

**Comment by partridge420x** [comment]
not exactly but ive been learning as im going, My colleague has more experience than i do but this even has his hands up in the air as he attempted it and gave up. I continued along with trying to get it going

**Comment by timothygwebb** [comment]
Thanks @BenNottelling you're guidance is in the right direction. For me to assist further I will need to know more about your nginx setup and what your webserver configuration is and whether or not you're running a reverse proxy with apache.

**Comment by partridge420x** [comment]
for what its worth i was able to get my other webserver going just fine:
http://status.midnighthostingsolutions.com

we are not running a reverse proxy to my knowledge, And nothing really changed from default settings

**Comment by BenNottelling** [comment]
Okay, so walking you through it step by step is way more work than I personally am willing to do, if someone else wants to they can. 

If you aren't already using a control panel, I would reinstall your server with one so you don't have to configure everything via command line. It's much simpler, more straightforward, and you're less likely to miss configure something.

I personally like [CWP](https://control-webpanel.com/) and can tell you BoxBilling works well with it.

**Comment by partridge420x** [comment]
@timothygwebb Ive put my discord contact info above if you'd like to reach out, It would end up being alot less time spent

I dont think i'll be running a control panel with it as thats a bunch more setup and learning i have to wrap my head around. Though ill possibly look at it in the future

**Comment by BenNottelling** [comment]
> I dont think i'll be running a control panel with it as thats a bunch more setup and learning i have to wrap my head around. Though ill possibly look at it in the future

Trust me, a control panel would be way way easier than what you're doing.
Especially once you consider SSL (auto renewal, configuration, ect), firewall, user management, account limits, integration into billing (with some control panels, BoxBilling will automatically create the hosting order by using your control panel's API and set it up for you), and much much more.

For only a test environment doing everything manually is fine, but in the past I have manually done it that way as well and as soon as I tried a control panel I realized it was dumb to not use one from the start.

Getting it setup requires the bare minimum that you would need to know in order to run a hosting company anyways.

You do you, imo not using a control panel is a mistake.

**Comment by partridge420x** [comment]
@timothygwebb helped me out with the issue, he went through quite a bit to get it started Thank you guys so much
Ill honesly look into getting the control panel at a later time, ive been learning for a couple months now and ive gotten somewhere with my knowledge, even if its little in comparison. Anyway thank you guys again i cant thank you enough
