### ISSUE TITLE
[Bug] Invalid period code. Period definition must be 2 chars length

### ISSUE THREAD

**Issue by givinghawk** [boxbilling/boxbilling#1037]
### What happened?

I am getting this error and its driving me crazy!

An exception has been thrown during the rendering of a template ("Invalid period code. Period definition must be 2 chars length").

i am running on php 7.3

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment]
Sounds like this may be related to themeing, please include what theme you are using and the page the error is happening

**Comment by givinghawk** [comment]
i am using darkly on bootstrap

**Comment by givinghawk** [comment]
its happening on the cart page

**Comment by givinghawk** [comment]
i can purchace anything else and get no error

**Comment by BenNottelling** [comment]
Okay, is this happening on the actual cart page, or is it happening when you go to pay for the purchase?
 Thanks

**Comment by givinghawk** [comment]
it is happening when you go to the cart page to pay for it

**Comment by givinghawk** [comment]
i found a way to get arround it! you have to use the membership extention/plugin
