### ISSUE TITLE
[Bug] When you delete a account when someone is logged in they cannot login

### ISSUE THREAD

**Issue by givinghawk** [boxbilling/boxbilling#1042]
### What happened?

Please describe the problem
i accidentally added a client myself and loged into that account and i now cannot login

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by givinghawk** [comment]
im getting the model not found error

**Comment by evrifaessa** [comment]
Please leave a comment when you close an issue. It helps us understand the problem better.

**Comment by givinghawk** [comment]
it works if you press on a account "view as client"

**Comment by BenNottelling** [comment]
So this is caused by BB caching that you're logged in via cookies, clear the cookies & cache for your website and it'll go away
