### ISSUE TITLE
[Question] Where are form submissons held?

### ISSUE THREAD

**Issue by givinghawk** [boxbilling/boxbilling#1043]
I need to get the info from the forms that people have submitted when ordering, where are they stored or where can i view them?

**Comment by BenNottelling** [comment]
Is this the form extension, or something else?

**Comment by givinghawk** [comment]
No, it is the built in form builder for every product

**Comment by 0x6b-dev** [comment]
Hi @givinghawk,
Best place to ask questions about Box Billing is on our [Discord Channel](https://boxbilling.org/discord).
If you have any bug or feature requests they can be made here on the Github repo.
Please close this task.

**Comment by givinghawk** [comment]
> Hi @givinghawk,
> Best place to ask questions about Box Billing is on our [Discord Channel](https://boxbilling.org/discord).
> If you have any bug or feature requests they can be made here on the Github repo.
> Please close this task.

I am I the discord, and I asked this question almost a year ago now...
