### ISSUE TITLE
[Feature Request] Add Namesilo

### ISSUE THREAD

**Issue by rjsurjo** [boxbilling/boxbilling#1049]
### What is the idea?

Feature request Please Add Namesilo Domain Register for all Namesilo Reseller

### Why would this be beneficial

Benefits

**Comment by givinghawk** [comment]
namesilo is allready added. you just need the extention

**Comment by evrifaessa** [comment]
There is an old adapter here: https://github.com/boxbilling/extensions/blob/master/bb-library/Registrar/Adapter/Namesilo.php
I'm not sure if it's still working.

If not, BoxBilling is extensible and everyone can bring support for external services by coding domain adapters for them. I don't think we'll be able to create and maintain all of the requested services with a small team and no help from the community.

So if you are interested, feel free to write your own adapter. And we'd be glad if you share it with the community. Thanks for your interest.
