### ISSUE TITLE
Add Referrals System

### ISSUE THREAD

**Issue by rjsurjo** [boxbilling/boxbilling#1050]
### What is the idea?

Please Add Referrals System

### Why would this be beneficial

Benefits

**Comment by evrifaessa** [comment]
I don't think we should include this as a core feature. It can be achieved by extensions, and I'd prefer a community-maintained extension instead.

**Comment by givinghawk** [comment]
i do have to agree with you evrifaessa, it would be a good extention, and it would be a very good way for people to get involved with sharing someones web store. but sould be a extention
