### ISSUE TITLE
[Feature Request] More Extensions.

### ISSUE THREAD

**Issue by TSFComputers** [boxbilling/boxbilling#1058]
### What is the idea?

Feature request BoxBilling use to have Affiliate extensions.

https://github.com/boxbilling/extensions/tree/243bc3be9184497189387a20f00d3f1d36735b19

As you can see here, this would be nice.

### Why would this be beneficial

Benefits Everyone

**Comment by evrifaessa** [comment]
I don't think we should maintain the affiliate extension. In my personal opinion we can even drop so many existing extensions in the extension repository and let interested community members adopt the useful ones and maintain them in the future.

We're already working hard on the core. I just don't think the volunteering team is big enough to maintain all those extensions. Same goes for most of the server managers except cPanel and Plesk. They can be maintained externally by other volunteering teams in the community.

So I'm going to close this issue if nobody replies in a few days. Thanks for your interest.
