### ISSUE TITLE
[Bug] Invoice download PDF Error

### ISSUE THREAD

**Issue by sittiphong** [boxbilling/boxbilling#1087]
### What happened?

Hi,
I see bug in billing system, After click Download PDF

![invoice-1](https://user-images.githubusercontent.com/34829333/138025019-2738442e-fbff-4109-9442-ce63630d6559.png)

Error code
![invoice-2](https://user-images.githubusercontent.com/34829333/138025022-c1ea80fc-e3b8-475b-87b8-6aff0ee811cc.png)

Do you have any solution ?

Thanks.

### BoxBilling Version

v4.22-beta.1

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment]
Thanks for the bug report. We have already fixed this issue in the master branch version of BoxBilling. Please see these changes if you want to manually update:
https://github.com/boxbilling/boxbilling/pull/927 and https://github.com/boxbilling/boxbilling/commit/b61ab381b82976cd56a8c8820c58bb606562c6d9#diff-78ac039cfe6da7ed25f18b3935e30b416c50f51cc844e261c65faa5e7c4fa98b
