### ISSUE TITLE
No page is working [Bug] 

### ISSUE THREAD

**Issue by lynkproject** [boxbilling/boxbilling#1105]
### What happened?

Hello, I have set up a fresh install of Boxbilling with a fresh mySQL Database.
Everything installed and when I wanted to go to the Admin Panel, it gave me an 404 error. So I tested out. Every button on the start page (https://lynkproject.org/customer) doesn't work and redirects to an 404 error.

Can anyone help me?

Kind regards

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment]
@lynkproject Did you resolve this issue?
If not, could you please verify that you have the .htaccess in the root BoxBilling folder
https://raw.githubusercontent.com/boxbilling/boxbilling/master/src/.htaccess
Thanks!

**Comment by evrifaessa** [comment]
No response, both links unreachable. It should work once you have the .htaccess available in the folder. Feel free to re-open if you have anything to add.
