### ISSUE TITLE
[Task] Release v4.22.0-beta.2

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#1113]
### What is the task

Currently, these issues seem to be the only problems that blocks the new preview release:

- [ ] #965
- [ ] #983
- [ ] #624 (not necessary, can be solved with a further preview release)

**Comment by BenNottelling** [comment]
There is also the milestone I created:
https://github.com/boxbilling/boxbilling/milestone/4

**Comment by evrifaessa** [comment]
Closing this issue in favor of the new **"release blocker"** label.
