### ISSUE TITLE
[Bug] ERROR CODE: 42000

### ISSUE THREAD

**Issue by ptnhan91** [boxbilling/boxbilling#1131]
### What happened?

My website was installed and working fine few days ago. However today I visit this page again and it says error and I don't know what to do to fix it. Please help me!
I tried opening debug I noticed the problem was reported that PDO error.
And, I tried a fresh install of boxbilling on a brand new site and when I got to the step of declaring the database it stopped there and gave me an error, even though the declared information was correct!
Pictures are attached below!

ERROR
ERROR CODE: 42000
SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation

Look for detailed error explanation

Powered by BoxBilling

IMAGE
https://i.postimg.cc/zfyNGLCz/box-2.jpg
https://i.postimg.cc/4dtTpr2j/box1.jpg
https://i.postimg.cc/1zmgCK1W/box3.jpg

### BoxBilling Version

v4.22-beta.1

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment]
It looks like you may not have the required permissions given to the DB user

**Comment by ptnhan91** [comment]
I have allowed all access rights for this database user.
Before that the website was running and one day it suddenly came up with an error, I don't know where it originated!

https://i.postimg.cc/wBtZBQL1/box6.jpg

**Comment by evrifaessa** [comment]
MariaDB or MySQL?

**Comment by BenNottelling** [comment]
@ptnhan91 Would you mind trying the latest release please?

**Comment by evrifaessa** [comment]
@ptnhan91

**Comment by RuddyPalmar** [comment]
I have the same problem, does anyone have a solution?

recently I have transferred a website from my previous hosting provider and before everything worked fine, but after the transfer to new hosting one of the software (Boxbilling) began to give me this error

ERROR CODE: 42000
SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation

the created user of database has all the privileges and all the permissions, but it still gives me that error

it seems that there is some kind of problem with the version or configuration of mySql

i dont know

does anyone have a solution?

**Comment by evrifaessa** [comment]
fix will be published with the next release.

meanwhile, you can also patch your existing installation: https://github.com/boxbilling/boxbilling/issues/1181#issuecomment-1026900063
