### ISSUE TITLE
[Feature Request] GoGetSSL module

### ISSUE THREAD

**Issue by vlad-evg** [boxbilling/boxbilling#1132]
### What is the idea?

Feature request. Dear BoxBilling! Some of our customers requesting the reseller module between GoGetSSL and Boxbilling, we will be happy to discuss that. Please contact us via partners@gogetssl.com

### Why would this be beneficial

Benefits

**Comment by evrifaessa** [comment]
Feel free to join us over [Discord](https://boxbilling.org/discord) or [Slack](https://boxbilling.org/slack).

We -maintainers- don't have access to any e-mail accounts under the boxbilling.org domain, and I don't really want to use my personal e-mail for anything unrelated.
