### ISSUE TITLE
[Bug] Bootstrap theme will be broken until you save settings for the first time

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#1139]
### What happened?

Bootstrap theme will be blank if you don't save theme settings (bb-admin/theme/bootstrap) for the first time.

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

PHP 7.4.3 on Ubuntu 20.04.3 LTS x86_64 Server

**Comment by GoudronViande24** [comment]
BTW, this also happened to me on v4.22-beta.1 version, not only in master.

**Comment by BenNottelling** [comment]
Will be fixed in the next minor release.
