### ISSUE TITLE
[Bug] cURL error with Plesk add-on

### ISSUE THREAD

**Issue by GoudronViande24** [boxbilling/boxbilling#1141]
### What happened?

Here is the error:
`cURL error: 6 - Could not resolve host:`

I get this when clicking "Test connection" button. I can access the plesk with the IP and the domain provided.
Using the latest maintenance release, where it says that it has been fixed.

### BoxBilling Version

v4.22-beta.1

### What version of PHP are you running?

PHP 7.4

**Comment by BenNottelling** [comment]
Are you able to create server or do anything else besides the test connection?
It _is_ possible that that function is broken. 

I'm not the one who fixed the plesk issue, so I don't have first hand experience

**Comment by GoudronViande24** [comment]
The same error happens when trying to create a hosting

**Comment by BenNottelling** [comment]
Strange, After further investigation, there seems to be a problem with the "host" and all the other data not being set

**Comment by BenNottelling** [comment]
@GoudronViande24 Please try this version and let me know if there are any remain problems.
I don't have a plex server, but can confirm the problem with the variable being empty is resolved

https://raw.githubusercontent.com/boxbilling/boxbilling/master/src/bb-library/Server/Manager/Plesk.php

**Comment by GoudronViande24** [comment]
Ok so I finished the testing:
The error message on test connection is now : `Plesk error: - `
And when trying to activate a hosting: `Plesk error: 1023 - cObject::update() failed: Some fields are empty or contain an improper value. ('state' = 'Québec') Errors : state`
I guess that the second one is because of the accent in "Québec"

**Comment by BenNottelling** [comment]
> And when trying to activate a hosting: `Plesk error: 1023 - cObject::update() failed: Some fields are empty or contain an improper value. ('state' = 'Québec') Errors : state`
> I guess that the second one is because of the accent in "Québec"

Does it work if you are manually creating the account?

**Comment by GoudronViande24** [comment]
This error message is from manually creating the account.
The automatic creation didn't work, I believe it's because of this error message.

**Comment by BenNottelling** [comment]
@GoudronViande24 sorry I should have specified, I meant creating the account from within plesk instead of BB.
I'm assuming it'll work, but want to verify

**Comment by GoudronViande24** [comment]
Oh sorry I didn't understand I thought manually creating with the button in BB. 

I can create accounts in Plesk, I will check if they link automatically but I think it will give an error because the account already exists.
