### ISSUE TITLE
[Bug] Could not connect to database

### ISSUE THREAD

**Issue by juamartinuk** [boxbilling/boxbilling#1150]
### What happened?

Could not connect to database. Please check database details. You might need to create database first. I get that error when entering my base data but it is correct, is there anything I don't need to know?

### BoxBilling Version

v4.21

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by evrifaessa** [comment]
Can you try with the latest version? v4.21 is an old version.

**Comment by BenNottelling** [comment]
You also may want to try giving full database permissions if you haven't already

**Comment by evrifaessa** [comment]
No response for over 2 weeks. Feel free to re-open the issue if you have anything to add.
