### ISSUE TITLE
[Bug] Registration Page Showing 404 Not Found Error

### ISSUE THREAD

**Issue by nilshinde29** [boxbilling/boxbilling#1165]
### What happened?

Hi,
I am testiing boxbilling on my subdomain, installed it successfully, but getting error when I am opening "REGISTER" from Home Page.

Please guide.

Thanks,
Nilesh
![BoxBilling-Error-01](https://user-images.githubusercontent.com/96096503/145924901-0377894e-774b-42b7-b36b-2a792829b3cd.jpg)
![BoxBilling-Error-02](https://user-images.githubusercontent.com/96096503/145924907-2f8496c9-a85a-4f3d-b27c-ac165fc5182f.jpg)

### BoxBilling Version

v4.21

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by mirosat** [comment]
Do you have version **4.21** installed or **4.22.1.2**?
If you do have the latest version did you rename the **useme.htaccess** to **.htaccess** ?

**Comment by nilshinde29** [comment]
Thanks for your reply,
I am using the latest version downloaded from BoxBilling website.
Now I changed the useme.htaccess to .htaccess & its now working.

THANKS FOR YOUR HELP!

Regards
Nilesh
