### ISSUE TITLE
[Feature Request] Payment freekassa

### ISSUE THREAD

**Issue by Ruszona** [boxbilling/boxbilling#1168]
### What is the idea?

Hello. Please add https://docs.freekassa.ru/

### Why would this be beneficial

To conveniently pay for the client

**Comment by evrifaessa** [comment]
Not going to happen.

**Comment by Ruszona** [comment]
> Not going to happen.

why?

**Comment by evrifaessa** [comment]
> > Not going to happen.
> 
> why?

There are hundreds of payment gateways, we can't really implement and maintain all of them. You're free to write implementations for your favorite gateway, but we probably won't provide official support for all of them.
