### ISSUE TITLE
[Bug] The Link for boxbilling extensions from within the boxbilling admin panel directs to a non existant page

### ISSUE THREAD

**Issue by Digitalbil** [boxbilling/boxbilling#1169]
### What happened?

While I am logged in the bb-admin area I tried to "explore BoxBilling extensions" takes me to a non existant web page. I m not sure if it would be better for it to redirect to the github page since that might be a bit confusing. I could create the page for you if i could get a list of the extensions along with a link for each one. I think that would be more helpful so we could optionally include a summary for each extension. I could have it done within a day if that helps. I think if you just link people to github it will just end up making more support tickets and result in people not knowing what to do with the extensions from github. I can be reached via email at bill@billlennox.me. I know you guys have been looking for more help and i really like the product so i would like to contribute if possible. 

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by GoudronViande24** [comment]
Since the revival of this project, there is no extension list or anything like that (that I'm aware of).

**Comment by BenNottelling** [comment]
There's no extension page / store at the moment, and no real plan to implement one either.
https://github.com/boxbilling/extensions

This is this list of extensions which you can try, though
