### ISSUE TITLE
Integration with wordpress

### ISSUE THREAD

**Issue by Chaitanya-3137** [boxbilling/boxbilling#1171]
Hii EveryOne,

I want to integrate boxbilling with wordpress can you please help me? I am using boxbilling for the first time.
and i don't know much about it so please.

Thanks and Regards 
Chaitanya Prakash.

**Comment by GoudronViande24** [comment]
Boxbilling must be installed separately. If your Wordpress is in `yourdomain.com` root, you could install boxbilling to a subdomain like `bb.yourdomain.com`. To integrate BoxBilling with Wordpress, you can add the links of the services or produtcs to a page or the menu in your Wordpress site.

**Comment by knightrideruk** [comment]
Hi
I think what Chaitanya is trying to say is how can you use WordPress themes, in a word I can't see as you can at present. Linking is OK but just as a major problem try using a mobile with any of the supplied BoxBilling themes!
Unless if anyone knows how to do it
Regards
Knightrideruk

out of the darkness come light..............

**Comment by 0x6b-dev** [comment]
Hi @Chaitanya-3137.
Best place to ask for help would be on the [Discord server](https://boxbilling.org/discord).
If you have any bug reports or feature requests feel free to open another issue, but this issue will be closed now.
