### ISSUE TITLE
[Bug] Unknown "sameas" test

### ISSUE THREAD

**Issue by MiracleGame** [boxbilling/boxbilling#1172]
### What happened?

Hello!
Please help me with this error, I'm stuck on this error for a day.
For the error's debug details:
https://pastebin.com/Wcpe8yia
For the screenshot:
<img src="https://cdn.discordapp.com/attachments/747473495247552644/923546068585676820/Screen_Shot_2021-12-23_at_8.02.11_PM.png">

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Nothing

**Comment by evrifaessa** [comment]
[How to Write a Bug Report that Will Make Your Developers Happy](https://marker.io/blog/write-bug-report)

Can you provide some steps to reproduce?

**Comment by MaybeELEMENT** [comment]
> [How to Write a Bug Report that Will Make Your Developers Happy](https://marker.io/blog/write-bug-report)
> 
> Can you provide some steps to reproduce?
Hello, im ELEMENT. I changed my account bcuz in on phone rn.
So, what i did is just press the order now button:
![Screenshot_20211223_232521.jpg](https://user-images.githubusercontent.com/66505831/147260670-90f2d2b9-e4f6-4c90-8e94-06ab97cde08d.jpg)

**Comment by evrifaessa** [comment]
This is not an officially supported theme and the issue seems to be caused by it. We don't maintain the theme and you'll have to ask it's developer for support.
