### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RudiBott** [boxbilling/boxbilling#1175]
### What happened?

![image](https://user-images.githubusercontent.com/73558202/147851394-b2c1459e-a439-4118-b96f-eb7e48ee247c.png)
hello i got this error after login in to my boxbilling after 5month, how to fix that?

### BoxBilling Version

v4.21

### What version of PHP are you running?

PHP 8.1

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment]
Is it possible that your SQl user lost permission to the DB?

**Comment by 0x6b-dev** [comment]
@evrifaessa stale, please close.
