### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by elixon01** [boxbilling/boxbilling#1177]
### What is the idea?

Feature request   hola abran un modulo de pago de boxbilling para latioamerica que sea mas comun y facil de usar como payu latam o mercando pago . epayco,,  instapago

hello open a boxbilling payment module for Latin America that is more common and easy to use as  ::   payu latam..  mercando pago ...  . epayco...  instapago....

### Why would this be beneficial

Benefits

Feature request   hola abran un modulo de pago de boxbilling para latioamerica que sea mas comun y facil de usar como payu latam o mercando pago . epayco,,  instapago

hello open a boxbilling payment module for Latin America that is more common and easy to use as  ::   payu latam..  mercando pago ...  . epayco...  instapago....

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
