### ISSUE TITLE
Change language not working

### ISSUE THREAD

**Issue by loisl** [boxbilling/boxbilling#118]
Hi,

I installed the lastest version 2.3.29
I have "bb-local/de_DE" + "bb-local/en_US"
I can also select both in the client area, but text is in English!
# locale -a

C
de_DE
de_DE.iso88591
deutsch
german
POSIX
# apt-get install php-gettext

messages.po
[...]
"X-Poedit-Language: Deutsch\n"
"X-Poedit-Country: Germany\n"
"X-Poedit-SourceCharset: utf-8\n"

msgid "Error"
msgstr "Fehler"

msgid "Dashboard"
msgstr "Dashboard"

msgid "Shopping cart"
msgstr "Warenkorb"

msgid "Profile"
msgstr "Profile"

msgid "Sign out"
msgstr "Abmelden"
[...]

**Comment by pierreozoux** [comment]
Ok, I feel stupid now, I can't manage neither :/

Do you have a command for us to run in order to debug this issue?

**Comment by adeshjohnson** [comment]
Hello. I am using Centos 6. I downloaded the files from Transifex, opened them with Poedit and created the .mo file too, and finally uploaded them (.mo and .po files) to ... /bb-locale/es_ES/LC_MESSAGES/ folder. The two languages are appearing in the admin panel (en_US and es_ES), but spanish translation seems not to be working (not translated). I have gettext installed and locale -a shows es_ES. What do I need to do? I have searched a lot in Google and didn't find a solution for this. Please help me. This may help others too.

**Comment by Komputronik** [comment]
I installed the BoxBilling version 4.2 in Windows 7, then make Indonesian translation in .\bb-locale\id_ID (follow instructions in docs), but when I switch to new language, words in client's dashboard still in English , could you give me some advice? Thanks.
