### ISSUE TITLE
[Feature Request] Demo Hosted on FossHost

### ISSUE THREAD

**Issue by callowaysutton** [boxbilling/boxbilling#1180]
### What is the idea?

Hey would it be possible to setup a demo with FossHost? You guys meet all the criteria for getting setup and it would be completely free

### Why would this be beneficial

Shows a demo to the general public

**Comment by neocentric17** [comment]
Hello BB team.  I would like to contribute to this project.  I can start by donating hosting for a demo install.  I can code too, except i am swamped at the moment

**Comment by evrifaessa** [comment]
Thanks for the suggestions. We already have received a lot of offers from the community regarding this, and are also considering to possibly go with FOSSHost when we get the demo module ready.

**Comment by evrifaessa** [comment]
duplicate of #662.
