### ISSUE TITLE
[Bug] ERROR CODE: 42000 SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied;

### ISSUE THREAD

**Issue by RuddyPalmar** [boxbilling/boxbilling#1181]
### What happened?

Recently I have transferred a website with Boxbilling from my previous hosting provider and before everything worked fine, but after the transfer to new hosting the software (Boxbilling) began to give me this error

ERROR CODE: 42000
SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation

the created user of database has all the privileges and all the permissions, but it still gives me that error

it seems that there is some kind of problem with the version or configuration of mySql
i dont know

I have activated debugging in the configuration file "bb-config.php" and I get all these errors

ERROR
ERROR CODE: 42000
SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation

Set BB_DEBUG to FALSE, to hide the message below
Class: "PDOException"

File: "/home/vendopa1/public_html/control/bb-di.php"
Line: "70"

Trace: #0 /home/vendopa1/public_html/control/bb-di.php(70): PDO->exec('SET CHARACTER_S...') #1 /home/vendopa1/public_html/control/bb-vendor/pimple/pimple/src/Pimple/Container.php(122): {closure}(Object(Box_Di)) #2 /home/vendopa1/public_html/control/bb-di.php(126): Pimple\Container->offsetGet('pdo') #3 /home/vendopa1/public_html/control/bb-vendor/pimple/pimple/src/Pimple/Container.php(122): {closure}(Object(Box_Di)) #4 /home/vendopa1/public_html/control/bb-library/Box/Authorization.php(22): Pimple\Container->offsetGet('session') #5 /home/vendopa1/public_html/control/bb-di.php(140): Box_Authorization->__construct(Object(Box_Di)) #6 /home/vendopa1/public_html/control/bb-vendor/pimple/pimple/src/Pimple/Container.php(122): {closure}(Object(Box_Di)) #7 /home/vendopa1/public_html/control/bb-modules/Index/Controller/Admin.php(48): Pimple\Container->offsetGet('auth') #8 [internal function]: Box\Mod\Index\Controller\Admin->get_index(Object(Box_AppAdmin)) #9 /home/vendopa1/public_html/control/bb-library/Box/App.php(199): ReflectionMethod->invokeArgs(Object(Box\Mod\Index\Controller\Admin), Array) #10 /home/vendopa1/public_html/control/bb-library/Box/App.php(249): Box_App->executeShared('Box\\Mod\\Index\\C...', 'get_index', Array) #11 /home/vendopa1/public_html/control/bb-library/Box/App.php(143): Box_App->processRequest() #12 /home/vendopa1/public_html/control/index.php(27): Box_App->run() #13 {main}

does anyone have a solution?

Thanks!

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Boxbilling version:: 4.22 Beta. 1.3
CPANEL PHP: 7.4

Database server:
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 8.0.27 - MySQL Community Server - GPL
Protocol version: 10
Server character set: UTF-8 Unicode (utf8mb4)

Web server:
cpsrvd 11.100.0.5
Database client version: libmysql - 5.6.43
extensión PHP: mysqli - cur - mbstring 

phpMyAdmin: 4.9.7

Versión de PHP: 7.3.33

**Comment by evrifaessa** [comment]
Thanks for reaching out. MySQL documentation states this for the `character_set_database` variable:

"As of MySQL 8.0.14, setting the session value of this system variable is a restricted operation. The session user must have privileges sufficient to set restricted session variables. See Section 5.1.9.1, “System Variable Privileges”."

We've used that before in the install script and the database manager, given the variable is deprecated, expected to be removed soon and causes trouble with MySQL 8.0.14+, I've removed the part of the code that interacts with the value.

I don't know if we'll make a release soon but until then you can manually make these changes on your system:

`install/install.php`: https://github.com/boxbilling/boxbilling/commit/628de31312b1426661f5c5877f4250692d7528c0

`bb-di.php`: https://github.com/boxbilling/boxbilling/commit/98826597e71629f3d698322fd0050929f262dfd1

**Comment by evrifaessa** [comment]
I'd also be glad if you could confirm whether this fixed the issue or not. Have a nice day.

**Comment by RuddyPalmar** [comment]
> I'd also be glad if you could confirm whether this fixed the issue or not. Have a nice day.

Yes, confirmed, I have solved with your recommendation.

thanks!
