### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by fraque** [boxbilling/boxbilling#1187]
### What is the idea?

Feature request: it would be great a client could contract my services to recover their debts... and transfer to me those debtors.

So that would demand a CLIENT AREA and a DEBTOR AREA (one account receivables for each one debtor as it is - and an account total for the CLIENT to keep up with the recovery evolution of each debtor...

a CLIENT in this process can transfer one debtor or several - each debtor would be an PROCESS with his internal ID

So when a client register in the site and acept the contract he has to be capable to create one or several processes for each debtor he transfers...

FOR THE OTHER HAND in after sales

Managing all porfolio of debtors should have the possibility to name the person who would take care of the process or to follow the evolution. If the debtor pays freely after notification CASE CLOSE/MILESTONE

Otherwise should have a map of no paying debtor for other strategy...

### Why would this be beneficial

Benefits: today with this pandemic situation all the corporations has a lot of debtor to recover... that would be huge to help the corporations.

**Comment by 0x6b-dev** [comment]
Hi @fraque, appreciate the feature request.
I can't say this won't be implemented at some point. But development assistance would be welcome if you have any skills.

**Comment by DJTerrum** [comment]
Unless I'm misunderstanding the feature request, this does not seem relevant to BoxBilling or any billing panel for that matter. Surely, a serious co-operation that wants to handle debt/debtors properly would use a completely dedicated system to their billing software that can manage debts and/or debtors separately.

The most I think BoxBilling should be able to do is mark an invoice as 'collection' or something similar, for staff members to then investigate accordingly.

**Comment by jaapmarcus** [comment]
@DJTerrum  Agree this should be inside Boxbilling.

**Comment by fraque** [comment]
Hi guys

Thanks for at least you kindly answer my request.

Unfortunelly i don't have any developments skills... i only do collections for my corporation

Anything else i can help
Fraque
Em 18/05/2022, 06:31 +0100, Jaap Marcus ***@***.***>, escreveu:
