### ISSUE TITLE
Automatic update bug regarding permissions.

### ISSUE THREAD

**Issue by timothygwebb** [boxbilling/boxbilling#1194]
### What happened?

![image](https://user-images.githubusercontent.com/16106877/151479374-20af4096-f781-480d-bbb6-93f7e737a0f2.png)

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 8.0

### Additional Notes

php -v
PHP 8.0.8 (cli) (built: Oct 26 2021 11:42:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies

**Comment by BenNottelling** [comment]
Most likely, you used composer under a different user than the PHP extraction is being run under and it therefore doesn't have permission to override it

**Comment by 0x6b-dev** [comment]
@evrifaessa close please (stale).
