### ISSUE TITLE
User question

### ISSUE THREAD

**Issue by sjpals** [boxbilling/boxbilling#1198]
Hi,

I'm sorry this is a user question, not an issue, but I didn't know where else to ask it. If there is somewhere else better and more appropriate, please point me in the right direction.

First of all, just to say thanks to all you wonderful people who make boxbilling happen! I am not overly techy, but have installed boxbilling, hooked it up with the API for namesilo and whm and it works beautifully, so thanks! I just have a question though....

I buy domains. If I want to sell a domain that I already own in namesilo, it would be great for it to stay registered with me. Instead of 'transferring' a domain to someone and to their registra, I could just give them the account details. How do I get a domain that I already own to 'appear' in an account in boxbilling? 

Thanks in advance for your help.

**Comment by quicklyweb** [comment]
You could simply add the domain to that client account as a transfer order in boxbilling without activating it. In the future, hopefully we should have an option to change ownership of an account between boxbilling accounts. Untill then manual work needed. 
As an alternative to above solution; you could also change the owner of the domain in mysql by using phpmyadmin or any other tool.

**Comment by ehimare369** [comment]
Hi, I really want to thank the BoxBilling team for their wonderful work. I didn't want to create another issue for a user question, so I decieded to ask mine under this comment.
I would love to know if there is a paystack payment gateway for boxbilling. Please help me out in fixing it, so that I can accept payment from my customers through paystack.
Thanks

**Comment by sjpals** [comment]
> You could simply add the domain to that client account as a transfer order in boxbilling without activating it. In the future, hopefully we should have an option to change ownership of an account between boxbilling accounts. Untill then manual work needed. As an alternative to above solution; you could also change the owner of the domain in mysql by using phpmyadmin or any other tool.

Hi Quickly, thanks so much for the reply. I was avoiding the transfer in, but I think that may be the best way to do it (and then delete the invoice). Im so not techy it didnt even twig there was an sql database!! I sometimes go in the wordpress one to change usernames and passwords when there are problems. Anyway, I have two test clients in boxbilling and one I bought a domain with. I went into the database (through myphp), looked at the user numbers of my test users and then went into orders and changed the user id. Works perfectly!! Which means I can transfer them all into one test account and when (hopefully) I sell them, I can set up a new client account and just change the user ID. THANK YOU SO MUCH!!
