### ISSUE TITLE
[Task] 

### ISSUE THREAD

**Issue by 4kplayeee** [boxbilling/boxbilling#1202]
### What is the task

[Enter task here](https://github.com/istiak101/boxbilling-quick-installer)

### Additional Notes

[Additional notes](https://github.com/istiak101/boxbilling-quick-installer)

**Comment by evrifaessa** [comment]
uh?

**Comment by evrifaessa** [comment]
> The link 

yeah...? and what's the task here?

**Comment by timothygwebb** [comment]
@evrifaessa @4kplayeee From my review of this Task I can only assume a couple of things. This task is either an individual trying to inform us that they have been able to create a bash shell script to install boxbilling with using lighthttpd as the server and could possibly be needing some assistance with it or is wanting us to incorporate into our product the ability to script an install kind of like what webmin has done using the install.sh script for  their product virtualmin. which can be found here https://github.com/virtualmin/virtualmin-install/blob/master/virtualmin-install.sh as an example. @4kplayeee please inform on whether or not you are asking for assistance here or other wise please give a clear directive. If no response is given I will close this with an additional follow up of no response closing task with comment. Thanks.

**Comment by 0x6b-dev** [comment]
@evrifaessa close please.
