### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by leedsrhinos** [boxbilling/boxbilling#1210]
### What happened?

Hey guys 
New to the chat and boxbilling.
Bit of a problem have downloaded up-to-date version think it was 16 Feb this year
I upload everything as stated get the install screens get to the database section fill it in click ok were it states it will take a while but cannot get to finished screen ?
Nothing happens when I click ok it creates 63 rows in database I've looked but it will not go to finish screen and all links it emails me revert back to the files I have uploaded.
Thanks

### BoxBilling Version

v4.22-beta.1

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by evrifaessa** [comment]
Can you provide more details? What's your MySQL version? Do the dependency checks pass in the first step?

**Comment by leedsrhinos** [comment]
hi getting there with instalation
i uploade all files to mydomain/user 
all good now and everything installed 
now i got the instalation done email with login details 
email said Access client area at mydomain/user 
This is what i get
![Clipboard01](https://user-images.githubusercontent.com/100451638/155855539-ecf0faad-7e91-4c5f-bbc8-b95530009be5.jpg)
any ideas?
thanks

**Comment by leedsrhinos** [comment]
For some unknown reason it's fine now 
Admin login I get this
![Screenshot_20220226-213311](https://user-images.githubusercontent.com/100451638/155859990-c377f34b-fed8-407f-8cda-5bec0dfed9ef.png)
How I update thought it was the new version.
How I set Cron what ever this is ?
Thanks
