### ISSUE TITLE
Help on setup

### ISSUE THREAD

**Issue by leedsrhinos** [boxbilling/boxbilling#1215]
Evening all setting up boxbilling and have a problem with logo 
Hear is the default images the logo is broke 
And URL link is there nothing changed yet as this is boxbilling standard logo from download installed files.
Any advice 

![Screenshot_20220301-231658](https://user-images.githubusercontent.com/100451638/156265650-98695f88-9b15-4741-9123-50f0235b532e.png)
![Screenshot_20220301-231529](https://user-images.githubusercontent.com/100451638/156265653-886058ee-4155-4fe2-af84-c3d77666c090.png)

**Comment by leedsrhinos** [comment]
Anyone ?

**Comment by samapraku** [comment]
Right click on the logo and use Inspect Element menu option to check the src of the logo. That will show you whether you have the correct link to the image
