### ISSUE TITLE
[Bug]  Paypal

### ISSUE THREAD

**Issue by leedsrhinos** [boxbilling/boxbilling#1232]
### What happened?

PayPal error 

### BoxBilling Version

v4.21

### What version of PHP are you running?

PHP 7.4

### Additional Notes

When a customer go to pay invoice via PayPal they get this image attached 
![Screenshot_20220322-143254](https://user-images.githubusercontent.com/100451638/159506976-1ed0fa4a-4aff-47e6-9bef-22bdf8cd630f.png)
My email is correct and plugin is enabled
Thanks in advance

**Comment by iiEpic** [comment]
This is also an issue for me, was working until recently. Nothing on my end was changed.

Using the below:
Version: BoxBilling 4.22.1.4
PHP: 8.0

**Comment by jqshuv** [comment]
> 

Could this be a error on side of PayPal?

**Comment by 0x6b-dev** [comment]
@evrifaessa stale, please close.
