### ISSUE TITLE
Issues with BoxBilling

### ISSUE THREAD

**Issue by chippytech** [boxbilling/boxbilling#1233]
ERROR
ERROR CODE: 1045
SQLSTATE[HY000] [1045] Access denied for user 'foo'@'127.0.0.1' (using password: YES)

**Comment by SlimJUC** [comment]
Thats not an issue with BoxBilling

there is an issue with your SQL connection.

make sure user/pass for SQL user is correct and that it has the required permissions

**Comment by 0x6b-dev** [comment]
@evrifaessa close.
