### ISSUE TITLE
I Updated BoxBillig Automatic, or Manual or Fresh Install from 4.22.1.4 it keeps saying "4.22.1.4 is available for download" is this a bug?

### ISSUE THREAD

**Issue by joejac** [boxbilling/boxbilling#1235]
Hello
I Updated BoxBilling: Automatic 3 times, then I did Manual Update, then I did a Fresh New Install, all from 4.22.1.4 and its zip, and in all the updates it keeps saying "4.22.1.4 is available for download", and the **footer** shows:
"**BoxBilling 4.22.1.3**" But I downloaded **4.22.1.4** from this link:
https://github.com/boxbilling/boxbilling/releases/download/4.22.1.4/BoxBilling.zip
This is very frustrating, now I have to configure BoxBilling again and I am not sure if this is a bug or what.
Can someone please check what is going on before I begin again with the data input, if /**4.22.1.4/BoxBilling.zip** is corrupted or what?
Thanks

**Comment by BenNottelling** [comment]
Looks like I forgot to update the version within BB with that last release
Just updated the zip to fix that now
