### ISSUE TITLE
[Bug] SQL[42000] 1044 - Access denied for user

### ISSUE THREAD

**Issue by tritonblaster** [boxbilling/boxbilling#1238]
### What happened?

This error occurs during the 3rd step.
After Database has been created this error occurs.
BoxBilling 4.22.1.4 & BoxBilling 4.22.1

![image](https://user-images.githubusercontent.com/6197076/160263487-77f6f1c0-5c9e-4181-b6e3-0621d5aea818.png)

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by andpavlenko** [comment]
Duplicate #1233. Look [reply](https://github.com/boxbilling/boxbilling/issues/1233#issuecomment-1079396670).

**Comment by tritonblaster** [comment]
Hello @andpavlenko ,

thank you for your reply, but it does not help.
Can you specify where the sql problem may occur?

Let me try to share you some more details:

1) user web_itraum_dev has mysql root priviledges
2) the application is hosted on a vm with ip 172.16.0.80
3) 2nd step creates the database boxbilling
4) 3rd step asks for confirmation to start database-manipulation
![image](https://user-images.githubusercontent.com/6197076/160298686-aa9641c0-ce47-46e7-9ffa-bff0e5ea4268.png)
5) shortly after confirming the previous message the error message is alerted
![image](https://user-images.githubusercontent.com/6197076/160298725-5607a11f-70c8-4d15-b0ac-d4d2cf7a73b2.png)
6) When I retry to run step 3 a new message is alerted: table already exists (I don't think this is caused because of connection problems...)
![image](https://user-images.githubusercontent.com/6197076/160298772-706cf502-9085-4ac9-8026-42339cb2edf1.png)

Here a mysql query from host where the application is hosted
![image](https://user-images.githubusercontent.com/6197076/160298887-96cde7bd-dba5-419a-93da-3e63429969f4.png)

Please tell me where I can check whats wrong with my database.

BR

**Comment by BenNottelling** [comment]
Please make sure you're using the latest release https://github.com/boxbilling/boxbilling/releases/tag/4.22.1.4
Then ensure your user has full permissions to the DB
Then completely empty the DB and try again

**Comment by tritonblaster** [comment]
> Please make sure you're using the latest release https://github.com/boxbilling/boxbilling/releases/tag/4.22.1.4
![image](https://user-images.githubusercontent.com/6197076/160299661-a6f91f10-ed18-43c2-b752-856ef1a7627c.png)

> Then ensure your user has full permissions to the DB
`GRANT Alter ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Create ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Create view ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Delete ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Drop ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Index ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Insert ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT References ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Select ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Show view ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Trigger ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Update ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Alter routine ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Create routine ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Create temporary tables ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Execute ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Lock tables ON *.* TO 'web_itraum_dev'@'172.16.0.80';
GRANT Grant option ON *.* TO 'web_itraum_dev'@'172.16.0.80';`

> Then completely empty the DB and try again
one of the previous grants fixed the problem - Thanks

@BenNottelling can you tell me which of the previous grant are necessary for productive run?
I would love to use least privileges that are necessary

**Comment by BenNottelling** [comment]
> > Please make sure you're using the latest release https://github.com/boxbilling/boxbilling/releases/tag/4.22.1.4
> > ![image](https://user-images.githubusercontent.com/6197076/160299661-a6f91f10-ed18-43c2-b752-856ef1a7627c.png)
> 
> > Then ensure your user has full permissions to the DB
> > `GRANT Alter ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Create ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Create view ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Delete ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Drop ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Index ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Insert ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT References ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Select ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Show view ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Trigger ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Update ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Alter routine ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Create routine ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Create temporary tables ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Execute ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Lock tables ON *.* TO 'web_itraum_dev'@'172.16.0.80'; GRANT Grant option ON *.* TO 'web_itraum_dev'@'172.16.0.80';`
> 
> > Then completely empty the DB and try again
> > one of the previous grants fixed the problem - Thanks
> 
> @BenNottelling can you tell me which of the previous grant are necessary for productive run? I would love to use least privileges that are necessary

I am sorry to say that I don't know
