### ISSUE TITLE
[Task] Update composer package stability

### ISSUE THREAD

**Issue by andpavlenko** [boxbilling/boxbilling#1239]
### What is the task

Please update composer packages stability to stable as default behavior.
Build with stable versions preferable because dev version fully of bugs, vulnerabilities and our efforts will be focused on new features instead of catch bugs in stranger code.

**Comment by timothygwebb** [comment]
https://github.com/boxbilling/boxbilling/issues/1240
https://github.com/boxbilling/boxbilling/pull/1201
https://github.com/boxbilling/boxbilling/discussions/1205
