### ISSUE TITLE
[Feature Request] Chargeback Does Not Remove or Reset Customer Balance

### ISSUE THREAD

**Issue by wcdsantos** [boxbilling/boxbilling#1283]
### What is the idea?

When making a reversal, it does not cancel the order and does not deduct the value of the customer's balance.

### Why would this be beneficial

It would help to avoid manual adjustments and consequently keep something the customer paid wrong

**Comment by givinghawk** [comment]
I think this is a bug and is not a feature request

**Comment by m4rkstevenson** [comment]
It'll probably be useful to know which payment gateway you are using, it isn't a bug if it isn't supported.

**Comment by wcdsantos** [comment]
I will delete and post in the correct section

**Comment by wcdsantos** [comment]
I figured it was an unimplemented function.
I will close and post as bug

**Comment by wcdsantos** [comment]
> Provavelmente será útil saber qual gateway de pagamento você está usando, não é um bug se não for suportado.

I'm talking within the billing box itself, at the time of the reversal, it continues with the balance and service order active and so manual adjustments are necessary
