### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MrLimoAK** [boxbilling/boxbilling#1290]
### What happened?

Admin section logo URL is missing the working directory.
I have installed BoxBilling as a test in a subdirectory.  The admin page logo is busted. The image URL is missing the working directory/subdirectory.
The Correct URL is:
https://www.domain.com/direcory/bb-themes/boxbilling/assets/images/logo.png
The URL is displayed in the browser:
https://www.domain.com/bb-themes/boxbilling/assets/images/logo.png

A small tweak in the theme should fix it.

### BoxBilling Version

v4.22-beta.1.5

### What version of PHP are you running?

Something unsupported

### Additional Notes

PHP v7.4

**Comment by givinghawk** [comment]
This is a simple configuration error, you need to change the directory in
bb-config.php I do believe

**Comment by evrifaessa** [comment]
#1253 tracks this.
