### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by fabpot-del** [boxbilling/boxbilling#1296]
### What happened?

Please describe the problem
The SolusVM plugin has remained at version **1.0.0**, not fully compatible with **SolusVM 1.26.11**, it also has bugs in the product configuration in particular the choice of virtualization, nodes and problems with user registration.

### BoxBilling Version

v4.21

### What version of PHP are you running?

PHP 8.0

### Additional Notes

Additional notes

**Comment by fabpot-del** [comment]
![164977559-f39aa1ba-984e-4802-b74d-0ba080627c2e](https://user-images.githubusercontent.com/93833001/165069319-b23baf8f-f91d-4ffc-8120-e27860eb8f55.png)

**Comment by evrifaessa** [comment]
duplicate
