### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by chippytech** [boxbilling/boxbilling#1297]
### What happened?

count(): Argument #1 ($value) must be of type Countable|array, null given

### BoxBilling Version

v4.22-beta.1.1

### What version of PHP are you running?

PHP 8.0

### Additional Notes

Additional notes

**Comment by evrifaessa** [comment]
any more details?

**Comment by evrifaessa** [comment]
can you try with the latest beta build?

**Comment by chippyapps** [comment]
Now i get Not Found

**Comment by evrifaessa** [comment]
https://www.browserstack.com/guide/how-to-write-a-bug-report

**Comment by 0x6b-dev** [comment]
@evrifaessa this can be closed.

@chippytech can consult the [contributing guidelines](https://github.com/boxbilling/boxbilling/blob/master/CONTRIBUTING.md) or our Discord channel for assistance with producing a bug report.

**Comment by jaapmarcus** [comment]
Please provide more info to reproduce the error
