### ISSUE TITLE
[Bug] Can not connected to the MySQL database when install

### ISSUE THREAD

**Issue by 123ysys** [boxbilling/boxbilling#1298]
### What happened?

Please describe the problem:
When I install the boxbilling, in the second step"Database" I get an error tip: Could not connect to database. Please check database details. You might need to create database first. But I think everything details I typed are correct.

### BoxBilling Version

v4.22-beta.1.5

### What version of PHP are you running?

PHP 8.0

### Additional Notes

Additional notes

I see on the Database installation page there are 4 parameters: 
```Database hostname:

Database name:

Database user:

Database password:
```

But on my hosting provider's system, I see there are 3 parameters
```Server, Database/Username,  Password``` 

in Section Manage MySQL and 2 parameters in Section Manage MySQL Users: 
```Username and Database```

. How can I match them between boxbilling and my hosting provider's system?
Thank you.

**Comment by scharez** [comment]
Database name must not include "." or "-" oder other character!

**Comment by 123ysys** [comment]
> Database name must not include "." or "-" oder other character!

Hello. After setting the database name with only letters I can not still connect successfully.

**Comment by jaapmarcus** [comment]
Contact your hosting provider what the correct settings are …

**Comment by 123ysys** [comment]
> Database name must not include "." or "-" oder other character!

May I know if it is the requirement of boxbilling? Thx.
