### ISSUE TITLE
Can not login to admin area

### ISSUE THREAD

**Issue by amvhost** [boxbilling/boxbilling#13]
even with the correct password not log

**Comment by lakshaholdings** [comment]
http://seodaddyhost.com/gateway/bb-admin.php
ERROR 404 - Not Found!

The following error occurred:

The requested URL was not found on this server.

Please check the URL or contact the webmaster.

everything is setup correctly and i even changed the passwords.
IF this is not a stable platform then i will be very disappointed cause it seems real good better than all the nonsense for host billing

**Comment by 4Giedrius** [comment]
Please use following URL: http://seodaddyhost.com/gateway/bb-admin

You can change it in `bb-config.php`file.
