### ISSUE TITLE
[Bug]  [emerg] no port in upstream "php" 

### ISSUE THREAD

**Issue by motoporasda** [boxbilling/boxbilling#1307]
### What happened?

hi
i am using nginx and this for my site configuration , when i restart nginx service i get this error (nginx: [emerg] no port in upstream "php" in /etc/nginx/sites-enabled/client.conf:20) "

 server {
     listen 80;

     set $root_path '/var/www/boxbilling/src';
     server_name  client.stellar-host.com;

     index index.html index.htm index.php;
     root $root_path;
     try_files $uri $uri/ @rewrite;
     sendfile off;

     location @rewrite {
         rewrite ^/(.*)$ /index.php?_url=/$1;
     }

     location ~ \.php {
         fastcgi_split_path_info ^(.+\.php)(/.+)$;

         #pass to upstream configured in global nginx.conf
         fastcgi_pass php;

         fastcgi_param PATH_INFO       $fastcgi_path_info;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         fastcgi_intercept_errors on;

         include fastcgi_params;
     }

     # Disable PHP execution in bb-uploads and bb-data
     location ^~ /bb-uploads/ { }
     location ^~ /bb-data/ {
       deny all;
     }

     location ~* ^/(css|img|js|flv|swf|download)/(.+)$ {
         root $root_path;
         expires off;
         proxy_no_cache 1;
         proxy_cache_bypass 1;
     }

     location ~ /\.ht {
         deny all;
     }
  }

### BoxBilling Version

v4.22-beta.1.5

### What version of PHP are you running?

PHP 8.0

**Comment by jaapmarcus** [comment]
fastcgi_pass php;

You need to replace it with the correct settings

**Comment by jaapmarcus** [comment]
It depends on how Nginx and PHP are setup. 

`fastcgi_pass    unix:/run/phpphpx.x-fpm.sock`

or 

`fastcgi_pass    unix:/run/phpphp-fpm.sock`

You need to verify it first as it depends on the setup

**Comment by 0x6b-dev** [comment]
Hi @motoporasda, has this solved your issue? 
As this is directly related to a support request I'll recommend catching up with us on our [discord server](https://boxbilling.org/discord). 
This issue will be closed now.
