### ISSUE TITLE
[Feature Request] Proxmox VE module

### ISSUE THREAD

**Issue by ourengine** [boxbilling/boxbilling#1313]
### What is the idea?

A good idea to create a module for provisioning VM's and LXC container's from the servers using Proxmox virtualization platform. Proxmox VE is a open-source server management platform for enterprise virtualization.

### Why would this be beneficial

Many hosting providers use Proxmox VE as server management platform, and the main billing selection criteria is supporting integration with Proxmox VE platform.

**Comment by notbasetwo** [comment]
This is an interesting proposition but there are few problems here...

Implementing Proxmox to just connect a service to the PVE is relatively trivial, their API is well documented and is definitely suited for that task.

But, the more advanced features as would be required for more typical hosting settings require a non-insignificant amount of work with features such as sensible IPAM. This is not native to the PVE and would require additional work in implementing.
