### ISSUE TITLE
no pdf [Bug] 

### ISSUE THREAD

**Issue by pvdhelm1974** [boxbilling/boxbilling#1316]
### What happened?

when a customer want to print a pdf invoice they get an error

### BoxBilling Version

v4.22-beta.1.5

### What version of PHP are you running?

PHP 8.0

### Additional Notes

i set the logo path in the settings but that doesn't help

**Comment by BenNottelling** [comment]
And what is the error?

**Comment by pvdhelm1974** [comment]
ERROR
imagecreate(): Argument #1 ($width) must be greater than 0

**Comment by BenNottelling** [comment]
Anything in the log file?

**Comment by pvdhelm1974** [comment]
[php_error.log](https://github.com/boxbilling/boxbilling/files/8697263/php_error.log)

here is the log file

**Comment by jaapmarcus** [comment]
```
15-May-2022 23:04:22 Europe/Amsterdam] 2 imagecreatefrompng(/home/strato/http/premium/rid/56/71/58535671/htdocshttps://www.pvdhelm.nl/invoice/bb-themes/boxbilling/assets/images/logo.png): Failed to open stream: No such file or directory /mnt/web310/c3/71/58535671/htdocs/invoice/bb-library/PDF_ImageAlpha.php 100
```
Logo doesn't exiss.

**Comment by pvdhelm1974** [comment]
There is a log it’s for now the standard boxbilling logo i see the logo on the top left of the dashbord and when i place a order in the proforma invoice it’s also on the upper left corner

**Comment by jaapmarcus** [comment]
/home/strato/http/premium/rid/56/71/58535671/htdocshttps://www.pvdhelm.nl/invoice/bb-themes/boxbilling/assets/images/logo.png

It is trying to use 
/home/path/to/htdocks/https://domain.com/ 

It should use the relative path instead

**Comment by pvdhelm1974** [comment]
i will try when i get home from work tonight

**Comment by 0x6b-dev** [comment]
Duplicate [#1282 ](https://github.com/boxbilling/boxbilling/issues/1282)

**Comment by jaapmarcus** [comment]
Duplicate
