### ISSUE TITLE
Create custom recurring order/invoice

### ISSUE THREAD

**Issue by jthomaschewski** [boxbilling/boxbilling#132]
Is there a way to create custom recurring invoices?
I just see the subscriptions but I think thats just for recurring payments with a payment gateway.

I really like the way it's possible to create custom invoices with custom items but I would like to add some recurring invoices and the only way to do this seems to be the creation of a a new product, login as a customer and order the product.

If it's not yet possible I would like to suggest this feature for the future.

**Comment by rafimd** [comment]
pay by custom then send the amount and invoiceid to another gateway is it possible
