### ISSUE TITLE
Has the Centova Cast extension been fixed in BoxBilling?

### ISSUE THREAD

**Issue by emar** [boxbilling/boxbilling#1321]
### What is the task

Centova Cast extension hasn't been working for a long time.
Has anyone fixed this extension?

### Additional Notes

Additional notes

**Comment by 0x6b-dev** [comment]
Duplicate of #904.

Hi Emar,
Just a friendly reminder about our [contributing guidelines](https://github.com/boxbilling/boxbilling/blob/master/CONTRIBUTING.md), for non-bug, non-technical related questions the best place to ask questions like this would be the [Box Billing Discord](https://boxbilling.org/discord).

You can track your prior request here: [#904](https://github.com/boxbilling/boxbilling/issues/904).

**Comment by 0x6b-dev** [comment]
@evrifaessa please close. Issue is a duplicate.

**Comment by jaapmarcus** [comment]
https://github.com/boxbilling/boxbilling/issues/904
