### ISSUE TITLE
[Bug] Running on docker does not render app on browser

### ISSUE THREAD

**Issue by angelocorreia27** [boxbilling/boxbilling#1334]
### What happened?

Although the docker image runs perfectly, it does not respond in the browser on the corresponding port.

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 8.1

### Additional Notes

Additional notes

**Comment by timothygwebb** [comment]
You need to make sure that you dom0 or host running docker does not have an existing instance running of any webserver such as apache or lighttpd. Docker launches instance and maps ports to existing dom0 or host.

**Comment by angelocorreia27** [comment]
Ok. thank you.

**Comment by timothygwebb** [comment]
> Ok. thank you.

Your welcome.
