### ISSUE TITLE
[Bug] Installation get stuck after created database

### ISSUE THREAD

**Issue by angelocorreia27** [boxbilling/boxbilling#1335]
### What happened?

After finished create all tables, app get stuck on screen 3. Administrator

trying again, get the error:
![error-boxbilling](https://user-images.githubusercontent.com/7281518/172030137-6df24e09-f8f0-4687-a9be-e1cbdcf7d1e1.png)

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 8.1

### Additional Notes

Additional notes

**Comment by timothygwebb** [comment]
You will need to drop all tables in the BoxBilling database and reinstall or try to directly access the install by going to localhost:85/specified address of root folder structure. /var/www/BoxBilling would be accessed as such localhost:85/BoxBilling. I think you're install was successful but install was not expecting to have :85. Default is 443 and 80.

**Comment by angelocorreia27** [comment]
Yes, its works after removing the install folder. thank you.

**Comment by timothygwebb** [comment]
> Yes, its works after removing the install folder. thank you.

Your welcome.

**Comment by angelocorreia27** [comment]
Its seems like create admin account but couldn't login with it. maybe something on step 4 Finished was missing.

**Comment by timothygwebb** [comment]
Reset the password.

**Comment by angelocorreia27** [comment]
;) thank you.
