### ISSUE TITLE
[Bug] cant create user at hestiacp

### ISSUE THREAD

**Issue by ourengine** [boxbilling/boxbilling#1365]
### What happened?

I have set up two servers, one is VestaCP, the other is HestiaCP, both show they are set up correctly (status: connected), but after activating the order for the HestiaCP server, the user did not register.
VestaCP module is working properly.

### BoxBilling Version

v4.22-beta.1.5

### What version of PHP are you running?

PHP 8.0

### Additional Notes

Another HestiaCP server shows the error "Connection to server failed Error: API has been disabled" at the connection check stage.

**Comment by jaapmarcus** [comment]
In the settings make sure you have "API access" enabled and enter your public ip of the "Boxbilling" server inside the text box.

**Comment by jaapmarcus** [comment]
And is "Legacy API" enabled?

**Comment by jaapmarcus** [comment]
Add 127.0.0.1 to the allowed ip list?

**Comment by jaapmarcus** [comment]
If you check /var/log/hesita/auth.log or /var/log/hesita/nginx-error.log what kind of error do you see?

**Comment by jaapmarcus** [comment]
v-generate-api-key and enter it in access hash will solve the issue.

It looks like:
https://github.com/boxbilling/boxbilling/blob/f777d037fe667353ce1723e1083deded47a42f92/src/bb-library/Server/Manager/Hestia.php#L73-L78

Return not false even when it is empty

**Comment by ourengine** [comment]
Solved!
Thank you very much I appreciate it

**Comment by ourengine** [comment]
> v-generate-api-key and enter it in access hash will solve the issue.
> 
working properly
