### ISSUE TITLE
Intention to use

### ISSUE THREAD

**Issue by ugintl** [boxbilling/boxbilling#1378]
I was wondering if this app would be suitable for what I have been thinking.

Requirements
**1. Charge station management**
a. Create and store charge stations’ basic information like installation
location, model and display as a list or on Google maps
b. Display charge stations’ current status and remotely manage their
on/off status
c. Allow user to book a charge station for charging his/her vehicle
**2. User vehicle management**
a. Allow user registration via email and phone number
b. Allow user to add/update his/her vehicle
**3. Billing**
Record the minutes of charging and generate bill based on the usage
**4. Notification**
Notify vehicle owner when the vehicle is fully charged

**Comment by jaapmarcus** [comment]
Not in this state you will need to develop your own plugins

**Comment by ugintl** [comment]
@jaapmarcus Plugins for what functionality? Can you list down?

**Comment by jaapmarcus** [comment]
Box billing is build for web hosting reselling not for car rental and that so you need a lot of changes. Unless you want to develop this kind of plugins it will not be possible
