### ISSUE TITLE
Custom registrars domain availability check.

### ISSUE THREAD

**Issue by m0lmk** [boxbilling/boxbilling#1389]
I would like to add a custom method for checking if a domain is available when using a custom registrar. Am I correct in thinking that I need to do this in /bb-library/Registrar/Adaptor/Custom.php?

**Comment by RanaMoizHaider** [comment]
Yes, you can surely use /bb-library/Registrar/Adaptor/Custom.php but I will suggest you to create a copy of Custom.php and rename it as your registrar name as Enom.php for Enom.

**Comment by m0lmk** [comment]
Great. Thanks!
