### ISSUE TITLE
[Bug] - [Error]

### ISSUE THREAD

**Issue by reaksiproton** [boxbilling/boxbilling#1398]
### What happened?

[Please describe the problem](https://i.vgy.me/9Da4Lx.png)
happen when i want to show popup test

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 8.1

### Additional Notes

happen when i want to show popup test

**Comment by farhanabc** [comment]
Can you share your problem with us?

**Comment by reaksiproton** [comment]
i need to re install it first... somehow i dont know suddently my user list error

but
i have already sent this:
https://i.vgy.me/9Da4Lx.png

happenn when i try to click show p[opup

**Comment by farhanabc** [comment]
> i need to re install it first... somehow i dont know suddently my user list error
> 
> but i have already sent this: https://i.vgy.me/9Da4Lx.png
> 
> happenn when i try to click show p[opup

Reply Farhan
Can you reinstall?
Could you tell me the name of your website?

**Comment by reaksiproton** [comment]
sure... wait.. i will reinstall and i will sent the credential to you.. where/how i can sent it to you privately ? (github newbie )

**Comment by reaksiproton** [comment]
update:
already reinstall
and the error not showing up

i will try to continue setup and update about this using new subject
now this thread/post marked as solved
