### ISSUE TITLE
[Bug] Discord & Slack url to join the community lead to 404 in contributors guide as well as in github READM.md

### ISSUE THREAD

**Issue by Tdnshah** [boxbilling/boxbilling#1422]
### What happened?

The links to join community group at slack/discord leads to 404 page in contributors guide as well as in github README.md file.

In need to join the groups  to request for correct url to join the community groups looking forward to active contributions.

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

PHP 8.1

### Additional Notes

Additional notes

**Comment by John-S4** [comment]
There is currently no active BoxBilling community forums as far as I know apart from here on GitHub. 

The old discord was repurposed and is now used by the FOSSBilling fork, and the slack is still there but very very quiet.

**Comment by jaapmarcus** [comment]
Updated both Contributing Guidelines and Readme.md

**Comment by Tdnshah** [comment]
Thank you @John-S4  & @jaapmarcus , one more question if I am planning to contribute which is the nice place to start with FOSSBilling or Box billing as I am coming back here after a long time, and have heard of some issue going on with box billing ownership, but today when I visited boxbilling homepage it seems to have taken the control back & is actively looking for contributors and maintainers, So if anyone can guide which would be the best repo to start back again would be of great help. Sorry if I asked wrong question at wrong place.

Thank you

**Comment by evrifaessa** [comment]
> Thank you @John-S4  & @jaapmarcus , one more question if I am planning to contribute which is the nice place to start with FOSSBilling or Box billing as I am coming back here after a long time, and have heard of some issue going on with box billing ownership, but today when I visited boxbilling homepage it seems to have taken the control back & is actively looking for contributors and maintainers, So if anyone can guide which would be the best repo to start back again would be of great help. Sorry if I asked wrong question at wrong place.
> 
> 
> 
> Thank you

The issues are still ongoing. We were the latest team and in fact the team that put the "looking for maintainers" notice before moving.

I know it's confusing but this repository will likely be unmaintained until the original author decides to care again. Any new contribution from the latest team will continue under [our new organization](https://fossbilling.org). Here is the link [to our Discord server](https://fossbilling.org/discord).

**Comment by jaapmarcus** [comment]
> 

Boxbilling is not active any more. Use FOSSBilling instead. I only committed the Changes to Boxbilling to solve the confusion over the non working links

**Comment by Tdnshah** [comment]
@evrifaessa and @jaapmarcus  thanks for pointing to the right direction.
