### ISSUE TITLE
Unable to use after successful installation

### ISSUE THREAD

**Issue by buycn** [boxbilling/boxbilling#1460]
### What is the task

I installed the latest package of BOXBILING.

System: ubuntu22.04

PHP version: 8.0

apache+nginx

After installation, only the first page is displayed. Other pages can't be switched by clicking. I have reinstalled them twice. It should not be caused by operation problems

### Additional Notes

Additional notes

**Comment by evrifaessa** [comment]
You should rename htaccess.txt to .htaccess (with the dot in the beginning).

You also might want to switch to [FOSSBilling](https://github.com/FOSSBilling/FOSSBilling). We are the latest BoxBilling team and we had to move to a new organization.

BoxBilling no longer receives any meaningful updates. New features and security patches go to FOSSBilling.

**Comment by evrifaessa** [comment]
What error do you see when you try to visit another page?

**Comment by buycn** [comment]
No error is displayed. My uri has been switched, but my page is still the home page

**Comment by BelleNottelling** [comment]
@buycn please create an issue on our repository, we would be happy to help you there

**Comment by buycn** [comment]
The web environment has been replaced to solve this problem, although I don't know what caused it. I installed the cloudpanel environment before, but now I have replaced it with hestia

**Comment by jaapmarcus** [comment]
Cloudpanel uses NGINX by default Hestia Apache2 with Nginx as proxy that might be the reason why it is working

**Comment by buycn** [comment]
Thank you for your answer. This may be the reason
