### ISSUE TITLE
ISPConfig 3 Error 500

### ISSUE THREAD

**Issue by chen369** [boxbilling/boxbilling#163]
I Keep Getting this error when a Client Tries to sign up for an account.
Also, When trying to delete a failed/pending ticket it spits out an error "looks like we got no XML document"

ISPConfig 3.0.5 (Working)

Any Ideas??

26-Nov-2012 22:22:29] exception 'SoapFault' with message 'looks like we got no XML document' in /var/www/clients/client0/web1/web/f/bb-library/Server/Manager/Ispconfig3.php:483
Stack trace:
#0 /var/www/clients/client0/web1/web/f/bb-library/Server/Manager/Ispconfig3.php(483): SoapClient->__call('client_delete', Array)
#1 /var/www/clients/client0/web1/web/f/bb-library/Server/Manager/Ispconfig3.php(483): SoapClient->client_delete('d6762d82d280355...', NULL)
#2 /var/www/clients/client0/web1/web/f/bb-library/Server/Manager/Ispconfig3.php(134): Server_Manager_Ispconfig3->_request('client_delete', Array)
#3 /var/www/clients/client0/web1/web/f/bb-modules/mod_servicehosting/Service.php(179): Server_Manager_Ispconfig3->cancelAccount()
#4 /var/www/clients/client0/web1/web/f/bb-modules/mod_servicehosting/Service.php(206): Box_Mod_Servicehosting_Service->action_cancel()
#5 /var/www/clients/client0/web1/web/f/bb-library/Model/ClientOrderTable.php(442): Box_Mod_Servicehosting_Service->action_delete()
#6 /var/www/clients/client0/web1/web/f/bb-library/Model/ClientOrderTable.php(210): Model_ClientOrderTable->_callOnService()
#7 /var/www/clients/client0/web1/web/f/bb-modules/mod_order/Api_Admin.php(483): Model_ClientOrderTable->deleteFromOrder()
#8 /var/www/clients/client0/web1/web/f/bb-library/Api/Handler.php(95): Box_Mod_Order_Api_Admin->delete()
#9 /var/www/clients/client0/web1/web/f/bb-modules/mod_api/Controller_Client.php(94): Api_Handler->__call('order_delete', Array)
#10 /var/www/clients/client0/web1/web/f/bb-modules/mod_api/Controller_Client.php(55): Box_Mod_Api_Controller_Client->_apiCall()
#11 /var/www/clients/client0/web1/web/f/bb-modules/mod_api/Controller_Client.php(35): Box_Mod_Api_Controller_Client->tryCall()
#12 /var/www/clients/client0/web1/web/f/bb-library/Box/App.php(240): Box_Mod_Api_Controller_Client->get_method(Object(Box_AppClient), 'admin', 'order', 'delete')
#13 /var/www/clients/client0/web1/web/f/bb-library/Box/App.php(289): Box_App->executeShared()
#14 /var/www/clients/client0/web1/web/f/bb-library/Box/App.php(189): Box_App->processRequest()
#15 /var/www/cloudfilez.org/web/f/index.php(180): Box_App->run()
#16 {main}

Next exception 'Server_Exception' with message 'looks like we got no XML document' in /var/www/clients/client0/web1/web/f/bb-library/Server/Manager/Ispconfig3.php:623
Stack trace:
#0 /var/www/clients/client0/web1/web/f/bb-library/Server/Manager/Ispconfig3.php(134): Server_Manager_Ispconfig3->_request('client_delete', Array)
#1 /var/www/clients/client0/web1/web/f/bb-modules/mod_servicehosting/Service.php(179): Server_Manager_Ispconfig3->cancelAccount()
#2 /var/www/clients/client0/web1/web/f/bb-modules/mod_servicehosting/Service.php(206): Box_Mod_Servicehosting_Service->action_cancel()
#3 /var/www/clients/client0/web1/web/f/bb-library/Model/ClientOrderTable.php(442): Box_Mod_Servicehosting_Service->action_delete()
#4 /var/www/clients/client0/web1/web/f/bb-library/Model/ClientOrderTable.php(210): Model_ClientOrderTable->_callOnService()
#5 /var/www/clients/client0/web1/web/f/bb-modules/mod_order/Api_Admin.php(483): Model_ClientOrderTable->deleteFromOrder()
#6 /var/www/clients/client0/web1/web/f/bb-library/Api/Handler.php(95): Box_Mod_Order_Api_Admin->delete()
#7 /var/www/clients/client0/web1/web/f/bb-modules/mod_api/Controller_Client.php(94): Api_Handler->__call('order_delete', Array)
#8 /var/www/clients/client0/web1/web/f/bb-modules/mod_api/Controller_Client.php(55): Box_Mod_Api_Controller_Client->_apiCall()
#9 /var/www/clients/client0/web1/web/f/bb-modules/mod_api/Controller_Client.php(35): Box_Mod_Api_Controller_Client->tryCall()
#10 /var/www/clients/client0/web1/web/f/bb-library/Box/App.php(240): Box_Mod_Api_Controller_Client->get_method(Object(Box_AppClient), 'admin', 'order', 'delete')
#11 /var/www/clients/client0/web1/web/f/bb-library/Box/App.php(289): Box_App->executeShared()
#12 /var/www/clients/client0/web1/web/f/bb-library/Box/App.php(189): Box_App->processRequest()
#13 /var/www/******/web/f/index.php(180): Box_App->run()
#14 {main}
[26-Nov-2012 22:22:29] looks like we got no XML document 0

**Comment by nelsondcosta23** [comment]
Hi guys, well just asking the scrpt stills wroking?!
I tested but I cant do it.. well im tired... so may try tomorow :)
