### ISSUE TITLE
Admin :: Category edit

### ISSUE THREAD

**Issue by AdamiPL** [boxbilling/boxbilling#205]
Hello
I using a new version and is a problem with editing product category.
When i edit a description product category and save, description enter to the field for icon.
http://postimg.org/image/c1gfj2v9l/

Next,
When i try to set up icon, i cant press OK i dont see this button and i cant scroll the web
http://postimg.org/image/bitnz9tjx/

and the last:
I dont see a price on category list :(
http://postimg.org/image/5xm1ea6wn/

**Comment by 4Giedrius** [comment]
Thank you for reporting this issue, I have fixed all of your mentioned problems. You can wait until next release or make changes to your files from following commits: https://github.com/boxbilling/boxbilling/commit/2e94853d11189afb2ff7ded3f28b65863cdc5ec3 https://github.com/boxbilling/boxbilling/commit/d329dbd0085afe569c8cf8f8651f09c9e97210f1 https://github.com/boxbilling/boxbilling/commit/cb4c2fc98cfd83601d7a2b27db7d0f532d87c34b

**Comment by 4Giedrius** [comment]
We have just released [new version of BoxBilling](https://github.com/boxbilling/boxbilling/releases/latest), feel free to download it.
