### ISSUE TITLE
Unable to find template

### ISSUE THREAD

**Issue by AdamiPL** [boxbilling/boxbilling#206]
I've got my own template and when i try enter to the invoice details (pay)
i saw 

Unable to find template
" (looked into: ...) in "layout_default.phtml" at line 108.
how to fix this? how to add template?

**Comment by 4Giedrius** [comment]
It seems that `partial_menu.phtml` is missing. Please have a look into [tutorials section of Boxbilling documentation] (http://docs.boxbilling.org/en/latest/reference/tutorials.html#how-to-edit-boxbilling-templates) where it is explained how to work with custom templates.
