### ISSUE TITLE
Admin Language File

### ISSUE THREAD

**Issue by xunilarium** [boxbilling/boxbilling#207]
Hi

when I translate the admin.po file and compile it with the Poedit nothing change in admin panel but when translate the message.po both user panel and admin panel change.
Another problem is in some hosting services when I change language from user panel nothing happen and it shows default language that is set in to the bb-config file.

**Comment by vaidas-lungis** [comment]
As i can see from the code here (https://github.com/boxbilling/boxbilling/blob/master/src/bb-load.php#L140) only messages.po file is used for translation.

>Another problem is in some hosting services when I change language from user panel nothing happen and it shows default language that is set in to the bb-config file.

Some hosting services does not provide gettext functions, or locale?

**Comment by vaidas-lungis** [comment]
default translation file is messages.po
additional admin panel translation file is admin.po
