### ISSUE TITLE
payment

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#209]
/bb-ipn.php?bb_gateway_id=2
{"result":null,"error":"Module invoice does not have service class"}

And no work (webmoney, interkassa and eth.)

**Comment by 4Giedrius** [comment]
We are unable to reproduce this problem. Please elaborate more on this issue and provide steps we need to take in order to see this error message.

**Comment by legion726** [comment]
This error, http://demo.boxbilling.com/bb-ipn.php?bb_gateway_id=2

Mod.php 

    public function hasService($sub = '')
    {
        $filename = sprintf('Service%s.php', $sub);
        return file_exists($this->_getModPath() . $filename);
    }

add var_dump($filename);

result - Servicetransaction.php (in bb-modules/Invoice/ServiceTransaction.php)

**Comment by 4Giedrius** [comment]
As you already noticed we have fixed(https://github.com/boxbilling/boxbilling/commit/05d475730bfd26d3051761455405284ba31c4221) this issue. Thank you for reporting!
