### ISSUE TITLE
order button 

### ISSUE THREAD

**Issue by hoobs1210** [boxbilling/boxbilling#210]
the "Order Now" button on the order page just redirects back to the  home page/dashboard, but the URL is /index.php?period=1W

![capturddd](https://cloud.githubusercontent.com/assets/7888101/5640688/9bd8fbc0-95ee-11e4-94d0-8b14752832c4.PNG)

**Comment by 4Giedrius** [comment]
Thank you for reporting, I have fixed this issue(https://github.com/boxbilling/boxbilling/commit/462844401f7ffff3ec91838b456ee13dde09265b) and [new release](https://github.com/boxbilling/boxbilling/releases/latest) with this fix included is available. Feel free to download it or just change your existing installation according to my aforementioned commit.
However please keep in mind that from version 4.0 we strongly encourage use of new `Huraga` theme! You can enable it from admin area: `Configuration -> Settings -> Theme`
