### ISSUE TITLE
WebMoney and Interkassa

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#212]
Hello,
no work modules gateway payment

url payment 

index.php?_url=/invoice/banklink/43b852737304a3014e5bc32826e2d33b19375c75/5

Fatal error: Call to undefined method Payment_Adapter_Interkassa::setDi() in /home/netengi/domains/portal/public_html/bb-modules/Invoice/Service.php on line 1286 
and
Fatal error: Call to undefined method Payment_Adapter_WebMoney::setDi() in /home/netengi/domains/portal/public_html/bb-modules/Invoice/Service.php on line 1286

haw fix?

**Comment by 4Giedrius** [comment]
This problem with DI is already fixed(https://github.com/boxbilling/boxbilling/commit/1d3068051d24ff37cfa4125c5c1976774901a7ac) and  will become available in the next release. As I can see in documentation of Interkassa, `ik_sign` variable is not obligatory parameter but you can feel free to pass it by modifying source code of Interkassa payment adapter file.
