### ISSUE TITLE
Class 'Box\Mod\Invoice\Servicetransaction

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#216]
Fatal error: Class 'Box\Mod\Invoice\Servicetransaction' not found in /home/netengi/domains/portal/public_html/bb-library/Box/Mod.php on line 125

**Comment by vaidas-lungis** [comment]
This should fix this issue.
https://github.com/boxbilling/boxbilling/commit/a335e61876e7e59a150da18a763a3707a207c55a
