### ISSUE TITLE
invoice and currency

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#217]
The client should Currency UAH, and create invoice in UAH, but payment is displayed as $

**Comment by legion726** [comment]
![e783d-clip-10kb](https://cloud.githubusercontent.com/assets/10427411/5661535/a0d92a12-9735-11e4-9b13-3789b75a9d3f.png)

**Comment by 4Giedrius** [comment]
It shows up fine in test environment. ![invoice](https://cloud.githubusercontent.com/assets/3658151/5662312/24df214a-9740-11e4-8f46-07aac4c357bb.png)
Did you set up currency format in `Configuration -> Settings -> Currency` when added new currency?

**Comment by legion726** [comment]
yes, of couse. And new version boxbilling.
![uah](https://cloud.githubusercontent.com/assets/10427411/5663858/1f56e49c-9754-11e4-8e3a-5a78cc6da5de.png)
![client](https://cloud.githubusercontent.com/assets/10427411/5663875/4c07247a-9754-11e4-826e-b14890775f72.png)
![invoice](https://cloud.githubusercontent.com/assets/10427411/5663899/7a42d08c-9754-11e4-9a0a-6f3697e780ff.png)

can check yourself, have access to ticket  	#5807

**Comment by vaidas-lungis** [comment]
Check your currency format at currency manage page

**Comment by legion726** [comment]
Ah, yes. Cloased
