### ISSUE TITLE
Mail is not sent

### ISSUE THREAD

**Issue by vachzar** [boxbilling/boxbilling#220]
I don't if it's similar with https://github.com/boxbilling/boxbilling/issues/208
but after upgrading to 4.x.xx (4.12.4) I cant send email: invoice, test mail nor using smtp.
I tried to install old version 3.xx, and it successfully sent the email. so I  guess the problem is 4.xx
I also test it by reset password for a client, but not sent. The cron that generate invoice didnt sent email too.

application.log

2015-01-08T22:26:27+00:00 INFO (6): Client requested password reset. Sent to email eternity17x@yahoo.co.id 
2015-01-08T23:11:04+00:00 DEBUG (7): onBeforeGuestPasswordResetRequest: array (
  'email' => 'eternity17x@yahoo.co.id',
)
2015-01-08T23:11:43+00:00 INFO (6): Staff member 1 logged in
2015-01-08T23:13:45+00:00 DEBUG (7): onBeforeAdminInvoiceSendReminder: array (
  'id' => '146',
)
2015-01-08T23:13:45+00:00 DEBUG (7): onAfterAdminInvoiceReminderSent: array (
  'id' => '146',
)
2015-01-08T23:13:45+00:00 INFO (6): Invoice payment reminder sent

**Comment by vaidas-lungis** [comment]
Hi, 
try to add 

```
$this->_exec($api, 'email_batch_sendmail');
```

here 
https://github.com/boxbilling/boxbilling/blob/master/src/bb-modules/Cron/Service.php#L68

**Comment by vachzar** [comment]
it works when I execute /bb-cron.php but else doesn't send.
I tried to send invoice reminder, it said email was sent but nothing happen.
After awhile, Then I executed /bb-cron.php, the email sent successfully

**Comment by AdamiPL** [comment]
@vachzar have you setup your cron? check errors.. If working by manually cron, they must working. Maybe is a problem with cron.. check this, show your cron entry.

**Comment by vachzar** [comment]
@adamiPL no, you got it wrong. The problem is the emails was not immediately sent. Let's say a client reset his password or I clicked "send reminder", boxbilling didn't immediately send the emails.
as @vaidas-lungis suggested, the code is for cron. my cron setting is twice a day. So, unless the cron isn't exceuted, email will be on pending to next cron job.

**Comment by chiareu** [comment]
All transitional emails must be send asap. Ex a password reset or an email verification for account creation must been send right away. Or the client fly away. If some lost password, It need to reset on that moment not tomorrow. As for registering users the same, or the client leave for other provider.
