### ISSUE TITLE
interkassa

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#221]
return_url
index.php?_url=%2Finvoice%2F900a4a7abcfb2c6134b76da39f5e6a68a9b1394d&status=ok&ik_shop_id=DECC2BD2-7A42-F5A0-6690-C9701AD1D763&ik_payment_amount=0.1&ik_payment_id=5&ik_payment_desc=Payment+for+invoice+BOX00005+%5B%D0%B2%D0%BF%D1%8B%D0%BF%D0%B2%D1%8B%5D&ik_paysystem_alias=privat24_w1_merchant2_uah&ik_baggage_fields=d%40brejnev.us&ik_payment_timestamp=1420806347&ik_payment_state=success&ik_trans_id=IK_32927890&ik_currency_exch=1&ik_fees_payer=1&ik_sign_hash=7794567704FE426E886C58E1EB68F816

please fix

**Comment by vaidas-lungis** [comment]
Could You possibly explain your question/issue once again?

**Comment by legion726** [comment]
after payment Interkassa returns to billing by such link

**Comment by vaidas-lungis** [comment]
And where is the problem?

**Comment by legion726** [comment]
upon return status invoice unpaid. 
and billing 
![222](https://cloud.githubusercontent.com/assets/10427411/5680545/41e85bb2-9817-11e4-9e13-f010f2f1c7f5.png)

**Comment by legion726** [comment]
billing dev.net** (access in ticket #5807 )

**Comment by vaidas-lungis** [comment]
What interkassa version you are using?

**Comment by legion726** [comment]
Use protocol v2.0

**Comment by legion726** [comment]
![inter1](https://cloud.githubusercontent.com/assets/10427411/5682575/abe9df10-9829-11e4-9d4e-d3f65e42cde6.png)
![inter2](https://cloud.githubusercontent.com/assets/10427411/5682577/adf6f7ca-9829-11e4-9336-cfa80899e496.png)

**Comment by legion726** [comment]
I tried to use v1

**Comment by vaidas-lungis** [comment]
BoxBilling is still using old v1 Interkassa api

**Comment by legion726** [comment]
i now check v1, return 
http://dev.netengi.com/index.php?_url=%2Finvoice%2Fafcf6d38529955111c1af518cd78ff095a95836f&status=ok&ik_shop_id=DECC2BD2-7A42-F5A0-6690-C9701AD1D763&ik_payment_amount=0.1&ik_payment_id=6&ik_payment_desc=Payment+for+invoice+BOX00006+[dssdh]&ik_paysystem_alias=yandexdengir&ik_baggage_fields=d%40brejnev.us&ik_payment_timestamp=1420819940&ik_payment_state=success&ik_trans_id=IK_32934225&ik_currency_exch=1&ik_fees_payer=1&ik_sign_hash=6CBA34E6910CF355639D33FD449FC454

**Comment by legion726** [comment]
and status - unpaid :(

**Comment by vaidas-lungis** [comment]
It looks like we need to update BoxBilling interkassa adapter to v2 version.

With current version can not validate interkassa ipn signature.

**Comment by legion726** [comment]
Ok. I'll wait :) And webmoney module please

**Comment by legion726** [comment]
Waiting for you, or somewhere to order development?

**Comment by vaidas-lungis** [comment]
Interkassa update to v2 will be available this week

**Comment by legion726** [comment]
Ok. And please, update module WebMoney (there is no payment processing functions)

**Comment by vaidas-lungis** [comment]
@legion726 can you download new interkassa adapter file  https://github.com/boxbilling/boxbilling/blob/feature/Feature-interkassav2/src/bb-library/Payment/Adapter/Interkassa.php and test it?

**Comment by legion726** [comment]
hm, http://new.netengi.com/index.php?_url=%2Finvoice%2Ff29d8f7fc808d0d8d906f491c2f0ba19f52fc1b4%3Fstatus&ik_co_id=530a290fbf4efce06724e2cc&ik_inv_id=33036589&ik_inv_st=success&ik_inv_crt=2015-01-13+19%3A31%3A37&ik_inv_prc=2015-01-13+19%3A32%3A59&ik_pm_no=1&ik_pw_via=liqpay_liqpay_merchant2_uah&ik_am=0.10&ik_co_rfn=0.0960&ik_ps_price=2.04&ik_cur=USD&ik_desc=Payment+for+invoice+BOX00001+[gddhs]&ik_x_iid=1

result url

**Comment by legion726** [comment]
and, fixed https://github.com/boxbilling/boxbilling/commit/24313b903f4f6f1cfdd6b5b1725a16ef4abea965 no include in relise 4.12.9

**Comment by legion726** [comment]
again test with fixid https://github.com/boxbilling/boxbilling/commit/24313b903f4f6f1cfdd6b5b1725a16ef4abea965 result_url
http://new.netengi.com/index.php?_url=%2Finvoice%2F824cccf7acd133223427b3aec2ec45ba4bcb1748&status=ok&ik_co_id=530a290fbf4efce06724e2cc&ik_inv_id=33037211&ik_inv_st=success&ik_inv_crt=2015-01-13+19%3A55%3A53&ik_inv_prc=2015-01-13+19%3A57%3A05&ik_pm_no=5&ik_pw_via=liqpay_liqpay_merchant2_uah&ik_am=0.10&ik_co_rfn=0.0960&ik_ps_price=2.04&ik_cur=USD&ik_desc=Payment+for+invoice+BOX00005+[test+inter+new]&ik_x_iid=5
![inter4](https://cloud.githubusercontent.com/assets/10427411/5725807/cad8bf62-9b5e-11e4-87e7-08d9872da801.png)
![inter5](https://cloud.githubusercontent.com/assets/10427411/5725817/e633c946-9b5e-11e4-8f17-faaf24a3caf1.png)

**Comment by legion726** [comment]
[13-Jan-2015 17:32:59 UTC] PHP Fatal error:  Call to a member function load() on a non-object in /home/netengi/domains/new.netengi.com/public_html/bb-library/Payment/Adapter/Interkassa.php on line 165

**Comment by legion726** [comment]
its wotk. Thank you
