### ISSUE TITLE
When Creating a new product it says, please edit mod_servicehosting_order_form.phtml file in order to change order form for hosting category products.

### ISSUE THREAD

**Issue by liptanbiswas** [boxbilling/boxbilling#222]
When Creating a new product it says, please edit mod_servicehosting_order_form.phtml file in order to change order form for hosting category products.
and when  we click on open editor editor does not open correctly.
![capture](https://cloud.githubusercontent.com/assets/8578543/5683933/07132234-9852-11e4-84b4-c9c9eb118ae3.JPG)
![capture1](https://cloud.githubusercontent.com/assets/8578543/5683931/05b94cba-9852-11e4-9fe0-6810c4b481fe.JPG)

**Comment by 4Giedrius** [comment]
Please perform changes from commit above or download new release with this bugfix included.

**Comment by DeekF** [comment]
Hi, I have latest version installed & still get this error

**Comment by 4Giedrius** [comment]
Which error are you talking about? Filemanager error was fixed in commit above. Do you see files when you open file manager? Are you talking about this informational message? If yes, you need to edit the form only if you want to change order form for particular product.

**Comment by DeekF** [comment]
sorry, my bad...appologies

**Comment by Listiyantoamk** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/24350836/21882338/93da0bac-d8dc-11e6-9894-d7a494a9a418.png)

**Comment by Listiyantoamk** [comment]
edit mod_servicedomain_order_form.phtml file in order to change order form for domain category products.

**Comment by Listiyantoamk** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/24350836/21882697/424f22de-d8de-11e6-9a14-e8ec77e71956.png)

**Comment by Listiyantoamk** [comment]
RENAMME SERVISEDOMAIN Menjadi domain
