### ISSUE TITLE
Problem with date in emails.

### ISSUE THREAD

**Issue by AdamiPL** [boxbilling/boxbilling#224]
Still not fixed! 

I update to new release, but email and date still not working proper...

Amount due: £180.00 Due Date: %AM, %04 %041 %0

still got this error (i'm generate new email templates)

https://github.com/boxbilling/boxbilling/issues/208

and i must manually change the Service.php in cron folder.

**Comment by 4Giedrius** [comment]
It is working fine on our end now. Did you update all of the files?   Do you also have `locale_date_format` value set in `bb-config.php` file. If the problem still persists, please submit a ticket from members area with your login details and we will check what is causing the problem.

**Comment by 4Giedrius** [comment]
It seems that issue is fixed for other users - http://www.boxbilling.com/forum/boxbilling-support/invoice-e-mail-notifications
