### ISSUE TITLE
WebMoney

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#226]
In module webmoney, please add function processTransaction

**Comment by 4Giedrius** [comment]
I have updated WebMoney `processTransaction` method - https://github.com/boxbilling/boxbilling/commit/a6b62fbce2d8cf92307bda19498dc09e6b532243 Could you check if the problem persists?

**Comment by legion726** [comment]
$data['LMI_SUCCESS_URL'] =	$this->config['success_url']; maybe return_url ?
and
Invoice status:
    Unpaid 

[14-Jan-2015 12:37:32 UTC] 8 Undefined index: secretWord /home/netengi/domains/new.netengi.com/public_html/bb-library/Payment/Adapter/WebMoney.php 186

**Comment by 4Giedrius** [comment]
I changed URL https://github.com/boxbilling/boxbilling/commit/d5c3e1bb684e4b69c61bbc3db38135a92a0738bf and added new field to WebMoney settings where you can enter secret word https://github.com/boxbilling/boxbilling/commit/c0208dcf4440e26c7f1df7797d2a65da6687294b. Could you check if it fixes your problem?

**Comment by legion726** [comment]
![w1](https://cloud.githubusercontent.com/assets/10427411/5740989/eb050cd4-9c10-11e4-9356-bab4e2895aaf.png)
![w2](https://cloud.githubusercontent.com/assets/10427411/5741004/0c5d0468-9c11-11e4-94a3-18300e7999b9.png)

**Comment by 4Giedrius** [comment]
I see that both transactions are $0.00. Is it intentional or a bug in BoxBilling?

**Comment by legion726** [comment]
bug

**Comment by 4Giedrius** [comment]
Could you submit ticket from members area providing your IPN and/or credentials so that we could check what is causing the problem.

**Comment by legion726** [comment]
ticket 5819

**Comment by 4Giedrius** [comment]
Thanks to your cooperation I was able to resolve this issue. It seems that WebMoney changed their validation hash algorithm from `md5` to `sha256` ant it was the reason why it was failing to process. Please check and confirm if it fixed the problem once you will do that I will merge fixes to master branch and release new version.

**Comment by legion726** [comment]
Thanks, works
