### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#231]
In Client settings there is option [Require email confirmation] that is not functioning.
No email confirmation are sent and the account is created and accessible.

**Comment by 4Giedrius** [comment]
It seems that `onAfterClientSignUp`hook is not triggered. Most likely it is because cron was not executed. Could you go to  `Configuration -> Settings -> Scheduled tasks` and check when was the last time when cron ran?

**Comment by chiareu** [comment]
It was manually run by me today - 2015-01-21 11:21:13 (4 hours ago)
Seams that my cron was not set up on server. I setup the cron on server to run properly.
Last run: 2015-01-21 16:40:01 (2 minutes ago)

NOW Cron is ok and we got the logs for Staff & Clients, but no Email log.
So I created another client account (email confirmation active) and we have 2 problem directions from here:

1. Creating new account. 
Filled the fields & hit register. the page was refreshed and login form appear. 
!ssue - We have no message to client to check his email address to confirm. So there is need of some info displayed.

2. Email confirmation
I know that I must confirm, but the email received are a little hard to understand :))) 
a. the password: ??? here we shall put real psw (unsafe) or text 'password you used on register form'. What is with that hash or ? there?
b. all that links confuse the client. On that part when we need confirmation we don't need the other 2 links who confuse

Let's see the received message: 
Note: changed real mail ellements with 'x'

Hello Bogdan Georgescu,

Thank you for signing up with us. Your new account has been setup and you can now login to our client area using the details below.

Email: x@x.com
Password: $2y$10$nH1buLLMGJhgXQtcvdOXauZxzPGRi2Wolkn96XnRwuS4SReA5Bemu

Approve your email by clicking on the link below:

http://client.domain.com/index.php?_url=/client/confirm-email/9xr8dhoppg3oojibcq1hrdrh12yylbgliell4nwt05t3lfcw5w

To login, visit http://client.domain.com/index.php?_url=/login&email=x%40x.com Edit your profile at http://client.domain.com/index.php?_url=/client/me

XXXXXXXXX

Powered by BoxBilling. Client management, invoicing and support software. http://www.boxbilling.com/

3. Email logs - are empty even with cron running ok. 
I also open support tickets and send some messages to and from. All come with notification on emails (the same email format not pleasant display) but no entry in Email logs.

**Comment by 4Giedrius** [comment]
Thank you for thorough explanation. I have fixed issue with hash in email instead of password and message also will be shown when confirmation of an email is required. Talking about too many links in email, feel free to edit `mod_client_signup.phtml` file and leave the text you find necessary.

**Comment by 4Giedrius** [comment]
Talking about email logs, it seems that logging to database is disabled. Please try go to `Configuration -> Settings -> Email -> Email Settings` and set `Log sent emails to database` to `Yes`.

**Comment by vaidas-lungis** [comment]
Email logs related #238

**Comment by chiareu** [comment]
Hi Giendrius, I made the code updates on mine working boxbilling.
- The email log is populated now after right config. OK
- on new client registration, 2 mail are logged (to client and to admin) OK
- Mail received by client is correct now. No hash, real password instead. OK

- Issue: On settings/client/ we maintain Require email confirmation YES but when new client are registered, after he fill the register form is redirected automatically on Client Dashboard. logged and active without mail confirmation.
a) after register form fill, no screen message to tell client to check his mail and confirm the email address. 
b) now client is automatically directed on dashboard and can place order. Here must can enter only after confirmation.
b.1) In fact because I was redirected to dashboard I place an order to check the situation.
Here we run in other needs. As i tell I put an order and selected custom payment. Enter. The popup box remain on screen no info, confirmation that the order was registered. Click outside the box to close so wondering where is my order, on dashboard was still 0. So need to refresh the page to update.
Here we need an onscreen confirmation message and autorefresh of page after to update the values accordingly.

**Comment by 4Giedrius** [comment]
I have fixed client email confirmation link and also added message for client if email needs to be confirmed.

**Comment by chiareu** [comment]
Great, working well. Anyway as a question when all changes will be committed to master?

**Comment by chiareu** [comment]
One observation. registered new client with need of confirmation of email.
All inpage message are ok, the email was received. But I didn't click to confirm the link and I try to login. The login was success and I'm on dashboard. The login must be disabled until the mail is confirmed.

**Comment by 4Giedrius** [comment]
All these changes will be merged to master and new major version will be released in the beginning of February. Talking about your second question, it was fixed some time ago https://github.com/boxbilling/boxbilling/commit/dc0cb6a1dae3cc91c91ed1ba93194080025f98b5

**Comment by chiareu** [comment]
Ahh :) I didn't observed that modif :) mea culpa. Anyway good job guys. Glad to have you so active ;) I'll go for PRO version because of you :)

**Comment by 4Giedrius** [comment]
We are really happy that you have decided to go with PRO version and thank you for your patience while we were fixing the issues. You are very welcome to open new issues if you feel there is a need to do it and contribute to our software by doing so. Cheers!

**Comment by chiareu** [comment]
One suggestion if it's permitted, an captcha on login form will be useful ;)
And after 5 failed login attepts redirect to password recovery. About security part I prefer to have a particular chat ;)
