### ISSUE TITLE
Order button settings

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#232]
Embedded button on external website is not working.
Added the script code to website and the button accordingly but not working.
On Chrome I get the error:
Uncaught index.php?_url=/orderbutton/js&options=1&width=600&theme_color=green&background_color=%23000000&bac…:2....etc.
TypeError: undefined is not a function

**Comment by 4Giedrius** [comment]
Please try to follow [this tutorial](http://docs.boxbilling.org/en/latest/reference/tutorials.html#how-to-add-order-popup-to-custom-theme) and let us know if the issue persists.

**Comment by chiareu** [comment]
Hi, let me give some details. 
Our main website is WP based, running on domain.tld;
Boxbilling is running on subdomain.domain.tld;

Already tried. Loaded the <script type="text/javascript" src="xxxxxxx..."></script> to WP header and add in page an element to trigger script <button class="order-button">Order</button>

 Resource interpreted as Script but transferred with MIME type text/html: "http://client.XXDOMAINXX.com/index.php?_url=/orderbutton/js&options=1&width=6…23000000&background_opacity=50&bind_selector=.order-button&border_radius=0".
index.php?_url=/orderbutton/js&options=1&width=600&theme_color=green&background_color=%23000000&bac…:2 Uncaught TypeError: undefined is not a functionindex.php?_url=/orderbutton/js&options=1&width=600&theme_color=green&background_color=%23000000&bac…:2 show_popupindex.php?_url=/orderbutton/js&options=1&width=600&theme_color=green&background_color=%23000000&bac…:108 (anonymous function)

**Comment by vaidas-lungis** [comment]
Can you create a support ticket in BoxBilling.com and tell us your url so we can investigate the issue?

**Comment by chiareu** [comment]
Sorry, I'm on free licence for now as we testing the application and can't submit any ticket on boxbilling
Anyway I can provide a test link here: http://www.hostomic.com/shared-hosting/

**Comment by juggalox2008** [comment]
should add on the Order Button to do categoies

**Comment by 4Giedrius** [comment]
@chiareu send us your information via [contact form](http://www.boxbilling.com/contact-us) so that we could check what is causing the issue.
@juggalox2008 please elaborate.
