### ISSUE TITLE
Activity log - Staff & Client empty

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#233]
On Activity section, Staff logings and Client logings history are empty

**Comment by 4Giedrius** [comment]
You need to make sure that cron job is running on your system. You can check if it is running and execute it by going to  `Configuration -> Settings -> Scheduled tasks`

**Comment by chiareu** [comment]
Hi, my scheduled tasks are up and executed once a day. Verified on Activity/Event history and are executed regularly. But Activity -> Email/Staff/Client history are empty.
Can't find other setting related to that logs.

**Comment by 4Giedrius** [comment]
Closed as it is the same problem as in https://github.com/boxbilling/boxbilling/issues/231
