### ISSUE TITLE
SMTP/SSL and CKEditor

### ISSUE THREAD

**Issue by FisherSam** [boxbilling/boxbilling#234]
Hi! I do not know where to report bugs and errors, so I'll write here ... I'm sorry if that ... but developers need to know ...
I have a problem with BoxBilling 4.13, does not work SMTP over SSL, the scheduler does not send a notice cron. Such as the version BoxBilling 3.6.11 everything works fine, although there was a problem, solution i described here - http://www.boxbilling.com/forum/boxbilling-support/mail-issues
What could be and how to solve the problem?
In the admin panel, under Settings, Wysiwyg, choose CKEditor, in response to the client, through visual editor CKEditor answer is not added, instead of the standard response appearing shabolon response type:
Hello, It is always a pleasure to help. Have a Nice Day!
For example, through a visual editor markItUp everything works fine.
How to solve the problem with the editor?

**Comment by 4Giedrius** [comment]
Thank you for reporting, issue with CKEditor was fixed and release 4.13.1 is available. Feel free to add these changes 301f74e38bb21940d24d6481cb61d7cfcb83ee05 or download new release.
