### ISSUE TITLE
Service Centova Cast

### ISSUE THREAD

**Issue by newairhost** [boxbilling/boxbilling#237]
API classes for Centovacast are missing namespaces plus I'm getting following error:

Fatal error: Call to a member function post() on a non-object in bb-modules/Servicecentovacast/ccapiclient/ccapiclient.php on line 156

**Comment by 4Giedrius** [comment]
Please let us know if it fixes your issue.

**Comment by newairhost** [comment]
There is no longer error regarding namesapces but I have found few other issues.

/Servicecentovacast/Service.php
after line 386 added new line to solve non-object error:
`$system->cc_initialize($centovacast_url);`

/Servicecentovacast/ccapiclient.php
`-233   $doc = new DOMDocument();`
`+233  $doc = new \DOMDocument();`

**Comment by 4Giedrius** [comment]
Thank you for taking time to report this!

**Comment by rolradio** [comment]
Other usernames for centovacast server instead of the default Admin.
How to create the username for centovacast as input field
Instead of the default "admin"
Is there anybody who can help?
