### ISSUE TITLE
email list

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#238]
![email2](https://cloud.githubusercontent.com/assets/10427411/5859285/fc37376e-a261-11e4-8036-ed2b994d3177.png)
no email list (email registration, creation of tickets, etc.)

**Comment by 4Giedrius** [comment]
It seems that logging to database is disabled. Please try go to `Configuration -> Settings -> Email -> Email Settings` and set `Log sent emails to database` to `Yes`.

**Comment by legion726** [comment]
no work!

**Comment by 4Giedrius** [comment]
Did you enable it? Please submit a ticket with your credentials from members area and we will check what's causing the issue.

**Comment by legion726** [comment]
access #5832
