### ISSUE TITLE
"Passed variable is not an array or object, using empty array instead"

### ISSUE THREAD

**Issue by VeseliD** [boxbilling/boxbilling#239]
Hello all :)
I was using version 3.6.11 for long time and its worked very good.
Few minutes ago, i just tried to upgrade to version 4.13.3, upload files to my dir and after that was run "bb-update.php" and got this error "Code: 4096

Argument 1 passed to Pimple::__construct() must be of the type array, integer given, called in /var/www/vhosts/xxxxxx/public_html/store/bb-di.php on line 17 and defined"

Can somebody help with this?

**Comment by 4Giedrius** [comment]
It seems that vendors are missing. You should download [newest release](https://github.com/boxbilling/boxbilling/releases) instead of downloading/cloning source code.

**Comment by vaidas-lungis** [comment]
Upgrading steps can be found at BoxBilling forum http://www.boxbilling.com/forum/boxbilling-support/faq-please-read-before-posting in second post.
