### ISSUE TITLE
Invoices Are Constantly Regenerated for Expiring Orders (partial fix included)

### ISSUE THREAD

**Issue by TheWizBM** [boxbilling/boxbilling#240]
Invoices are constantly re-generated for expiring orders because the function:
public function setUnpaidInvoice(\Model_ClientOrder $order, \Model_Invoice $proforma)
cannot successfully execute. This is because the ClientOrder model attempts to make an SQL query statement to a table named "ClientOrder" instead of the proper "client_order" table. 

I was unsuccessful in tracing where the Model is executing the ClientOrder value from (didn't appear in the Models I looked at). So, I temporarily put in a workaround in runQuery in rb.php to replace any sql statement with ClientOrder as the table name back to client_order:

$sql = str_replace("ClientOrder", "client_order", $sql); //fix spelling issue

Simple spelling mistake it would seem. Obviously finding where this is originally called would be ideal but this suits my purposes and resolves the issue for now.

**Comment by 4Giedrius** [comment]
Thank you for taking time to report this issue and locating the problem. It seems that there was a problem with function which should convert array of RedBean beans to models. I have fixed that and it seems to be functioning fine now. Could you check that by downloading new release or just changing lines from the commit above and let us know if the issue persists?

**Comment by TheWizBM** [comment]
I have merged the code change and it seems to be working OK with my partial fix disabled as well. I will re-notify if a newer invoice starts showing the same behavior.

Always happy to contribute bug fixes to the project. Thanks for your hard work with development.
