### ISSUE TITLE
Adding Translations to Transifex

### ISSUE THREAD

**Issue by gOOvER** [boxbilling/boxbilling#241]
As i see, the Translations are very old in the Extension Repro. Plaese add Translations to Transifex,

https://www.transifex.com

It have a Github integration and you can easily ship Translations on a Relaese :)

**Comment by gOOvER** [comment]
As i see, the .pot File need Metadata for Uploading to Transifex like:

```
msgid ""
msgstr ""
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Project-Id-Version: Boxbilling Admin\n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: en_150\n"
"X-Generator: Poedit 1.7.4\n"
"X-Poedit-SourceCharset: UTF-8\n"
```

**Comment by 4Giedrius** [comment]
I am happy to let you know that from now on official BoxBilling translation project can be found at https://www.transifex.com/projects/p/boxbilling/
