### ISSUE TITLE
Adopt Recaptcha to API v2

### ISSUE THREAD

**Issue by gOOvER** [boxbilling/boxbilling#242]
It would be great, when in the Spam Addon Recaptcha API v2 will be used.

More info's

https://developers.google.com/recaptcha/intro

**Comment by 4Giedrius** [comment]
I am happy to tell you that reCAPTCHA v2.0 has been added upon your request. Administrator will be able to choose which version to use from admin area, `SpamChecker` extension settings. Feel free to perform changes from commit above or, if you prefer, new release with these changes included will be available shortly.
