### ISSUE TITLE
Remove Licence Check from Boxbilling

### ISSUE THREAD

**Issue by gOOvER** [boxbilling/boxbilling#243]
I my Eye's the Licence Check is not really usefull in an opensource Project... so Please remove it

**Comment by 4Giedrius** [comment]
“Free software” means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, “free software” is a matter of liberty, not price. To understand the concept, you should think of “free” as in “free speech,” not as in “free beer”.

**Comment by gOOvER** [comment]
But whats the sence of the Licence Check??? Only that you force everyone to register at your Outdaed Page ;)

**Comment by nuxwin** [comment]
@4Giedrius 

Well, if you're opening the code to everyone and that the code is distributed under a license which allow any modification and redistribution, nothing prevent a developer to circumvent the license checker and redistribute the software itself.

**Comment by Dylan3304** [comment]
Removing the license is as simple as this:
https://gist.github.com/Dylan3304/014149939b7a8354fa6e#file-gistfile1-php-L65

**Comment by chen369** [comment]
remove this shit!

**Comment by Mecanik** [comment]
+1 guys, remove the license shit ! I paid you a lot of money, even after it`s open source!

**Comment by Sturtuk** [comment]
Customize the License.php from bb-library 

e.g.

public function check()
    {
//        if(!$this->isValid()) {
//            throw new \Box_Exception('License is not valid');
//        }
        return true;
    }

**Comment by A-Stranger1k** [comment]
Remove it ffs
