### ISSUE TITLE
Solution for payment gateways fee management

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#244]
At level site, cart and so, the tax rules are not displayed anywhere. You see them only on amount you have to pay at PAYPAL in our tested case.

How I get here, because my first transaction was over PAYPAL and I loose 6 Pounds on fee because I don't have an option to add that fee on payment method.

So I think to a trick, to add a tax rule who would add that % to the cart. Problem is that the % Tax is not displayed on cart

So all that need some attention and correcting:
1. To display the TAX properly in cart
2. To have a solution for PayPal fee management

A simple implementation is on Tax rules level. 
Create custom tax, example PayPal transaction fee, and here to have possibility to set to be used only Paypal payment method. That because if you have other payment method to not charge the client.
So you can set different fees for each payment method :))

**Comment by vaidas-lungis** [comment]
Can you elaborate more on second issue (2) PayPal fee management?

**Comment by chiareu** [comment]
Hi, I'll try to explain. As we all now for receiving money in Paypal we as sellers are charged some % fee.
Most shops have implemented an option for payments via Paypal, to announce and charge customer supplementary with that Paypal fee if they choose to pay via Paypal.
We need a similar option otherwise we loose money on fees (in my case I lose on one transaction more than BB month/license and is not good.

Now it's my play around situation:
Because that option is not implemented on BB, I make that trick. To add a custom tax, but the nasty part is that the custom tax is applying on all payments methods so there need an config set to witch payments method to apply the tax. It's just an idea.

At BB implementing it's more normal that payment method to have that option to add the processing fee.

On the other side, the idea of more configurable custom taxes may be very useful on different situations.

**Comment by lifehome** [comment]
So what we need is something like "when pay with PayPal, additional charge applies", right?
If so, I'm agree in it.

**Comment by i7Grendel** [comment]
A fair word of warning: PayPal's terms prohibit charging money to let people pay with PayPal. Some still do, but having the feature may give off a wrong signal.

**Comment by 4Giedrius** [comment]
@i7Grendel is right. Excerpt from [PayPal User Agreement](https://www.paypal.com/en/webapps/mpp/ua/useragreement-full#4):  

`4.6 No Surcharges. You agree that you will not impose a surcharge or any other fee for accepting PayPal as a payment method. You may charge a handling fee in connection with the sale of goods or services as long as the handling fee does not operate as a surcharge and is not higher than the handling fee you charge for non-PayPal transactions.`
