### ISSUE TITLE
installing on iis fails with empty($_SERVER['HTTPS'])

### ISSUE THREAD

**Issue by gcphost** [boxbilling/boxbilling#246]
I use II7 and PHP 5.4.24

Installer forces https when https is not available.

Windows IIS returns "off" to $_SERVER['HTTPS'], so empty() would not be a valid check here.

One could do this instead:
                `  if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') {`

**Comment by vaidas-lungis** [comment]
Thank you for contribution! 
New release will come in near future (this or next week) or you can just apply code from commit https://github.com/boxbilling/boxbilling/commit/71bd95fe3a4e7b76b40aa5b7713e494982952d48
