### ISSUE TITLE
Contact us- Internal Server Error

### ISSUE THREAD

**Issue by VeseliD** [boxbilling/boxbilling#248]
Hello.
I am using version 4.14
When i try to send mail from contact us page, always getting this "Internal Server Error"
Can somebody help with this?

Thank you

**Comment by vaidas-lungis** [comment]
Did you checked php_error_log file for errors?

**Comment by 4Giedrius** [comment]
Could you also temporary enable `debug` mode in your `bb-config.php` file to see if there are any error messages?

**Comment by VeseliD** [comment]
There is nothing in error_log.
After enabling debug options, i am getting "Loading .." for while and nothing happening...
This is my config file:

<?php 
return array (
  'debug' => true,
  'license' => 'XXXX',
  'salt' => 'XXXX',
  'url' => 'XXXX',
  'admin_area_prefix' => '/bb-admin',
  'sef_urls' => false,
  'timezone' => 'UTC',
  'locale' => 'en_US',
  'locale_date_format' => '%A, %d %B %G',
  'locale_time_format' => ' %T',
  'path_data' => '/var/www/vhosts/XXXX/public_html/prodaja/bb-data',
  'path_logs' => '/var/www/vhosts/XXXX/public_html/prodaja/bb-data/log/application.log',
  'log_to_db' => true,
  'db' => 
  array (
    'type' => 'mysql',
    'host' => 'localhost',
    'name' => 'XXXX',
    'user' => 'XXXX',
    'password' => 'XXXX',
  ),
  'twig' => 
  array (
    'debug' => true,
    'auto_reload' => true,
    'cache' => '/var/www/vhosts/XXXX/public_html/prodaja/bb-data/cache',
  ),
  'api' => 
  array (
    'require_referrer_header' => false,
    'allowed_ips' => 
    array (
    ),
    'rate_span' => 3600,
    'rate_limit' => 1000,
  ),
)
;

**Comment by 4Giedrius** [comment]
Could you open support ticket in BoxBilling.com members area and send us a link so that we could check what is causing this error?

**Comment by VeseliD** [comment]
Ticket is opened.
From javascript console got this error:

" Uncaught TypeError: undefined is not a functionbb-jquery.js?4.14:74 bb.popupbb-jquery.js?4.14:107 bb.msgbb-jquery.js?4.14:9 $.ajax.errorjquery.min.js?4.14:2 njquery.min.js?4.14:2 o.fireWithjquery.min.js?4.14:4 wjquery.min.js?4.14:4 send.d"

**Comment by vaidas-lungis** [comment]
Issue fixed in [4.14.2 release](https://github.com/boxbilling/boxbilling/releases/tag/4.14.2)
