### ISSUE TITLE
Cron Error

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#249]
Hello 

When i run cron i have bellow error

Notice: Undefined index: client in */public_html/bb-modules/Invoice/Service.php on line 361
Fatal error: Call to undefined function __() in */public_html/bb-library/Box/Exception.php on line 24

when i remove line 61 on */public_html/bb-modules/Cron/Service.php 

$this->_exec($api, 'invoice_batch_invoke_due_event');

there is no error

**Comment by raulr** [comment]
I've the same issue.

It can be resolved if you add the following line on `bb-cron.php` after `bb-di.php` is included:

```php
$di['translate']();
```

**Comment by mdaskin** [comment]
i cant find there is no line included bb-di.php

**Comment by vaidas-lungis** [comment]
Thank you for reporting bug. 
It will be fix in the next release of BoxBilling.

**Comment by vaidas-lungis** [comment]
Issue fixed in [4.14.2 release](https://github.com/boxbilling/boxbilling/releases/tag/4.14.2)
