### ISSUE TITLE
Bitcoin payment

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#251]
i have create bitcoin payment adapter 
May optimize for usage 

<?php
class Payment_Adapter_Bitcoin
{
    private $config = array();
    protected $di;
     public function __construct($config)
    {
        $this->config = $config;
        if(!$this->config['btcaddress']) {
            throw new Exception('Payment gateway "Bitcoin" is not configured properly. Please update configuration parameter "Bitcoin address" at "Configuration -> Payments".');
        }
    }

    /**
     * @param Box_Di $di
     */
    public function setDi($di)
    {
        $this->di = $di;
    }
    public static function getConfig()
    {
        return array(
            'can_load_in_iframe'   =>  true,
            'supports_one_time_payments'   =>  true,
            'supports_subscriptions'       =>  false,
            'description'     =>  'bitcoin',
            'form'  => array(
                'btcaddress' => array('text', array(
                            'label' => 'Your Btc Address',
                            
                    ),
                 ),
            ),
        );
    }
    /**
     * Generate payment text
     * 
     * @param Api_Admin $api_admin
     * @param int $invoice_id
     * @param bool $subscription
     * 
     * @since BoxBilling v2.9.15
     * 
     * @return string - html form with auto submit javascript
     */
    public function getHtml($api_admin, $invoice_id, $subscription)
    {
        $data['btcaddress']           = $this->config['btcaddress'];
        $invoiceModel = $this->di['db']->load('Invoice', $invoice_id);
        $invoiceService = $this->di['mod_service']("Invoice");
        $invoice = $invoiceService->toApiArray($invoiceModel, true);
        $rate = json_decode(file_get_contents("http://www.coinvibes.com/api/v1/tickers/btce/btc_eur"),1);
        $price_in_btc = round($invoice['total'] / $rate['average'],8);
        return "Price in BTC = <strong>".$price_in_btc."</strong>BTC<br>Please send to <strong>".$data['btcaddress']."</strong><br>or Scan QR code your bitcoin app<br><img style='margin:5px' id='qrsend' src='https://blockchain.info/qr?data=bitcoin:".$data['btcaddress']."%3Famount=".$price_in_btc."%26label=CCcamServer.com&size=125'/><br>When You sent your payment <a href='/support' class='btn btn-info btn-small' target='_blank'type='button' data-toggle='modal'>Open Ticket</a> which included your Bitcoin address.";
    }
    public function process($tx)
    {
        //do processing
        return true;
    }
}

**Comment by legion726** [comment]
Thank U. useful to

**Comment by 4Giedrius** [comment]
Please open a pull request regarding this payment gateway in https://github.com/boxbilling/extensions repository.

**Comment by jebwizoscar** [comment]
there are some automated services which can do this work (like Coinbase)
