### ISSUE TITLE
Cant Refund invoice

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#252]
In admin panel refund invoce button not work 

here log

2015-02-06T10:27:21+02:00 INFO (6): Refunded invoice #3360

**Comment by vaidas-lungis** [comment]
Please elaborate more. What payment adapter was used?

**Comment by mdaskin** [comment]
paypal used 
in stable version 3.6.11 when click refund creates refund invoice

**Comment by vaidas-lungis** [comment]
Can you describe what outcome you are expecting after clicking on refund button?

I have ....
I click on ...
and want to get ...

**Comment by 4Giedrius** [comment]
I am closing this issue as we were not able to reproduce this problem. Feel free to give us more detailed explanation it will be reopened.
