### ISSUE TITLE
After database upgrade from 3.6.11, adding new products will always says "reached free version limit"

### ISSUE THREAD

**Issue by ericwongcm** [boxbilling/boxbilling#254]
I have upgraded my boxbilling installation from version 3.6.11 to the latest version 4.14.2. I have run bb-update.php and my boxbilling installation appears to work fine. 

However, when I try to create new products, I always get the error message "You have reached free version limit. Upgrade to PRO version of BoxBilling if you want this limit removed." I continue to get this message even after I deleted almost all products I have.

If I clear the database and re-install boxbilling while using exactly the same files, I am able to create products without such error. This probably means the problem is database related and I suspect something is missing during database upgrade.

**Comment by mdaskin** [comment]
http://yourwebsite/bb-update.php may work for you

**Comment by ericwongcm** [comment]
I have already run http://yourwebsite/bb-update.php 
If I don't run database update, boxbilling won't run anyway.

I am saying AFTER database update, I see this bug.

**Comment by 4Giedrius** [comment]
Did you have any products before you have upgraded to BoxBilling v4.14.2

**Comment by ericwongcm** [comment]
Yes, I have 5 products before upgrading.

**Comment by vaidas-lungis** [comment]
> I continue to get this message even after I deleted almost all products I have.

So how many products do you have?
Do you have a pro license?
Free license is restricted to only 4 products.

**Comment by ericwongcm** [comment]
I have 5 products before boxbilling/database update, i.e. I am already at the product limit.
However, after I do boxbilling/database update, even if I delete most of the products, e.g. leave 1-2 products, Boxbilling continue to show the message "You have reached free version limit. Upgrade to PRO version of BoxBilling if you want this limit removed."

No, I don't have inactive products. I press the DELETE button to get rid of them specifically to test/reproduce this bug.

I am 100% sure the product is deleted from database. I have double check this just now.

Can someone try to reproduce this to check this rather than simply asking the obvious?

**Comment by vaidas-lungis** [comment]
I am sorry i can not reproduce your error. 
Unit tests were created to test existing code.

**Comment by ericwongcm** [comment]
OK, I know the reason. I also have more than 5 products addon in my database which boxbilling is also counting towards the limits.

If I also remove those product addons, the error does not show anymore and I can create new products.
In version 3.6.11, those product addons are not counted towards the limit.

**Comment by vaidas-lungis** [comment]
Thank you for given information. It is very valuable! 
We didn't expect that.
