### ISSUE TITLE
Dottk registrar does not work

### ISSUE THREAD

**Issue by ericwongcm** [boxbilling/boxbilling#255]
Can you test and make sure the Dottk registrar does work?
e.g. I have tested boxbilling ver 4.14.2 using Dottk registrar but the domain checking functionality has been broken since version 3.6.11.

http://www.boxbilling.com/forum/plugins-and-extensions/dottk-registrar-failed-setup

**Comment by vaidas-lungis** [comment]
BoxBilling will not support DotTk registrar. 
It will be removed in next release of BoxBilling

**Comment by ericwongcm** [comment]
Sigh.... I hope someone will have a fix for this in the future though.

**Comment by jebwizoscar** [comment]
change line 293,             return $result["process_availability_check"]; and it should work

**Comment by ericwongcm** [comment]
You are right, changing the line you mentioned (actually it is line 281) makes domain checking work.... even though boxbilling can't register dottk domain name.

jebwizoscar, you have any plans to edit the Dottk code or create new registrar using freenom api?

**Comment by jebwizoscar** [comment]
@ericwongcm I don't even have a freenom reseller account :disappointed:
I don't have a Paypal account, so I can't pay it. I only use bitcoin for payments atm.
Also I'm busy with schoolwork, so I may not have time coding (in the near future)

**Comment by jebwizoscar** [comment]
@ericwongcm use this: https://github.com/jebwizoscar/extensions/blob/master/bb-library/Registrar/Adapter/Dottk.php

**Comment by ericwongcm** [comment]
Well, the link you provided doesn't seems to work. Even the domain name checker is not working whether as is or with that line replaced.

I didn't noticed freedom API needs a paid reseller account. I don't really need to use its API for now, I can register domains manually for the time being.

I am sure someone would be willing to help you pay and get freedom reseller account if you are willing to create the required plugin for freedom and publish it here but that is meaningless if you don't have time to code it.

**Comment by jebwizoscar** [comment]
@ericwongcm I guess I uploaded wrong code...
at least it work for me - demo: http://asac.casa/

**Comment by ericwongcm** [comment]
mm.. no idea, maybe because you are using huraga theme whereas I am using a custom theme that is similar to boxbilling? Anyway, registration of dotTK doesn't work on your test site as well but domain checking does.

I have posted a message on boxbilling forum and someone might want to donate a paid freedom reseller account in the future, so you can try to write the adapter then.

Anyway, you have my gmail e-mail in your test installation if you need/want to contact me.
If you don't mind, sent me a e-mail, so I can discuss other things with you.

**Comment by jebwizoscar** [comment]
@ericwongcm can you try again? I uploaded the wrong code to my server by mistake :(

just tested with new code, and it's fine
domainshare panel

QWERTYPOI.TK	11-FEB-15	11-FEB-16

email

Received: from localhost.localdomain (unknown [85.17.59.82])
	by fakanava.taloha.tk (Postfix) with ESMTP id 41576BFB2D
	for <1@wa.vg>; Wed, 11 Feb 2015 03:48:06 +0000 (GMT)
Subject: Registration complete for QWERTYPOI.TK


Service Panel

Domain details

Domain	qwertypoi.tk
Registration date	Wednesday, 11 February 2015
Expires at	Thursday, 11 February 2016

**Comment by jebwizoscar** [comment]
@ericwongcm registered poiiii.tk and work too

**Comment by ericwongcm** [comment]
@jebwizoscar 
I will try a little later, the problem now is http://www.dot.tk/ is down and I can't check if domain registered is actually registered or not. I have been having problem accessing dot.tk lately.

**Comment by ericwongcm** [comment]
@jebwizoscar
I have registered two dottk domain using your installation but both domain are still showing as available from http://www.dot.tk/

Any idea?

**Comment by jebwizoscar** [comment]
@ericwongcm did you check your e-mail?

**Comment by ericwongcm** [comment]
@jebwizoscar
Yes, nothing in my gmail or spam.
You can see on dot.tk that both domain I registered are still available.

**Comment by jebwizoscar** [comment]
@ericwongcm Oops... default nameserver not set...
check 'I want to use my nameservers' and that should work

**Comment by ericwongcm** [comment]
@jebwizoscar
Yes, it works now after I check 'I want to use my nameservers' and I receive e-mail from dottk.

That means dottk API still works and the dottk adapter can be fixed rather than using freenom API?

**Comment by jebwizoscar** [comment]
@ericwongcm yes. 
https://github.com/jebwizoscar/extensions/blob/master/bb-library/Registrar/Adapter/Dottk.php

**Comment by ericwongcm** [comment]
@jebwizoscar
Strange, I replaced my Dottk adapter with yours but the dottk domain is not registered.
Do you know why? Are you using boxbilling version 4.14.2?

**Comment by jebwizoscar** [comment]
@ericwongcm check nameserver settings and site e-mail settings (that's the problem I faced today)

**Comment by ericwongcm** [comment]
@jebwizoscar
I had just tried setting two default name server and also manually inputting the name server when ordering but didn't work... my site e-mail is no-reply@somedomain.com

I actually noticed I don't receive any e-mails from my installation...
I think I found a new bug..

When I press "Sent test e-mail to staff members" button, I see this error..
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'prefix_boxbill.mod_email_queue' doesn't exist

Looks like a side-effect from my boxbilling 3.6.11 upgrade. I will re-test this on a fresh database and post another ticket for this new found bug.

**Comment by jebwizoscar** [comment]
@ericwongcm better use a fresh install. some orders won't process if message cannot be sent I think.

**Comment by vaidas-lungis** [comment]
@ericwongcm Did you updated BoxBilling to v4 and mod_email_queue is missing? and if you did, was  email extension enabled on previous version?

**Comment by ericwongcm** [comment]
@vaidas-lungis 
I know e-mail was working on boxbilling version 3.6.11. I had previously (a year ago) installed boxbilling and tested e-mail. I can't login to test boxbilling version 3.6.11 anymore because the server I am using is missing "ionCube loader". I can't be bother contacting server admin to fix it since I won't be using boxbilling version 3.6.11 anymore.

**Comment by 4Giedrius** [comment]
Could you try to run following query in your database? It should create missing table for you.
```sql
CREATE TABLE `mod_email_queue` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `to` varchar(255) NOT NULL,
  `from` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `to_name` varchar(255) DEFAULT NULL,
  `from_name` varchar(255) DEFAULT NULL,
  `client_id` int(11) DEFAULT NULL,
  `admin_id` int(11) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `tries` int(11) NOT NULL,
  `status` varchar(20) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by ericwongcm** [comment]
@4Giedrius
Thanks... the query works and test e-mail works now.

**Comment by ericwongcm** [comment]
@jebwizoscar
I think I know why the new dottk adapter is not working. After I clear my database and do a clean install for the database, I noticed the dottk adapter is missing in the list of Domain registrars. 

I only see these three domain name adapter in the list of registrars
Custom	    
Internet.bs	    
Reseller Club

Can you check if you see the same on your installation?

**Comment by 4Giedrius** [comment]
Are you aware that you need to go to `Configuration -> Domain management -> New Domain Registrar` and you will be able to install from there?

**Comment by ericwongcm** [comment]
@4Giedrius 
Thanks for the information, I had forgotten or over-look this option while testing, I see the Registrars now.

@jebwizoscar
Can you check again if your test server is indeed running the same code on the github link you posted? because I have retested this with fresh database and double check that I am using the dottk adapter you posted BUT even domain checker is not working.

**Comment by hackersrage** [comment]
https://github.com/boxbilling/boxbilling/pull/295    DotTK support is now functional with this pull request

**Comment by ericwongcm** [comment]
@hackersrage I tried the DotTK you have submitted but it still does not work when I test it on my server. Even domain checker is not working. I suspect that my inability to use your version and jebwizoscar's version of the DotTK adapter is related to the php version my server is using.

I am using php 5.3.19. I have no idea what you both are using.

**Comment by hackersrage** [comment]
Make sure your credentials are correct. I tested this on PHP 5.2, and 5.4.  Github tested it against multiple php versions. The version of BoxBilling used is the /master branch.

**Comment by ericwongcm** [comment]
@hackersrage Could it be the dotTK adapter you submitted won't work with Boxbilling version BoxBilling 4.15.7? I am not using the /master branch, I am using BoxBilling 4.15.7 release.

I have double check my dotTK login and it is correct.

This is the response I get from the server I had installed boxbilling.
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<dottk>
  <process_ping>
    <status>PING REPLY</status>
    <timestamp>2015-03-22 05:54:39 UTC</timestamp>
  </process_ping>
  <status>OK</status>
</dottk>

**Comment by hackersrage** [comment]
I havn't tested with earlier revisions of BoxBilling. Just found out about this project a few days ago.  It is working fine from here, and while testing, I noticed that some of the responses coming back from the registrar contained HTML, which I then strip as part of this patch.  The message above is good as it shows your server can communicate fine.  Double check the credentials by logging into their reseller portal, and try updating to master branch.  Please let me know.

**Comment by ericwongcm** [comment]
Well, I have just updated my boxbilling to the latest release of 4.15.9. When I use the Dottk adpater you committed, I get a more useful message now that says "Order status	Failed Setup" on the order page, i.e. .......index.php?_url=/order/service/manage/6

It is stated somewhere that you should use the release version of Boxbilling, not the master branch.
Maybe I need to wait for the next major release of Boxbilling before this adapter will work then.

**Comment by ericwongcm** [comment]
@hackersrage
I have just updated my boxbilling to the latest release of 4.16.2. Using your Dottk adapter, domain checker seems to work ok now but I still get "Order status Failed Setup" on the order page.

Does anyone know where I look up the details of the failure?

Btw, the Dottk adapter is not included in the boxbilling 4.16.2.

**Comment by 4Giedrius** [comment]
Please try to enable debug mode in your `bb-config` file and check error log for more information why order is failing.

**Comment by ericwongcm** [comment]
I suppose you mean this line in bb-config?

  'debug' => true,

And I am supposed to see something in error_log file at the same folder as bb-config?
but I don't see anything in error_log file after debug is enabled.
