### ISSUE TITLE
Resending confirmation mail

### ISSUE THREAD

**Issue by mdeboer** [boxbilling/boxbilling#260]
I created a client and tried to log in but I got a message saying that I should verify my email. I had enabled that option so that's fine, problem is that I never received that message and I found no way to re-send that confirmation email.

Where I've done / looked:
- Used control panel (logged in through bb-admin -> login to client area)
- Edit client (set it to active)
- Forgot password (e-mails work fine and password was reset)
- Checked the application log (with debug mode on)
- Checked the queue
- Ran cron multiple times
- Sent test email to staff (worked fine)

There's just no way to re-send the confirmation e-mail or better yet, manually "confirm"/activate the user. It seems the "active" settings have no effect.

Thanks in advance!

**Comment by 4Giedrius** [comment]
Thank you for reporting, you can resend any sent email by going to `Activity -> Email history` and clicking edit icon on the email which you would like to resend. In the meantime I will add confirmation option in client profile for admin.

**Comment by mdeboer** [comment]
I did some more testing and it seems the account confirmation mail was actually never sent and I can't get it to send. I made sure emailing worked correctly (using sendmail), test mails and others all arrive fine hence I was able to change my password. Strangely enough the account confirmation mail never arrives and *also* doesn't show up *ever* in the email history panel.

I appreciate you took the time to make fixes in 1a8859fe566bdf2ee8000c1629bafc16a2b213d9 and I'll check those in the meanwhile! Looking at the code though I doubt this will fix the emailing issue of the actual confirmation email.

Thanks in advance @4Giedrius

**Comment by 4Giedrius** [comment]
Your mentioned commit does not fix mail sending, however it enables you to confirm user from admin area. Talking about your issue, could you try to register with another mail address? It might be that your server's IP is blacklisted (you can check that using [MXToolbox](http://mxtoolbox.com/blacklists.aspx)) and emails do not go where they are intended to.

**Comment by marsoltys** [comment]
this is still true in v4.20 
Confirmation emails are not sent so customers can't login.

That's why I have noticed sale drop for quite long time now :/ ...

**Comment by marsoltys** [comment]
This happend to me. I believe this happend after last upgrade to 4.20.

You need to go to Settings -> Email -> mod_client_signup, backup your template and then reset your template (or simply add confirmation link placeholder within existing template)

I've hope that helps
