### ISSUE TITLE
Multiple payment methods (icons) for one payment adapter

### ISSUE THREAD

**Issue by mdeboer** [boxbilling/boxbilling#261]
Payment gateways like Mollie (dutch) offer multiple ways of paying like iDeal, Paypal, Creditcard. It would be nice to have a way to define multiple payment methods per payment adapter. This would allow people to select their payment preference right from the invoice screen instead of being offered only one payment method (Mollie).

The Mollie API allows an optional parameter (string) to specify the payment method when creating the transaction. The methods they support can be requested through their API and thus are dynamic.

It works with only one icon as Mollie offers a screen to select the payment type so it's not a showstopper but it's a really nice feature to have and would benefit the user experience. When I'm done writing the Mollie module with the current possibilities I would gladly offer my help to make this feature possible. It would be nice to have a little help though!

**Comment by 4Giedrius** [comment]
I am afraid that BoxBilling by default are listing payment gateways, not their payment methods. However as a simple workaround you can create payment gateway, where you can choose in config which payment method to use and then add same payment gateway multiple times with different configuration. Using this way client will be able to see all the payment options Mollie is offering and will be redirected directly to it.
