### ISSUE TITLE
Gettext usage cleanup in code

### ISSUE THREAD

**Issue by mdeboer** [boxbilling/boxbilling#262]
I might be wrong but as I browsed through the code and worked on translations I noticed that most translated strings are not using the _e or __ notation but instead po and pot files add keywords like Box_Exception to be able to find them in code. Trouble is that there's plenty of more methods with strings that need to be translated like Payment_Exception. As far as I know the best solution would be to refactor the code to use _e and __ to mark translatable strings.

Before:
```php
throw new Exception('PHP Curl extension must be enabled in order to use PayPal gateway');
```

After:
```php
throw new Exception( __( 'PHP Curl extension must be enabled in order to use PayPal gateway' ) );
```

Another thing I noticed is the seperation of admin.po and messages.po where as admin.po only contains one string. Unless there is clear code separation between admin code and front-end code I would recommend combining the two. Gettext used the binary .mo files so I don't think there'll be any noticable performance issues and would greatly benefit translatability.

**Comment by vaidas-lungis** [comment]
Admin.pot file merged into messages.pot.
Messages.pot file will have all translations from core, modules and themes
