### ISSUE TITLE
Migrating from encrypted to GitHub version

### ISSUE THREAD

**Issue by 2braincells2go** [boxbilling/boxbilling#263]
Firstly, thanks for opening up the door:)

I had no clue BB was going into open source so installed Version: 3.6.11 and tested for a few months and now paying pro license. For the record I do not mind the small monthly fee as it will help keep the project alive (i hope).

But I have issue:

I have Version: 3.6.11 installed, setup and working. How do I upgrade to the latest GitHub version without starting over?

Many thanks and cheers!

**Comment by nuxwin** [comment]
Hello ;

I thinks that you can follow normal update path ( uploading un-encoded files ).  Need a confirmation but...

**Comment by vaidas-lungis** [comment]
You can find update instructions here: http://www.boxbilling.com/forum/boxbilling-support/faq-please-read-before-posting in second post.
Also keep it mind to turn off webcron if you were using it.

**Comment by 2braincells2go** [comment]
Thank you both for answers. I have to admit my eyesight is very poor and I missed the instruction to upgrade from 3 to 4.
