### ISSUE TITLE
After updating from 3.6.11, e-mail templates not updated accordingly

### ISSUE THREAD

**Issue by ericwongcm** [boxbilling/boxbilling#265]
Hi,

In fresh install of boxbilling version 4.14.2, I see there is a total of 30 e-mail templates BUT in my database which was upgraded from version 3.6.11, there are only 8 e-mail templates.

I can manually replace the e-mail template table I inherited from version 3.6.11 with the e-mail template table from version 4.14.2 but I am not sure if this is the right way to do this or whether there are other things that I need to modify.

In any case, I believe the database upgrade script is missed out this part and this should be added.

Thanks
Eric

**Comment by 4Giedrius** [comment]
Hi, we did not change amount of templates in 4.x version of BoxBilling. If you have modified or deleted some templates before, you can feel free to copy e-mail template table from your old installation to new one. If this is not the case, you can simple regenerate all default templates by clicking on `Generate templates` button in `Configuration -> System -> Email`.

**Comment by ericwongcm** [comment]
Well, I am pretty sure I have never modified the templates on version 3.6.11 of boxbilling, so I have no idea why I only have 8 e-mail templates in my database.

Anyway, using the Generate templates button works to regenerate all the templates.

Thanks
