### ISSUE TITLE
Upgrade to 4.15 error

### ISSUE THREAD

**Issue by VeseliD** [boxbilling/boxbilling#267]
After last upgrade to version 4.15 i got this error

"Unable to find template "partial_pending_messages.phtml" (looked into: /var/www/vhosts/XXXXXXX/public_html/prodaja/bb-themes/boxbilling/html, /var/www/vhosts/XXXXXXXX/public_html/prodaja/bb-modules/Pending/html_client) in "layout_default.phtml" at line 228."

Can somebody help me with this?

**Comment by vaidas-lungis** [comment]
issue is fixed in the [latest BoxBilling release](https://github.com/boxbilling/boxbilling/releases/latest) >4.15.1
