### ISSUE TITLE
Cant see client invoice in PDF

### ISSUE THREAD

**Issue by VeseliD** [boxbilling/boxbilling#268]
"FPDF error: Not a PNG file: /var/www/vhosts/XXXXXX/public_html/prodaja/mskaG0DGbm"

**Comment by 4Giedrius** [comment]
Did you set your company's logo in BoxBilling settings?

**Comment by hostingseguro** [comment]
Same error here! -> output ↓

Notice: getimagesize(): Read error! in /bb-library/PDF_ImageAlpha.php on line 95 Warning: imagecreatefrompng(): Cannot read image data in /bb-library/PDF_ImageAlpha.php on line 96 Warning: imagecreate(): Invalid image dimensions in /bb-library/PDF_ImageAlpha.php on line 97 Warning: imagecolorallocate() expects parameter 1 to be resource, boolean given in /bb-library/PDF_ImageAlpha.php on line 100

FPDF error: Not a PNG file: /mskaMFXPve

**Comment by 4Giedrius** [comment]
Could you give us URL to your logo image here or by sending us ticket from client area, so that we could check what is causing the problem?

**Comment by hostingseguro** [comment]
This is my logo -> https://clientes.hostingseguro.co/logo.png

**Comment by 4Giedrius** [comment]
I have tried to generate several various PDFs with your logo and it seems to be working fine. In order to debug further I need you to create new staff member with full permissions and send us credentials by opening ticket from members area.

**Comment by hostingseguro** [comment]
Don't worry, I've fixed this by recompiling my php installation, anyway Thank you very much!

**Comment by zeigerpuppy** [comment]
I am having this same problem after a new install, 
it's a valid PNG file, my error is
FPDF error: Not a PNG file: /var/www/billing/mskaOmGl7d

**Comment by atulbhalerao** [comment]
Same Problem as @zeigerpuppy ay solution ??

**Comment by webdesires** [comment]
We've had this problem too and we fixed it using the following:
[https://webdesires.co.uk/blog/boxbilling-pdf-invoice-fpdf-error/](https://webdesires.co.uk/blog/boxbilling-pdf-invoice-fpdf-error/)

**Comment by atulya** [comment]
@webdesires i did follwed the steps but no effect same problem

**Comment by webdesires** [comment]
Would you perhaps be interested in letting me take a look? Catch us on Skype: WebDesires
