### ISSUE TITLE
Unable to submit ticket when Paid support is enabled and helpdesk selected

### ISSUE THREAD

**Issue by ericwongcm** [boxbilling/boxbilling#271]
I noticed there is a new module called Paid support in the version 4.15.1 and I was trying to see whether it will suit my needs but I noticed a bug...

After Paid support plugin is enabled and a specific helpdesk department is checked for Paid support, I am unable to submit ticket as a client.

I will get a blank, white pop up instead of ticket successfully submitted.

**Comment by vaidas-lungis** [comment]
Can you elaborate more on this issue? I could not reproduce this error. 
Do you have any errors logged in php_error_log file?
What BoxBilling theme you are using?

**Comment by vaidas-lungis** [comment]
We will release New BoxBilling minor version later this day fixing this issue

**Comment by ericwongcm** [comment]
I suppose this means you don't need additional information from me then...?

**Comment by vaidas-lungis** [comment]
I have managed to reproduce this error when I left error message blank.

**Comment by vaidas-lungis** [comment]
[New release is now available to download](https://github.com/boxbilling/boxbilling/releases/tag/4.15.2)

**Comment by ericwongcm** [comment]
I see the error saying Insufficient funds appear when I try to create a ticket as a user but I don't see how the user obtain this fund in the first place....

As usual, the extension site is still missing and there is no guide/document for additional information.

**Comment by 4Giedrius** [comment]
I am sorry for information scarcity, extensions site are under development at the moment. 

User can add funds by going to `Payments history` and entering desired amount in textbox. Invoice will be created and as soon as payment will be received, funds will be added to account.

**Comment by ericwongcm** [comment]
This works but it seems like this functionality is missing a critical component, i.e. a way to allow user and admin to see how much funds a specific user has left in his account.

After the user used the add funds button and the invoice marked as paid. When logged in as user, going into the Payment history shows nothing there. I can't figure out how the admin can tell how much funds that user account has remaining from this transaction too..

**Comment by vaidas-lungis** [comment]
In huraga theme cilent can see its balance in client area. At the moment this information is missing on admin side.  

As i can guess you are using boxbilling theme?

**Comment by vaidas-lungis** [comment]
Missing item in payment history list - confirmed

**Comment by vaidas-lungis** [comment]
As a matter of fact admin is able to see how many funds are in client account. Just go to client manage page Payments tab.

Missing payment item in history fix will be available shortly.

**Comment by vaidas-lungis** [comment]
Fix will be included in next major release

**Comment by ericwongcm** [comment]
Yes, I am using boxbilling theme.
Using boxbilling theme, I don't see anything in Payments tab after the user use add funds and the admin mark it as paid.

I see the user have balance in huraga theme, this still makes no difference for the admin view though. I suppose this is fixed in your new patch?

**Comment by vaidas-lungis** [comment]
Payments tab is in admin area in client manage page.

**Comment by ericwongcm** [comment]
That is the page I was looking at and I don't see anything there after user adding funds via invoice.
The payment tab only shows payment if the payment was added by the admin.
