### ISSUE TITLE
 Uncaught ReferenceError: docReady is not defined index.php:152 (anonymous function)

### ISSUE THREAD

**Issue by evnix** [boxbilling/boxbilling#272]
this problem is there in latest version 4.15.2 from error console

 Uncaught ReferenceError: docReady is not defined index.php:152 (anonymous function)

**Comment by evnix** [comment]
ok the problem was with the default theme "huraga"

**Comment by 4Giedrius** [comment]
Could you elaborate more - what was the problem? Did you manage to fix it? We want to know it if there is something wrong so that we could fix it or if there is not anything wrong you could still elaborate more in case someone will experience it. Your input will be very appreciated!

**Comment by evnix** [comment]
The error is shown below and none of the links work because of that error.
Note: it is a clean install

![screenshot from 2015-02-23 19 26 42](https://cloud.githubusercontent.com/assets/1516273/6328922/ffd2c2fa-bb91-11e4-8033-f6e99172f126.png)

**Comment by 4Giedrius** [comment]
Thank you for clarifying. I have located and fixed the problem. Please perform changes from commit above or download [latest release] (https://github.com/boxbilling/boxbilling/releases/latest)
