### ISSUE TITLE
custom form doesn't show up for default theme

### ISSUE THREAD

**Issue by evnix** [boxbilling/boxbilling#273]
custom form doesn't work in default theme as shown below 
![screenshot from 2015-02-23 19 31 33](https://cloud.githubusercontent.com/assets/1516273/6329008/c449d8da-bb92-11e4-8ec5-6fd8a5864482.png)

Now it works in theme: haruga
![screenshot from 2015-02-23 19 32 20](https://cloud.githubusercontent.com/assets/1516273/6329014/d0c387aa-bb92-11e4-8b27-c1e775becf4e.png)

**Comment by 4Giedrius** [comment]
It has been fixed(https://github.com/boxbilling/boxbilling/commit/c861baa966420316464b82a426aec5a7ad756c14) and there is [new release available to download](https://github.com/boxbilling/boxbilling/releases/latest).

**Comment by evnix** [comment]
amazing support!!
