### ISSUE TITLE
Popup orderbutton registration

### ISSUE THREAD

**Issue by hostingseguro** [boxbilling/boxbilling#274]
Please add this -> " {% import "macro_functions.phtml" as mf %} " <- to first line in -> https://github.com/boxbilling/boxbilling/blob/master/src/bb-modules/Orderbutton/html_client/mod_orderbutton_client.phtml

Without it the recaptcha not works (not shown), in registration tab.

**Comment by 4Giedrius** [comment]
It has been fixed(https://github.com/boxbilling/boxbilling/commit/c861baa966420316464b82a426aec5a7ad756c14) and there is [new release available to download](https://github.com/boxbilling/boxbilling/releases/latest).

**Comment by hostingseguro** [comment]
Perfect!
