### ISSUE TITLE
client name сyrillic

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#277]
Does not display the name and surname of the Cyrillic alphabet in the admin (russian)
![c1](https://cloud.githubusercontent.com/assets/10427411/6393906/8ec2ac00-bdd6-11e4-8a40-49a222463adc.png)
![c2](https://cloud.githubusercontent.com/assets/10427411/6393908/9490b9ec-bdd6-11e4-82f1-7a659bbff062.png)

**Comment by 4Giedrius** [comment]
Please try to perform changes from commit above. It should solve the problem you are experiencing.
