### ISSUE TITLE
Resell.biz API

### ISSUE THREAD

**Issue by codexify** [boxbilling/boxbilling#278]
I tried every possible option to integrate Resellbiz into my box billing but every time anyone tries to order a domain, this message shows up
Access Denied. You are not authorized to perform this action.

**Comment by vaidas-lungis** [comment]
You need to whitelisted your Hosting server IP's
You have to do this in the Settings > API section

**Comment by victorycck** [comment]
I whitelisted your Hosting server IP's in Settings > API of resell.biz and resellerclub but the error is still there. What else needs to be done?

**Comment by zar00731** [comment]
I have a ready domain, hosting, subscription and product billing system completely developed by me for sell. If anyone need it, can contact me anytime.
