### ISSUE TITLE
serviceboxbillinglicense

### ISSUE THREAD

**Issue by juggalox2008** [boxbilling/boxbilling#279]
when setting up boxbilling license to sell and when you go to set the api key on bb-admin/extension/settings/serviceboxbillinglicense and click update it goes to api/admin/serviceboxbillinglicense/config_updateclass= then it says {"result":null,"error":{"message":"Unknown API call admin\/serviceboxbillinglicense\/config_updateclass=","code":879}}

**Comment by 4Giedrius** [comment]
It seems that there was a typo in template. Please perform changed from commit above and it should start working fine. Thank you for reporting this issue!
