### ISSUE TITLE
client can't login if "Require email confirmation" set to "yes"

### ISSUE THREAD

**Issue by amsainfor** [boxbilling/boxbilling#281]
If i set to yes "require email confirmation" on "configuration->settings->client settings->require email confirmation" all clients with "NULL" value on column "email_approved" in boxbilling db cannot login anymore.

For new clients confirmation email never sent.

I update to new version (4.15.4) cleaning all data on folder before, and run after that /bb-update.php

Thankyou.

**Comment by 4Giedrius** [comment]
Please add function from commit above to your code, go to `Client settings` and click on `UPDATE` button. It should set all users you had before enabling this functionality as confirmed.

**Comment by 4Giedrius** [comment]
I have added permanent fix for this problem. If `Require email confirmation` option will be enabled while there are some users who did not confirm their emails, they will get confirmation link when trying to sign in into members area.
