### ISSUE TITLE
Security Risk

### ISSUE THREAD

**Issue by hostingseguro** [boxbilling/boxbilling#283]
Hello,

I have a serious bug to share, I opened a ticket in boxbilling site because would be dangerous to publish the bug before being repaired, this affect from the stable to the current version in development.

My ticket is the #5957.

I await your response soon.

Thank you.

**Comment by vaidas-lungis** [comment]
Confirmed. Thank you for the report

**Comment by hostingseguro** [comment]
Dont Worry,

If you need a security expert or a admin server, do not hesitate to contact me.

Thanks to you.

**Comment by chiareu** [comment]
Hm that's a serious issue, please keep us informed about a solution.

**Comment by vaidas-lungis** [comment]
We advise to use [latest version of BoxBilling](https://github.com/boxbilling/boxbilling/releases/latest)

In order for other users not to be misleaded I must say that it was not security issue as it did not pose a threat to sensitive data or essential BoxBilling's features. 
There was an issue related to IPN (Instant Payment Notification) which was patched and new release is available to download. 

Thank you for your support and contribution. We really appreciate that.
