### ISSUE TITLE
huraga theme, Inquiry Form not Available for guest.

### ISSUE THREAD

**Issue by liptanbiswas** [boxbilling/boxbilling#288]
When using huraga theme, its not possible to create any inquiry without logging in, thus contact us form is not working for this theme. and like other themes the default screen is the login form, which should be changed.

**Comment by vaidas-lungis** [comment]
This is how hugara theme suppose to do. 

You can edit everything what you see in BoxBilling. All templates are open source and are available at **bb-themes** folder.

If you are creating your own theme you can use **myboxbilling** theme as an example. You can change any page in boxbilling by copying the file you want to override from the original bb-themes/boxbilling/html folder to your theme folder.

In your case I suggest copying **bb-themes/myboxbilling** to **bb-themes/danboxbilling**. Remove all files from **bb-themes/danboxbilling/html/** and start copying the files you need to be replaced from bb-themes/boxbilling/html to bb-themes/danboxbilling/html. What you need now is to copy bb-themes/boxbilling/html/mod_index_dashboard.phtml and edit it for your needs. After you are done with the modifications, please remember to enable the new theme in admin area.
