### ISSUE TITLE
Database connection issues

### ISSUE THREAD

**Issue by PingLord** [boxbilling/boxbilling#290]
Hello,

I got the latest version from here ( 4.15.7 ) and when i try to install and get to database configuration , it says it cannot connect to the database even though i can connect to it from the command-line.
I tried also the manual completion of the bb-config.php and got the following error : 

Code: 4096

Argument 1 passed to Pimple::__construct() must be an array, integer given, called in /var/www/html/clientarea/bb-di.php on line 17 and defined

With debugging on true i get verbose error description : 

File: "/var/www/html/clientarea/bb-vendor/pimple/pimple/lib/Pimple.php"

Line: "49"

Trace:
#0 /var/www/html/clientarea/bb-vendor/pimple/pimple/lib/Pimple.php(49): handler_error(4096, 'Argument 1 pass...', '/var/www/html/c...', 49, Array)
#1 /var/www/html/clientarea/bb-di.php(17): Pimple->__construct(1)
#2 /var/www/html/clientarea/bb-vendor/pimple/pimple/lib/Pimple.php(113): {closure}(Object(Box_Di))
#3 /var/www/html/clientarea/index.php(16): Pimple->offsetGet('config')
#4 {main}

Any help would be highly appreciated.

**Comment by vaidas-lungis** [comment]
Please check your config file. Do you use config file from 3.6v?
Config file was changed in new 4+ version.  It should return array. 
Example is in [bb-config-sample.php](https://github.com/boxbilling/boxbilling/blob/master/src/bb-config-sample.php)

**Comment by PingLord** [comment]
But without config file and install from scratch , it cannot connect to db even if i give it root pass and user and i try also from console.
Do i have to write the config file myself? if thats the case , how i can add the administrator user if i dont use the setup wizard from the browser?

**Comment by vaidas-lungis** [comment]
Are all requirements met?

Install script:
- creates bb-config file, writes information into it;
- imports database structure;
- creates admin client;
- sends greeting mail;

Does install wizard create bb-config file?

Try to rename bb-config-sample.php file to bb-config,php  give it a 777 permissions and run install script again. After install make bb-config.php file permissions to 644.

Installation without wizard:
You can import install/structure.sql file into your database. 
Rename bb-config-sample.php file to bb-config. Fill config values;
Open in browser [yoursite.com]/`index.php?_url=/bb-admin/staff/login` and create admin client.

**Comment by PingLord** [comment]
Hello,

The wizard creates an empty bb-config file , then in the wizard i fill up the database fields, i press next and it says it cannot connect to database.I also gave 777 permissions to the bb-config file and still same issue.
I will use the installation without wizard this weekend and let you know how it behaves.

Thanks for the quick responses.

**Comment by 4Giedrius** [comment]
Let us know how it goes, if the problem still persists please open support ticket from members area and send us your credentials, so that we could check what is causing the problem.

**Comment by hemant17** [comment]
The problem is still there.

**Comment by TuxMay** [comment]
@hemant17 is your issue with regards to installing BoxBilling?

**Comment by hemant17** [comment]
@TuxMay yes when i click on the next after fill db detail not not going anywhere and in console it's getting check db no found.

**Comment by TuxMay** [comment]
@hemant17 This is due to you using PHP 7.x, which is not yet supported by BoxBilling. Please use PHP 5.6.x or lower.
