### ISSUE TITLE
Better orderbutton dimensions

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#291]
The iframe container for orderbutton are set on 100% height.
On most cases this is too much for any page rendering because will fail in 2 scroll bars on page. One for iframe and one for the page itself.

A better setup is to put a limit of 80%.

/bb-modules/Orderbutton/html_client/mod_orderbutton_js.phtml

on line 98 change the value:
this.style.height = '80%';

**Comment by vaidas-lungis** [comment]
Hello, 
Thanks for suggestion. 
Can you attach a screenshot of two scroll bars? 
how 80% value will help if windows is very narrow and product list is long?

**Comment by vaidas-lungis** [comment]
This will be fixed in next BoxBilling release
