### ISSUE TITLE
How does similar articles block work?

### ISSUE THREAD

**Issue by ericwongcm** [boxbilling/boxbilling#293]
I have installed BoxBilling 4.15.7 and I am using boxbilling theme.
I have created 19 articles for the knowledge base so far and they are placed in different category.

I noticed ALL of the articles in the knowledge base are actually listed under similar articles block at the bottom. This means the "similar articles block" isn't working to show a limited number of similar articles.

Can someone explain why I see this behaviour? or is there a setting somewhere to limit the number of similar articles shown?

If I have 100 articles in KB, that would mean I would see 100 articles in the similar articles block, this simply does not make sense....

Thanks

**Comment by vaidas-lungis** [comment]
Thank you for reporting a bug. 
There was missing per_page variable to limit result set. 
Speaking of similar articles - no magic is done. It only fetches articles from same category.

If you can apply changes made in this commit https://github.com/boxbilling/boxbilling/commit/84bd79e024b72dd1a8a0ed76264d2adc3486e8a0 or we are planing to release new BoxBilling version in near future

**Comment by ericwongcm** [comment]
I tried applying that commit manually but the changes in 
src/bb-modules/Kb/Service.php
results in this error

An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4") in "layout_default.phtml" at line 146.

**Comment by ericwongcm** [comment]
Works now after I manually apply that commit. The similar articles block only shows 5 articles out of the lot now :)

Thanks
