### ISSUE TITLE
Why do I need a license?

### ISSUE THREAD

**Issue by Dylan3304** [boxbilling/boxbilling#296]
Since this is open source, why do I still need a license. Also, why does the free license still have its restrictions?

**Comment by Dylan3304** [comment]
PDO_MySQL wasn't installed correctly. Since this is open source, why do I still need a license. Also, why does the free license still have its restrictions?

**Comment by 2braincells2go** [comment]
I made the mistake of installing version 3.6.11 directly from boxbilling site. It has restrictions. Had to start over and install latest version from here at GitHub to rid myself of restrictions.

**Comment by Dylan3304** [comment]
I did Install 4.* from GitHub...

**Comment by Dylan3304** [comment]
See my pull request, I think that might have fixed the licensing issue I was having.

**Comment by vaidas-lungis** [comment]
Your question was already answered here https://github.com/boxbilling/boxbilling/issues/243#issuecomment-71649959
