### ISSUE TITLE
Please change lines.

### ISSUE THREAD

**Issue by hostingseguro** [boxbilling/boxbilling#298]
The following lines should be changed by causing error.

https://github.com/boxbilling/boxbilling/blob/master/src/bb-modules/Api/Controller/Client.php#L154

to:

throw new \Box_Exception('Authentication Failed', null, 201);

https://github.com/boxbilling/boxbilling/blob/master/src/bb-modules/Api/Controller/Client.php#L158

to:

throw new \Box_Exception('Authentication Failed', null, 202);

https://github.com/boxbilling/boxbilling/blob/master/src/bb-modules/Api/Controller/Client.php#L162

to:

throw new \Box_Exception('Authentication Failed', null, 206);

Thank you!

**Comment by 4Giedrius** [comment]
Thank you for reporting. It has been fixed and new release will be available shortly.
