### ISSUE TITLE
Admin Order Overview - Orders with Add-on price display

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#301]
On Admin/Order/Overview

For orders who include add-on the total amount are not displayed correct.
The table show only amount for main order not including the add-on value.

On Overview the total order should be displayed if there is add-on active.
Ex: Order value 50E and add-on 20E. Total is 70E but on overview are displayed only order itself (50E)

Second recommendation. the Title is shorted to strictly. Need it to be listed more characters.
Ex. we have a product name like: Managed VPS - StartVPS for.... the domain name it's cut :)) and it's hard to find who and what.

**Comment by vaidas-lungis** [comment]
Regarding order amount is related to my answer https://github.com/boxbilling/boxbilling/issues/303#issuecomment-88079387  

As I mentioned addon has its own order which is hidden by default. If you want to addon orders in order list please change "Show addon orders in orders list" setting at "extension/settings/order"
