### ISSUE TITLE
Products Addon - for existing orders

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#302]
Hi for example we have an active order. StartHosting let say. And we want to add an addon for that order. Example one dedicated IP.

There is no option on client side or admin panel to add a new addon to an an existing order.

**Comment by vaidas-lungis** [comment]
Addon is a product property not order's.

You setup up product with optional addons (products) as bonus.

Client makes order for product and can select additional addons.

 So later on you can not add addons to order as addon is not order property but products.

I am very hopeful that i expressed myself clearly.

**Comment by chiareu** [comment]
OK, I understand now, the logic behind of add-on. In my mind I think about as something who a client can opt in + basic service. Like additional IP or some

**Comment by chiareu** [comment]
And to complete my explanations about. As the add-on is managed as a stand alone option/product with his own life-cycle attached to one product why there not be an option to add one new add-on to an  existing product witch is related to.

Ex. WHMCS has that option. to add add-on.

And another problem related, if I create an order from admin, can't add add-on to it :)

**Comment by 4Giedrius** [comment]
Thank you for your insight, we will consider adding your requested features in future releases.

**Comment by vaidas-lungis** [comment]
In admin side you can create additional order with product which will represent addon instead of attaching add-on to order

**Comment by chiareu** [comment]
But to do that we must configure that specific service as Add-on and Product as well :)))
Example:
Add-on: Dedicated IP (for use as an option to a product)
Product: Dedicated IP (for use as a stand alone product and here we don't have the option to specify that this service is available only for a specific product/package)

So here we have a dilemma :)) it's more useful that add-on can be added as an option to a order/product and later when that service is active. It's a development idea, think about.

**Comment by sacredwebsite** [comment]
This sees to be very useful to have. As even ordering from admin side currently does not allow for selecting an addon.
