### ISSUE TITLE
Auto Invoice/renewal for existing orders - add-on problem

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#303]
We have an Order with and Add-on.
When that order was automatically renewed, 2 Invoices was generated.
One for each product (main product and add-on).

When order was placed, the first invoice has two items, product and add-on.
Now we gave two invoices. and that are not good at all.

2 invoices, means, 2 Paypal payments and that near double the fees  to accept that money.

Wrong wrong logic

**Comment by vaidas-lungis** [comment]
BoxBilling separates main product order and addon product after cart checkout. Add-ons are like ordinary orders with its own lifecycle. 

We can get situation where main product and addon renewal dates are not the same. For example shared hosting for 3 years and free domain just for 1year. We just can't bind them together as one as it will lead to another set of problems.  

Addon is just additional benefit/bonus when creating first  main product order.

There is a "Show addon orders in orders list" setting at "extension/settings/order" to show or hide addon orders in order list.

**Comment by chiareu** [comment]
OK understand the logic, I'll adapt my needs on it. thanks
