### ISSUE TITLE
Proforma vs Invoice Issue date problem.

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#307]
Hi guys, I have running few months already on BB pro so I observe some logic that must be enhanced on Proforma vs Invoice. 
Now Proforma it's generated on order or recurrent and has a date.
When it's marked as payed it become Invoice with own Number but with the old date of Proforma. The invoice shall have her date, when are generated as an Invoice or transformed from Proforma to Invoice.

WHY!

Let me explain steps:
1. Client X put a new order and Proforma 00001 are issued on date 25.01.2015
2. Client Y put an order and Proforma 00002 are issued on date 30.01.2015

3. Client Y make a payment on 30.01.2015 and Invoice 00001 are issued with date 30.01.2015
4. Client X make a payment later on 31.01.2015 and Invoice 00002 are issued with date 25.01.2015.

Now we have a fiscal regulation problem. Invoice 00002 has issued with date before 00001 and that technical it's an accounting problem.

For that reason the INVOICE shall have her own date.

**Comment by vaidas-lungis** [comment]
Invoice has 6 dates fields in database:
- created_at (You are referring as issued_at)
- paid_at
- updated_at
- due_at
- reminded_at 

Invoice generation script uses created_at field for invoice date. We can change it to paid_at and it will solve your issue? What your thoughts on this?

**Comment by chiareu** [comment]
Hi, I think that changing to paid_at it's perfect.
In that case we have:
Proforma date: created_at
Invoice date: paid_at

That changes shall be made on both PDF generation script and Dashboard (client/admin) view.

**Comment by vaidas-lungis** [comment]
Fix will be available in the next major BoxBilling release.
