### ISSUE TITLE
url for public tickets

### ISSUE THREAD

**Issue by lowformat** [boxbilling/boxbilling#308]
the install path will always redirect me to the log-in, is there a way to show products and be able to receive public tickets in the contact form with out having the user to visitor to create an acc?

**Comment by vaidas-lungis** [comment]
Huraga theme does not have this ability at the moment. It requires user to log into system. 

Solution:
* use boxbilling theme
* completly remove redirect to login form for unauthorized user from Huraga theme.
Redirect code is here:  https://github.com/boxbilling/boxbilling/blob/master/src/bb-themes/huraga/html/layout_default.phtml#L43-45 But this can lead to undesired results.
To avoid the situation when a new version is released and old theme is overwritten, You can simply rename bb-themes/boxbilling to bb-themes/mytheme and rename the theme in manifest.json file.

**Comment by lowformat** [comment]
thanks, before i attempt to integrate the contact form unto the existing website, is there anything that prevent me or will brake the code if i grab the code from mod_support_contact_us.phtml and implement it onto the main website contact from for a complete seamless integration and still use the hugara theme , and replys are sent via emails , i could try to code this , as am new to the project i would like more info about the hooks used ,

**Comment by vaidas-lungis** [comment]
Updated BoxBilling documentations can be found at docs.boxbilling.org at the moment. 

You can edit everything what you see in BoxBilling. All templates are open source and are available at **bb-themes** folder. Just duplicate folder, rename and customize it
