### ISSUE TITLE
mass mailler dont use smtp settings

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#309]
when i try to send mail all members mass mailler dont use smtp setting only using php mailler

**Comment by 4Giedrius** [comment]
Are you using newest release of BoxBilling? Is SMTP enabled in settings? Please open support ticket from members area so that we could assist you better.

**Comment by mdaskin** [comment]
yes latest realese i have installed all mails sent with relay host only mass mailler use php mailler

**Comment by 4Giedrius** [comment]
It has been fixed (https://github.com/boxbilling/boxbilling/commit/d8f92421c42b84f8407f227de752118b56f0036a) and will become available in next major release. In the meantime feel free to perform changes manually.
