### ISSUE TITLE
emailed links gives "client not loged in"

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#311]
hello

when notification email send user if use links gives error "client not logged in" 
may redirects automaticly login page

**Comment by vaidas-lungis** [comment]
What theme you are using? 
I could not reproduce this issue as client is redirected to login page.

**Comment by mdaskin** [comment]
im using huraga

**Comment by vaidas-lungis** [comment]
can you provide a link or create a support ticket to better assist you.

**Comment by mdaskin** [comment]
ok thanks
