### ISSUE TITLE
order button not work on wp

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#312]
when i try to use order button on wordpress there is an error 
js line 24 "        $(document).keyup(function(e) { // esc"

but using fresh blank html file works good

**Comment by vaidas-lungis** [comment]
Does jQuery loads before the BoxBilling js script?

**Comment by mdaskin** [comment]
before i used 4.14 it was work but i have updated today 4.16.2 not work

i sended my webpage with email
![orderbutton](https://cloud.githubusercontent.com/assets/10865015/7233127/2178decc-e788-11e4-8a3c-1f92d93ddf89.png)

**Comment by mdaskin** [comment]
fixed i have added this js on wordpress header 

 <script src="http://*******/bb-themes/huraga/assets/js/libs/jquery.js"></script>

**Comment by lukapaunovic** [comment]
I have this issue too, help!
