### ISSUE TITLE
[Feature request] attachments for licenses 

### ISSUE THREAD

**Issue by DrakeNn** [boxbilling/boxbilling#314]
add the option to upload downloadable files for the license, eg the user can download the same file script.zip requires the license key you have purchased. or link 2 products (Download and License) if the user purchases a license obtained free downloadable product.

In advance thank you very much.
very good work. I have acquired a PRO license system

**Comment by 4Giedrius** [comment]
Honestly, this is the first time someone requests feature like this, so I believe that this is an edge case feature. We have two separate modules for license and downloadable product, so you can easily merge these two modules to fit your needs by copying methods/views and slightly modifying them.
