### ISSUE TITLE
Mail mod_servicehosting_activated is not send

### ISSUE THREAD

**Issue by lolmensem** [boxbilling/boxbilling#315]
Hi,

All my mails are sended correctly. However, the 'mod_servicehosting_activated' is not been send. It only sends when i force in adminpannel 'activate'.

When an user pays and the order is by the system autmaticly marked as activated, it does not send.

**Comment by lolmensem** [comment]
I see that it only won't send when a paypal transaction (and maybe a custom) is made....

**Comment by 4Giedrius** [comment]
Could you open support ticket from members are in boxbilling.com so that we would be able to assist you better? We will look into this issue.
