### ISSUE TITLE
[Feature Request]  apply taxes in all countries except a certain country

### ISSUE THREAD

**Issue by DDynamic** [boxbilling/boxbilling#319]
1. As Sellers, we are charged various fees for various gateways. Some gateways charge a flat percentage rate, while others charge a percentage and a flat rate (e.g. Stripe charges $0.30 + 2.9%) on the taxes page, we should have the ability to specify a percent and a flat rate.
2. It would also be great to apply taxes in all countries except a certain country. Like if you are charge an additional currency coversion fee.

**Thank you in advance, and I'd love to hear other people's input on this!**

**Comment by 4Giedrius** [comment]
More suggestions for issue https://github.com/boxbilling/boxbilling/issues/244
