### ISSUE TITLE
Resellbiz Hosting server

### ISSUE THREAD

**Issue by sal404** [boxbilling/boxbilling#325]
I need to add resell.biz hosting server on boxbilling. they use their own control panel.
here is their api related information:

http://www.resell.biz/knowledgebase/questions/480/API-+Accessing%2C+Verification%2C+Fancy+and+Plain+methods

Please help someone :(

**Comment by 4Giedrius** [comment]
ResellBiz registrar adapter is already implemented and you can find it [here]( https://github.com/boxbilling/boxbilling/blob/master/src/bb-library/Registrar/Adapter/Resellbiz.php).

**Comment by sal404** [comment]
Only Domain registrar implemented. I also using their hosting. I need hosting server. You should take a look on this lnk. They have their own control panel. Its not WHM

**Comment by 4Giedrius** [comment]
I am afraid we do not have plans to implement resell.biz hosting server, however you can feel free to do it by yourself or order custom development service.
