### ISSUE TITLE
Product without login 

### ISSUE THREAD

**Issue by lorddanger** [boxbilling/boxbilling#326]
I have installed new 4.17 but now client cannot see the product list without login 
Anyone help me out how i can get it a before like 
New client can see the product list without making account and can login or create new account at the time of check out

**Comment by nuxwin** [comment]
Hello ;

You must switch to older layout. See in theme settings ;)

**Comment by 4Giedrius** [comment]
@nuxwin is right - unfortunately `huraga` theme does not have public views, so you either can [use order popup](http://docs.boxbilling.org/en/latest/reference/tutorials.html#how-to-add-order-popup-to-custom-theme) or switch back to `boxbilling` theme.
