### ISSUE TITLE
Domain order does not allow to place Domain Transfer order

### ISSUE THREAD

**Issue by samapco** [boxbilling/boxbilling#327]
Domain registration order does not allow for placing orders for domain transfers. It only has "Register a new domain" and no option for Transfer domain

**Comment by 4Giedrius** [comment]
Which domain registrar are you using? It might be that registrar does not support domain transfers or this feature is not enabled.

**Comment by samapco** [comment]
Thanks you for the quick response. 
I'm using Resell.biz

**Comment by samapco** [comment]
I have actually gone through this file /boxbilling/bb-modules/Servicedomain/html_client/mod_servicedomain_order_form.phtml and it doesn't have any form fields that handle Domain transfer.

**Comment by 4Giedrius** [comment]
You are right, sorry about that. It seems that domain transfer option was missing from huraga theme, so I went ahead and added it to `mod_servicedomain_order_form.phtml` template. Could you replace this template with [new one](https://github.com/boxbilling/boxbilling/blob/develop/src/bb-modules/Servicedomain/html_client/mod_servicedomain_order_form.phtml) and let us know if it works as intended?

**Comment by samapco** [comment]
Thank you very much. It is working for me now.
