### ISSUE TITLE
2CO confrimation 

### ISSUE THREAD

**Issue by lorddanger** [boxbilling/boxbilling#328]
I have set up the 2co gateway , after payment i am getting this error 
I have det Direct return as mentioned in my BB 2CO set up page 
{"result":null,"error":{"message":"Invoice id could not be determined for this transaction"}}

**Comment by lorddanger** [comment]
ok it was because of the url encode can any tell how to get rid of it

**Comment by 4Giedrius** [comment]
Could you be more specific about the issue you are having?

**Comment by lorddanger** [comment]
I place order 
move to check out page 
redirected to 2co payment page 
after successfully payment 2CO send me back to my site 
there this comes
{"result":null,"error":{"message":"Invoice id could not be determined for this transaction"}}

after checking down more i think its because the redirected link have url encode 
like %3f etc 
the link on which i was redirected the issue this part of link because of the encode %3f etc 
BB is not able to find the bb_invoice_id because of %26bb_invoice_id%3D

x_receipt_link_url=bb-ipn.php%3Fbb_gateway_id%3D10%26bb_invoice_id%3D7%26bb_invoice_hash%3Dcc94830555b3f3409ae9c0a0e45766fc6207d56a%26bb_redirect

**Comment by 4Giedrius** [comment]
COuld you submit a ticket from members area and provide us login credentials to admin area so that we could check what is causing the problem?

**Comment by lorddanger** [comment]
http://makewebhost.com/my/
deepankardimna@gmail.com
123456

**Comment by 4Giedrius** [comment]
In order to investigate this issue deeper, I need login details for your admin area. Please do not post login credentials in this thread because it it public and can be seen by everyone.

**Comment by lorddanger** [comment]
how can i send you let me know

**Comment by 4Giedrius** [comment]
You need to login to client's area at http://www.boxbilling.com and submit support ticket referencing this issue and provide your login credentials.

**Comment by lorddanger** [comment]
When i create a ticket this i get 
Support is available for BoxBilling PRO license owners. Use community forums instead.

**Comment by lorddanger** [comment]
check the ticker at my site

**Comment by 4Giedrius** [comment]
I am sorry but we provide support for PRO license holders only. It does not seem like bug in BoxBilling as I tested in locally and it works fine. Please use [http://www.boxbilling.com/forum](community forum).

**Comment by lorddanger** [comment]
i have got the PRO lic activate it

**Comment by vaidas-lungis** [comment]
https://github.com/boxbilling/boxbilling/commit/8004eea16a6aa5cdfc7898962ac2ea8f0536cac9

**Comment by 4Giedrius** [comment]
Redirect URL fixed:  https://github.com/boxbilling/boxbilling/commit/d3251cadc95c00204be933643523c25fadc0e75e
