### ISSUE TITLE
No bb-admin.php file

### ISSUE THREAD

**Issue by shoquebd** [boxbilling/boxbilling#330]
There is  no "bb-admin.php" file. Unable to login in admin area! can you plz explain how can I enter in Admin area?

**Comment by gOOvER** [comment]
URL must look like this:

/index.php?_url=/bb-admin


It's poor, not to have an own Forum. I created an inofficial Support Community:

http://www.my-boxbilling.com

**Comment by shoquebd** [comment]
Ok  got it but how is it open source while it still has product limit? How to remove limitation?

**Comment by gOOvER** [comment]
https://github.com/boxbilling/boxbilling/pull/297

**Comment by gOOvER** [comment]
or here:

http://www.my-boxbilling.com/thread/6-remove-limitations/

**Comment by shoquebd** [comment]
Thanks it is now full version. I have some old theme edited files can I apply that with new version? Also plz let me know is this version run well with php 5.4? 

thanks

**Comment by gOOvER** [comment]
With the Themes..... good question. I don't know..

my Boxbilling runs under php 5.6 ;)

**Comment by shoquebd** [comment]
is that possible to make client area visible for unregistered users too as it before? So user can also order from that page.

**Comment by shoquebd** [comment]
I'm unable to add new invoice from admin area. while typing client name that is not appearing from existed client name, any solution?

**Comment by gOOvER** [comment]
I think, this is the worong plae to discuss. Manybe you can register at:

http://www.my-boxbilling.com

I think, the dev's dont want to see suppot Questions here

**Comment by vaidas-lungis** [comment]
Question about themes was answered in following issues:
https://github.com/boxbilling/boxbilling/issues/288#issuecomment-78437920
https://github.com/boxbilling/boxbilling/issues/308#issuecomment-93269859

**Comment by 4Giedrius** [comment]
@gOOvER BoxBillin has an [official forum](http://www.boxbilling.com/forum), so any advertising will not be tolerated in this repository. 

@shoquebd if you are free license holder, please write to aforementioned forum, if you have bought PRO license, please submit a ticket from members area at http://www.boxbilling.com and we will help to resolve your issue.

**Comment by nuxwin** [comment]
@4Giedrius

You are talking about a forum which is unmaintained (including all official boxbilling site)? Eg, dowload link which refers to a very old version? You're kidding right?. Well, I see two solutions here: Either you stop play with the community, either we create a fork of boxbilling and trust me, you will loose a lot ;)

**Comment by 4Giedrius** [comment]
@nuxwin let me shed some light on this issue. I agree that about a year ago BoxBilling was not in the best state (however I wouldn't call it unmaintained). Talking about nowadays, since we open sourced BoxBilling, all new queries in forum were answered by our staff (and usually it does not take more than 24 hours). Moreover, currently we are redesigning our main website and it should be launched in less than a week. I hope that this post answers concerns you are having. We are working really hard to make BoxBilling as awesome as possible.
