### ISSUE TITLE
Bug in Reset Password: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'recipient' in 'field list'

### ISSUE THREAD

**Issue by i7Grendel** [boxbilling/boxbilling#331]
I just tried to reset a password of a client through the client interface using the old 'boxbilling' theme (a call was made to api/guest/client/reset_password) and got the following error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'recipient' in 'field list'

**Comment by vaidas-lungis** [comment]
Try to run bb-update.php

**Comment by i7Grendel** [comment]
Sorry for not replying before, bb-update.php was the solution.
