### ISSUE TITLE
Only client login page instead of page for order

### ISSUE THREAD

**Issue by harry014** [boxbilling/boxbilling#333]
Hello,

i today installed boxbilling v 4.17 on my server together with i-MSCP 1.2.2 .

The problem is i do not get the order page, i allways (be forwarded ?) get a client
login page.
Even if i use "Products" "links" the view button i get client login page.
Same with "Order page with ID" and "Order page with slug".
I do not get anything else than login page "billing/index.php?_url=/login"

What am i doing wrong ?

Kind regards
Harry

P.S.:
The server is running on Ubuntu 14.04 (up-to-date) with kernel 3.13.0-53-generic
PHP version is :
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader + Intrusion Protection from ioncube24.com (disabled) v5.0.7, Copyright (c) 2002-2015, by ionCube Ltd.
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
Apache 2.4.7-1ubuntu4.4
libapache2-mod-fastcgi

License.php is replaced.

**Comment by nuxwin** [comment]
Hello ;

It's the expected behavior with newest Boxbilling theme. You can switch back to old behavior by using old boxbilling theme. See theme settings in admin area.

**Comment by harry014** [comment]
Hello,
Thank you.
That's what i wanted to have.

Kind regards

**Comment by 4Giedrius** [comment]
Huraga default theme does not have guest interface because it's main purpose is to [easily integrate with any existing theme](http://docs.boxbilling.org/en/latest/reference/tutorials.html#how-to-add-order-popup-to-custom-theme).
