### ISSUE TITLE
"TRY YOUR POPUP” button does not work

### ISSUE THREAD

**Issue by newbot23** [boxbilling/boxbilling#334]
Fresh install, bb version 4.17, Chrome 43.0.2357.81 m. 
Theme huraga. 
Screenshot from the admin dashboard and dev console opened. 
https://www.dropbox.com/s/hnimvbem7j2b4lc/2015-06-01-bb.png?dl=0

**Comment by vaidas-lungis** [comment]
update files and button should work.
