### ISSUE TITLE
Client orders end in "status pending"

### ISSUE THREAD

**Issue by harry014** [boxbilling/boxbilling#335]
Hello,

after configuring my servers and hosting plans i tried
to do some testing.

I have boxbilling 4.17 and i-MSCP 1.2.2 installed on Ubuntu server 14.04

But up to now all test client orders are in status "pending setup".

After email verification of 1.st test clients email and then login
and continue/finish order, i got an "internal server error"
message.
The 2nd test client sigup ended also in status "pending setup".

So i enabled debug in bb-config.php .

php_error.log then gives me following lines:

[01-Jun-2015 13:58:28 America/Montreal] Account has been created. Please check your mailbox and confirm email address. 7777
[01-Jun-2015 14:00:59 America/Montreal] PHP Fatal error:  Class 'Box_Db' not found in /var/www/virtual/blahlahblah.com/htdocs/billing/bb-library/Server/Manager/Imscp.php on line 363
[01-Jun-2015 14:08:10 America/Montreal] PHP Fatal error:  Class 'Box_Db' not found in /var/www/virtual/blahlahblah.com/htdocs/billing/bb-library/Server/Manager/Imscp.php on line 363

G**gle doesn't give me anything interesting for 'Box_Db'.
The one and only reference is in "Imscp.php".

How to get rid of this?

Kind regards

P.S.:
I have not had this prob on my test server at home with boxbilling 3.6
version and identical server setup (same file "Imscp.php").

**Comment by vaidas-lungis** [comment]
Box_Db was used in BoxBilling 3.6 version. 
With new version Box_Db class is not used. So apparently  Imscp.php file is not compatible with newer BoxBilling version. Please contact developer for more information.
https://github.com/i-MSCP/plugins/blob/master/incubator/ImscpBoxBilling/Manager/Imscp.php#L361 this line should be changed.

**Comment by nuxwin** [comment]
@vaidas-lungis 

I'm the author of the imscp server provisionning module and yes, I've not tested it since a lot ;)

If I update it and do a PR, you can integrate it in boxbilling directly?

**Comment by fordnox** [comment]
We accept pull requests if test cases are provided and build is passing.

**Comment by nuxwin** [comment]
@fordnox 

Of course. Test case with mock objects so?
