### ISSUE TITLE
serviceboxbillinglicense error

### ISSUE THREAD

**Issue by juggalox2008** [boxbilling/boxbilling#336]
when you go to test connection after you update the api key that you get on boxbilling.com  it gives error.

error
Unable to connect to BoxBilling API. Make sure API key is valid.
so i check my error log and this is the log

[05-Jun-2015 07:41:40 UTC] exception 'Exception' with message 'You need to login in order to this api/client/client/get page' in /home/user/public_html/billing/bb-modules/Serviceboxbillinglicense/ServiceBoxbilling.php:124
Stack trace:
#0 /home/user/public_html/billing/bb-modules/Serviceboxbillinglicense/Service.php(214): Box\Mod\Serviceboxbillinglicense\ServiceBoxbilling->__call('client_get', Array)
#1 /home/user/public_html/billing/bb-modules/Serviceboxbillinglicense/Service.php(214): Box\Mod\Serviceboxbillinglicense\ServiceBoxbilling->client_get()
#2 /home/user/public_html/billing/bb-modules/Serviceboxbillinglicense/Api/Admin.php(114): Box\Mod\Serviceboxbillinglicense\Service->testApiConnection()
#3 /home/user/public_html/billing/bb-library/Api/Handler.php(112): Box\Mod\Serviceboxbillinglicense\Api\Admin->test_connection(Array)
#4 /home/user/public_html/billing/bb-modules/Api/Controller/Client.php(166): Api_Handler->__call('serviceboxbilli...', Array)
#5 /home/user/public_html/billing/bb-modules/Api/Controller/Client.php(166): Api_Handler->serviceboxbillinglicense_test_connection(Array)
#6 /home/user/public_html/billing/bb-modules/Api/Controller/Client.php(85): Box\Mod\Api\Controller\Client->_apiCall('admin', 'serviceboxbilli...', Array)
#7 /home/user/public_html/billing/bb-modules/Api/Controller/Client.php(76): Box\Mod\Api\Controller\Client->tryCall('admin', 'serviceboxbilli...', Array)
#8 [internal function]: Box\Mod\Api\Controller\Client->post_method(Object(Box_AppClient), 'admin', 'serviceboxbilli...', 'test_connection')
#9 /home/user/public_html/billing/bb-library/Box/App.php(199): ReflectionMethod->invokeArgs(Object(Box\Mod\Api\Controller\Client), Array)
#10 /home/user/public_html/billing/bb-library/Box/App.php(249): Box_App->executeShared('Box\\Mod\\Api\\Con...', 'post_method', Array)
#11 /home/user/public_html/billing/bb-library/Box/App.php(143): Box_App->processRequest()
#12 /home/user/public_html/billing/index.php(27): Box_App->run()
#13 {main}
[05-Jun-2015 07:41:40 UTC] Unable to connect to BoxBilling API. Make sure API key is valid. 0

**Comment by vaidas-lungis** [comment]
Apply changes to fix issue.

this fix will be included in next major BoxBilling version 4.18.
