### ISSUE TITLE
Stripe gateway unfinished!

### ISSUE THREAD

**Issue by leejohnie099** [boxbilling/boxbilling#337]
Hello guys!
I have a problem using Stripe on BoxBilling 4.17
Actually everything works perfect except last step of order processing.
For example: when customer trying to order service on my website, he is trying to pay with credit card (Stripe), next stipe open's modal popup, where customers has to fill credit card number and date of expiry, customer click buy, Stripe changes "buy" button from blue to green color (successful charge) and then payment form appears again!
The problem is that customer is going to be charged for unlimited times, till he spend all money from card, and order status in boxbilling dashboard is - unpaid!
Help me please!
Thank you.

**Comment by leejohnie099** [comment]
The amount of charge was 19.99 twice! But in my dashboard i see this
$0.20	Stripe transaction ch_16AczmB4gHAV4uceGBagVd9T	2015-06-06 08:49	
$0.20	Stripe transaction ch_16Acx4B4gHAV4uceitZGqZyi	2015-06-06 08:46
Is there any solution of this problem?

**Comment by vaidas-lungis** [comment]
It will be included in new BoxBilling version.
