### ISSUE TITLE
serviceboxbillinglicense

### ISSUE THREAD

**Issue by juggalox2008** [boxbilling/boxbilling#340]
when a client goes to reset there key on the client side of the site it brings up a error saying order id not passed and in the error log it says

[10-Jun-2015 03:08:52 UTC] Invalid request. Make sure request origin is http://www.boxbilling.com/
[10-Jun-2015 03:09:19 UTC] Order id not passed 9999
[10-Jun-2015 03:10:01 UTC] Error executing massmailer queue: Admin is not logged in
 not sure why its saying 9999 thats not the order id

**Comment by 4Giedrius** [comment]
If you want to use API from other domain than boxbilling.com, you need to set `require_referrer_header` to `false` in `bb-config.php` file. 9999 is an error code, it seems that you are not sending client order data to API.

**Comment by juggalox2008** [comment]
it is set require_referrer_header to false and it says that when i set it to true it gives this error
{"result":null,"error":{"message":"Order id not passed","code":9999}}

**Comment by juggalox2008** [comment]
then it gives this error
{"result":null,"error":{"message":"Invalid request. Make sure request origin is http:\/\/www.boxbilling.com\/","code":1004}}

**Comment by 4Giedrius** [comment]
Which version of BoxBilling are you using? Could you upgrade to the [latest release](https://github.com/boxbilling/boxbilling/releases/latest) and let us know if it fixes your problem?

**Comment by vaidas-lungis** [comment]
Could not reproduce this error. Can you trace what data is sent to api? And if order_id parameter is set here https://github.com/boxbilling/boxbilling/blob/develop/src/bb-modules/Serviceboxbillinglicense/ServiceBoxbilling.php#L87

**Comment by juggalox2008** [comment]
how do i trace the data? also my ServiceBoxbilling.php is like above and im runing the latest 4.18 and ive turn on and off require_referrer_header and it both gives the same error

**Comment by juggalox2008** [comment]
the admin part of the boxbilling key reset works great its just the client side

**Comment by vaidas-lungis** [comment]
Can you provide client\s side reset button link?
