### ISSUE TITLE
2co IPN problem

### ISSUE THREAD

**Issue by shoquebd** [boxbilling/boxbilling#342]
2checkout IPN url mydomain.com/clients/bb-ipn.php?bb_gateway_id=4 is no longer working but this is one of the very important part of boxbilling I need working. Can I expect any correction?

**Comment by 4Giedrius** [comment]
Are you using latest release of BoxBilling? Could you describe issue you are having in more detailed way?

**Comment by shoquebd** [comment]
I'm using latest open source version, installed 2/3 weeks ago. old version was working well. but after new version 2co not sending any payment notification. if you give me your email address I can show you my site url. actually no error message I saw anywhere.

**Comment by 4Giedrius** [comment]
Please submit support ticket from members area of boxbilling.com so that we could investigate your installation.

**Comment by shoquebd** [comment]
Got an error 
{"result":null,"error":{"message":"2Checkout IPN is not valid"}}

when entering direct to www.mysite.com/clientarea/bb-ipn.php?bb_gateway_id=4
getting above error.

**Comment by 4Giedrius** [comment]
Could you upgrade to BoxBilling v4.18? We had a bug related to 2checkout payment gateway fixed. Let us know if you still experience this problem.

**Comment by shoquebd** [comment]
Now using boxbilling 4.18 but still same error on above URL 
{"result":null,"error":{"message":"2Checkout IPN is not valid"}}

if no error there what should I see on this page mydomain.com/clients/bb-ipn.php?bb_gateway_id=4 ?

**Comment by shoquebd** [comment]
Unable to submit ticket in boxbilling member area cause it is saying "Support is available for BoxBilling PRO license owners. Use community forums instead." where to send admin login to check my installation?

**Comment by shoquebd** [comment]
IPN problem gone I forget to use 'Header Redirect' in 2co account. but new problem I saw yesterday is, one of client added fund $35 but boxbilling added same fund 5 times!! that mean 35x5=$175! and seems this is a very very big problem. any idea what it is?

**Comment by 4Giedrius** [comment]
We run multiple tests and were not able to reproduce this problem. If it still persists, please open support ticket from members area at http://www.boxbilling.com  so that we could investigate further.
