### ISSUE TITLE
I keep getting an error when I try to activate/delete an hosting order.

### ISSUE THREAD

**Issue by kkprince1998** [boxbilling/boxbilling#344]
Every time I try to activate an order I get an Internal Server Error, and when I try to delete it I get "looks like we got no XML document"

**Comment by vaidas-lungis** [comment]
Do you have any errors in errors_logs file? What server adapter you are using?

**Comment by kkprince1998** [comment]
Where is the log? I am using ISPconfig from your github.

Here is my bb-data/logs/php-error.log: https://gist.github.com/kkprince1998/896c654300cadde54fa6#file-php-error-log

**Comment by 4Giedrius** [comment]
From log it looks like you are using BoxBilling v3.6. Please upgrade to [latest release](https://github.com/boxbilling/boxbilling/releases/latest).
