### ISSUE TITLE
Invoice details

### ISSUE THREAD

**Issue by chiareu** [boxbilling/boxbilling#345]
Hi guys, a recomandation for details on INVOICE. That comes from my clients.

On Invoice we have the Title field (Service/product name) and for hosting services there is concatenated with domain name reference.

But there is no info regarding invoiced time frame. Something like Hosting Package for xyz.com from date to date.
My client complain that they don't know explicit for what period that invoice/ service is about.

**Comment by 4Giedrius** [comment]
Title does not have time frame because invoice could have several items with different expiration dates. However if there is a need, you can easily do that by concatenating date with title.
