### ISSUE TITLE
Admin Login Error 4.18

### ISSUE THREAD

**Issue by darkcyber** [boxbilling/boxbilling#347]
Hi,

I just updated my boxbilling 3.x to 4.18

Overwrite old files and setting bb-config.php

Run bb-update, and it's say now you are in 4.18

Trying to login as member and work like a charm, but unfortunatelly not for admin login, here what i get once i open www.mywebsite.com/billing/bb-admin.php

```
Set BB_DEBUG to FALSE, to hide the message below
Class: "Box_Exception"

File: "/home/lamerzho/public_html/billing/bb-library/Box/Mod.php"

Line: "167"

Trace:
#0 /home/lamerzho/public_html/billing/bb-library/Box/AppAdmin.php(19): Box_Mod->getAdminController()
#1 /home/lamerzho/public_html/billing/bb-library/Box/App.php(142): Box_AppAdmin->init()
#2 /home/lamerzho/public_html/billing/index.php(27): Box_App->run()
#3 {main}
```

Let me know whats going on ? how to fix it ? 

Thanks.

**Comment by fordnox** [comment]
The link for admin area is now www.mywebsite.com/billing/bb-admin (no .php extension)

**Comment by darkcyber** [comment]
@fordnox Thanks dude, never mind about it.
