### ISSUE TITLE
Dashboard statistic currency income sync issue 4.18

### ISSUE THREAD

**Issue by darkcyber** [boxbilling/boxbilling#348]
Hi,

I have 2 Currency in my Settings , there is USD and IDR , i have already set the exchange rate.
Some times my client choose IDR, and some times USD, Then i found currency sync issue in Dashboard like this one.

![Screen Shoot](http://i.imgur.com/qHiXAyR.png)

It says 1812108.92 actually this ammount come from IDR rate and USD rate. I Think it should convert all ammount to USD or IDR, maybe there is available additional option to show total IDR and USD separately so we can know total ammount for clients which using IDR or USD (separately).

I don't know if this bug or something wrong with my configuration.

Thanks.

**Comment by 4Giedrius** [comment]
I just have tried to reproduce this problem in our test environment unsuccessfully. It looks like stats module is returning correct values. However I believe the problem could be that you set 1IDR to have same value as $13330 (it should be vice versa). Please recheck that (`Update rates` button might come in handy) and let us know if you still have any problems.

**Comment by darkcyber** [comment]
@4Giedrius Sorry i do not understand excactly what you say, i just pressed `Update Rates` and statistic still the same, Here is my currency configuration let me know if something wrong with this.

![Currency](http://i.imgur.com/X0EWcQt.png)

Thanks.

**Comment by DeekF** [comment]
is it just me, or do you have $1 = 13 thousand rupees ?

**Comment by DeekF** [comment]
ok, so looks like that is correct.. sorry, ignore me :)

**Comment by darkcyber** [comment]
Sorry, anyone know how to fix this income statistic currency issue ? Thanks.

**Comment by darkcyber** [comment]
is there anyone facing this issue ?

**Comment by darkcyber** [comment]
![idr](http://i.imgur.com/lSS65QL.png)
@4Giedrius look at this dude, i just change the default to IDR, with the same setting but at the last month it says Rp. 10.00 , it should arround Rp 130.000. look's like there is no database which hold currency convertion. only change the Rp to USD or vice versa, but it missing convert the currency.

**Comment by darkcyber** [comment]
@DeekF is you facing this problem for your INR currency ? may i look your currency setting ? thanks.

**Comment by 4Giedrius** [comment]
@darkcyber it works fine in your test environment. Please submit ticket with your login credentials from members area of http://www.boxbilling.com if you wand us to check it in your installation.
