### ISSUE TITLE
API Guest Client Loggin

### ISSUE THREAD

**Issue by bet0x** [boxbilling/boxbilling#349]
There is a error on the API, if the login details are okey i do get the info from the customer, if not the api returns nothing, not even a error, here is my code:
```
$config = array(
    'api_role'  =>  'guest',
    'api_url'   =>  'http://XXXXX/api',
);
$api_guest = new Service_BoxBilling($config);

$paramsOkey = array(
	'email'			=> 'XXXXX@XXXXX.XXXXX',
	'password' 	=> 'XXXXX'
);
$result = $api_guest->client_login($paramsOkey);
echo '<pre>';
print_r($result);
echo '</pre>';
echo '<hr />';

$paramsWrong = array(
	'email'			=> 'XXXXX@XXXXX.XXXXX',
	'password' 	=> 'XXXXX'
);
$result = $api_guest->client_login($paramsWrong);
echo '<pre>';
print_r($result);
echo '</pre>';
```

**Comment by 4Giedrius** [comment]
We would need access in order to investigate this issue. Please submit a ticket with your login credentials from members area of http://www.boxbilling.com

**Comment by bet0x** [comment]
I not asking for support on the website, just community one. This is a development issue and you don't need access, just git clone and done.
