### ISSUE TITLE
[Request] Paymentwall module

### ISSUE THREAD

**Issue by DrakeNn** [boxbilling/boxbilling#350]
Hi, is possible implement paymentwall module to payment methods.

**Comment by 4Giedrius** [comment]
Yes it is possible to implement it however we do not have any plans to do it in nearest future. Please refer to [our documentation](http://docs.boxbilling.com/en/latest/reference/extension.html#payment-gateway) and existing payment adapters.

**Comment by DrakeNn** [comment]
how to set IP process ? need say OK to IPN result, but that return json result. :(

**Comment by 4Giedrius** [comment]
Could you describe in more detailed way what you are trying to achieve?
