### ISSUE TITLE
Upcoming Renewals Report

### ISSUE THREAD

**Issue by abarrezueta** [boxbilling/boxbilling#351]
Does anyone knows if there is any kind of report or screen view where I can see the upcoming renewals?

Thanks

**Comment by 4Giedrius** [comment]
There is no such screen at the moment, however you can easily add it by modifying [`getSearchQuery` method](https://github.com/boxbilling/boxbilling/blob/master/src/bb-modules/Order/Service.php#L367-L485) to search by expiration date as well.
