### ISSUE TITLE
relative paths are not used everywhere

### ISSUE THREAD

**Issue by newbot23** [boxbilling/boxbilling#352]
I have installed bb in a subdirectory and here is how it currently looks: http://pasteboard.co/1ZLBrx0E.png
bb has been installed under %domain%/cp/
but it looks up for images (and probably other things) under %domain%
adding cp to the beginning of the image's src parameter solves the problem, so this is definitely a path issue. 
bb-config.php has proper value: 
url = %domainname%/cp, but is not used

**Comment by vaidas-lungis** [comment]
This is fixed (https://github.com/boxbilling/boxbilling/commit/f646bcdd808b380bdd557e0dd90a107fdb3d3024)
and will be in the next release.

**Comment by newbot23** [comment]
OK, thanks!
