### ISSUE TITLE
"Next" and "Previous" links don't work in Services

### ISSUE THREAD

**Issue by MikyKuroneko** [boxbilling/boxbilling#354]
Using huraga theme, accessing (from the client side) the Services page and attempting to use the "Next" and "Previous" buttons results in navigating to the home page again.

These two buttons are missing the ```_url``` parameter.

**Comment by 4Giedrius** [comment]
Could you provide us a screenshot of the buttons you are talking about.

**Comment by MikyKuroneko** [comment]
Hovering on "->" button (look the URL at the bottom of the screenshot):
![captura de pantalla 2015-07-23 a las 15 09 37](https://cloud.githubusercontent.com/assets/3064045/8851020/e91cab8a-314c-11e5-912c-5f15212cc3d7.png)

Hovering on "13" button (again, look the URL):
![captura de pantalla 2015-07-23 a las 15 09 49](https://cloud.githubusercontent.com/assets/3064045/8851022/eccebb10-314c-11e5-938f-2a70713900ca.png)

**Comment by 4Giedrius** [comment]
Thank you for taking time to explain it. I have pushed fix for this issue: https://github.com/boxbilling/boxbilling/commit/0e618a5c457880ab24c3184995128904e29b5377
