### ISSUE TITLE
"Show page header" option in Huraga settings does nothing

### ISSUE THREAD

**Issue by MikyKuroneko** [boxbilling/boxbilling#355]
If you set "Show page header" to "No" in Huraga theme settings, the header is still present on the client frontend. Disabling components from the header does work, though, but the header itself is still present.

**Comment by 4Giedrius** [comment]
Thank you for reporting this issue. It was fixed (https://github.com/boxbilling/boxbilling/commit/c763b26acb5d5b8b5b5f7dc1dc01623c70b9b6f7) and will become available in next release.
