### ISSUE TITLE
[Suggestion] Visitor able to order without registering first

### ISSUE THREAD

**Issue by darkcyber** [boxbilling/boxbilling#359]
Hello,

new boxbilling required login before order, it's okay for existing customer but not for visitor which plan to order. so i suggest to add feature, visitor able to order without registering first, so visitor can check the price, the package, payment gateway, etc before he decide to order. then register form show at the end of process. AFAIK almost all billing able to order without registering at first or we can say, register at the end of order process.

Thanks.

**Comment by vaidas-lungis** [comment]
You can use old BoxBilling theme (boxbilling) which does not require user to log in. 

Moreover there is extension "orderbutton". Order button extensions lets you add JS script in your external site and attach event to button. Event will open pop up where client can select product add to cart and then proceed to check out.

**Comment by vaidas-lungis** [comment]
Related 
#326
