### ISSUE TITLE
Automatic update not working

### ISSUE THREAD

**Issue by darkcyber** [boxbilling/boxbilling#360]
Hello,

I use 4.18 version and the latest version is 4.19. When i try to press "Automatic Update" button at extensions section it says, you have latest version and no need to update. Is this bug or something ?

Thanks.

**Comment by vaidas-lungis** [comment]
At the moment automatic update with new BoxBilling version (4+)  is not implemented. 
You can setup updates with [composer](https://getcomposer.org/)
