### ISSUE TITLE
New boxbill user registration

### ISSUE THREAD

**Issue by shoquebd** [boxbilling/boxbilling#361]
Hello

New boxbilling theme not letting go into order from before register. How can I stop that? it should be register before checkout.

Thanks

**Comment by 4Giedrius** [comment]
Please refer to this [tutorial](http://docs.boxbilling.com/en/latest/reference/tutorials.html#how-to-add-order-popup-to-custom-theme)

**Comment by vaidas-lungis** [comment]
Related 
#326
#359
