### ISSUE TITLE
update ordered product prices

### ISSUE THREAD

**Issue by mdaskin** [boxbilling/boxbilling#364]
there is no update ordered products prices

can you add

**Comment by 4Giedrius** [comment]
Could you elaborated more on this issue?

**Comment by i7Grendel** [comment]
I support this request.

When an order is created, the product price gets configured for the order. However, when you update a product price, all existing orders for that product keep the old pricing. Right now, you would have to update all existing orders manually and any created proforma invoices are not updated.
