### ISSUE TITLE
Public Ticket Link

### ISSUE THREAD

**Issue by darkcyber** [boxbilling/boxbilling#365]
Hello,

In old boxbilling we can use this link http://mywebsite.com/billing/index.php/contact-us for public ticket, what about in new boxbilling ? i can't find the link for public ticket in new version of boxbilling.

Thanks.

**Comment by 4Giedrius** [comment]
I am afraid that public ticket template is not included in `huraga` theme. I have added it to `Feature Requests` in the meantime, you can feel free to implement it by yourself by adding template for public ticket view.
