### ISSUE TITLE
Smart Search Not working

### ISSUE THREAD

**Issue by liptanbiswas** [boxbilling/boxbilling#366]
When searching clients through admin panel it just displays nothing even if client is there, tested in mozilla, chrome.
![screenshot 18](https://cloud.githubusercontent.com/assets/8578543/9389310/0d1e682e-4788-11e5-8517-1d424aa2b4d1.png)

**Comment by 4Giedrius** [comment]
I have just tried and it works flawlessly in our test environment. Are you sure that your are typing user name correctly? If you are sure that it is not working, please submit support ticket from member area with your login credentials so that we could check it.
