### ISSUE TITLE
Trying to load http links on https

### ISSUE THREAD

**Issue by kkprince1998** [boxbilling/boxbilling#369]
Your fonts load from http. Can someone change it to autoswitch? (//)

**Comment by 4Giedrius** [comment]
Do you mean our installation page? Everywhere else we use `https` to load fonts.

**Comment by kkprince1998** [comment]
I am not too sure now, but chrome was complaining about mixed content

**Comment by kkprince1998** [comment]
Yes installation page. In src/install/layout.phtml

**Comment by kkprince1998** [comment]
I think there may be more

**Comment by kkprince1998** [comment]
Ok, I found the issue. In `src/install/layout.phtml`, It has a base tag, that for some reason directs to http.
After commenting it out it works.

**Comment by vaidas-lungis** [comment]
base tag url is generated from bb-config.php file url param. 
So if your config file has url param without https prefix install's layout template will not have it too.

Your solution is almost correct but you could just update bb-config.php file url param to https prefix
