### ISSUE TITLE
Client / Orders / Invoices Overview broken

### ISSUE THREAD

**Issue by peet86** [boxbilling/boxbilling#375]
After I added some clients and tested the system the overview pages doesn't list the clients / oreders / invoices.. (screenshot attached)
I don't know exactly what's happened and where to start debugging.
Have you seen something like this before? 

<img width="1052" alt="screen shot 2015-08-26 at 21 01 36" src="https://cloud.githubusercontent.com/assets/598962/9512355/b73ac99a-4c35-11e5-9885-32034866fea1.png">

**Comment by 4Giedrius** [comment]
Could you tell us exact steps we need to take in order to reproduce the problem as I did not manage to do it in my environment?

**Comment by newbot23** [comment]
We have the same issue here, clean install, version 4.20. PHP Version 5.3.29

**Comment by newbot23** [comment]
Issue resolved, after enabling debug mode in boxbilling, I've a got a fatal error - call to undefined function mb_internal_encoding, so I have found that I need to install extension mbstring and everything is back to normal. 
@peet86 You can enable that debug mode too, but I guess you have the same issue with missing extension - check it via phpinfo.

**Comment by peet86** [comment]
Thank you @newbot23 your answer solved my problem as well! I'm closing this issue.
