### ISSUE TITLE
tax not shown in invoices

### ISSUE THREAD

**Issue by zeigerpuppy** [boxbilling/boxbilling#376]
I have set up a tax rate of 10% on purchases.
It is applied but the invoice does not show the tax charged, just the total.
Also, is it possible to have prices quoted inclusive of the tax (this is required by law in Australia)?

**Comment by i7Grendel** [comment]
+1. Most legal systems require you to show taxes on invoices.

**Comment by fossxplorer** [comment]
+1

**Comment by Ryan-Nolan** [comment]
+1

**Comment by Ryan-Nolan** [comment]
@TuxMay im presuming this has been added now yes?
