### ISSUE TITLE
Client1 can relate tickets to Client2's service

### ISSUE THREAD

**Issue by newbot23** [boxbilling/boxbilling#378]
Backend does not check hidden fields content, just inserts it into DB. 
So client1 is able to create tickets for client2.

**Comment by 4Giedrius** [comment]
Could you be more specific regarding this issue and provide steps we need to take in order to reproduce problem?

**Comment by newbot23** [comment]
I'm sorry, the title is quite inaccurate. 
It's more about ticket related to a specific service, you can change that directly in the browser and the tickets will be related no to your service, but to the service of other client. Here is a screenshot:
http://pasteboard.co/G4oARqu.png
