### ISSUE TITLE
BB-IPN.PHP should be updated for redirecting

### ISSUE THREAD

**Issue by increatech** [boxbilling/boxbilling#381]
In line number 55 I found that 
55 var_dump($url);exit;
56    header("Location: $url");
57    exit;

Due to line 55 it is not redirecting after successful payment. Kindly remove that line so that it will redirect seamlessly.

**Comment by 4Giedrius** [comment]
I am happy to tell you that this issue is fixed in our [newest release](https://github.com/boxbilling/boxbilling/releases/latest).

**Comment by increatech** [comment]
That's good. I just noticed what while I develop custom payment gateway. Anyhow if any bugs I found will make a contribution in fixing it.

**Comment by 4Giedrius** [comment]
Thank you, we really appreciate that!
