### ISSUE TITLE
PDF conversion Problem

### ISSUE THREAD

**Issue by increatech** [boxbilling/boxbilling#382]
When I tried to click on pdf button in invoice page it is showing following error

FPDF error: Not a PNG file: /home/indyahst/public_html/mskaUmdJ6N

But in my local host working fine but in server it is throwing such error please let me know whether I need to enable any module for make it work.

**Comment by 4Giedrius** [comment]
Please make sure that picture you are using as logo of your company is a valid PNG file.

**Comment by increatech** [comment]
Picture is valid.. I just figure out if allow_url_fopen is disabled means then this problem arises. In one of my service provider is not supporting to enable that future. Kindly help me in get some alternative solution for it.. Waiting for your favorable reply.

**Comment by increatech** [comment]
Server provider is asking to use curl instead of allow_url_fopen. Is there any possibilities to do so? Due to this In my boxbilling PDF generation is not possible. Is that able to modify so?

**Comment by webdesires** [comment]
We had the same problem and fixed it by following the below guide:
[https://webdesires.co.uk/blog/boxbilling-pdf-invoice-fpdf-error/](https://webdesires.co.uk/blog/boxbilling-pdf-invoice-fpdf-error/)
