### ISSUE TITLE
How to enable public views with the Huraga theme?

### ISSUE THREAD

**Issue by i7Grendel** [boxbilling/boxbilling#390]
I want people to be able to see products without being signed in and I want to be able to accept public tickets. However, I cannot use the new Huraga theme, I can only use the old theme. When using the Huraga theme, I can only access the login and registration pages.

Why is that? And what needs to be done to give Huraga a public version as well?

**Comment by vaidas-lungis** [comment]
Related
https://github.com/boxbilling/boxbilling/issues/359 
#326

**Comment by i7Grendel** [comment]
Thank you. While those issues are related, my first priority is not product orders (I already cobbled something together for that using the Guest API) but public tickets. Order Button does not include that.

**Comment by tenaki** [comment]
Is there a fix for this yet or is there a plan to fix it. I think guests should be able to open tickets, view knowledge base etc

**Comment by aichounweb** [comment]
hello guys !
i still dont know how to make new client creat thiem account in order page on Huraga theme like boxbilling theme so if u dont mind im asking :
 1 - how to make new client creat thiem account in order page on Huraga theme like boxbilling theme OR 

2 - how to change boxbilling.com link   on boxbilling theme  to any link i want.
