### ISSUE TITLE
Switch between languages happens by itself

### ISSUE THREAD

**Issue by newbot23** [boxbilling/boxbilling#406]
Hi, 

I have added localization to bb-locale and have following issue: 
If I open index.php?_url=/invoice the UI is sometimes in English sometimes in the second language. I have specified the correct one in bb-config.php and in the dashboard itself. 

Has anyone a hint, what could be the reason for that? 

br
newbot23

**Comment by newbot23** [comment]
It does look like httpd restart helped.

**Comment by pmichelazzo** [comment]
Unfortunately the httpd restart doesn't work with this issue.

In my case I try a lot of different approaches for a similar problem. I change the default language to pt_BR and nothing that I can do show me this language on the client's interface. I try to remove en_US, I give 777 for all files, I made a new po and nothing change.

If I put both languages on the bb-locale folder, I can see the dropdown box on client area but If I change that, nothing happens.
