### ISSUE TITLE
Login required to access everything in Huraga theme

### ISSUE THREAD

**Issue by samapco** [boxbilling/boxbilling#416]
The huraga theme is nice but I find it problematic that you have to login before you can access everything  in there. 

For instance, if you want to view any of these sections, you are required to login first:
-View invoice as a client
-knowledgebase
-Faq
-products order
-announcements

I don't know if it was purposely done that way but I believe if these sections were made public like it is in the default boxbilling theme, the huraga theme would be great.

I am still using the default boxbilling theme because of these limitations in huraga theme

**Comment by fordnox** [comment]
This was made on purpose.

**Comment by vaidas-lungis** [comment]
Related
#359 
#326
