### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by domkalan** [boxbilling/boxbilling#417]
I'm using Nginx, PHP-FPM, and Cloudflare on Ubuntu 14.04 and keep running into this very weird error. Every time I enable the sef_urls this happens. The issue seems to be coming from a syntax error as the Chrome console describes. I do not have a clue where this error is originating from and its happening on more than one server.

![30c9f1e978a05034bb3d298971b82dc5](https://cloud.githubusercontent.com/assets/6377796/12073666/8cefa548-b0df-11e5-8981-eaf23d48341d.gif)

**Comment by domkalan** [comment]
Issue only seemed to be with my Nginx setup.

**Comment by budimanfajarf** [comment]
Hi, I have the same issue, how you solve it?

**Comment by timothygwebb** [comment]
Please respond with the following file src/bb-data/log/php_error.log and
your domain address that you are accessing before the redirect.

**Comment by timothygwebb** [comment]
@domkalan @budimanfajarf I would also recommend that if you have a reverse proxy setup that you make sure all domain url on your site are using https:// and not http://

**Comment by budimanfajarf** [comment]
It is my latest php_error.log https://gist.github.com/budimanfajarf/c964682c7bbccbffeeb053f37ae12205

**Comment by budimanfajarf** [comment]
I don't have a reverse proxy setup I think, but do you have an example for nginx server block configuration?

**Comment by rndevuk** [comment]
@budimanfajarf it appears that you are not using the latest version.

You either need to use a lesser version of php or you need to update to the master repo version of boxbilling

**Comment by budimanfajarf** [comment]
@rndevuk do you have recommendation version of PHP and version of boxbilling to use for stability reason?

**Comment by rndevuk** [comment]
The latest release and php 7.2 should work fine untill the next release.
The next release will require php 7.4 I beleive.

**Comment by timothygwebb** [comment]
@rndevuk @budimanfajarf The master branch requires 7.3 or higher. Last release 4.21 is up to 7.2.

**Comment by rndevuk** [comment]
i was not talking about the master branch @timothygwebb i was talking about the latest release.

Im pretty sure the master branch requires php 7.4. weasnt there a bunch of depreciations in php 7.4? or am i mistaken?

**Comment by timothygwebb** [comment]
@rndevuk @budimanfajarf https://www.php.net/eol.php
https://www.php.net/supported-versions.php

**Comment by timothygwebb** [comment]
@rndevuk @budimanfajarf master branch did depricate a lot of the commands in 7.2.

**Comment by timothygwebb** [comment]
@rndevuk @budimanfajarf https://www.php.net/manual/en/migration72.deprecated.php

**Comment by timothygwebb** [comment]
@rndevuk @budimanfajarf https://www.php.net/manual/en/migration74.deprecated.php

**Comment by budimanfajarf** [comment]
Thank you for the replies @rndevuk @timothygwebb, you guys help me a lot :)
Do you guys have an example for nginx server block configuration to run boxbilling at /billing path? my current configuration is look like this https://gist.github.com/budimanfajarf/7732a8795f123f2661de60f52c9167c6
I am curious if my nginx server block configuration is wrong, so maybe that why I still have the issue about redirect loop?

**Comment by timothygwebb** [comment]
If you are running apache make sure that you don't have a double
declaration of redirect specification.
Some vendors have their own plugins and tools that deal with redirects from
http to https such as wordpress and others.
Please read the following articles and I believe they will guide you to
where you need to be.

<goog_940990051>
https://gist.github.com/ScottPhillips/1721489

https://www.plesk.com/blog/various/nginx-vs-apache-which-is-the-best-web-server/

https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/

https://wordpress.org/support/article/nginx/

**Comment by rndevuk** [comment]
@budimanfajarf I dont have much experience with nginx but have you tried using and modifying the one in the git repo to suit:
https://github.com/boxbilling/boxbilling/blob/master/data/nginx.conf
