### ISSUE TITLE
Can't use/edit/create custom form fields

### ISSUE THREAD

**Issue by Vandread911** [boxbilling/boxbilling#420]
As the subject states I cannot use custom form fields, I was using the very old version of Boxbilling, when i updated i noticed the custom form fields/builder and i cannot create any, maybe due to updating from old version straight to latest version caused database issues that won't allow  me to create the fields, can you not in the latest version have a script pre installed in boxbilling that checks if database is good and repairs the database to latest version

**Comment by 4Giedrius** [comment]
We already have this script - when you update BoxBilling, you need to run `bb-update.php` file by going to `yourdomain.com/bb-update.php` and it shoud add missing fields to database.
