### ISSUE TITLE
This is not free software license, by Debian's standards

### ISSUE THREAD

**Issue by pierreozoux** [boxbilling/boxbilling#422]
(To continue discussion from #368)

https://people.debian.org/~bap/dfsg-faq

Check the desert island experiment.
If I land to a desert Island with your software, I can't install it, because I need a license key from your server.

I'm totally fine to have "pro/paid" features. But I think it would make sense to remove this check on install.
Why not doing like odoo, a shop with paid addons :) Just an idea :)

Anyway, thanks for your work, we plan to use your software and pay you license ;)
https://github.com/indiehosters/website/issues/64

All the best!

**Comment by scith** [comment]
+1
I don't mind keeping the pro license, but having to create an account and do license check for the free version is neither practical nor really "free".

- Keep PRO license (can be asked at install or later)
- Remove FREE licenses (in install) and unlock free features without licenses
