### ISSUE TITLE
[Improvement] Hosting module

### ISSUE THREAD

**Issue by scith** [boxbilling/boxbilling#431]
Hello,
I have some problems with the hosting module the way it is implemented at the moment:
1. Although custom fields can be added to hosting plans, a lot of default fields are related to web hosting only (not VPS etc)
2. No possibility to add custom fields to the servers?
3. There should be possibilities to customize each server's panel/outputs like: http://docs.whmcs.com/Provisioning_Module_Developer_Docs (clientArea, adminArea, ...)
4. There is no possibility to put servers into groups and allocate clients to servers within a group automatically (e.g. filling the least filled server, filling the most fulled server...)

As a result, non-web hosting providers seem to have their own plugins (like solusvm) rather than be part of the hosting module, which is strange...

If others are interested, I could help develop points 1, 2 (easy) and point 4 (I already coded this behaviour into another module I'm creating).
However I have no idea about how to code 3 as it requires template files and API.... Perhaps taking inspiration from WHMCS behaviour? http://docs.whmcs.com/Provisioning_Module_Developer_Docs#Client_Area_Output

Each server should thus have one folder containing those files instead of just a single PHP page which is too limited

What do you think?
If not many are interested, I'll just develop my own module doing that like SolusVM did

Thank

**Comment by fossxplorer** [comment]
Hi @scith 
i'm very interested. I'm currently using WHMCS, but has been watching Boxbilling for some of the upcoming projects.
I was planning to take a closer look at oVirt, but never had spare time. I see you are working on Boxbilling support for Proxmox, that sounds really great. 
I'll be able to test and if possible help in other ways after July 2016.

But +1 from me!
