### ISSUE TITLE
Plesk 12 extension.

### ISSUE THREAD

**Issue by Toggie** [boxbilling/boxbilling#432]
I was informed by your support rep Ahmad Abu Assab to paste a notice here.

I noticed in your version history on github it states the following, just to make sure I am doing things correctly, it states as of version 4.17 released May 18, 2015 "updated Plesk server manager to Plesk 12". I tried to look for said server manager, and it is non obvious, and also cannot be found in documentation so easily online, or via google search. The only thing I found was this extension https://github.com/boxbilling/extensions/blob/master/bb-library/Server/Manager/Plesk.php

I found it curious that this file shows last commit in 2012 (perhaps I am reading it wrong).

Is this the correct thing to add? I tried setting it up, but I only get server errors with no other information. The server manager successfully connects when I tested it.

**Comment by Toggie** [comment]
In the meantime, I am paying for a license, solely to evaluate this functionality.  Additionally, your default installation point to extensions.boxbilling.com at the bottom of the extensions page in the admin interface, which no longer exists.  This should be updated as it misleads your users.

**Comment by Toggie** [comment]
Help?  It has been nearly an entire week now and no update.  Why would anyone pay for this?

**Comment by Toggie** [comment]
I give up.  Off to Blesta.

**Comment by phamid** [comment]
https://github.com/boxbilling/boxbilling/blob/babbdd3b49a754283ab7930e54fea0452556f995/src/bb-library/Server/Manager/Plesk.php

This appears to be compatible with Plesk Oynx. Additional testing on my end, but trying to ensure that it is all good to go

**Comment by OnlyHardOfficial** [comment]
I already gave up this softwer a long time ago! At the time I was part of the CircleBilling team (boxbilling fork) this one had some improvements of rest I do not know anything else

**Comment by OnlyHardOfficial** [comment]
If this is still compatible with Plesk or Plesk Onix I must tell you that it is a miracle my dear friend
