### ISSUE TITLE
Trouble with custom Server Manager

### ISSUE THREAD

**Issue by Y-Young** [boxbilling/boxbilling#434]
I just want to build a custom server manager based on Whm.php but now I am in trouble.I copied  Whm.php and renamed it,I replaced the class name and the value of 'label' in getForm().But however it doesn't work,Hosting Management keeps loading and the ' Server Manager' option box is empty,everything behind it is missing.

**Comment by n3bir0s** [comment]
Did you reedit file ( your version of whom)

**Comment by n3bir0s** [comment]
class Server_Manager_Whm extends Server_Manager
{.... }

To 
class Server_Manager_MyManager extends Server_Manager
{ ... }

Where MyManager mean your name of class

**Comment by Y-Young** [comment]
@n3bir0s Of Course I did.But except these,I Didn't edit any other part,It still doesn't work.

**Comment by Y-Young** [comment]
I Didn't do any changes except renamed class,file and 'label' name to test.now I'm puzzled

**Comment by scith** [comment]
What about the logs? They are usually very explicit
/boxbilling/bb-data/logs

**Comment by Y-Young** [comment]
@scith Well,there is only application.log and no error log inside it.What's more,if I edit other server managers(eg.Kloxo or Custom) in this way,they will work well.It seems only Whm.php has this issue.By the way,you may try this way yourself so that you could find out if it is a common issue or just for me.

**Comment by scith** [comment]
Perhaps because of what's in public function init()
Some functions are specific to WHM.

To start a new server manager, I'd recommend starting from scratch (with the function you need but nothing in them) and remove all the things you don't need.

**Comment by Y-Young** [comment]
@scith But if some functions are specific to WHM,they must be defined in the same file as well,so what cause this issue?

**Comment by scith** [comment]
I don't know, perhaps it tries to call WHM, perhaps inside one function is a call to a MySQL table already in use...
This is why I think you should start from an almost blank template, empty most of the function and fill them as needed

**Comment by Y-Young** [comment]
@scith Thanks.But I stll wonder how the error is caused,That's too strange.As you said,if there is a call to mysql it may cause the issue,But I have copied the WHOLE file so it can't be wrong.Would you mind telling me what varibles/functions are defined by Boxbilling so that I can use them directly in my custom server manager?

**Comment by scith** [comment]
These are the ones you should put at least: http://docs.boxbilling.com/en/latest/reference/extension.html#server-manager

**Comment by Y-Young** [comment]
@scith I Mean those can be used without defination in my Class,eg.$_config,getLog()...

**Comment by Y-Young** [comment]
@scith Now here comes another issue,Almost all the functions in Whm.php are required,I will do some simple change to make it work well for me,so It is useless to copy all the functions one by one.Also,after I copied all the functions,the same issue will appear again if it does exists.So I think it is necessary to find and solve this issue.

**Comment by Y-Young** [comment]
@n3bir0s @scith Thanks for help.I think I have solved the problem.The cause is that My manager and Whm both have a Xml-api class included,but a same class can't be loaded twice so it caused the problem.
