### ISSUE TITLE
Custom extension help 

### ISSUE THREAD

**Issue by n3bir0s** [boxbilling/boxbilling#435]
Hello 

I'm trying to develop boxbilling extension for SMS notifications. I'm trying to produce some functionality but i'm unable, but mostly for lack of knowledge of this framework.  

My concept is based on example extension provided in version 4.20. I also thinking about plugin system for this extension which I see in license product in box billing. And here I encounter a issue 
I.e my URL for editing plugin is similar to this:
/smsgateway/plugin&code=clickatel 
I know that I need to register get in admin controller
Which I did .
But how can I manage last part 'code=clickatel'

Should I check this in api or controller part of extension

In example are only samples with id which are numeric and I can't use numeric values for plugin classes. 

Can you point me in right direction? 

Regards

**Comment by n3bir0s** [comment]
Currently most of extension is done ( forms, reports, plugin classes etc. 

The only thing where I stuck is mentioned above

**Comment by scith** [comment]
Hi,
I think you need to do it in both controller and API. Controller is for the URL. API is for the functions.
Look at the code of the Invoice module (admin controller and API), I think they are more explicit for your case.

Perhaps in controller register function
$app->get('/smsgateway/plugin/:code','get_code', array('code'=>'[A-Za-z0-9]+'), get_class($this));

Then a get_code function in the controller that does whatever you wish to do (api call like in get_invoice, or just show a template...)

**Comment by n3bir0s** [comment]
Well I tried this but can get this working 
I'll cleanup my code little bit ( it's still have old example code there in some templates ) 

I'll upload this on git and send you details if you interested to see

**Comment by n3bir0s** [comment]
@scith I uploaded on my repo 
It's mostly skeleton and concept
https://github.com/n3bir0s/boxbilling/tree/SmsGateway

**Comment by n3bir0s** [comment]
@scith 

I finally managed :) 
take look at 

https://github.com/n3bir0s/boxbilling/tree/SMSGateway

And let me know what you think

**Comment by scith** [comment]
It looks very nice! I can't test it further because I'm not a client of these companies, but the admin interface looks amazing!
Good idea this plugin system.

**Comment by n3bir0s** [comment]
@scith 
re.: error that is solved in last commit - i'll post another in next few hour ( or minutes :) ) 

regarding testing i write plugins as stand alone modules and works so this part is easy since i've got them written before and tested them. but currently this part is on hold. i need to get functionality of module first.

**Comment by gsikorsky** [comment]
Is it working module? How may I test it? How may I download Smsgateway module from: https://github.com/n3bir0s/boxbilling/tree/SMSGateway/src/bb-modules/Smsgateway  
?

**Comment by n3bir0s** [comment]
Currently is under still development
