### ISSUE TITLE
Facing a Blank Error

### ISSUE THREAD

**Issue by liptanbiswas** [boxbilling/boxbilling#437]
Hi There,

Updated from 4.19.1 to 4.20, and getting a blank error, each time I create a account or delete an account, I am using cPanel via access hash, everything worked correctly before. 
but now I am getting a blank
![screenshot 114](https://cloud.githubusercontent.com/assets/8578543/13175917/e314776c-d733-11e5-9f1f-c777eb839b8f.png)
 error.
please see the screenshot. 
![screenshot 113](https://cloud.githubusercontent.com/assets/8578543/13175903/c25c6764-d733-11e5-99ab-56a931957103.png)

**Comment by n3bir0s** [comment]
did you add username and password for cpanel whm

**Comment by liptanbiswas** [comment]
Yes, I updated the Access hash too, then I tried to recreate another account, the account got created in cPanel but again there was the blank error and the status of the account was still pending. no emails were also sent to user. then I tried to delete that account, which was in pending state, the account got deleted from cPanel but again there was the same blank error and the status of account was still pending.

**Comment by liptanbiswas** [comment]
I took it back to boxbillig 3.19.1, but still same problem occurring.

**Comment by anud06** [comment]
Hi, I have the similar issue. Upon activating a hosting account, cpanel account get created but the admin area gets an blank error and doesn't send the customer activation email as well. Boxbilling version is 4.20. Does any one have a solution to this?

**Comment by fordnox** [comment]
Check log files for more information

**Comment by anud06** [comment]
Unfortunately there's nothing on the logs. But with the blank error boxbilling mark the account status as setup failed though whm does sends me the account creation email (boxblling does not sends account activation email but do sends order creation emails and the rest).  However if I click again the activation button again, an error prompt with an account is already on whm and at that point account deletion from the boxbilling is possible (no errors but no notification emails as well)
