### ISSUE TITLE
0 to no documentation on how to create a custom product

### ISSUE THREAD

**Issue by devlinpadayachee** [boxbilling/boxbilling#438]
Hi 

How does one actually do thism cant find any tuts on how to create a product which uses a custom integration to a backend system

please assist

BR

**Comment by domkalan** [comment]
The company that manages BoxBilling is a very odd company and you will most likely not get a reply. My suggestion would be to find a different script.

**Comment by scith** [comment]
What do you want to do exactly?

**Comment by devlinpadayachee** [comment]
To create a custom product with service provisioning

**Comment by Jawanet** [comment]
Go whmcs/blesta/clientexec for seriously business.


boxbilling only for study.
