### ISSUE TITLE
Order button java code conflict

### ISSUE THREAD

**Issue by shoquebd** [boxbilling/boxbilling#441]
Order button code not working on my web pages because of it is conflicting with my theme's jquery.js. But I have to keep jquery.js for my site design. So how can I get your button working with it?

**Comment by shoquebd** [comment]
Still waiting for a solution.

**Comment by scith** [comment]
Which Boxbilling theme are you using? I thought the code of the order button was in bb-jquary.js, not in jquery.js
If you use the default jquery.js instead of your theme's one, does it work? Can't you put your theme-specific js code in another file?

**Comment by shoquebd** [comment]
I tried both theme in boxbilling. I'm using CSS theme pink rio for my main site. You can download it here http://www.free-css.com/free-css-templates/page182/the-pink-rio
then try order button code on this theme then you can understand me.

**Comment by scith** [comment]
What did you do exactly to adapt this theme to BoxBilling? Have you included the BoxBilling code into your custom theme? Have you also included the correct files like bb-jquery.js?
For instance here are the JS dependencies in my BoxBilling boostrap theme: https://github.com/scith/boxbilling-bootstrap/tree/master/bootstrap/assets/js
My order button is just an HTML button: https://github.com/scith/boxbilling-bootstrap/blob/master/bootstrap/html/mod_order_index.phtml#L63
