### ISSUE TITLE
When Creating a new product it says, please edit mod_servicehosting_order_form.phtml file in order to change order form for hosting category products

### ISSUE THREAD

**Issue by mefail** [boxbilling/boxbilling#442]
HOW TO SOLVE THIS PROBLEM?
![gggg](https://cloud.githubusercontent.com/assets/17839418/13764153/0c5f3266-ea7f-11e5-9ba4-6ff6bd87e892.jpg)

**Comment by scith** [comment]
It is not a problem. It just says that if you wish to have a custom order form, you need to edit that file.
If you are OK with the default order form, there is nothing to change

**Comment by Y-Young** [comment]
@scith I wonder how to add a custom field to the order form in order to allow clients to choose their own passwords,but It seems that there isn't any documentations about adding custom fields to form templates.Could you please show me an example?
