### ISSUE TITLE
About Branding Removal

### ISSUE THREAD

**Issue by shoquebd** [boxbilling/boxbilling#443]
Am I allowed to remove all boxbilling branding from my installation? Including deactivate branding extension? Please let me know.

**Comment by trendebook** [comment]
in one click i login to my gmail account using this gmail email login tips 
http://www.trendebook.com/gmail-email-login-gmail-sign-in/

I download all my mobile files in on clicks  
http://www.trendebook.com/waptrick-music-games-videos-mp3-download-www-waptrick-com/


get free mp3 top music in one click 
http://www.trendebook.com/waphan-free-games-music-videos-apps-download/

i open all my web page at no cost 
http://www.trendebook.com/operamini-mobile-web-browser/

i chat for free using the best mobile messaging app
http://www.trendebook.com/hike-messenger-review-and-download/

**Comment by domkalan** [comment]
You can deactivate BoxBilling branding only if your application is running with a PRO license. There are ways to get this for free as BoxBilling is released under open source Apache License.
