### ISSUE TITLE
XSS attack vulnerable 4.2

### ISSUE THREAD

**Issue by jnico** [boxbilling/boxbilling#446]
public tickets vulnerable to xss. the only way around is to edit
`bb-modules/Support/Service.php`

fixed by editing public ticket templates

**Comment by jnico** [comment]
replaced where applicable in user/admin support ticket templates
`|bbmd`
with twig defaults
`|escape|nl2br`

**Comment by mike-bailey** [comment]
Recommend re-opening this. It needs fixed upstream.
