### ISSUE TITLE
Need Custom payment methode to mark the invoice paid.

### ISSUE THREAD

**Issue by scwebdes** [boxbilling/boxbilling#453]
Hello All

I have used custom payment method to add a gateway.There i added the gateway details which makes all the payment.Now what return Url should be used to make the invoice paid?

**Comment by KY4U** [comment]
The return url can be determined by the following example

- your domain name is _mydomain.com_
- boxbilling is installed in _billing_
- your gateway ID is 4 (you'll be able to determine that by going to Payment Gateways and click on the Pencil icon)

Your return URL will be
https://mydomain.com/billing/bb-ipn.php?bb_gateway_id=4
