### ISSUE TITLE
No documentation on how to add a custom field to servicehosting order form

### ISSUE THREAD

**Issue by Y-Young** [boxbilling/boxbilling#454]
I wonder how to add a custom field to the order form in order to allow my clients to choose their own passwords,but It seems that there isn't any documentations about adding custom fields to form templates.Could anybody show me an example? Thanks!

**Comment by Eiskaltereistee** [comment]
Yes, I can. Do you still need it?

**Comment by Y-Young** [comment]
@Eiskaltereistee Yes,please.I think it's useful and worth studying.Thanks
