### ISSUE TITLE
No data visible but still works fine? Eh?

### ISSUE THREAD

**Issue by Snus** [boxbilling/boxbilling#455]
Great project, testing the Boxbilling at the moment, connected to a WHM/Cpanel server, does what it should, creates account, can create tickets and such BUT nothing is visible. etc if there is a new client the only thing that shows in the client list is their picture, have to press it so that i can view their name etc but when i press those other tabs nothing is vissible but stuff should be there also. Same with the help desk. A user can write a ticket, i can see that there is a ticket but i cant see what it says, what helpdesk its sent to and so on. Stuff is missing and the wierd thing is, nothing shows in the logs? 

Help appreciated

**Comment by Snus** [comment]
Is there any staff in this project anymore? Cant see many issues answered by a staff member. To bad cause Boxbilling seems to be a really nice billing panel.

**Comment by Snus** [comment]
Solved it weeks ago. Thanks for the help anyways.

**Comment by jorgegaspar** [comment]
Do you remember how you fixed that no data showing? Even in the latest versions I'm facing the exact same problem
