### ISSUE TITLE
I can send emails and invoices

### ISSUE THREAD

**Issue by mogekko** [boxbilling/boxbilling#458]
Just installed BoxBilling, everything is working except emails and invoices. All the settings are ok. Test email works. Any help please.

**Comment by ericwongcm** [comment]
I noticed my Boxbilling 4.20 installation have similar problems. Test e-mail and reset e-mail works but I don't see any e-mails received by client or admin when order/ticket is raised. I am using PHP 5.5.

How is one supposed to use this when both client and admin don't see e-mail notifications?
