### ISSUE TITLE
Emails after a user signs up

### ISSUE THREAD

**Issue by Snus** [boxbilling/boxbilling#461]
Boxbilling emailing does work on my setup and in my systems but when a user signs up one mail is missing.

When a new user signs up and order a service they receives one email saying welcome to Boxbilling and another one with some information about the service, like cpanel password, username, nameservers and such(the activation email). That last one is missing for me. I can see that it is enabled but not a single of my clients receives it and i cant seem to find what the problem is. The Cron is working fine and i do not get any errors. 

I have understood that its not even being sent as in it is not even sent to the email queue which means something is causing the system not to even want to send it.

**Comment by marsoltys** [comment]
This happend to me. I believe this happend after last upgrade to 4.20.

You need to go to Settings -> Email -> mod_client_signup, backup your template and then reset your template (or simply add confirmation link placeholder within existing template)

I've hope that helps

**Comment by ericwongcm** [comment]
Also using 4.20 here, reset template only seems to fix e-mails sent to client but does not seems to work for all the e-mails sent to staff.

Can you check if you receive email sent to your staff accounts too? e.g. when client placed order, open ticket, etc.

**Comment by Snus** [comment]
Yeah, emails are being sent out to staff(user sign up and such) but no emails are sent to clients unless we manually send them. Tried to reset template.

We're running whmcs as we speak but we still try to fix our old boxbilling installation tho it is going much slower as we use whmcs temporarly.


27 dec. 2016 kl. 07:37 skrev Eric Wong <notifications@github.com<mailto:notifications@github.com>>:


Also using 4.20 here, reset template only seems to fix e-mails sent to client but does not seems to work for all the e-mails sent to staff.

Can you check if you receive email sent to your staff accounts too? e.g. when client placed order, open ticket, etc.

-

**Comment by ericwongcm** [comment]
Try execute bb-update.php if you have not done so after upgrade. This fixed a "Reset password" e-mailing for me.

Other than test e-mail, the only staff e-mail I receive so far is user sign up but not invoice nor support. Do you receive order and support e-mail for staff? Or do you have any idea how I could fix this?

I also enabled email logging to database and staff e-mail for order and support e-mail is not recorded.

**Comment by arvelius** [comment]
I was not able to get it working by resetting the templates.

The problem lies in the bb-modules/Order/Service.php in the onAfterAdminOrderActivate() function which expects the Admin being logged in (it writes the 'Admin is not logged in' into the error log)
this change fixes it: https://github.com/boxbilling/boxbilling/pull/409/files

**Comment by TimeHost** [comment]
I have a very similar problem. Boxbilling will send all other emails but when someone opens a ticket the system will not send an email to staff unless I'm logged in to the staff area. Error logs say, 'Admin is not logged in' just as was mentioned above. Thus, I'm wondering if there is a file that deals with fixing the ticket system like the order file above.
