### ISSUE TITLE
PHP7 support for for exception handling

### ISSUE THREAD

**Issue by anthonyryan** [boxbilling/boxbilling#462]
Looking for guidance here as it appears this might cause some issues with upgrades to php7. I've done some research and it seems most people are adding in Thowable and others are adding in a hack based off of php version. Any thoughts?

`Fatal error: Uncaught TypeError: Argument 1 passed to handler_exception() must be an instance of Exception, instance of Error given in /www/bb-load.php:33 Stack trace: #0 [internal function]: handler_exception(Object(Error)) #1 {main} thrown in /www/bb-load.php on line 33`

**Comment by Mecanik** [comment]
I am really dissapointed in boxbilling that is has been abandoned. I have no time to start fixing the issues and make my system work properly, and I have hundreds of customers in boxbilling... I can`t even port to WHMCS wich is 10 times more professional, I can`t do anything... nice job BOXSHIT.

**Comment by RNKushwaha022** [comment]
How to resolve the issue?
