### ISSUE TITLE
Is this project still continue ?

### ISSUE THREAD

**Issue by pentatonicfunk** [boxbilling/boxbilling#469]
Is this project still continue ?

**Comment by pentatonicfunk** [comment]
or dead already ?

**Comment by Jawanet** [comment]
Boxbilling dead by developers, but you can continue with own developers

**Comment by pentatonicfunk** [comment]
does it mean, i can change the codes as i want ?, like remove license check , etc ?

**Comment by Jawanet** [comment]
What do you mean remove license to use boxbilling pro?

**Comment by marsoltys** [comment]
Yeah, to use boxbilling pro.

Why should I pay for product which is bugged, no longer supported and improved ?

Last release was A YEAR AGO !(?)

This is a bit unfair from my point of view.
Boxbilling owner is receiving subscription money every month and part of these money should be placed for dev team to improve product.

I think they try to be smart....
Get people to improve their product for free and still getting money for it.
Very smart ...

If something is opensource it means it should be free (in most cases) ...
I would like to hear from BB owner on what basis we are still charged.

**Comment by Jawanet** [comment]
If you have more private question, please contact us on indteamhost@gmail.com

**Comment by Mecanik** [comment]
+1 !! They are taking money each month normally, and doing NOTHING. Take a look at the bugs I found including the one when someone added 250$ into his account, and many more.. and what happened ? NOTHING. I stopped paying this month, this is bullshit allready. I paid 2 years, and even since it got open sourced, because I thought they will actually do something, but nope. I will try to somehow refund my money from paypal, if I can`t... go to hell boxshit developers.

**Comment by TuxMay** [comment]
BoxBilling is still in active development, the development team are having a break from development of BoxBilling and are focusing on other projects at this time.

If you know of any bugs in the system, please let Musicboxset Limited know (a partner of ours) who is currently collecting bug reports and feature requests so we can work together on developing a new update for you.

**Comment by Jawanet** [comment]
Musicbox only theme integration @TuxMay

**Comment by marsoltys** [comment]
@TuxMay in Active development ?

By who ? General public contributors ? xD

@Jawanet what sort of questions ? 
If dev related, I'm dev as well :)

**Comment by pentatonicfunk** [comment]
Look, i have no problem for subscription, but when i used boxbilling, i found some bugs and its critical, so i need to fix it by my self, since this github have small activity, so im sure, issue handling will be taking a long time to finish
First time i look at boxbilling, i already consider to use the PRO version, just like i said no problem for paid subscription. The problem is, when i see on github project, its just no "significant updates", i mean why i should pay if there is no support.

> Even i can't visit 
> http://extensions.boxbilling.com/
> This site can’t be reached
> 
> extensions.boxbilling.com’s server DNS address could not be found.
> DNS_PROBE_FINISHED_NXDOMAIN

So this issue just want to make sure, is it dead or not, if its not dead, just please behave that you are not like childish developer who said its "in development" when what i see is, "8 Months ago" on Branch **"develop"**

**Comment by TuxMay** [comment]
Hello Everyone,

If you require more information on the BoxBilling Development process - I will be posting an update on the FAQ thread on our forum some point tonight (BST) or tomorrow for those that would like an official update.

Best Regards,
Nathan - General Support
www.boxbilling.com

**Comment by scith** [comment]
Yes please, thanks

**Comment by TuxMay** [comment]
The thread has been updated on the forum for you. If you require any more information than what is stated on the FAQ on the forum, please contact Musicboxset Limited directly.

**Comment by freesurr** [comment]
@TuxMay Nathan seriously? Two years ago same story...

I cannot believe development is active...
I cannot believe an update is coming soon...
I cannot believe BoxBilling will ever return as normal maintained product...

**Comment by Jawanet** [comment]
@freesurr

Yes boxbilling dead by developer but you continue with own modification, if you seriuosly business i recommend you paid billing software

**Comment by freesurr** [comment]
@Jawanet I paid for BoxBilling, because it had lots of potential. I prefer to stay with BoxBilling, but they really need to do something...

**Comment by pentatonicfunk** [comment]
@TuxMay
By saying you have another project, i can take it that you guys already abandon this boxbilling that time.  And now when you see some potential buyer, and alot of complaining from paid users, you suddenly make this project active again. Thats just my opinion.

**Comment by Mecanik** [comment]
+1 Yes yes, absolutely true. I stopped paying these guys. I need to find some way to migrate to WHMCS because this boxshit was a big dissapointment, I should have known better.

**Comment by Jawanet** [comment]
I sure, if boxbilling active development features boxbilling can compare with whmcs.

Boxbill simple and minim error, but dev not seriuosly develop boxbilling.

**Comment by marsoltys** [comment]
Any updates ? Go AGILE !

**Comment by gocheap** [comment]
Boxbilling is not 100% free software either when you limit it. Charging for  a pro version is not open source and free.

**Comment by marsoltys** [comment]
@TuxMay 

Still nothing ?

Here is something more on AGILE approach and what I believe you should start do practice:
https://en.wikipedia.org/wiki/Agile_software_development#Iterative.2C_incremental_and_evolutionary

Thit will give at least the feeleing that something is happening ;) lol

What do I pay subscription for ?

**Comment by marsoltys** [comment]
@TuxMay Any updates mate ?

**Comment by trinitynet** [comment]
dead as a dodo

**Comment by Mecanik** [comment]
No updated, you are paying for nothing. The project is dead, but they still
want money, this is why I`m not paying anymore.

**Comment by TuxMay** [comment]
Hello Everyone,

The more you support BoxBilling in the next version the more we can get this new version developed. The more demand you give to get a new version released, the quicker our developers will get to developing feature's you want!

Regarding AGILE - have you requested the feature to us via proper channels? Has any of you requested features via proper channels?

At this time, we are concentrating on feature requests regarding security & maintenance, once this has been done, updates to current father's such as cPanel & PayPal, then new feature requests and hopefully new free themes.

Best Regards,
Nathan - General Support.
www.boxbilling.com

**Comment by Mecanik** [comment]
That`s bullshit, and you know it.

**Comment by marsoltys** [comment]
@TuxMay one of the Agile approaches are short frequent iterations which at least are giving customers feeling that something proper is happening with software development so don't give me rubbish about requesting new features (first fix bugs then do new features). Read about agile first. Then I thought that GitHub might be a proper channel to request different stuff as well as bug fixes.

Boxbilling will loose all support if you won't do anything with it soon... (you probable have noticed it already)

**Comment by TuxMay** [comment]
We will be releasing a small release in the coming weeks to fix a couple bugs including cPanel, Plesk & PayPal modules.

**Comment by michael-724** [comment]
Oh man, boxbilling would be my first choice. But when i saw last version of 2015 and a long list of bugs that are not fixed, then I have a bad feeling. And then these ridiculous comments here from boxbilling support. It seems as if they want to milk the cow as long as possible. Shame on you. Now I realize I will never use boxbilling.

**Comment by Mecanik** [comment]
Oh Michael, I've been trying to say the same thing !! I migrated manually all my stuff to whmcs long time ago. It's was a pain, but that's the price for trying to use something cheaper. At least whmcs has support and updates. These guys from boxbilling are exactly "trying to milk the cow as long as possible" for a few bucks....

**Comment by marsoltys** [comment]
You can buy one off licence through https://portal.mymbs.eu/cart.php?a=view.
If someone is happy with current BB state then that is the best option to follow.
Paying for subscription doesn't make any sense now :P

**Comment by scith** [comment]
Or you can just my fork in which I removed the licence check code...

**Comment by Mecanik** [comment]
This is not about license checking ... this is all the bugs it has, and their asking for $$.

**Comment by scith** [comment]
Its the only open source around. You are free to fix them yourself or pay your own dev to fix the ones that are critical for you. Nobody's forcing you to pay them specifically.

**Comment by OnlyHardOfficial** [comment]
Well it's going to start a new unofficial development over the BoxBilling panel ... Good News
