### ISSUE TITLE
How to escape mysql query

### ISSUE THREAD

**Issue by hinhthoi** [boxbilling/boxbilling#490]
Hi,

I'd like to process data from a form. I have a simple query like this:
``$query = "SELECT id FROM service_hosting WHERE sld='$var1' and tld='$var2'";
$list = $this->di['db']->getAll($query, array());``
However, $var1 and $var2 are raw input from the form. So I should escape the special characters before using it. How to do so? Which command should I put just above the above code? (In normal mysql query, we can simply use mysqli_real_escape_string, but I'm not sure how to do in boxbilling)

Thanks for any help!

**Comment by scith** [comment]
Hi
$query = "SELECT id FROM service_hosting WHERE sld='".$var1."' and tld='".$var2."'";

**Comment by hinhthoi** [comment]
Hi scith,

Where is the escaping function in the command? Your command is slightly different from my command in the opening post, but they are actually identical in querying mysql

**Comment by Eiskaltereistee** [comment]
Hi,

```php
$query = "SELECT id FROM service_hosting WHERE sld=:var1 and tld=:var2"; 
$list = $this->di['db']->getAll($query, array(':var1 => 'test', ':var2'=>'test');
```

**Comment by hinhthoi** [comment]
I know what you meant, but I'm interested in knowing how to escape (make it safe) the variables. Since the variables may not be as simple as "test" in your command, it may contains dangerous string which is used to inject bad sql command to the database.

**Comment by Eiskaltereistee** [comment]
Hi,

they're using RedBean for database interactions.

So have a look here: http://www.redbeanphp.com/index.php?p=/querying

> Remember: 
There is no need to use mysql_real_escape as long as you use parameter binding.

**Comment by hinhthoi** [comment]
So, as long as I follow the same syntax as your example command, it should be automatically internally escaped, is it true?, something like (I replace "test" with my variable)
```
$query = "SELECT id FROM service_hosting WHERE sld=:var1 and tld=:var2"; 
$list = $this->di['db']->getAll($query, array(':var1 => $var1, ':var2'=>$var2);
```
Thank you very much for your clarification. By the way, the link you posted doesn't work.

**Comment by Eiskaltereistee** [comment]
Yes, it's true.

The link works fine on my side...

**Comment by hinhthoi** [comment]
Thank you very much for your help, Eiskaltereistee.

**Comment by Eiskaltereistee** [comment]
You're welcome @hinhthoi

**Comment by scith** [comment]
Woops I misunderstood sorry. Glad you found the answer
