### ISSUE TITLE
Error Code: 9999

### ISSUE THREAD

**Issue by str33thack3r** [boxbilling/boxbilling#492]
Hello, 

I really love Boxbilling but recently it gives an error. Could you look into the matter, if time permits you? 

Thanking you.

**Error Message:** 

 **"curl_exec threw error "Could not resolve: Server-IP-ADDREE (Domain name not found)" for https://Server-IP-ADDREE :2087/json-api/listpkgs?"**

**Comment by scith** [comment]
Hi, it looks like you try to use cPanel plugin or some other plugin with a server that has no hostname defined...
In your plugin settings, update the server IP address or hostname accordingly and the problem will go away I think
