### ISSUE TITLE
Error: Gateway id not passed

### ISSUE THREAD

**Issue by faysal99** [boxbilling/boxbilling#499]
Hi, i am getting this error. Gateway id not passed

When i am trying to update custom payment gateway

Please help!

**Comment by lukapaunovic** [comment]
Which PHP version are u using?
What is in your error_log?

**Comment by faysal99** [comment]
Current PHP version:  5.6

[20-Sep-2017 05:35:25 UTC] Gateway id not passed 0

**Comment by faysal99** [comment]
please help anybody

**Comment by psycholyzern** [comment]
Boxbilling is dead. Please move on.

**Comment by lukapaunovic** [comment]
BoxBilling is not dead. The company which does development of BoxBilling is called MusicBox Limited. They gave information a few months ago that they are currently working on a brand new release of BoxBilling.

**Comment by psycholyzern** [comment]
@lukapaunovic it might come back, but now it is pretty much dead. Yes they said they are working on a new version and they said to me on Facebook it will be release very "soon". Many months passed and still nothing. Unreliable and no support. I can see people strugling with bugs and issues with no support from them including paid user.  
Even if someday they will come back, we don't know when they will halt the development again.

**Comment by lukapaunovic** [comment]
Well for it's price does job very well for my company. This is info i Got From them right now:

1. The software is not Dead.
2. We are working with many developers with regards to BoxBilling.
3. The software is having a 100% revamp which is the reason it is taking so long.
4. There is a lot of old code that needs stripping out, specially to make it PHP 7 compatible, this is taking so long as we are trying to keep it so previous versions can still upgrade but keep old themes/modules etc with it.

**Comment by psycholyzern** [comment]
I hope those promises won't be broken. Thank you for those informations tho. I didn't buy the paid plan, but was about to. Until I saw people strugling by themselves to solve errors and bugs they had.

**Comment by lukapaunovic** [comment]
I have a strong belief the revamp will be extraordinary.
