### ISSUE TITLE
does boxbilling support php 7.0 and mysql 5.7?

### ISSUE THREAD

**Issue by dedetok** [boxbilling/boxbilling#500]
I can not install boxbilling 4.18 nor 4.20 under Debian 9 (mysql community and php 7.0).
does boxbilling support php 7.0 and mysql 5.7? no error message on logs (access_log nor error_log )

# mysql --version
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
# php --version
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
# apt-get install php7.0-mcrypt php7.0-curl php7.0-gettext php7.0-mysql
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php7.0-common' instead of 'php7.0-gettext'

Thank you

**Comment by Eiskaltereistee** [comment]
Check out my answer: https://github.com/boxbilling/boxbilling/issues/474#issuecomment-291483755

Maybe it can help you

**Comment by dedetok** [comment]
Thank you Eiskaltereistee, I'll try your code... 
I close this issue.
