### ISSUE TITLE
Upgrade from PHP 5.5.9 to 5.6: undefined method Closure::country

### ISSUE THREAD

**Issue by hinhthoi** [boxbilling/boxbilling#505]
Hi,

I am running ubuntu 14.04.5 which used php5.5.9 as the default PHP version. Lets call this SERVER 1. Recently I have upgraded to PHP5.6, and I get the following error:

    PHP Fatal error:  Call to undefined method Closure::country() in /home/domain/public_html/boxbilling/bb-library/Box/TwigExtensions.php on line 101

The line 101 is

    $record = $this->di['geoip']->country($value);

I am also running another ubuntu 14.04.5 server ( let's call it SERVER 2), and I also upgraded php from 5.5.9  to 5.6 in the same way, but when I copy the boxbilling files and database from the previous server to this server, and I see it works fine, no error happens.

When I compared the list of installed packages of the 2 servers, here is the list of packages that is in SERVER 2 and not in SERVER 1

    libtsan0
    rsync
    sudo

Then in SERVER 1, I tried installing libtsan0 (even though I don't know what it is)

    apt-get install libtsan0

I got the following error:

    Unable to locate package libtsan0

I guess my SERVER 1 doesn't have some components neccesary for boxbilling to work in PHP5.6. (When I switch it back to 5.5.9, it works again!)

Could someone here help me troubleshoot the problem? I want it to work in PHP5.6 and in SERVER 1.

Thank you very much!

**Comment by TristianK3604** [comment]
Try upgrading to PHP 7.0. I use that with BoxBilling and it works just fine.
