### ISSUE TITLE
Im getting this (Invalid Period Code) issue, and its driving me nuts!!

### ISSUE THREAD

**Issue by sgreat123** [boxbilling/boxbilling#506]
An exception has been thrown during the rendering of a template ("Invalid period code. Period definition must be 2 chars length") in "mod_orderbutton_checkout.phtml" at line 1.

What am I doing wrong.....I've undone all my products, and redone till im blue in the face....

Please...any ideas!!

**Comment by KO-N** [comment]
Hello!

What version of PHP are you using?
Did you change something in the boxbilling files before this error message occurred?

**Comment by sgreat123** [comment]
PHP 7.2 And no not really...simply adding products...However it seems to have gone away for now...was driving me insane tbh.. But would love a handle on this!! someone must know...

Thankyou for your reply fella!!

**Comment by KO-N** [comment]
Well, if now there is no such problem, it's good.

If the problem appears again, try using PHP 7.0 or better PHP 5.3. :)

**Comment by pepijndik** [comment]
same issue with php version 5.3

**Comment by Khodour** [comment]
Same issue on php 7.4 , when trying to register domain 


ERROR
An exception has been thrown during the rendering of a template ("Invalid period code. Period definition must be 2 chars length").
