### ISSUE TITLE
News Module Issue

### ISSUE THREAD

**Issue by xeu100** [boxbilling/boxbilling#512]
Setting News text doesn't apply and it remains with either blank or default content. I've had to edit the posts table in mysql to fix it.

**Comment by xeu100** [comment]
Also applies to product creation

**Comment by TuxMay** [comment]
What PHP Version, Operating System & PHP Extensions are you using?

**Comment by xeu100** [comment]
7.0/7.1, Ubuntu, Standard PHP Extensions. The system is hosted on a cPanel server.

**Comment by Eiskaltereistee** [comment]
@xeu100 I think BoxBilling does not support php7.0+.

There is a active redevelopment of BoxBilling, Maybe you can have look there: https://github.com/CircleBilling/CircleBilling

There is a working version in the development branch - Maybe you can give them a try?
