### ISSUE TITLE
Email not sent after migrating the site to https

### ISSUE THREAD

**Issue by mylselgan** [boxbilling/boxbilling#517]
Recently we have switched our site to https with Letsencript SSL since then the system not able to send mails to clients and admins. I have tried SMTP configuration with SSL and TLS but no luck. I dont know where and how to check log file. please help.

**Comment by mylselgan** [comment]
forgot to mention we are using the latest version 4.20

**Comment by TuxMay** [comment]
SMTP is a very complicated thing & could be an issue with your hosting provider not allowing SMTP connections. Have you checked if BoxBilling installation is allowed to send SMTP emails from the server?

If you have & they have stated that your installation is white listed, you should check your SMTP log to see if BoxBilling was able to connect to the SMTP, if you do not know how to do this, again, your hosting provider will be able to assist in this.

You should try using your hostname as the host as well as trying localhost, sometimes using your hostname means using SMTP outside of the server is not allowed by hosts (if this makes sense).

If problems still persist, please do contact us ( http://www.boxbilling.com/contact-us ) & please reference this GitHub URL in your message.
