### ISSUE TITLE
how to make new client creat thiem account in order page 

### ISSUE THREAD

**Issue by aichounweb** [boxbilling/boxbilling#518]
hello guys !
i still dont know how to make new client creat thiem account in order page on Huraga theme like boxbilling theme so if u dont mind im asking :
 1 - how to make new client creat thiem account in order page on Huraga theme like boxbilling theme OR 

2 - how to change boxbilling.com link   on boxbilling theme  to any link i want.

**Comment by TuxMay** [comment]
The BoxBilling branding is enforced by A license key on the free edition of BoxBilling unless you have the technical expertise to remove it yourself (if you do, support of any kind is prohibited).

Huraga theme requires the customer to sign up or login before customer can order a service - some customers don't like this idea so we have the original theme that allows ordering before sign up/login.
