### ISSUE TITLE
Three bad practices: use of MD5, binding to 0.0.0.0, and keeping empty passwords

### ISSUE THREAD

**Issue by akondasif** [boxbilling/boxbilling#519]
Greetings,

I am a security researcher, who is looking for security smells in Puppet scripts. I noticed instances of MD5 uses in one of the Puppet scripts. MD5 is vulnerable to attacks, and should be avoided. The Common Weakness Enumeration organization recommends against usage of weak cryptographic algorithms such as MD5. Reff: https://cwe.mitre.org/data/definitions/327.html. 

I suggest the use of SHA512 , which is more secure. Any feedback is appreciated.  

Source: https://github.com/boxbilling/boxbilling/blob/master/puphpet/puppet/modules/postgresql/manifests/server/config.pp

**Comment by akondasif** [comment]
I also noticed instances of binding to 0.0.0.0. Binding an address to 0.0.0.0 indicates allowing connections from all IP addresses. I would like to draw attention to these instances. Binding to 0.0.0.0 may lead to denial of service attacks. Practitioners have reported how binding to 0.0.0.0 facilitated security issues for MySQL (https://serversforhackers.com/c/mysql-network-security), Memcached (https://news.ycombinator.com/item?id=16493480), and Kibana (https://www.elastic.co/guide/en/kibana/5.0/breaking-changes-5.0.html).    

I suggest to use a dedicated IP address other than 0.0.0.0. 


Source: https://github.com/boxbilling/boxbilling/blob/master/puphpet/puppet/modules/postgresql/manifests/params.pp

**Comment by akondasif** [comment]
Along with the two smells, I also noticed instances of empty passwords. Empty passwords increase the guessability of passwords. The Common Weakness Organization (CWE) identifies use of empty passwords as a security weakness (https://cwe.mitre.org/data/definitions/258.html). 

I suggest that to follow the strong password guidelines, and manage passwords with hiera.  

Any feedback is appreciated.  


Source: https://github.com/boxbilling/boxbilling/blob/master/puphpet/puppet/modules/postgresql/manifests/server/role.pp

**Comment by psycholyzern** [comment]
This project is dead. Sad to see such a good opensource project gone.

**Comment by Eiskaltereistee** [comment]
Hi,

I don't think it's dead. @TuxMay still give support for the latest released version. And CircleBilling also looking forward to contribute some bugfixes to BoxBilling. 

If you need a php 7.2 working version, you should follow CircleBilling: https://github.com/CircleBilling/CircleBilling

Otherwise all of you are welcome to share bugs. BB or CB will fix that then.

Thank you and have a nice day!

**Comment by BenNottelling** [comment]
It actually looks like the files relating to this no longer exists. There are still a few instances of using MD5 that I know of, though

**Comment by notbasetwo** [comment]
From what I can see, most of the current uses of MD5 are in places like payment gateways or APIs which is required.

This specific issue was (and should be considered) closed by #700 as Puhpet was removed.

**Comment by BenNottelling** [comment]
> From what I can see, most of the current uses of MD5 are in places like payment gateways or APIs which is required.
> 
> This specific issue was (and should be considered) closed by #700 as Puphpet was removed.

Yes, you're right. There are a few instances of our code using `md5(uniqid())` to generate hashes though.
I'm going to close this and we can talk in slack about changing aforementioned code that's used in a few places
