### ISSUE TITLE
An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by ryanapil** [boxbilling/boxbilling#522]
An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'DBNAME.p.priority' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") in "mod_order_index.phtml" at line 20.

https://DOMAIN.TLD/billing/index.php?_url=/order

**Comment by rebelholic** [comment]
> Hi,
> this is because of some incorrect group queries (Already a known bug)
> 
> Here is a workaround: https://stackoverflow.com/questions/23921117/disable-only-full-group-by
> 
> I had no time the past weeks, so I'am not able to merge the queiers to boxbilling - But I'am looking forward to create the pull request soon.
> 
> Thank you.

so anyone already fix it such as release new patch?

**Comment by rndevuk** [comment]
it appears that this was closed without any indication. il test it out tomorrow morning and report back.

**Comment by rebelholic** [comment]
Any update on this?
