### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Gateway not found") in "mod_invoice_gateways.phtml" at line 31.

### ISSUE THREAD

**Issue by DJTerrum** [boxbilling/boxbilling#527]
Unfortunately I messed up the gateways somehow, and I have no idea how, but now when I click on 'Payment gateways' in Configuration from the admin panel, it shows this error:

An exception has been thrown during the rendering of a template ("Gateway not found") in "mod_invoice_gateways.phtml" at line 31.

I honestly have no idea what to do, seems that even temporarily purging the 'pay_gateway' table doesn't effect the error.

Any help is greatly appreciated!

**Comment by TuxMay** [comment]
The error is referring to a "Gateway not found" error (not directly to a template file), which means one of the Payment Gateways cannot be found or is not properly configured/coded.

**Comment by DJTerrum** [comment]
Thanks for the really swift response and the helpful information.

Can you tell me how it searches the payment gateways? I assumed the 'pay_gateway' was the only place that the gateways are read, therefore I have no idea where else it is searching for gateways that can't be found. (If that makes sense?)

Is there a way to verbose the error and make it print or log further details?

**Comment by TuxMay** [comment]
It searches all the payment gateways you have in the bb-library/Payment/Adapter/ directory of your BoxBilling installation. From the error above, it is a coding error with the displaying of an invoice.

Are you using a custom payment gateway?

**Comment by DJTerrum** [comment]
I managed to fix it by removing id 0 (for some reason there was a blank column with id 0 in the database).

However now I am having an issue with my PayPal gateway (not custom), it is no longer detecting payments made through PayPal. The IPN link that I was given on the gateway is the same as my PayPal account also.

When I go to the 'transactions' tab and press 'Process' on the transaction, it just says 'IPN is not valid'. Not entirely sure what this means seeing as the gateway gave me the IPN link and I have definitely set it  correctly to my PayPal account.

Any help is greatly appreciated!
