### ISSUE TITLE
Attention! The license file has been amended!

### ISSUE THREAD

**Issue by notfo** [boxbilling/boxbilling#528]
Attention! The license file has been amended! I suggest removing these vile corrections, or stop licensing the project under the Apache 2.0 license. This is contrary to the spirit and meaning of the Apache 2.0 license

**Comment by TuxMay** [comment]
I'm sorry? What do you mean the license file has been amended?

**Comment by notfo** [comment]
Thank you for understanding me.

**Comment by TuxMay** [comment]
@notfo The bit you saw at the end of the license is still valid, it has just been moved to the end of our README.md file.

**Comment by notfo** [comment]
@TuxMay I have seen that. In README.md you can edit anything you like. This has no legal effect.
Because the additional agreement of the end user is contrary to the freedom of modification, fork and distribution, which is prescribed in the main license - apache 2.0

**Comment by notfo** [comment]
@TuxMay
To license this software with this requirement:
"Those that wish to distribute a modified version of BoxBilling must gain permission from BoxBilling before releasing the software. "
You must write your license, such as Boxbilling open License.
But this will definitively kill the project and destroy the community.

**Comment by notfo** [comment]
As soon as Hostinger update Boxbilling like open software, it ceased to be just yours. It became the property of the developer community. Read carefully the Apache 2.0 license. Anyone can now modify and distribute Boxbilling for any price, provided that it changes the naming of software.

The only responsibility of the distributor is to leave the mention of Boxbilling in each licensed file. At the same time, the distributor is not obliged to distribute the modified software under an open license and may that change to its own.

So your claims are groundless.

**Comment by TuxMay** [comment]
Regardless, that is our restriction at this time. We also have that in place so we know who is distributing it (we can see what people are doing with the BoxBilling software).

And the Apache License doesn't make it not ours, the copyright remains ours regardless of the license, just isn't as restricted as other licenses (such as WHMCS, HostBill, ClientExec etc.)

**Comment by notfo** [comment]
Copyright belongs to everyone who contributed to the source code or the design of Boxbilling. And personally you do not have the right to decide on what terms this project is licensed.

I understand your pain. Every year you make less and less money on paid licenses of Boxbilling. But this is not due to the fact that someone is using their rights in conformity with the Apache license.

This is a consequence of your attitude to the product. No one will pay for billing software, which has not been updated for several years. Where is the promised version 5?

If Hostinger believes that someone is using its product  incorrectly, but according to the Apache license, then I advise you to sue them.

And I'm sure that the truth will be on the side of open source software. Maybe this will finally attract developers again to participate in Boxbilling.

**Comment by notfo** [comment]
Why do you delete my comments?

**Comment by Eiskaltereistee** [comment]
@TuxMay you should know, that you are not able to change the license agreement forks which are done before.

You license change is just valid to changes that you do in future.
Sooo it just makes sense if you're planning to continue the work of bb.

Otherwise, we did the fork before your license change, so we're not affected to that.

Thank you.

**Comment by TuxMay** [comment]
@Eiskaltereistee the the licence agreement was made when v4 was released, so the agreement applies to anyone from when the source code was brought into action.

We have done many changes and moved the additional terms all over the place so it is still valid.

**Comment by Eiskaltereistee** [comment]
@TuxMay you're wrong, I think. Please help me, if you think that I am wrong.

You added that part to the license 12 days ago to the license file. So please show me where can I find that part from older revisions in that git tree?

Please notice, it's not possible to add license stuff everywhere you want. There are fixed locations where to have license agreements and you also have to keep to the apache2 defaults.

**Comment by TuxMay** [comment]
You are right in which the distribution rules don't apply to you (CircleBilling) - we are already aware of CircleBilling & have contributed to BoxBilling itself.

We are referring to the copyright itself, check every file, this retains the copyright of the software and must stay intact.

**Comment by StefvanEgmond** [comment]
Thanks for the confirmation @TuxMay 👍
