### ISSUE TITLE
Order Popup button not working

### ISSUE THREAD

**Issue by sks1123** [boxbilling/boxbilling#530]
Hi I am using Order Pop-up button on a website which has boxbilling as a folder like http://domain.tld/boxbilling. I am trying to integrate the pop-up button in index file in the root folder. I have done exactly as given in tutorial but the button does not work. It is not even showing in required colour (green). Is anyone else facing this issue?
It seems my website Template is interfering with the pop-up script. Is there any way to override it?

**Comment by kieran2001** [comment]
Are you still having this issue?

**Comment by sks1123** [comment]
yes. the button is still non-responsive.
