### ISSUE TITLE
Hello, could anyone help me with this error warning?

### ISSUE THREAD

**Issue by duduxweb** [boxbilling/boxbilling#531]
Hello, could anyone help me with this error warning?

`An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'compras_bxl.stm.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") in "mod_index_dashboard.phtml" at line 71.`

**Comment by duduxweb** [comment]
`An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'serverho_bxl.tr.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") in "mod_servicedomain_index.phtml" at line 248.`

**Comment by kieran2001** [comment]
Where are you getting this error from?

**Comment by desfire** [comment]
You may want to check https://github.com/CircleBilling/CircleBilling/, did not face that issue there

**Comment by Raistlin31** [comment]
For the people who having the same problem, the solution is turning off only_full_group_by from mysql.

**Comment by smghosting** [comment]
Hi im getting this error... Any Help ..
An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'smgwebho_smg.tr.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") in "mod_servicedomain_index.phtml" at line 248.
this is on Boxbilling
