### ISSUE TITLE
Licence 

### ISSUE THREAD

**Issue by soumyadip77** [boxbilling/boxbilling#533]
Why i need licence for all unlimited is any one can provide me licence for free

**Comment by soumyadip77** [comment]
How brother? Plz help and i want to add Indian payment method i want if some one click on that payment method he will get a pop-up and details plz help me if u can add me in fb plz https://www.facebook.com/soumyadip.dutta.9

**Comment by TuxMay** [comment]
You do not require a license to modify the BoxBilling code. 

However, If you decide at a later date that you wish to get technical support from BoxBilling, we will not provide it if you do modify the base code of BoxBilling.

**Comment by soumyadip77** [comment]
oh..me checked my products i don't need to change code :dancer:  because i have only hosting and VPS catagory VPS have 3 sub catagory an hosting too. But i want to add my country pyment method.

Read this whole and help me plz.

I want to add 1 payment gateway where if client click on that method he will redirect to 1 page where he will see 1 QR code he need to scan and pay this page have only 1min time then it will redirect to thing which happend after pay. Can you plz help me plzz URGENT

**Comment by TuxMay** [comment]
> I want to add 1 payment gateway where if client click on that method he will redirect to 1 page where he will see 1 QR code he need to scan and pay this page have only 1min time then it will redirect to thing which happend after pay. Can you plz help me plzz URGENT

You will need to either request the feature via our official feature request page or you will need to hire a developer in order to develop the payment gateway (or you can develop it yourself).
