### ISSUE TITLE
Payment Gateway

### ISSUE THREAD

**Issue by soumyadip77** [boxbilling/boxbilling#534]
oh..me checked my products i don't need to change code dancer because i have only hosting and VPS catagory VPS have 3 sub catagory an hosting too. But i want to add my country pyment method.

Read this whole and help me plz.

I want to add 1 payment gateway where if client click on that method he will redirect to 1 page where he will see 1 QR code he need to scan and pay this page have only 1min time then it will redirect to thing which happend after pay. Can you plz help me plzz URGENT

**Comment by kieran2001** [comment]
You will need to hire a BoxBilling developer to add functions that aren’t currently included.
