### ISSUE TITLE
How to attach a screenshot in support ticket?

### ISSUE THREAD

**Issue by hinhthoi** [boxbilling/boxbilling#535]
I read in the documentation, it stated that it is possible to attach a file to support ticket

docs.boxbilling.com/en/latest/reference/support.html

> There is also an attachment box if you need to attach a file with your ticket

However, I haven't found out how to do that. I love to see this feature. Is there any way (modify code) to have this feature? This is a core feature to give support to users, since very frequently they will need to show a screenshot of the problem

**Comment by kieran2001** [comment]
No one appears to be active at BoxBilling anymore, as there’s being no updates in over 3 years. 

At the moment, there’s no complete upload image option. However, with the BoxBilling WHMCS Theme (
https://github.com/yokowasis/boxbilling-whmcs-bootstrap) they give 3 image upload options which all go via external sites, and you can copy and paste the link into the reply. 

Just makes image sharing easier for the customer.
