### ISSUE TITLE
cPanel Generation doesn't work.

### ISSUE THREAD

**Issue by Syndanimux** [boxbilling/boxbilling#537]
So I've set up boxbilling mostly. There's a hosting server and hosting packages. However, when an account orders a service and the service gets activated, the cPanel generated only redirects to google for some reason.

**Comment by TuxMay** [comment]
What do you mean it redirects to Google? You mean when a customer tries to login or when the account physically gets created?

**Comment by Syndanimux** [comment]
When a customer tries to open the generated cPanel link. Would you like a ljnk to the site for a demonstration of the issue?

**Comment by Syndanimux** [comment]
Expanding on the explanation. When the customer successfully purchases a package, boxbilling produces a cPanel link to access the panel, however that exact link only redirects to google. I am unable to figure out a solution.
