### ISSUE TITLE
("Currency not found") in "mod_index_dashboard.phtml" at line 33.

### ISSUE THREAD

**Issue by belko2** [boxbilling/boxbilling#538]
Hello, forgive my English

I just made a new installation of Boxbilling. I had to do it manually by importing the database from /install/structure.sql and manually editing the bb-config.php file

I registered the administrator in [mydomain.com] /index.php?_url=/bb-admin/staff/login

I have checked the database and the administrator has been created. But when I want to access the admin panel through [mydomain.com] /index.php?_url=/bb-admin, the following error appears:

An exception has been thrown during the representation of a template ("Currency not found") in "mod_index_dashboard.phtml" on line 33.

**Comment by g4m3r0** [comment]
You forgot to import the content.sql database after the structure.sql.
That's the reason why there was no default currency in the DB and you got this error.

I think this issue should be closed.
