### ISSUE TITLE
Cannot click next on install page 

### ISSUE THREAD

**Issue by WuXeR** [boxbilling/boxbilling#541]
I'm trying to install it but once I get to the configure database page it won't let me click next. Also I cannot get php-mcrypt to work. It keeps telling me it's not installed even though it should be....

**Comment by TuxMay** [comment]
If you cannot get passed step 2 (database), this means you are using a PHP version that is not supported by BoxBilling, note that BoxBilling does not yet support PHP 7.x

**Comment by WuXeR** [comment]
Alright so what version should I use? Also is it possible to have two versions of php installed at the same time? I’m currently running a controlpanel that requires php7.2
