### ISSUE TITLE
Cannot generate a slug (pretty url) in forum if topic is not alphanumerical

### ISSUE THREAD

**Issue by jefflin555** [boxbilling/boxbilling#543]
I am not sure if anyone can help me with this.

I discovered that if a client attempts to create a new forum topic, and if the topic is completely non-alphanumerical (e.g. all in Chinese characters), then the system will not be able to generate a slug for the topic.

The url to view discussion threads is `index.php?_url=/forum/topic_slug`, which renders these topics inaccessible since they have no slugs logged in the database.

The majority of my clients are Chinese speakers, so I wonder if anyone here could offer some insights as to how I can fix this problem. Or is it possible to access discussion threads using database id instead of slugs?

Thank you!

**Comment by jefflin555** [comment]
Just an update. 
I fixed the issue (king of) by making the following revision to `bb-modules/Forum/Api/Client.php`.

**Original code** (line 186)
```
$topic->slug = $this->di['tools']->slug($data['topic']);
```

**My code**
```
$topic->slug = random_bytes(5);`
```

It's just a bodge, and by no means a long-term fix, though. I am going to leave this issue as open for a bit to see if anyone can offer a better solution.

**Comment by SnakePin** [comment]
Why not use `rawurlencode` ?
