### ISSUE TITLE
SMTP doesnt work

### ISSUE THREAD

**Issue by GKLennie** [boxbilling/boxbilling#545]
Hello,

Whatever I do, my smtp settings never work. I have tried everything I can, any help would be appreciated.

Thanks,
GKL.

**Comment by TuxMay** [comment]
If SMTP is not working, you will need to contact your hosting provider to see what might be blocking it. A lot of  providers require you to notify them in order for it to be enabled on your hosting account.

**Comment by GKLennie** [comment]
I host it my self, b

> 
> 
> If SMTP is not working, you will need to contact your hosting provider to see what might be blocking it. A lot of providers require you to notify them in order for it to be enabled on your hosting account.

I host it my self

**Comment by TuxMay** [comment]
What do you host it on?

**Comment by jefflin555** [comment]
What versions of BoxBilling and PHP are your running?
I used BoxBilling 3.6 and the SMTP function never worked with PHP 5.6, and now I've upgraded to BB 4.2, it doesn't seem to work with PHP 5.5 or below...
Try switching the PHP version up or down if possible, and see if the issue gets resolved.

**Comment by TuxMay** [comment]
@jefflin555 BoxBiling uses the standard SMTP which has been tested & does work for the PHP 5.x branch, most hosting providers block SMTP emails as they are a huge way to send SPAM & manually enable them for certain customers when they request it.
