### ISSUE TITLE
boxbilling does not send hosting account activation email

### ISSUE THREAD

**Issue by powerflips** [boxbilling/boxbilling#549]
boxbilling does not send hosting account activation email after the client makes the request for the hosting and domain it only sends the data of the new domain to the client and does not send the data of the new hosting, such as login, password, cpanel and nameservers does anyone know what it can be?

**Comment by TuxMay** [comment]
Emails are tricky to diagnose. Majority of the time if other emails are being sent from BoxBilling but not the account activation, this means it is being blocked by the server.

If no emails are being sent by the system, then your hosting provider has blocked outgoing emails for third-party scripts to prevent abuse & SPAM.

**Comment by powerflips** [comment]
it does not have any logic whatsoever, if you are sending emails of tickets, configuration of domain and everything, you have to send the activation email of hosting account.

**Comment by TuxMay** [comment]
I'm sorry, I do not understand your response? Like I said, emails are tricky to diagnose & usually are because of restrictions from your hosting provider.

**Comment by powerflips** [comment]
all the emails are being sent correctly, except for the activation of hosting account, my hosting provider is not blocking any email from me even because they would disrupt the work of my work.

**Comment by TuxMay** [comment]
I would suggest you contact your hosting provider, if the account activation is the only one not sending, then it is getting disrupted by your hosting provider.

**Comment by powerflips** [comment]
I've figured out what the problem is!
I offer hosting with free domain, and when in the configuration of the domain I put the value of $ 0.00 and the client makes the request it only sends the configuration of the domain and does not send the configuration of the host that has to go together, but when I charge the domain value such as $ 10 it sends the email with the client's hosting data.
Can you help me with this?

**Comment by powerflips** [comment]
I need my clients to be able to order with the domain at $ 0 and get the email or enable their option to use a subdomain of mine and I did not find this option in the software

**Comment by TuxMay** [comment]
@powerflips Instead of having the price $0, why not use the option we provide for a free domain with hosting?
