### ISSUE TITLE
How To Make cPanel Login Username As Domain

### ISSUE THREAD

**Issue by IbraaMx** [boxbilling/boxbilling#550]
Hello
I Want Make cPanel Login Username As Domain Registration

**Comment by AmirOVH** [comment]
Do you mean you wanna change the default username which Boxbilling automatically creates like "u12345678" ?

**Comment by IbraaMx** [comment]
yeah

**Comment by viktaroa** [comment]
Any answer?

**Comment by VirtualworldGlo** [comment]
Any answer?
