### ISSUE TITLE
"Failed Setup" for domain registration /resellerclub

### ISSUE THREAD

**Issue by J3706** [boxbilling/boxbilling#551]
Thanks in advance for all who throw in their two cents, I've been looking into this for about two weeks now since I wanted to try and find the solution first hand.

I've got box billing setup and installed properly, whm connected, packages/categories created, and cpanel accounts being created perfectly however, whenever I try registering a domain name it fails.

For example, I have domains included with hosting packages and when an order is made the account/cpanel will be setup just dandy, although the domain registration will report that setup failed.

Registering domains alone also seem to not work

**Notes**
- ResellerClub(RC) is the linked and the only reseller listed. Others have been deleted.
- I've whitelisted the single ip address in resellerclub
- I've added the domains in admin panel(BB)
- I've added the reseller id(BB)
- I've added the API Key in BB
- Domain lookup/check on the website DOES properly work

**Comment by TuxMay** [comment]
I can see you have done the main things, have you got any Third Party API restrictions running on your hosting server? Majority of third party api's are restricted by the server on cPanel (it is now default disabled on cPanel/WHM) for security reasons & you may need to white list Reseller Club's IP's with WHM (a root user may need to do this).

**Comment by J3706** [comment]
@TuxMay Thank you for getting back as quickly as you have! Really appreciated.

I was not aware of that and will have to look to see where that's all located. I'll have to see it work.
Thanks again!

**Comment by J3706** [comment]
@TuxMay 

Is what you're talking about called ModSecurity? (in cp)

Could you please point me in the proper direction on where I can learn these things, or give the steps to accomplishing this?

Thanks,

**Comment by J3706** [comment]
@fordnox maybe you could please point

**Comment by J3706** [comment]
Accidentally closed, although problem persists. Still new to github, sorry.

**Comment by binaryme** [comment]
I also encountered a problem when registering a new domain through reseller club 

error message is: Invalid credentials, or your User account maybe Inactive or Suspended 

it's likely that the user I'm sending has different data
email and password should be the same (that same tidbit happened on whmcs software) 

I'm researching on what's the data expected and where the mismatch comes from.

**Comment by BenNottelling** [comment]
> I also encountered a problem when registering a new domain through reseller club
> 
> error message is: Invalid credentials, or your User account maybe Inactive or Suspended
> 
> it's likely that the user I'm sending has different data
> email and password should be the same (that same tidbit happened on whmcs software)
> 
> I'm researching on what's the data expected and where the mismatch comes from.

It's very probable that that integration is broken fyi
