### ISSUE TITLE
New TLD - Allow transfer radiobutton ingnored

### ISSUE THREAD

**Issue by g4m3r0** [boxbilling/boxbilling#557]
When a new TLD is created the "allow transfer" radiobutton input will be ignored (always false/no).
at /bb-admin/servicedomain

**Comment by BenNottelling** [comment]
This should have been fixed by this commit
https://github.com/boxbilling/boxbilling/commit/e8110a7930548b95128746a822162ded2c2b734e#diff-1e382f6289eb376883736caeb482ff78aa8c0d984829caecc3c1f3c6765b4fd8
