### ISSUE TITLE
License is not valid

### ISSUE THREAD

**Issue by AshleyHunter01** [boxbilling/boxbilling#561]
I have the free license and i made the key 24 hours ago and it says it is not valid.

**Comment by gOOvER** [comment]
Boxbilling is really dead. i would install it. Too old and no support

**Comment by gOOvER** [comment]
btw you can remove the senseless Licence Check. Boxbilling is GPL and there is no need to register or bus a licence

**Comment by AshleyHunter01** [comment]
> Boxbilling is really dead. i wouldn't install it. Too old and no support

Is there any other free alternative ?

**Comment by AshleyHunter01** [comment]
I get errors when trying to remove the domain registration thing and when a user creates an account

**Comment by gOOvER** [comment]
> > Boxbilling is really dead. i wouldn't install it. Too old and no support
> 
> Is there any other free alternative ?

No

**Comment by gOOvER** [comment]
> I get errors when trying to remove the domain registration thing and when a user creates an account

Search the Tickets. There is a Way to remove useless Licence Check. But as i said. Don'tz use it. It's insecure ;) out of date and not maintained :) As long the original Author don't know what GPl means, i wouldn use this script

**Comment by AshleyHunter01** [comment]
Going to switch to WHMCS then

**Comment by gOOvER** [comment]
@TuxMay Remove that fuckinmg Licence registration from your site and Script. I will start a report to European privacy Agancy, becasue you have a really bad Privacy Agreeement and you collect data without reason.

**Comment by TuxMay** [comment]
@gOOvER I'm no longer apart of the BoxBilling team.
