### ISSUE TITLE
registrant_role

### ISSUE THREAD

**Issue by Burny87** [boxbilling/boxbilling#563]
Hi,

when registring a domain with internetbs the error message comes:

Required parameter "registrant_role" missing!

How can I change that, can you help me ?

thanks

**Comment by Burny87** [comment]
please help me

**Comment by g4m3r0** [comment]
Where do you get this error?
I'm not registered in internetbs but I think the bb api adapter is outdated.

**Comment by Burny87** [comment]
Where can I get a new one?

**Comment by Burny87** [comment]
or for soap api

**Comment by g4m3r0** [comment]
> Where can I get a new one?
You will need to update https://github.com/boxbilling/boxbilling/blob/master/src/bb-library/Registrar/Adapter/Internetbs.php by yourself to get it working again.
