### ISSUE TITLE
Directadmin extension???

### ISSUE THREAD

**Issue by pepijndik** [boxbilling/boxbilling#570]
Hi BoxBilling,

Your direct admin extension is old and not working any more??

Are you going to update it or did you stop this project....??
Your still selling license and I wanted to buy them only if Directadmin is still supported (Found out) that it isn't working on my free account..

So hope you will update so I  and many other people will maybe buy the licenses..

**Comment by fordnox** [comment]
Hi @pepijndik 
This project is now open source and community support driven. The code is open and can be freely updated. 

Create a pull requests and it will be checked.

**Comment by pepijndik** [comment]
> Hi @pepijndik
> This project is now open source and community support driven. The code is open and can be freely updated.
> 
> Create a pull requests and it will be checked.

Hi okey,

Than I know enough. I have made my own extension for directadmin.
Is there any possibility that I can use the BoxBilling pro without to buy? I want to buy it but only if I get support end the software is getting updated 🗡

**Comment by g4m3r0** [comment]
DA works fine for me.
What error do you get?

**Comment by nightstryke** [comment]
@g4m3r0 

How did you get Directadmin working?
Any help or insight would be appreciated.

**Comment by g4m3r0** [comment]
@nightstryke the only thing I changed is that I commented line 90-91 in clients/bb-library/Server/Manager/Directadmin.php out to use the packages I predefined in DA.
