### ISSUE TITLE
cpanel Login for client without adding a WHM

### ISSUE THREAD

**Issue by VirtualworldGlo** [boxbilling/boxbilling#571]
Hi,

Is there any way where we can create a customer login to their cpanel account from the client area using cpanels latest API for cpanel user account (NOT WHM API)

We resell a few cpanel accounts to clients where we onlu have acces to IP address, cPanel Username, Password, cPanel API Token 

Can we set this up in the admin section so that the user can click "Login To cPAnel" from client area and directly login without the username or password

--
Rajesh M

**Comment by samapraku** [comment]
Hi @VirtualworldGlo,

From the cpanel api documentation page, it appears it is not possible to create a user login session using only UAPI without using WHM API ([UAPI - Session::create_temp_user](https://documentation.cpanel.net/display/DD/UAPI+Functions+-+Session%3A%3Acreate_temp_user))

I have implemented the cpanel/WHM logins from both client and admin areas. It uses the WHM API and the login details configured for the server (username and api token or password).

The implementation is available here:  
Login to cpanel: samapraku/boxbilling@0be898ada7fcc11cfac5eb86f727996a024b8e2a
Login to WHM: samapraku/boxbilling@72cf77b7a7ff3d281bef1f73658a13b6c3eaa2f4
