### ISSUE TITLE
Php 7.x support

### ISSUE THREAD

**Issue by kasperireland** [boxbilling/boxbilling#574]
Hi there,
I was wondering if boxbilling will support php version 7.x soon.
Thanks

**Comment by fordnox** [comment]
Hi @Kasper2040 

I kindly invite you to participate in contribution of this open source software to keep it up to date.

**Comment by sohamb03** [comment]
@fordnox Well I'm ready to contribute in a few ways if you'd like to.

**Comment by emar** [comment]
I hope boxbilling will support php 7+ soon,

My cPanel MultiPHP Manager says:

Warning: PHP versions PHP 5.4, PHP 5.5, PHP 5.6, PHP 7.0, and PHP 7.1 are deprecated. We recommend that you update to a supported version of PHP.

I have a cms set up to use the latest php 7+  
Installed boxbilling on the same hosting account,
Maybe I shoulda used a subdomain for boxbilling.

I got a warning in boxbilling admin about my site using php 7+
If I want to enable php 5.6 for my boxbilling installation, I ticked yes .

Should we really be using php versions that are not supported/deprecated?

**Comment by Neustradamus** [comment]
Any news?

**Comment by vahidalvandi** [comment]
please upgrade to php 7

**Comment by 4yx** [comment]
There seem to be two issues about this subject.
Most of the discussion is happening on #592 and there is an active PR about PHP 7.2 on #602.

**Comment by Neustradamus** [comment]
@samapraku: It is has been merged!
- https://github.com/boxbilling/boxbilling/pull/602

Guys can you test the master?

Linked to:
- https://github.com/boxbilling/boxbilling/issues/592

**Comment by timothygwebb** [comment]
Closed by PHP 7.4 Compatibility Update #645
