### ISSUE TITLE
Webinstaller only shows a blank page

### ISSUE THREAD

**Issue by MaxMuster3333** [boxbilling/boxbilling#580]
Hello there,
I was recently looking into BoxBilling again since my old (self-made) system wasn't able to take all requests and so I hoped that BB will. However: After I uploaded version 4.21 and extracted it, moved it over etc. it only showed me a list of all files.
After navigating around a little bit I found out that there was an index.php in src. So I navigated there and it showed me the error 101 (bb-config.php is missing/incomplete) and asked me if I wanted to run the installation. After I said yes, it redirected me to ../src/installer and only showed me a blank page. No Title or content.

I tried several other ways to solve this problem such as:

- Making src the root directory
- Deleting the config before running the installer
- ~~Banging my head against the wall~~
- Doing it the manual way

None of these worked.

I tried it on
- PHP 5.3
- PHP 5.4
- PHP 5.5
- PHP 5.6
- PHP 7.1
- PHP 7.3
with all needed extensions (if available).

I am doing this in my (private) sandbox, so don't worry about stuff breaking.

Best regards and thanks for being alive
 -Jonas from 3001.Host

PS: You might want to update your website, it's starting to look old. (or you could ask me to make a new one. I would be happy to do so.)

**Comment by kirksmacdonald** [comment]
the vendor's folder is missing with the required files from the master's branch
