### ISSUE TITLE
Deleting account on the website

### ISSUE THREAD

**Issue by ncodeyx** [boxbilling/boxbilling#583]
Under GDPR, I have exclusive rights to have my account removed from your grotesque platform.

Since you guys love keeping a dead website "alive" how about you provide a support method to accomplish this?

Failure to do this will assume liability under the General Data Protection Act.

**Comment by timothygwebb** [comment]
> Under GDPR, I have exclusive rights to have my account removed from your grotesque platform.
> 
> Since you guys love keeping a dead website "alive" how about you provide a support method to accomplish this?
> 
> Failure to do this will assume liability under the General Data Protection Act.

**Comment by ncodeyx** [comment]
cc @ton31337

**Comment by gOOvER** [comment]
I thought the same. Shut down ur site. Can be  very expensive, when someone report u. U Sell not existing  Subscription and noone can delete account

**Comment by ncodeyx** [comment]
cc @fordnox

**Comment by ncodeyx** [comment]
cc @fordnox
