### ISSUE TITLE
Latest Release?

### ISSUE THREAD

**Issue by amlanrd** [boxbilling/boxbilling#586]
I'm using BoxBilling 4.20. Update checker says that it's the latest release. But in your github, latest release is 4.21. If so, then why I can't update from BoxBilling itself? What are the changelogs?

**Comment by zohaib87** [comment]
I just manually updated it now it says 0.0.1 version... I am so confused.

**Comment by zohaib87** [comment]
Ok guys don't click the download button as it says on README.md. Use clone or download.

**Comment by Neustradamus** [comment]
Any news?

**Comment by zohaib87** [comment]
Update it manually. Before update change "VERSION" to 4.21 in "/bb-library/Box/Version.php"

1. Download latest BoxBilling from here.
2. Extract files at your computer
3. Upload (overwrite) extracted files via FTP to /home/xecreate/clientsarea.xecreators.pk
4. When upload is complete, execute https://yourdomain.com/bb-update.php in your browser
5. Your BoxBilling is now updated to latest version.
