### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by MutegekiHenry** [boxbilling/boxbilling#590]
Was following through the installation steps on the Docs [http://docs.boxbilling.com/en/latest/reference/installation.html](url) but when i go to the Download Page [https://www.boxbilling.com/download](url) and try to download, i get an error of the kind below, yet i registered and got a free licence. 
![failedtoDownload](https://user-images.githubusercontent.com/36065782/80685543-38199580-8a7c-11ea-956d-6a26171c7a93.PNG)

**Comment by MutegekiHenry** [comment]
Got another way around it via [https://github.com/boxbilling/boxbilling/releases/tag/4.21](url)
But the download button on the official website is faulty

**Comment by S4-Hosting** [comment]
@MutegekiHenry Just curious, after you did manage to download it, did you install it using the install instructions from the site (and linked to from the github readme). I've just run through them and it doesn't work.

It's a terrible first impression when people go to an 'official' site and click a download link and it gives an error. I'm also a bit confused about the whole thing, are the site and the github controlled by the same people, they don't seem very in sync with each other?

Is this now a community open source project or is it owned by someone, the whole license key and 'pro' thing doesn't seem to make sense for software that hasn't been maintained for so long, I think some clear statement about the state of the project and a way forward would really help.

**Comment by MutegekiHenry** [comment]
@S4-Hosting I run into the same state of confusion like you did and paused it for other alternatives

**Comment by antwal** [comment]
Hi, same problem, link is broken

**Comment by NatarajaVj** [comment]
Get it here: https://github.com/CircleBilling/CircleBilling
