### ISSUE TITLE
Will BoxBilling support PHP 7+ 

### ISSUE THREAD

**Issue by emar** [boxbilling/boxbilling#592]
Hope boxbilling supports php 7+ soon,

I see there's a new update on your site, version 4.21

In my cPanel > MultiPHP Manager
Warning: PHP versions PHP 5.4, PHP 5.5, PHP 5.6, PHP 7.0, and PHP 7.1 are deprecated.
We recommend that you update to a supported version of PHP.

I have a cms set up to use the latest php 7+ on the server.
Installed boxbilling on the same hosting account,
Maybe I should use a subdomain and set BoxBilling to php 5.6.

I got a warning in boxbilling admin about the site using php 7+
And an option to enable php 5.6 for my boxbilling installation, I ticked yes .

Should we be using unsupported/deprecated versions of php?

**Comment by fordnox** [comment]
This is a large task though and i never got a chance to do it. Until a contributor is found for this task, it is unlikely I will tackle it in the immediate term unfortunately.

**Comment by emar** [comment]
I understand, you've got a nice neat little system there,
It's a pity it doesn't have more developers on the project.
It's not always easy to find support when we can't fix things ourselves.

**Comment by NatarajaVj** [comment]
Check for CircleBilling. It’s ported to php 7.x

**Comment by emar** [comment]
There site is under maintanance and it says copyright 2018 at the bottom.

**Comment by NatarajaVj** [comment]
> There site is under maintanance and it says copyright 2018 at the bottom.

Indeed, it also have a lack of development but at least it works under php 7.

**Comment by emar** [comment]
Well thanks for the pointer

**Comment by Neustradamus** [comment]
Any news?

**Comment by timothygwebb** [comment]
If someone knows exactly what needs to be done regarding this issue let me
know and I will try to fix it. I know mcrypt is a part of this issue is
there anything else?

**Comment by emar** [comment]
I was using the latest php version because my site required it,
When I enabled debug in BoxBilling that's when it threw a few warnings.
But I wouldn't know what needs to be updated in BoxBilling to make it compatible with the later php versions.
You are welcome to have the login if it helps.

**Comment by samapraku** [comment]
I have submitted a pull request https://github.com/boxbilling/boxbilling/pull/602 for upgrading to PHP 7.2

I realised that a migration script isn't really necessary if you want to migrate an existing boxbilling installation from PHP 5.6 to PHP 7.(2). However, I have put together a migration script that can handle the migration of the database.

Migration script for mcrypt to openssl: https://github.com/samapraku/boxbilling-mcrypttopenssl

I am using it in production on PHP 7.2 and it works great. I did a little testing on PHP 7.3 and it works although I haven't tested it extensively on PHP 7.3.

Hopefully this will give us a starting point for further progress if the PR is accepted.

**Comment by Neustradamus** [comment]
@samapraku: Thanks for your job!

Now I hope that the team will test and integrate quickly to all.

**Comment by emar** [comment]
I upgraded all my sites to php 7.3
So I don't know if I want to use BoxBilling on an older php version
Because all php versions older than 7.3 are now marked as obsolete
I want to continue using BoxBilling but it's not yet compatible with the latest php versions

**Comment by S4-Hosting** [comment]
> Because all php versions older than 7.3 are now marked as obsolete, security risk
> I want to continue using BoxBilling but it's not yet compatible with the latest php versions

True, but it's a much much smaller leap from 7.2 to 7.3-4 than it was from 5.6

**Comment by Neustradamus** [comment]
@samapraku: It is has been merged!
- https://github.com/boxbilling/boxbilling/pull/602

Guys can you test the master?

Linked to:
- https://github.com/boxbilling/boxbilling/issues/574

**Comment by timothygwebb** [comment]
Closed by PHP 7.4 Compatibility Update #645
