### ISSUE TITLE
Multiple XSS Vulnerabilities 

### ISSUE THREAD

**Issue by Hbkhan** [boxbilling/boxbilling#596]
There are multiple XSS vulnerabilities (support ticket, forum topics, and guest inquiries mentioned in #526  ). In this issue, I would demonstrate the Stored XSS that exists in a support ticket!

Method to reproduce : 

1- Go to support and click on create a ticket

![image](https://user-images.githubusercontent.com/17072444/85305019-13391180-b472-11ea-877d-41415187b1ae.png)

3- In the message field enter  `<script>alert('test');</script>`

![image](https://user-images.githubusercontent.com/17072444/85305082-2d72ef80-b472-11ea-928d-49f4a62ab0ce.png)

4- Click on Submit

![image](https://user-images.githubusercontent.com/17072444/85305218-60b57e80-b472-11ea-81e2-3e0ea4c9fc9a.png)

![xss2](https://user-images.githubusercontent.com/38255282/44303627-3c833680-a30b-11e8-91a3-668f14b73881.png)

### 💻 Technical Description *

if we look in `src/bb-modules/Support/html_client` file we do find the following javascript code which is responsible for making the API request. The javascript serialize the input fields and send a post request to `example.com/index.php?_url=/api/client/support/ticket_create`

```javacript
<script type="text/javascript">
$(function() {
    $('#ticket-submit').bind('submit',function(event){
        $('.wait').show();
        bb.post(
            'client/support/ticket_create',
            $(this).serialize(),
            function(result) {
                bb.redirect('{{ 'support/ticket'|link }}' + '/' + result);
            }
        );
        return false;
    });
```

The request is received by `ticket_create` function in `/src/bb-modules/Support/Api/Client.php`. The only check in this function exists is for the required parameters. 

```php
public function ticket_create($data)
    {
        $required = array(
            'content'             => 'Ticket content required',
            'subject'             => 'Ticket subject required',
            'support_helpdesk_id' => 'Ticket support_helpdesk_id required',
        );
        $this->di['validator']->checkRequiredParamsForArray($required, $data);

        $helpdesk = $this->di['db']->getExistingModelById('SupportHelpdesk', $data['support_helpdesk_id'], 'Helpdesk invalid');

        $client = $this->getIdentity();

        return $this->getService()->ticketCreateForClient($client, $helpdesk, $data);
    }
```

Once it verifies that the provided data contains the required parameters, it combine the request with _client identity_ and _helpdesk id_ and sends its request to `ticketCreateForClient` function in `src/bb-modules/support/service.php`

```php

...
...
        $ticket                      = $this->di['db']->dispense('SupportTicket');
        $ticket->client_id           = $client->id;
        $ticket->subject             = $data['subject'];
        $ticket->support_helpdesk_id = $helpdesk->id;
        $ticket->created_at          = date('Y-m-d H:i:s');
        $ticket->updated_at          = date('Y-m-d H:i:s');

        // related task with ticket
        $ticket->rel_id        = $rel_id;
        $ticket->rel_type      = $rel_type;
        $ticket->rel_task      = $rel_task;
        $ticket->rel_new_value = $rel_new_value;
        $ticket->rel_status    = $rel_status;

        $ticketId = $this->di['db']->store($ticket);

        $this->messageCreateForTicket($ticket, $client, $data['content']);

...
    }
```

It stores the subject and other ticket info in `support_ticket` table in database and sends the `content` to `messageCreateForTicket` function. 

```php
    public function messageCreateForTicket(\Model_SupportTicket $ticket, $identity, $content)
    {
        $msg                    = $this->di['db']->dispense('SupportTicketMessage');
        $msg->support_ticket_id = $ticket->id;
        if ($identity instanceof \Model_Admin) {
            $msg->admin_id = $identity->id;
        } elseif ($identity instanceof \Model_Client) {
            $msg->client_id = $identity->id;
        } else {
            throw new \Box_Exception('Identity is not valid');
        }
        $msg->content    = $content;
        $msg->ip         = $this->di['request']->getClientAddress();
        $msg->created_at = date('Y-m-d H:i:s');
        $msg->updated_at = date('Y-m-d H:i:s');

        return $this->di['db']->store($msg);
    }
```

The function basically stores the `content` value (which is the ticket body) in `support_ticket_message` table in the database!

![image](https://user-images.githubusercontent.com/17072444/85304373-4929c600-b471-11ea-87a2-d5869db44756.png)

which makes it stored cross-site scripting

**Reposting this from my original account** 
**OLD Post [Issue#526](https://github.com/boxbilling/boxbilling/issues/526)**

**Comment by Hbkhan** [comment]
@fordnox Can you request CVE for this through the Github advisory? Here's [how](https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory#requesting-a-cve-identification-number)

**Comment by huntr-helper** [comment]
### Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by Neustradamus** [comment]
2 years ago, big warning!

**Comment by timothygwebb** [comment]
What remains to be done regarding this issue?

**Comment by JamieSlome** [comment]
@timothygwebb - we have received a fix through https://huntr.dev which we are currently reviewing. We will look to merge a fix in the next week or so (https://github.com/418sec/boxbilling/pull/1).

Cheers! 🍰

**Comment by huntr-helper** [comment]
‎‍🛠️ A fix has been provided for this issue. Please reference: https://github.com/418sec/boxbilling/pull/1

🔥 This fix has been provided through the https://huntr.dev/ bug bounty platform.

**Comment by Neustradamus** [comment]
It has been merged, thanks @huntr-helper!

@Hbkhan @echoIamnoob @huntr-helper @timothygwebb @JamieSlome @fordnox: Do you confirm that now the master branch is secure?

**Comment by Neustradamus** [comment]
It has been merged, thanks @huntr-helper!

@jonahbohlmann @TuxMay @rubenmdh @KO-N @Hbkhan @echoIamnoob @huntr-helper @timothygwebb @JamieSlome @fordnox: Do you confirm that now the master branch is secure?

Linked to:
- https://github.com/boxbilling/boxbilling/issues/526
- https://github.com/418sec/huntr/pull/82

**Comment by huntr-helper** [comment]
### Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._
