### ISSUE TITLE
:8443/enterprise/control/agent.php Jump to Cpanel Error

### ISSUE THREAD

**Issue by timothygwebb** [boxbilling/boxbilling#597]
When I click on Jump to Cpanel anywhere I get the below error message and it takes me to my domain with the following address. 8443/enterprise/control/agent.php

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<packet version="0.0.0.0">
<system>
<status>error</status>
<errcode>1003</errcode>
<errtext>Wrong request</errtext>
</system>
</packet>

**Comment by timothygwebb** [comment]
This is still an issue stale it closed my issue.

**Comment by rndevuk** [comment]
we need to setup stalebot to not close issues that have a particular label..

**Comment by timothygwebb** [comment]
Ryan,

This is a very good idea and would you like to take interest in setting
that up I have enough on my plate right now as it is.

Thank you

Timothy Webb
