### ISSUE TITLE
Product ID is missing

### ISSUE THREAD

**Issue by zohaib87** [boxbilling/boxbilling#598]
Hi, 

Any one encountered this error while uploading a 17mb file to downloadable product?
"Product ID is missing"

max_execution_time = 1200
memory_limit = 128M
post_max_size = 64
upload_max_filesize = 50M

Regards,

**Comment by timothygwebb** [comment]
Contact your hosting company and show them a screenshot of your error, or
email them the error message. Ask them to assist by increasing the
following values, until you are able to upload your 17mb file. Your hosting
company may have restrictions on these values.

memory_limit
upload_max_size
post_max_size
upload_max_filesize
max_execution_time
max_input_time

Preferably to the following values.

memory_limit = 256M
upload_max_size = 64M
post_max_size = 64M
upload_max_filesize = 64M
max_execution_time = 300
max_input_time = 1000

Editing php.ini File

The  php.ini file is the default PHP configuration file. Most of your
shared hosting companies does not allow access to this file. If you are
certain that you have access to php.ini file on your server, you may
proceed with the following steps.

   1. Access it using your FTP program.
   2. Backup a copy of this file before attempting to edit it.
   3. Open it and find the following values, one at a time (They are
   located at different lines within the file)

   memory_limit
   upload_max_size
   post_max_size
   upload_max_filesize
   max_execution_time
   max_input_time
   	

   4. Preferably, edit them to the following values.

   memory_limit = 256M
   upload_max_size = 64M
   post_max_size = 64M
   upload_max_filesize = 64M
   max_execution_time = 300
   max_input_time = 1000

**Comment by zohaib87** [comment]
Well, I am the hosting provider :) 

Sorry... it was my mistake i was changing php.ini for PHP 7.2 and i have restricted BoxBilling to use PHP 7.1.
