### ISSUE TITLE
Tradução BoxBilling PT-BR RC1

### ISSUE THREAD

**Issue by amvhost** [boxbilling/boxbilling#6]
Tradução PT-BR em 50% em breve será postado novidades

**Comment by taidos** [comment]
If you want a good translation please go to

https://github.com/petermann/BoxBilling-pt_BR

**Comment by rndevuk** [comment]
@taidos unless things have changed. languages are supposed to be submitted to this site: https://www.transifex.com/boxbilling/boxbilling/ :)

**Comment by taidos** [comment]
There is a good translation, far as i see
