### ISSUE TITLE
BoxBilling registration only if ordering

### ISSUE THREAD

**Issue by emar** [boxbilling/boxbilling#601]
Hi,

Can you explain this please,

If you disable user registration, does that mean a user can only sign up if they are ordering a product?
And how do we remove that registration button if we only allow user to sign up if they are ordering?

Thanks

**Comment by rndevuk** [comment]
Its been a long time since i used Boxbilling in a professional, I'm currently only using in development but if my memory serves my right, what you described above is the intended use case. Should be easy enough to test though.

create a free product, disable registration and then try to order the free product from he client side

**Comment by emar** [comment]
Thanks for your reply rndevuk
What I mean is, that register button is still visible even after we select don't allow registrations.
If we only allow a user to signup if they are going through the checkout, that register button shouldn't be there.

**Comment by rndevuk** [comment]
Which theme do you use?

**Comment by emar** [comment]
Using the bootstrap theme

**Comment by rndevuk** [comment]
OK, so if I'm not mistaken the bootstrap theme is a third party theme that doesn't come with Boxbilling so you would need to ask the developer of the bootstrap theme to fix it.

On a side note, i have looked at the themes that come with Boxbilling and it appears they also have the same issue so i will work on a fix for them later today.

**Comment by emar** [comment]
Yes I just assumed that register button would go away after disabling registration under Clients.
So that's what it is suppose to do but it's not?

**Comment by rndevuk** [comment]
Hi Emar, I've put together a fix for this, I'll be pushing it once my current approved merge request has be merged.
The bootstrap theme will require a slight update too but only about 2 lines of code, nothing much.

**Comment by emar** [comment]
Thanks rndevuk,

I will definitely keep an eye on this one.
I think I need to get BB updated to work with php 7.4

**Comment by rndevuk** [comment]
I think 7.3 is the current working version for the master repo. master repo does still have a few issues to be worked out though.. 

if your current installation works. i wouldn't update just yet, i would wait for the next release.

**Comment by timothygwebb** [comment]
I have a current working version on 7.4.9. and I will be doing another pull
request into the master branch here shortly. This should get everything up
to date including composer information.

**Comment by rndevuk** [comment]
Looking forward to it timothygwebb :)

**Comment by timothygwebb** [comment]
Ryan,

Here is a glimpse into the install.

https://webbhostingservices.com/boxbilling/install/

As you can see the above link verifies the version I am developing on

The below is a screen shot of the composer packages and the versions I am
working on.

[image: Screenshot_2020-08-26_18-27-07.png]

Thanks

Timothy Webb

**Comment by timothygwebb** [comment]
![Screenshot_2020-08-26_18-27-07](https://user-images.githubusercontent.com/16106877/91363452-a53efc80-e7ca-11ea-93eb-3cd466b0aed3.png)
![Screenshot_2020-08-26_18-32-43](https://user-images.githubusercontent.com/16106877/91363453-a5d79300-e7ca-11ea-85ea-c0dc615415c0.png)
Sorry the links and the images didn't come through so here they are.

**Comment by timothygwebb** [comment]
> Looking forward to it timothygwebb :)
@rndevuk I have attached screenshots to my prior message for a preview of what I am working on.

**Comment by rndevuk** [comment]
@timothygwebb Thanks for the screenshots, I've been keeping an eye on your commits. Looking forward to them being merged. 
Is that a new Box Billing UI for composer or that a third party software you are using?

**Comment by timothygwebb** [comment]
@rndevuk I would love to create something as wonderful but I don't have the time to do so right now. This is actually a third party software called Plesk that I use for a control panel for my clients in my company for their management of their domains web hosting.

**Comment by timothygwebb** [comment]
Closed by PHP 7.4 Compatibility Update #645
