### ISSUE TITLE
Unable to add global "current_theme" as the runtime or the extensions have already been initialized.

### ISSUE THREAD

**Issue by samapraku** [boxbilling/boxbilling#606]
This error is thrown when the invoice banklink is opened. In the huraga theme it occurs when the Payment method logo is clicked or when the invoice bank link is opened directly in the browser.

```
Unable to add global "current_theme" as the runtime or the extensions have already been initialized.`
Class: "LogicException"

File: "...\htdocs\bb-test\bb-vendor\twig\twig\src\Environment.php"

Line: "907"
Trace:

 0 ..\htdocs\bb-test\bb-library\Box\AppClient.php(99): Twig\Environment->addGlobal('current_theme', 'huraga')
1 ..\htdocs\bb-test\bb-library\Box\AppClient.php(74): Box_AppClient->getTwig()
2 ..\htdocs\bb-test\bb-modules\Invoice\Controller\Client.php(97): Box_AppClient->render('mod_invoice_ban...', Array)
3 [internal function]: Box\Mod\Invoice\Controller\Client->get_banklink(Object(Box_AppClient), 'd0d38d432ab30c1...', '1')
4 ..\htdocs\bb-test\bb-library\Box\App.php(199): ReflectionMethod->invokeArgs(Object(Box\Mod\Invoice\Controller\Client), Array)
5 ..\htdocs\bb-test\bb-library\Box\App.php(249): Box_App->executeShared('Box\\Mod\\Invoice...', 'get_banklink', Array)
6 ..\htdocs\bb-test\bb-library\Box\App.php(143): Box_App->processRequest()
7 ..\htdocs\bb-test\index.php(27): Box_App->run()
8 {main}
```

**Cause:**
When the invoice banklink route is opened, two calls are made to twig->addGlobals. The second call from app->render throws the exception because the twig environment has already been initialized.

**Fix:**
One working fix is to create a new instance of twig environment from the dependency injection $di object each time $di['twig'] is called. 

Using pimple Factory:

```
$di['twig'] = $di->factory( function () use ($di) {
    $config = $di['config'];
    $options = $config['twig'];

    $loader = new Twig\Loader\ArrayLoader();
    $twig = new Twig\Environment($loader, $options);

    $box_extensions = new Box_TwigExtensions();
    $box_extensions->setDi($di);
    ...
  
   return $twig;
});
```

That way, a new instance of twig environment is created each time and the addGlobals can be called safely without throwing the LogicException.

@fordnox is this fix inline with the architecture of the application? That is, creating a new twig instance each time $di['twig'] is called.

**Comment by S4-Hosting** [comment]
Not my place to say what is inline with the architecture, but in my opinion fixing any errors without breaking anything else seems to  be a lot better than leaving it unresolved.

**Comment by rndevuk** [comment]
@S4-Hosting it appears this fix was merged 13 days ago... maybe the author or @fordnox could close this now?
