### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by S4-Hosting** [boxbilling/boxbilling#607]
In the readme it states that the license for BoxBilling is Apache 2.0 but then it goes on to state things that are not in line with that license: 

_"Those that wish to distribute a modified version of BoxBilling must gain permission from BoxBilling before releasing the software. All authorised modified versions of BoxBilling must retain this copyright notice. All modified releases of BoxBilling must release the software under the same license as the BoxBilling software (Apache License 2.0)"_

This is explicitly against the terms of the Apache license which not only says that anyone can copy, modify and distribute without seeking permission but also that they can then apply any license to the derivative work. 

_"The Apache License is a permissive open source software license — so you can release your modified version of the Apache licensed product under any license of your choice."_

I just think that it's important to be clear and consistent about licensing if this project is going to move forward again, and at the moment this is contradictory. 

References:
http://www.apache.org/licenses/LICENSE-2.0.html
https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered

**Comment by NatarajaVj** [comment]
Yeah, indeed you’re fully right!
Those licenses agreements are fully wrong. 

Check, search for CircleBilling. A fork of BoxBilling and you will see how this is interpreted by other activ dev. 

Envoyé de mon iPhone

**Comment by rndevuk** [comment]
@fordnox This could do with being cleared up. It will definaitly be putting off some developers from contributing. I have a couple of extentions im working on and would like to choose a licence that works with boxbilling licence but as it stands i get the feeling you may end up changing the licence of box billing.

**Comment by S4-Hosting** [comment]
> It will definaitly be putting off some developers from contributing.

Yeah, I'm fairly sure it is. It's super confusing, and a lot of people won't want to contribute code (or documentation or anything else) to a project that then sounds like it is going to grab copyright of those submissions even if that is explicitly against the license.

**Comment by S4-Hosting** [comment]
@fordnox any thoughts on this?

**Comment by timothygwebb** [comment]
@fordnox @S4-Hosting https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by fordnox** [comment]
[Removed confusion from Readme file](https://github.com/boxbilling/boxbilling/commit/0cf413b8c115605dcd72ccc3973f0243a8d6ef5d)
