### ISSUE TITLE
Download Link on Site leads to Forbidden content

### ISSUE THREAD

**Issue by carlosgili** [boxbilling/boxbilling#613]
Download Link on Site leads to Forbidden content

**Comment by rndevuk** [comment]
What site? the boxbilling website or your website?

**Comment by carlosgili** [comment]
boxbilling site

    On Monday, August 17, 2020, 9:51:51 AM GMT-4, Ryan Nolan <notifications@github.com> wrote:  
 
 


What site? the boxbilling website or your website?

**Comment by S4-Hosting** [comment]
It's been like that for months. 

With the recent merges here updating with PHP 7, it would probably be really good to put out a new BB release and then to fix the download link (and install instructions) on that site.

**Comment by S4-Hosting** [comment]
Is there a reason, as a literally two minute fix, that link can't just be pointed to the github page?

**Comment by timothygwebb** [comment]
#635

**Comment by evrifaessa** [comment]
Well, we could directly use GitHub to host the ZIP file, and give link to the latest release on boxbilling.com. For example, we can just get the download link to download from https://github.com/boxbilling/boxbilling/releases/download/4.20/BoxBilling.zip

**Comment by timothygwebb** [comment]
@evrifaessa I am in agreement with this but an actual build of a release must occur for this link to be valid. As of right now there has been no release past 4.21 and there needs to be. Look at the number of commits past 4.21.

**Comment by timothygwebb** [comment]
@fordnox @evrifaessa  fordnox released this on Feb 21 · 187 commits to master since this release

**Comment by evrifaessa** [comment]
@timothygwebb, giving a download link that directly downloads from the master branch will mostly result users completing an unstable install of boxbilling. we should get people to download the latest stable release, not the unstable master branch. we can also change the link from 4.20 to 4.21, mine was just an example.

**Comment by evrifaessa** [comment]
The download link on the website now works, it uses GitHub releases as a mirror and a file host. @fordnox, we can close this.

**Comment by carlosgili** [comment]
It's so sad to realize how UNPROFESSIONAL and LAZY are the ppl from BoxBilling, thanks to GOD, nobody is using BoxBilling anymore, and the poors that do i'm sure they will have problems. it's so easy to fix a link on a HTML code that is RIDICULOUS how you can't even handle it. As a PROOF that the link in the site is STILL leading to YOUR CRAPPY SITE, check the screenshot.

**Comment by carlosgili** [comment]
You can also click the following LINK: https://www.boxbilling.com/download

**Comment by carlosgili** [comment]
unfortunatedly the link to download leads to: https://www.boxbilling.com/bb-themes/bb2015/assets/
