### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by digitalosaurus** [boxbilling/boxbilling#620]
Hi, I tried installing BB, it sadly just says i need a bb-config.php, its strange because i have it inside. Can you assist me=?

**Comment by taidos** [comment]
You just need when you create or do one new installation the bb-config.php, you can create one empty file with that name and chmod it to 777 to be written.

After the installation you need to change again permissions to 644. If does not detect the file inside please do oneother upload of your install directory and retry

**Comment by rebelholic** [comment]
How I can update boxbilling to latest verson in one folder? because I don't see any guide on readme.md

**Comment by rndevuk** [comment]
@digitalosaurus did you manage to overcome this issue?

**Comment by digitalosaurus** [comment]
Hi,
yes, I guess there was an error in my php-chache.
BR

Von: Ryan Nolan <notifications@github.com>
Gesendet: Sonntag, 20. September 2020 11:40
An: boxbilling/boxbilling <boxbilling@noreply.github.com>
Cc: Thomas Stinner <Thomas.Stinner@stinner-it.com>; Mention <mention@noreply.github.com>
Betreff: Re: [boxbilling/boxbilling] Installation Issues (#620)


@digitalosaurus<https://github.com/digitalosaurus> did you manage to overcome this issue?
