### ISSUE TITLE
onBeforeClientSignUp event is not being called

### ISSUE THREAD

**Issue by rndevuk** [boxbilling/boxbilling#624]
`onBeforeClientSignUp` doesn't appear to be called and as a result the **spam checker** module does not work.

I'm not sure what is causing this and i haven't checked if the other event calls are being ignored. I'm going to keep digging and try to figure it out. If anyone has any insight, feel free to comment.

**Comment by taidos** [comment]
i will try too

**Comment by rndevuk** [comment]
Ok, so if i have figured this out correctly, the event manager looks in the database and grabs a list of event hooks to be called from the various modules.

But looking at a freshly installed database, the information that it is looking for is not there. Now to find out why..

here is the extract of code that does this lookup:
```php
private function _connectDatabaseHooks(&$disp, $event)
{
    $sql="SELECT id, rel_id, meta_value
        FROM extension_meta
        WHERE extension = 'mod_hook'
        AND rel_type = 'mod'
        AND meta_key = 'listener'
        AND meta_value = :event
    ";
    $list = $this->di['db']->getAll($sql, array('event'=>$event));

    // no need to connect listeners
    if(empty($list)) {
        return ;
    }

    foreach($list as $listener) {
        $mod = $listener['rel_id'];
        $event = $listener['meta_value'];
        try {
            $s = $this->di['mod_service']($mod);
            if(method_exists($s, $event)) {
                $disp->connect($event, array(get_class($s), $event));
            }
        } catch(Exception $e) {
            error_log($e->getMessage());
        }
    }
}
```

**Comment by rndevuk** [comment]
In case anyone else has this issue, this happens when you don't setup the cron job, as @samapraku brought to my attention:

> The hooks are initialised at the first cron job run and gets updated if it needs to be, each time the cron job executes.

If like me you use Boxbilling for development only and don't require an active cron job, you can manually run the cron job once after installation.
