### ISSUE TITLE
Unofficial Discord Community

### ISSUE THREAD

**Issue by rndevuk** [boxbilling/boxbilling#626]
I hope @fordnox is OK with me posting this here.

I have created a Discord server for The BoxBilling Community in the hope's that we can all communicate more efficiently and maybe try to get the general support requests away from GitHub.

There are various channels that separate support from development chatter and there is also channels that allow you to advertise your BoxBilling Website, Module or Theme.

As of writing this message it has only myself as a member but I hope that I can encourage you all to join me there and turn it into a useful place for BoxBilling Enthusiasts, Modder's, Maintainers and even Developers.

As the community grows, I will be looking to create a community support team. These will be volunteers that help spread knowledge when it is needed.

The details are below:
**Name:** [Unofficial] BoxBilling Community
**Invite Link:** [https://discord.gg/PYNcFVM](https://discord.gg/PYNcFVM)

**Comment by fordnox** [comment]
@rndevuk yep this is me, replying to PM on discord
