### ISSUE TITLE
File structure issue

### ISSUE THREAD

**Issue by rndevuk** [boxbilling/boxbilling#629]
@timothygwebb Your merge has put these directories in the wrong place.

![image](https://user-images.githubusercontent.com/7151228/92041413-16a12100-ed70-11ea-92d3-677532491e44.png)

**Comment by rndevuk** [comment]
same thing going on in subfolders of `src/bb-themes`, not to sure but that commit might need to be reverted and and then fixed.

Can i ask how to you manage your git repo's do you edit the files in the repo or do you copy the files to the repo after editing?

![image](https://user-images.githubusercontent.com/7151228/92045300-1b69d300-ed78-11ea-8af5-79ad3971337a.png)

**Comment by timothygwebb** [comment]
I edit the files in the repo.

**Comment by rndevuk** [comment]
the reason i ask is because it looks like each time you commit. you overwrite every file in the repo... which isn't the way git normally does things.

**Comment by timothygwebb** [comment]
I also use Devart Code Compare.

**Comment by fordnox** [comment]
rollbacked the pr.

**Comment by rndevuk** [comment]
@timothygwebb fordnox has rolled back the pr. so you need to resubmit it with the files changed... 

If you need help checking it over etc before submitting it for a merge, feel free to join me on discord https://discord.gg/PYNcFVM

We can talk in depth about anything that's needed. :)

**Comment by timothygwebb** [comment]
Closed by #645
