### ISSUE TITLE
Github Repo Suggestions.

### ISSUE THREAD

**Issue by rndevuk** [boxbilling/boxbilling#632]
So I have a few suggestions.

### 1) Branches
Once the currentrly known bugs are fixed and we have created a new release, We should create a new branch called dev.
All development should be done in that branch and then just before each release the branch gets merged into the master.

### 2) Staff/Community helpers.
Although we do need maintainers, this project really could do with a community led support team for dealing with github issues. labeling them, closing issues that are irrelivent and pointing people in the right direction for the information they seek when the github issue is not development related.

### 3) Maintainers
I know @fordnox is looking for a maintainer but realistically you need 3-4 maintainers, Experienced Programmers that would then be tasked with reviewing PR's and voting on the approval. It would be the maintainers job to make sure each pr works and at the very least doesnt break too many things.

Thoughts anyone?
@fordnox would be nice to know what you think also.

**Comment by timothygwebb** [comment]
I completely understand and agree with your suggestion. I have been working
on many different development teams for many years and just for a quick
guide and reference. I believe what is trying to be communicated here can
be found already layed out in many best practice guides online regarding
GitHub and how to make the best use of it.

I particularly like the ones below.

If anyone else knows what I am talking about please let me know and
comment. There is also a long debated topic of are we or are we not an
agile workshop is our process a water flow. Just a few ideas for comment. I
have also linked below the best practice guide below from GitHub.

https://www.datree.io/resources/github-best-practices

https://resources.github.com/videos/github-best-practices/

https://gist.github.com/pandeiro/1552496

**Comment by timothygwebb** [comment]
@rndevuk I have updated the branch called develop with all information from master and it is now up to date with master and new work. It says there is 18 new commits ahead of master and nothing behind.  I wanted to give it a trial run personally to see if we can maybe resolve issues better working in a development branch as you suggested and then merging to master at each release.
