### ISSUE TITLE
The Extension Website

### ISSUE THREAD

**Issue by rndevuk** [boxbilling/boxbilling#635]
@fordnox is the extensions website going to be a thing still or should we remove all references to it from boxbilling until something similar does exist?

**Comment by timothygwebb** [comment]
@fordnox if you need hosting arrangements for your domain and someone to take over the website. I am a hosting provider and would welcome the opportunity to maintain not only the codebase but the website as well. Let me know your thoughts.

**Comment by S4-Hosting** [comment]
I'm of the opinion that there should be an extensions website for free extensions. 

It's an important part of building a user ecosystem for people to be able to find extensions/modules/themes/whatever in one place. 

It's part of a bigger issue with website, clarity, documentation, etc. that I think are probably driving away many people at the moment.

If there is not to be an extensions website then any visible references to it should definitely be removed though.

**Comment by fordnox** [comment]
Extensions should be installable via [composer](https://getcomposer.org/). Then this is done, extensions site can be easily created.
