### ISSUE TITLE
Release 4.21 is missing index.php

### ISSUE THREAD

**Issue by timothygwebb** [boxbilling/boxbilling#641]
AH01276: Cannot serve directory: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm,index.shtml) found, and server-generated directory index forbidden by Options directive

Tested .htaccess, htaccess.txt directives not an issue.

index.php does not exist which breaks the directive in .htaccess.

Release 4.21 is missing the file below index.php

<?php
/**
 * BoxBilling
 *
 * @copyright BoxBilling, Inc (http://www.boxbilling.com)
 * @license   Apache-2.0
 *
 * Copyright BoxBilling, Inc
 * This source file is subject to the Apache-2.0 License that is bundled
 * with this source code in the file LICENSE
 */

This may resolve https://github.com/boxbilling/boxbilling/issues/640

require_once dirname(__FILE__) . '/bb-load.php';
$di = include dirname(__FILE__) . '/bb-di.php';
$url = $di['request']->getQuery('_url');
$admin_prefix = $di['config']['admin_area_prefix'];
if (strncasecmp($url,$admin_prefix, strlen($admin_prefix)) === 0) {
    $url = str_replace($admin_prefix, '', preg_replace('/\?.+/', '', $url));
    $app = new Box_AppAdmin();
    $app->setUrl($url);
} else {
    $app = new Box_AppClient();
    $app->setUrl($url);
}
$di['translate']();
$app->setDi($di);
print $app->run();
exit(); // disable auto_append_file directive
?>

This may fix https://github.com/boxbilling/boxbilling/issues/640

**Comment by rndevuk** [comment]
I've just downloaded it and it does exist.... I'm unsure how you came to this conclusion.
this index file in release 4.21 contains:

```php
<?php
/**
 * BoxBilling
 *
 * @copyright BoxBilling, Inc (http://www.boxbilling.com)
 * @license   Apache-2.0
 *
 * Copyright BoxBilling, Inc
 * This source file is subject to the Apache-2.0 License that is bundled
 * with this source code in the file LICENSE
 */

require_once dirname(__FILE__) . '/bb-load.php';
$di = include dirname(__FILE__) . '/bb-di.php';
$url = $di['request']->getQuery('_url');
$admin_prefix = $di['config']['admin_area_prefix'];
if (strncasecmp($url,$admin_prefix, strlen($admin_prefix)) === 0) {
    $url = str_replace($admin_prefix, '', preg_replace('/\?.+/', '', $url));
    $app = new Box_AppAdmin();
    $app->setUrl($url);
} else {
    $app = new Box_AppClient();
    $app->setUrl($url);
}
$di['translate']();
$app->setDi($di);
print $app->run();
exit(); // disable auto_append_file directive
```

**Comment by timothygwebb** [comment]
@rndevuk Thanks for the verification. Must have been a bad download.
