### ISSUE TITLE
PHP 7.4 Update Issues on develop branch

### ISSUE THREAD

**Issue by timothygwebb** [boxbilling/boxbilling#644]
Deprecated: Function get_magic_quotes_gpc() is deprecated in bb-load.php 
Deprecated: Array and string offset access syntax with curly braces is deprecated in multiple Service.php files.
@rndevuk the above is what i have been trying to get pulled into the master branch. 
It is the only thing left to fix in the develop branch and should merge with no issues.

**Comment by timothygwebb** [comment]
@rndevuk I have found another [13-Sep-2020 16:47:23 UTC] PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /var/www/vhosts/webbhostingservices.com/httpdocs/boxbilling/src/bb-library/Box/Requirements.php on line 80

**Comment by rndevuk** [comment]
> @rndevuk I have found another [13-Sep-2020 16:47:23 UTC] PHP Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/vhosts/webbhostingservices.com/httpdocs/boxbilling/src/bb-library/Box/Requirements.php on line 80

Thanks @timothygwebb found and fixed this one locally the other day.... going through all your suggestions as we speak..
