### ISSUE TITLE
date formatting in email template

### ISSUE THREAD

**Issue by Nirose** [boxbilling/boxbilling#646]
I am testing a new build from the github releases. overwriting files into the old 4.20 version.

I was testing the invoicing and the code at email template file at ```billing/bb-modules/Invoice/html_email/mod_invoice_payment_reminder.phtml```

```Due Date: {{ invoice.due_at|bb_date }}``` 

sent out 

```Due Date: %AM, %30 %041 %0```

in the email. is there any way to fix this?

Thanks

**Comment by samapraku** [comment]
Which release are you using exactly and which php version?

**Comment by Nirose** [comment]
> Which release are you using exactly and which php version?

4.21 : https://github.com/boxbilling/boxbilling/releases/tag/4.21

PHP 7.2

**Comment by samapraku** [comment]
What is your hosting environment? Windows or Linux?
The default locale is set to en_US in bb-config file. Have you changed it?

On linux, `locale -a` this is will show the installed locales on your system.

**Comment by Nirose** [comment]
It is Linux. I haven't changed it. 

the ```en_US``` locale seems to be installed. any idea which file should i look to track this down?

```
es_US
es_US.iso88591
es_US.utf8
```

**Comment by samapraku** [comment]
The bb_date filter is defined here:

https://github.com/boxbilling/boxbilling/blob/8e329832c8488de15029f4de8bb70c2e2303c1a4/src/bb-library/Box/TwigExtensions.php#L83

I don't think the 4.21 release is compatible with PHP 7.2. The upgrade was done few weeks ago and there hasn't been a PHP 7.x release yet.

If it is possible to switch your PHP to 5.6, you can do so and try again. That way we can rule out the PHP version as the cause.

**Comment by Nirose** [comment]
i found the solution:
while the .phtml template file had ```|bb_date``` inside the template, the actual template which were used for email were from the database table ``` email_template```. and they just had ```|date``` in them (missing bb_ prefix). may be remnants from the old installation?

Changing them to ```|bb_date``` fixed the problem. didn't need to go back to 5.6 yet

just leaving the solution up if anyone runs into same problem
