### ISSUE TITLE
Is anyone keeping BoxBilling updated to the latest PHP version?

### ISSUE THREAD

**Issue by emar** [boxbilling/boxbilling#651]

**Comment by emar** [comment]
Hi,

I want to use BoxBilling for one of my sites but it's outdated,
The latest PHP version on my servers is 7.4 and we need to keep
that up to date for different applications on the server, websites etc.

I'm just curious is anyone able to keep BB up to date with the latest PHP versions?

Thanks in advance

**Comment by timothygwebb** [comment]
@emar the last merge into master will operate on 7.4. You must do composer install then composer update and make sure the permissions are set correctly for the directories on your web server user and group. on the boxbilling directories and files. If you have any issues let me know and thanks. I am currently running it on 7.4.10.

**Comment by emar** [comment]
@timothygwebb thanks, 
I'm reading the comments for your "PHP 7.4.9 Revision 2 and Composer Update"

**Comment by timothygwebb** [comment]
@emar those comments have been resolved by @rndevuk  last merge. You shouldn't have to go through those comments unless you do not have composer installed at all. I did not have it installed at all. If you need further assistance. @rndevuk , @samapraku, have been the key players besides myself working on this project getting it to where it needs to be. Just ask and I am sure between the three of us we should be able to get you where you need to be.

**Comment by timothygwebb** [comment]
@emar Can this issue be closed?

**Comment by emar** [comment]
Ok I will close it, thanks
