### ISSUE TITLE
The documentation is outdated

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#661]
The documentation in [docs.boxbilling.com](http://docs.boxbilling.com/) is really outdated. It was written according to the 4.18 release, and is now outdated. We need to re-write it according to the latest version. The source of the documentation site can be found and edited in [@boxbilling/docs](https://github.com/boxbilling/docs).

**Comment by evrifaessa** [comment]
should we create a new branch instead of making changes directly on the master branch of boxbilling/docs? it'd be less confusing, and we will be able to compare differences easier.

**Comment by timothygwebb** [comment]
@evrifaessa Link to boxbilling documentation repository. https://github.com/boxbilling/docs/blob/master/en/index.rst
I suggest integrating this information into the wiki. https://github.com/boxbilling/boxbilling/wiki

**Comment by timothygwebb** [comment]
@evrifaessa You can also clone the wiki https://github.com/boxbilling/boxbilling.wiki.git

**Comment by evrifaessa** [comment]
also, a documentation that shows how to directly install from the master branch would be cool. I'd like to start contributing somewhere, but don't really know how to set up my development environment.

**Comment by S4-Hosting** [comment]
I've just made a pull request in the documentation repository - just updating some dates, etc. and a notice about out of date docs and where to get help. 

@fordnox are you an active maintainer there, or is there someone else who would merge pull requests in that repo?

**Comment by timothygwebb** [comment]
@fordnox @S4-Hosting It seems that I am only able to merge pull requests in the boxbilling repository and none of the other ones. So @fordnox will need to approve and pull your documentation requests or allow me to do so in the other repositories as well. There is more then just yours that needs to be merged in that repository. Here is a link to your pull request for @fordnox  reference.
https://github.com/boxbilling/docs/pull/3

**Comment by S4-Hosting** [comment]
@timothygwebb Te other pull request in that repository is 4 years old though :-)

**Comment by fordnox** [comment]
documentation can be edited here https://github.com/boxbilling/docs

everyone is welcome to contribute
