### ISSUE TITLE
New Design for BoxBilling Admin Area

### ISSUE THREAD

**Issue by mahofficial** [boxbilling/boxbilling#663]
As I have CSS and HTML experience so I can offer help in making new design for BoxBilling Admin Area.

**Comment by evrifaessa** [comment]
@mahofficial, you can see [src/bb-themes/admin_default](https://github.com/boxbilling/boxbilling/tree/master/src/bb-themes/admin_default) for the default admin theme. you can use it as a stub and make your designs based on that stub. once you fully test it on your development infrastructure, you can create a pull request as usual. thanks for your contribution :)

**Comment by mahofficial** [comment]
Thanks, will do that.

**Comment by rndevuk** [comment]
@mahofficial with the above commit thats now been merged you can now copy and rename the `admin_default` theme and then select the admin theme in the theme settings. This should give you a good starting point.
make sure any admin theme had the `admin_` prefix.

**Comment by evrifaessa** [comment]
@mahofficial, anything new about this? We'd be happy to gain a new theme.

**Comment by evrifaessa** [comment]
As @mahofficial didn't respond for 15 days, I'm closing this issue. Feel free to create pull requests, you can also re-open this issue if you need to.
