### ISSUE TITLE
Consider removing deprecated add-ons like "YouHosting product"

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#666]
Since YouHosting is gone forever, why do we keep making new releases with the YouHosting add-on packed with them?

**Comment by timothygwebb** [comment]
> Since YouHosting is gone forever, why do we keep making new releases with the YouHosting add-on packed with them?

@evrifaessa I am in agreement with you on this. It seems the company is out of business and the domain no longer resolves.
@fordnox  What is your opinion do we remove or not?

**Comment by fordnox** [comment]
remove it

**Comment by timothygwebb** [comment]
Andrius,

It is on the project board as To Do. I will pick it up tomorrow.

Thank you

Timothy Webb
