### ISSUE TITLE
/bb-admin/servicedomain throws out errors on default mysql settings

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#672]
running BB (master branch) on Ubuntu Server 20.04 with MySQL 8.0.21-0ubuntu0.20.04.4 installed. I get this error whenever I navigate /bb-admin/servicedomain:

`An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'bb_dev.tr.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by").`

it seems like my server has `sql_mode=only_full_group_by` flag, which I didn't add explicitly. my server is running on default MySQL configurations.

How to reproduce?:
- Make sure your MySQL server has "only_full_group_by" setting enabled (which was enabled by default on my end)
- Navigate to /bb-admin/servicedomain by choosing "Configuration -> Domain registration" on the admin panel
- You'll see the error appear

a possible fix can be [this](https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql). another reference for the error can be [this](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html) I'll try investigating the issue further and make a pull request if I can succeed.

**Comment by evrifaessa** [comment]
Solved with the pull request.

**Comment by timothygwebb** [comment]
@evrifaessa I am beginning to enjoy working with you and your quick pickup of how to use the kanban board. Do you have anything else that needs my immediate attention before I turn off my phone.

**Comment by evrifaessa** [comment]
no, I don't need anything for now. thanks :)
