### ISSUE TITLE
Box_log generates error when instance created without $di service

### ISSUE THREAD

**Issue by samapraku** [boxbilling/boxbilling#686]
Box_log class requires $di object in order to access bb config values. 

Server_Manager, Payment_AdapterAbstract, and Registrar_AdapterAbstract classes create new instances of Box_log without injecting a $di service.

This causes the error below to be generated when debug mode is enabled:

`8 Trying to access array offset on value of type null ../bb-library/Box/Log.php 123`

**Comment by samapraku** [comment]
This issue has not been fixed. The PR #685 only fixes a part of the issue related to registrar adapter and payment adapter but the main issue with Box_log class hasn't been fixed.

**Comment by samapraku** [comment]
These sections  still need a proper implementaton:
1. https://github.com/boxbilling/boxbilling/blob/babbdd3b49a754283ab7930e54fea0452556f995/src/bb-library/Registrar/AdapterAbstract.php#L134
2. https://github.com/boxbilling/boxbilling/blob/babbdd3b49a754283ab7930e54fea0452556f995/src/bb-library/Payment/AdapterAbstract.php#L150
3. https://github.com/boxbilling/boxbilling/blob/babbdd3b49a754283ab7930e54fea0452556f995/src/bb-library/Server/Manager.php#L83

**Comment by timothygwebb** [comment]
@samapraku I have reopened your issue and moved it to in progress.

**Comment by evrifaessa** [comment]
@timothygwebb, @samapraku: is this still not solved? does the bug still exist?

**Comment by timothygwebb** [comment]
@evrifaessa I closed it and reopened it myself after notification from @samapraku that the pull request he made did not cover all aspects of items that needed to be modified. I have not seen any activity on it since and I have not been actively developing or doing anything related to boxbilling.
