### ISSUE TITLE
Paid, but didn't received license key

### ISSUE THREAD

**Issue by zigazajc007** [boxbilling/boxbilling#706]
Hello,

I have paid order #93361 with Paypal - bank transfer and I didn't receive the license key and the order is still not marked as paid.
I can't contact you thru tickets as the invoice didn't mark as paid and I can't contact you thru the contact form as I'm already a registered user, so here is the only option to contact you.

Best regards,
Žiga Zajc

**Comment by rndevuk** [comment]
You dont need a license key any more.

@fordnox are you aware of this? also boxbilling appears to be pointing at the old website again, is this intended?

**Comment by zigazajc007** [comment]
![image](https://user-images.githubusercontent.com/44822563/97843743-1da1cc80-1cea-11eb-991f-9074bcb09418.png)

The whole order is still marked as unpaid. I can provide you with a Paypal transaction id.

**Comment by zigazajc007** [comment]
![image](https://user-images.githubusercontent.com/44822563/97844236-f5ff3400-1cea-11eb-87ab-2240e74611aa.png)

PayPal transaction id: 0E2691863S639402H

**Comment by timothygwebb** [comment]
@zigazajc007 https://www.paypal.com/si/webapps/mpp/ua/useragreement-full#:~:text=When%20you%20buy%20something%20from,costs%20you%20paid%2C%20if%20any.
@rndevuk @fordnox

**Comment by zigazajc007** [comment]
So I need to do a refund and order again?

**Comment by zigazajc007** [comment]
"You don't need a license key anymore."

How can I get the PRO version then?

**Comment by fordnox** [comment]
download latest version from here https://github.com/boxbilling/boxbilling/releases/latest

and will refund the payment

**Comment by zigazajc007** [comment]
Okay, thanks. So PRO package won't exist anymore?

**Comment by fordnox** [comment]
refund complete
