### ISSUE TITLE
Move the default logo to somewhere else, possibly directly pack it with the ZIP file.

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#710]
Right now, after an installation is done, the installer initializes the website with BoxBilling's logo predefined. The logo file is hosted on Google Sites, that means we're making every new installation dependent to Google's CDN.

What I mean is, when the website is initialized with default settings, the logo path is being set to "https://sites.google.com/site/boxbilling/_/rsrc/1308483006796/home/logo_boxbilling.png". We shouldn't host it in Google Sites, but pack the logo directly with BoxBilling's files instead.

**Comment by rndevuk** [comment]
I agree

**Comment by fordnox** [comment]
Lets create PR

**Comment by evrifaessa** [comment]
I'll.

**Comment by evrifaessa** [comment]
#708 also solves this.

**Comment by evrifaessa** [comment]
Solved.
