### ISSUE TITLE
GROUP BY & ORDER BY issues

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#713]
We still have issues with the usage of GROUP BY and the ORDER BY at the same time.

The typical error message looks like this:
`An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'db.client_balance.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by").`

I've found out and fixed some, but now, I get the error in `/cart`.

Some useful details which I hope will help you to debug:
* Server: Localhost via UNIX socket
* Server type: MySQL
* Server version: 5.7.32 - MySQL Community Server (GPL)
* Protocol version: 10

**Comment by fordnox** [comment]
I have reverted this change https://github.com/boxbilling/boxbilling/commit/6e24c6adab75f83c3f72d0fcb8679f2528475080 because it introduced another problem with mysql permission.

Most of the hosting providers will not give such permissions

**Comment by evrifaessa** [comment]
@fordnox, the latest commits you added resulted the build to fail.
