### ISSUE TITLE
Drop out gettext, or fix it.

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#719]
While gettext throws out numerous errors, it seems somehow unsupported with PHP 7.

While checking my PHP logs, I saw so many of these: `Methods with the same name as their class will not be constructors in a future version of PHP; gettext_reader has a deprecated constructor /bb-library/php-gettext/gettext.php`

Also while running the installation on a typical cPanel setup, I saw that gettext extension is not bundled with cPanel and not included in most of the installations with default settings anymore. So the installation says a red "FAIL" for the gettext part.

We can directly stop using gettext and replace it with a custom array-based translation solution (maybe?). An example might be [this](https://sandbox.onlinephpfunctions.com/code/301ae624da5084afd881ae95303e38feefca4893).

While it's pretty annoying to see so many errors related to gettext in my logs, there are alternatives to the old and deprecated gettext. A similar workaround can be fixing gettext with a process similar to [this](https://stackoverflow.com/questions/37002494/php-7-with-phpmyadmin-gives-lots-of-deprecation-notices), or [this](https://bugs.launchpad.net/php-gettext/+bug/1522900).

**Comment by fordnox** [comment]
lets drop it completely

**Comment by evrifaessa** [comment]
> lets drop it completely

That would require a huge change in the way we use translations, and would require some workforce.
Instead, I got the library compatible with newer versions of PHP by the pull request I made. If Travis succeeds to build it, I'll merge it. (#720)
