### ISSUE TITLE
Error placing order

### ISSUE THREAD

**Issue by roger-net** [boxbilling/boxbilling#725]
When placing the order, regardless of the type of order, the following error appears: "Unknown" sameas "test. Did you mean" same as "?".
I'm using version 4.21, in the previous version this error doesn't happen.

**Comment by timothygwebb** [comment]
This issue has already been resolved.

Please refer to the following comments.

https://github.com/boxbilling/boxbilling/issues/649#issuecomment-695334203

**Comment by roger-net** [comment]
I found out that was the theme and I was going to post here that I found out when I saw your post. Thanks.
