### ISSUE TITLE
keyhelp integration

### ISSUE THREAD

**Issue by Radio-Quergedacht** [boxbilling/boxbilling#732]
Is it possible to integrate it into boxbilling keyhelp yes there is an api available

Link https://app.swaggerhub.com/apis-docs/keyhelp/api/1.1.1

**Comment by fordnox** [comment]
@Radio-Quergedacht pull request are always welcome

**Comment by evrifaessa** [comment]
Not actionable. Feel free to contribute about this by creating pull requests.
