### ISSUE TITLE
How can I expand other pages such as add privacy policy 

### ISSUE THREAD

**Issue by Radio-Quergedacht** [boxbilling/boxbilling#735]
How can I expand other pages such as add privacy policy

**Comment by timothygwebb** [comment]
Append the following to your base
domain /boxbilling/src/index.php?_url=/bb-admin/extension/settings/system.

Example as follows:

https://whatever.com/boxbilling/src/index.php?_url=/bb-admin/extension/settings/system

or

https://whatever.com/boxbilling/src/bb-admin/extension/settings/system

You will need to fill in the sections on the systems page called.

Company terms of service, legal regulation

Company privacy policy

**Comment by Radio-Quergedacht** [comment]
Okay I know that but how can I add my own pages like. z. B. Server status and so on

**Comment by timothygwebb** [comment]
@Radio-Quergedacht I do not believe that feature currently exists and will need to be developed please feel free to contribute to the project by following the guidelines located at the following address. https://github.com/boxbilling/boxbilling/blob/master/CONTRIBUTING.md or submit a feature request.  I have marked this issue as a feature request.
