### ISSUE TITLE
Admin bootstrap bb-themes

### ISSUE THREAD

**Issue by Radio-Quergedacht** [boxbilling/boxbilling#736]
You could make an admin bootstrap bb-themes out of that?
https://startbootstrap.com/theme/sb-admin-2

**Comment by fordnox** [comment]
@Radio-Quergedacht Pull request are welcome, are you going to create this feature?

**Comment by Radio-Quergedacht** [comment]
@fordnox  I am looking for someone who can do it

**Comment by fordnox** [comment]
> @fordnox I am looking for someone who can do it

Let me just clearify, you are expecting someone to create the feature **you need** for free, is that correct?

**Comment by Radio-Quergedacht** [comment]
Let me be clear, I don't expect anyone to provide the functionality I need for free

**Comment by evrifaessa** [comment]
Not actionable, closing.
