### ISSUE TITLE
Can't add domain orders (PHP 7.3)

### ISSUE THREAD

**Issue by lfglopes** [boxbilling/boxbilling#743]
`var_dump(preg_match('/^[a-z0-9]+[a-z0-9\-]*[a-z0-9]+$/i', "boxbilling.com"));`

> int(0)

This regex is present in the function `Box_Validate::isSldValid` and it's not working in PHP7.3.

I believe it could be related with the PCRE -> PCRE2 migration?

https://php.watch/versions/7.3/pcre2

EDIT:

If we're not concerned about older php versions, maybe we could simplify the function to:

```php
function isSldValid($sld)
{
    return filter_var($sld, FILTER_VALIDATE_DOMAIN) !== false;
}
```

**Comment by evrifaessa** [comment]
It would be good to keep PHP 7.0, 7.1 and 7.2 supported along with 7.3+. If you know a potential fix that works in both PHP 7.3+ and under, pull requests would be welcome.

**Comment by lfglopes** [comment]
Actually, I was completely misguided.

The page was not loading the "Select TLD" macro, so I was typing the full domain name in the box.

This fixed it: https://github.com/tastybitok/boxbilling/commit/4a2b670c89d1c2fc72ce22392e733eb295e90df2

Should I open a PR?

**Comment by evrifaessa** [comment]
sure, you can open a PR.
