### ISSUE TITLE
Add VestaCP support

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#789]
I may write a server module for VestaCP soon.

API documentation: https://vestacp.com/docs/api/

**Comment by evrifaessa** [comment]
I guess someone already wrote one: https://github.com/jaapmarcus/boxbilling-hestia

We may contact the developer to see if he wants his code to be in the extension ecosystem once we get our extension repository working back again.

**Comment by Neustradamus** [comment]
VestaCP has 2 developed forks, it is important to have full support with:
- HestiaCP: https://github.com/hestiacp/hestiacp
- MyVesta: https://github.com/myvesta/vesta
