### ISSUE TITLE
No database?

### ISSUE THREAD

**Issue by Dexxa1024** [boxbilling/boxbilling#791]
I've setup the database correctly  but on install on boxbilling all im getting is Could not connect to database. Please check database details. You might need to create database first.

anyone know how to fix it?

**Comment by evrifaessa** [comment]
The error message is clear enough, I doubt this is related to BoxBilling. Make sure the MySQL database is already created -BoxBilling won't create it for you-, the server is reachable, and the specified user account is able to run queries on that database.

**Comment by Dexxa1024** [comment]
Sorted, You was right, it was 20i's database server, moved to another host and works perfect, Like the new ext custom pages thats been added :-D
