### ISSUE TITLE
Fix the in-built updater

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#797]
Currently, the update script tries to download the latest release from boxbilling.com

https://github.com/boxbilling/boxbilling/blob/64c47131e14d431d19c34ed0c675452229b1352a/src/bb-library/Box/Update.php#L36

The API endpoints no longer work, and they actually don't need to. We are now working with GitHub for the release part, and we should integrate GitHub's API to get the latest release whenever there is a newer one.

Maybe we can also add options like "opt in for beta releases".

**Comment by BenNottelling** [comment]
We need the API key created for this. @fordnox or @timothygwebb can either of you set it up? I'd love to get the updater working in the next release of BoxBilling

**Comment by BenNottelling** [comment]
@evrifaessa Can you make the API key for this?

**Comment by evrifaessa** [comment]
API key for what? @BenNottelling

**Comment by BenNottelling** [comment]
@evrifaessa Don't we need an API key so we can pull updates from GitHub?

**Comment by evrifaessa** [comment]
> @evrifaessa Don't we need an API key so we can pull updates from GitHub?

Nope. Github has public endpoints that list releases.

**Comment by timothygwebb** [comment]
travis.yml

deploy:
provider: releases
token: $GITHUB_DEPLOY_TOKEN
file: ./build/distribution/BoxBilling.zip
draft: true
overwrite: true
name: ${TRAVIS_TAG}
skip_cleanup: true
on:
tags: true
all_branches: true
Question regarding the above: Is this how the deployment/releases are
currently handled?
