### ISSUE TITLE
Some Points

### ISSUE THREAD

**Issue by tobias992** [boxbilling/boxbilling#803]
Hello,
attached some Points and questions:

Questions:
- Does boxbilling support reverse-charge system (also for b2b deals with vat number)
- There is any public roadmap for boxbilling (example -> beta2, rc, etc.)

Problems/Requests:
xxx

I hope this helps a little bit ;)

**Comment by evrifaessa** [comment]
Thank you for this detailed report.

Let me answer your questions,
> Does boxbilling support reverse-charge system (also for b2b deals with vat number)
I'm not really sure.

> There is any public roadmap for boxbilling (example -> beta2, rc, etc.)
No, we just deal with issues. There may be a public board in the future though.

About the feature requests and problems, it would be really awesome if you split these requests/problems to separate issues per each. With separate issues, it'll be a lot easier for us to manage them easily.

**Comment by tobias992** [comment]
Okay no problem. I opened some new issues. I also send you a small donation in hope, you can quickly fix some points. I really want to use BoxBilling as new Main System :)

**Comment by evrifaessa** [comment]
As you splitted these to separate issues, we can close this.
