### ISSUE TITLE
Multiple issues about the client area.

### ISSUE THREAD

**Issue by tobias992** [boxbilling/boxbilling#805]
- Client portal -> service details -> custom product (recurring payment) -> why there is an renew button? not needed because its an subscription
- ~~Client portal -> service details -> open ticket ends up in 404 error~~
- Client portal -> service details -> cancel button has no options like confirmation or question like "when do you want to cancel (end of period or just in time)
- Client portal -> service details -> after cancel button the order is away (the client can not see them) -> better is to also show them in service list (maybe as grayout) -> with this the client has a nice order history
- ~~Client portal -> support ticket -> area little bit confused (every message gets an own line in summary - one line per ticket number is better)~~

**Comment by BenNottelling** [comment]
> * Client portal -> service details -> open ticket ends up in 404 error

This is going to be fixed when I merge https://github.com/boxbilling/boxbilling/pull/928
