### ISSUE TITLE
Duplicate entries for the "shopping cart" link in the navbar & more about the cart

### ISSUE THREAD

**Issue by tobias992** [boxbilling/boxbilling#806]
- [x] ~~In header menu there are 2 times "shopping cart"~~
- [ ]  Improve the shopping cart in header menu -> maybe show a small number when products in cart

**Comment by BenNottelling** [comment]
@tobias992 Hi, would you mind letting me know what theme you were using with all of these tickets? It helps a lot, thanks

**Comment by BenNottelling** [comment]
Going to condense these tickets into one
