### ISSUE TITLE
How to remove the powerd by Boxbilling in the outgoing emails

### ISSUE THREAD

**Issue by Glenshoun** [boxbilling/boxbilling#817]
How to remove the powerd by Boxbilling in the outgoing emails, I have desable the boxbilling plugins and im still getting the powered by boxbilling in the footer of my outgoing emails please asssit how to remove it, especial when a client purchase a service the confirmation email comes with it , even the test messages do, and i have attached the sample of what i am talking about.
![boxbilling email  branding](https://user-images.githubusercontent.com/48568586/102759195-77368700-437c-11eb-858c-832ed8352993.jpg)

**Comment by zohaib87** [comment]
its in "\bb-modules\Email\Service.php" on about line 544. check screenshot. 

[https://paste.pics/988e2201d7d91d9243b2c374d2e1ed3b](https://paste.pics/988e2201d7d91d9243b2c374d2e1ed3b)

**Comment by evrifaessa** [comment]
> its in "\bb-modules\Email\Service.php" on about line 544. check screenshot.

We can directly remove branding from outgoing e-mails. There's no reason to attach an advertisement to every e-mail.
