### ISSUE TITLE
Sent email history is empty

### ISSUE THREAD

**Issue by aftabsaqib** [boxbilling/boxbilling#821]
Unable to access email list or history both from client area and admin panel.

**Comment by zohaib87** [comment]
This was also working before this beta release.

**Comment by evrifaessa** [comment]
Are you sure that you have "Log sent emails to database" enabled in `/bb-admin/extension/settings/email`?
It's disabled by default.

**Comment by evrifaessa** [comment]
> Are you sure that you have "Log sent emails to database" enabled in `/bb-admin/extension/settings/email`? It's disabled by default.

Just checked. This is a bug and it doesn't log any emails even when this is enabled.

**Comment by 0x6b-dev** [comment]
#819
