### ISSUE TITLE
Normal order form doesnt show tax informations

### ISSUE THREAD

**Issue by tobias992** [boxbilling/boxbilling#827]
Hi,
Maybe i am blind and cannot find the setting but when i try to place an order as guest the order form shows "(No VAT)".
But Tax is enabled in settings.

**Comment by BenNottelling** [comment]
Could you please confirm BoxBilling version and what theme you are using? Both of these are important when submitting bug reports, thanks!

**Comment by BenNottelling** [comment]
Is it possible the tax system isn't detecting the location of you correctly? If I set my tax rate to the US only I get nothing, but if I set it for any country then it works
![image](https://user-images.githubusercontent.com/17304943/128637867-f9599a8d-c2f9-4945-a1be-21b43d04e235.png)

**Comment by BenNottelling** [comment]
I believe this was actually working as intended and that we need to instead improve how BB determines the user's country. 
See discussion on https://github.com/boxbilling/boxbilling/issues/945
I'll update that ticket as I think it's not a bug, but something we need to enhance
