### ISSUE TITLE
Cannot loggin to the admin area

### ISSUE THREAD

**Issue by srobert2** [boxbilling/boxbilling#828]
Hello,

I'm currently installing BoxBilling 4.22 

After the installtion I have a message "Not Found" when I try to login to the admin area.

I'have tried to re-install several times: no way

I also saw that https://github.com/boxbilling/boxbilling/issues/13 

Can you please help me ?

information about my installation:
php 7.3
Apache2 configured with ssl

**Comment by samapraku** [comment]
Try these:
1. Make sure the url option value in your bb-config.php ends with a trailing slash.
2. Open your bb-config file and set debug option to true. It should output a little more information about the issue. 
3. You can alsso set 'sef_urls' to false to turn off url rewriting.

**Comment by srobert2** [comment]
Hello Samuel,
Thank you for your quick reply.... this is really apreciated
Indeed the sef_url to false did the job and I can now loggin the admin area!
Thanks you very much
Stéphane.
