### ISSUE TITLE
Mail: the advertisement for boxbilling appears two times

### ISSUE THREAD

**Issue by srobert2** [boxbilling/boxbilling#831]
Hello
Just tu report a small issue but problematic to communicate with clients:
When sending an email the advisement for box billing appears two time:

Powered by BoxBilling. Client management, invoicing and support software. https://www.boxbilling.com/ Powered by BoxBilling. Client management, invoicing and support software. https://www.boxbilling.com/ 

kind regards

**Comment by evrifaessa** [comment]
It shouldn't appear at all, actually. We have already removed these advertisemets, can you confirm your BoxBilling version please?

**Comment by srobert2** [comment]
Hello I have boxbilling 4.21

**Comment by BenNottelling** [comment]
@srobert2 I know it's been awhile since you've heard anything, but in the latest release this should be completely gone as BoxBilling is 100% free and open source these days. We are actually hoping to have a new beta out within a week or so.

**Comment by evrifaessa** [comment]
You may want to update to the latest beta. I'd advise you to take a full backup however. It is not stable.

**Comment by BenNottelling** [comment]
We actually plan to put out a new beta soon that has some bug fixes and security patches, so consider holding off until then
