### ISSUE TITLE
License error when changing server in version 4.21

### ISSUE THREAD

**Issue by nicaraohosting** [boxbilling/boxbilling#832]
I installed version 4.21 that comes out in softaculous and everything is fine

I changed the server and now it doesn't let me enter the license by mistake. I mean invalid license

I had requested a free license at boxbilling.com and there appears reset and still does not work

any comment is welcomed

**Comment by timothygwebb** [comment]
Boxbilling is now an open source project no licenses are required.

**Comment by evrifaessa** [comment]
Please do not use Softaculous for BoxBilling. The latest version indexed in Softaculous is an outdated one, and we've made a new release that removes the whole licensing system.

Download the archive named BoxBilling.zip from this link:
https://github.com/boxbilling/boxbilling/releases/latest

**Comment by nicaraohosting** [comment]
Okay. Thanks a lot.

this version is beta and you have problems downloading the pdf invoice


I will not have problems when there are updates?

Thanks a lot

**Comment by evrifaessa** [comment]
Not sure if there'll be any updates for the near future. I'm afraid people are losing interest in developing BoxBilling, just like 2015.. We still need more contributors. Until then, we may not even be able to publish an update.

**Comment by nicaraohosting** [comment]
okay. I get it

**Comment by nicaraohosting** [comment]
Hi there

My question is the following:

I know that boxbilling is free code but if you have to help a person by updating the software how much could be given for their working hours.

I have the question why in version 4.22 the invoice in pdf cannot be downloaded and the email history cannot be read in the customer area

I would like your comments on how much could you help for that update?

and by the way, don't let this project die

thanks

**Comment by nicaraohosting** [comment]
Hi there
My question is the following:
I know that boxbilling is free code but if you have to help a person by updating the software how much could be given for their working hours.
I have the question why in version 4.22 the invoice in pdf cannot be downloaded and the email history cannot be read in the customer area
I would like your comments on how much could you help for that update?
and by the way, don't let this project die
thanks 
 
  El dom., 24 de ene. de 2021 a la(s) 2:59 p. m., Yağızhan<notifications@github.com> escribió:   


Not sure if there'll be any updates for the near future. I'm afraid people are losing interest in developing BoxBilling, just like 2015.. We still need more contributors. Until then, we may not even be able to publish an update.
