### ISSUE TITLE
Support Tickets Listed Duplicated By # Responses 4.22-b1

### ISSUE THREAD

**Issue by DataLores** [boxbilling/boxbilling#838]
The following change introduced the same ticket being listed for each comment made on the ticket:

https://github.com/boxbilling/boxbilling/commit/17dc286a1f13c67467f11b99f6dc4104f961fba5#diff-826633fa9e1851761dfe7bc13751fca721abe08cbf6e6a03627d7d820af9ee32

Reverting line 358 and 1058 of src/bb-modules/Support/Service.php resolved the issue and creates the expected behavior again.

**Comment by pexcreative** [comment]
In fact, when the line is reversed, the operation is normal.
How many bugs does the software have ...
