### ISSUE TITLE
ReCaptcha v2 for SpamChecker extension no longer works

### ISSUE THREAD

**Issue by OstojaOfficial** [boxbilling/boxbilling#839]
I been using ReCaptcha v2 just fine for past week and out of nowhere it just stopped working and it spits out the error posted under. No clue why this is happening it worked just fine couple of days ago. I tried getting new ReCaptcha v2 API keys but that didn't do anything, error is still there.

`Argument 2 passed to GuzzleHttp\Client::post() must be of the type array, null given, called in <PATH>\bb-modules\Spamchecker\Service.php on line 163`

**Comment by OstojaOfficial** [comment]
I also tried to replace SpamChecker files from a freshly downloaded latest release but that also didn't work.

**Comment by OstojaOfficial** [comment]
Also I am using PHP 7.4.

**Comment by OstojaOfficial** [comment]
Downgrading to PHP 7.3 didn't fix the error.

**Comment by OstojaOfficial** [comment]
Also tried the fresh install of boxbilling but only copied over bb-config.php which also didn't work.

**Comment by emar** [comment]
I have the same issue, using php 7.0
The ReCaptcha checkbox floats over the form.

**Comment by OstojaOfficial** [comment]
> 
> 
> I have the same issue, using php 7.0
> The ReCaptcha checkbox floats over the form.

Any solutions?

**Comment by emar** [comment]
Not yet no,
I tried ReCaptcha v1 but not sure if that's working either.

**Comment by OstojaOfficial** [comment]
> 
> 
> Not yet no,
> I tried ReCaptcha v1 but not sure if that's working either.

As far as I know Google shut down ReCaptcha v1. So that wouldn't work.

**Comment by emar** [comment]
Have you tried the new version of BoxBilling yet?
4.22 Beta. I haven't upgraded, still testing my install.

**Comment by OstojaOfficial** [comment]
> 
> 
> Have you tried the new version of BoxBilling yet?
> 4.22 Beta. I haven't upgraded, still testing my install.

I am running 4.22 Beta.

**Comment by OstojaOfficial** [comment]
> 
> 
> Have you tried the new version of BoxBilling yet?
> 4.22 Beta. I haven't upgraded, still testing my install.

I found a fix for this.
Find lines
```
$request  = $di['guzzle_client']->post('https://www.google.com/recaptcha/api/siteverify', null, $postData);
$response = $di['guzzle_client']->send($request)->json();
```
They should be about line 163 and 164.
And replace them with this.
```
$postData = http_build_query($postData);
$response = $di['guzzle_client']->post('https://www.google.com/recaptcha/api/siteverify', [
	'headers' => [ 'Content-Type' => 'application/x-www-form-urlencoded' ],
	'body' => $postData
]);
$response = json_decode($response->getBody(), true);
```
I wrote this fix. I am unsure if I should make a pull request. I haven't seen anyone else having this problem.
