### ISSUE TITLE
Setting 'sef_urls' => true, page not found

### ISSUE THREAD

**Issue by emar** [boxbilling/boxbilling#840]
I moved my BoxBilling installation from:
home \ user \ public_htm \ billing

To it's own subdomain:
homes \ user \ service.mysite.com

So I could give service.mysite.com directory it's own php version. (7.0)

I edited the urls in the bb-config.php
Do I need to change anything else?

Everything seems to work on the front end.

When I set 'sef_urls' => true,
I can't access any of the pages.

Not Found
The requested URL /bb-admin/system was not found on this server.

Setting 'sef_urls' => false, the pages load fine.

I'm not using the htaccess.txt I got different errors when I tried that file.

I have an empty .htaccess
The only line in it is: AddHandler application/x-httpd-php70 .php

I haven't upgraded to 4.22 beta yet.

Any pointers appreciated.

Thanks

**Comment by samapraku** [comment]
sef_urls uses apache mod rewrite which requires the rules set in .htaccess

**Comment by emar** [comment]
The only line on my BoxBilling root htaccess file is:

AddHandler application/x-httpd-php70 .php

**Comment by emar** [comment]
I did the upgrade again via FTP with the latest release from GitHub, seems to have fixed everything.

**Comment by emar** [comment]
I did the upgrade again via FTP with the latest release from GitHub, seems to have fixed everything.
The GitHub releases contain packages for Composer, which fixed another issue "Pimple no found"
