### ISSUE TITLE
Bruteforce attack on login API [WILL PAY FOR FIX]

### ISSUE THREAD

**Issue by DJTerrum** [boxbilling/boxbilling#842]
The reCAPTCHA addon only applies to registrations, it should apply to logins too to avoid bruteforce attacks. Can anyone help me add code to the addon that will allow the reCAPTCHA to work with the login form too?

EDIT: The issue seems to be a lot more serious than just a lack of reCAPTCHA on the login page, it seems the API itself is actually being attacked, which would bypass the reCAPTCHA anyway. This needs to be fixed. Can anyone offer assistance in a matter of urgency? I am willing to pay.

> 29892 K 4 23.76 billing.epichosts.co.uk:80 177.53.103.14 POST /index.php?_url=/api/guest/client/login HTTP/1.1
29892 K 4 23.76 billing.epichosts.co.uk:80 103.111.22.26 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30013 K 4 18.38 billing.epichosts.co.uk:80 103.69.20.108 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30146 K 4 18.65 billing.epichosts.co.uk:80 103.206.252.218 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30147 K 4 18.71 billing.epichosts.co.uk:80 85.222.69.218 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30147 K 4 18.71 billing.epichosts.co.uk:80 212.119.217.206 POST /index.php?_url=/api/guest/client/login HTTP/1.1
29892 K 3 23.79 billing.epichosts.co.uk:80 43.242.39.75 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30012 K 3 18.89 billing.epichosts.co.uk:80 212.119.217.206 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30012 K 3 18.89 billing.epichosts.co.uk:80 86.109.60.58 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30013 K 3 18.38 billing.epichosts.co.uk:80 36.89.46.38 POST /index.php?_url=/api/guest/client/login HTTP/1.1
30013 K 3 18.39 billing.epichosts.co.uk:80 124.78.25.45 POST /index.php?_url=/api/guest/client/login HTTP/1.1

**Comment by OstojaOfficial** [comment]
What can be done about this is keeping track of number of failed login attempts so lets say the person failed to login after 5 failed attempts and the account can be IP blocked or even locked out for lets say 15 minutes and successful logins will reset the number of failed login attempts.

**Comment by DJTerrum** [comment]
> What can be done about this is keeping track of number of failed login attempts so lets say the person failed to login after 5 failed attempts and the account can be IP blocked or even locked out for lets say 15 minutes and successful logins will reset the number of failed login attempts.
That does sound like it would work best, but I'd think even something as simple as having a reCAPTCHA on the login page would suffice.
My issue however is more targeted towards the performance-side of BoxBilling, as every single PHP request is really heavy on the CPU load. When I redirect the login traffic to a 403 so that it doesn't touch any BoxBilling code, the resource is far less.
Hence I feel a reCAPTCHA on the login page would be better so that there can't be any connections/submissions made on the login form without passing the challenge first.

**Comment by OstojaOfficial** [comment]
> 
> 
> > What can be done about this is keeping track of number of failed login attempts so lets say the person failed to login after 5 failed attempts and the account can be IP blocked or even locked out for lets say 15 minutes and successful logins will reset the number of failed login attempts.
> 
> That does sound like it would work, but I'd think even something as simple as having a reCAPTCHA on the login page would suffice.
> 
> My issue however is more targeted towards the performance-side of BoxBilling, as every single PHP request is really heavy on the CPU load. When I redirect the login traffic to a 403 so that it doesn't touch any BoxBilling code, the resource is far less.
> 
> Hence I feel a reCAPTCHA on the login page would be better so that there can't be any connections/submissions made on the login form without passing the challenge first.

I think I can try to add it to login page just tell me what theme are you using?

**Comment by DJTerrum** [comment]
> I think I can try to add it to login page just tell me what theme are you using?

I am using the 'boxbilling' theme (**not** the huraga theme).

**Comment by OstojaOfficial** [comment]
I managed to add reCAPTCHA on login page but not on the login form.
![image](https://user-images.githubusercontent.com/21225822/108443135-8a6cb280-7258-11eb-9995-54efbfe313bf.png)
![image](https://user-images.githubusercontent.com/21225822/108443188-a5d7bd80-7258-11eb-8a2f-c68658f3c1e3.png)

**Comment by OstojaOfficial** [comment]
If you want I can edit the theme so when user clicks onto sign in button instead of dropping downthe login into client area form, it will redirect them to login page.

**Comment by OstojaOfficial** [comment]
I also added the reCATPCHA to login form but it overflows.
![image](https://user-images.githubusercontent.com/21225822/108445195-3f549e80-725c-11eb-8468-29de3ae2b667.png)

**Comment by OstojaOfficial** [comment]
@DJTerrum So what do you want me to do? Do you want me to change the theme and do what I said above?

**Comment by DJTerrum** [comment]
Right now it's not of highest priority to me, as I'm now using CloudFlare's JS challenge on the login page, but should anyone that isn't using CloudFlare need this fix you're welcome to share it.

All my concern is that the login form should have come with a reCAPTCHA in the first place (especially if whoever made the extension put the effort into having it work on the registration form anyway).

**Comment by OstojaOfficial** [comment]
> 
> 
> Right now it's not of highest priority to me, as I'm now using CloudFlare's JS challenge on the login page, but should anyone that isn't using CloudFlare need this fix you're welcome to share it.
> 
> All my concern is that the login form should have come with a reCAPTCHA in the first place (especially if whoever made the extension put the effort into having it work on the registration form anyway).

Alright then if your issue has been fixed then you should close this issue.

**Comment by OstojaOfficial** [comment]
I will get around making pull request eventually.

**Comment by DJTerrum** [comment]
The issue itself hasn't necessarily been fixed, I'm just choosing not to apply any fix at this time as the issue is no longer of concern to me, but I am sure it is of concern to any others that are using BoxBilling, therefore I feel it should stay open, at least until a public fix is made available in reference to this post.

**Comment by OstojaOfficial** [comment]
Yea, you are right.

**Comment by rndevuk** [comment]
> 
> 
> What can be done about this is keeping track of number of failed login attempts so lets say the person failed to login after 5 failed attempts and the account can be IP blocked or even locked out for lets say 15 minutes and successful logins will reset the number of failed login attempts.

This is the correct fix for the problem as its the only thing that would offer some protection to the api but it should also be complented with captcha on almost all forms.

**Comment by andrewl64** [comment]
> What can be done about this is keeping track of number of failed login attempts so lets say the person failed to login after 5 failed attempts and the account can be IP blocked or even locked out for lets say 15 minutes and successful logins will reset the number of failed login attempts.

This can be done with **Fail2ban** but as stated in their official wiki:

> Fail2Ban is able to reduce the rate of incorrect authentications attempts however it cannot eliminate the risk that weak authentication presents. Configure services to use only two factor or public/private authentication mechanisms if you really want to protect services.

**Comment by rndevuk** [comment]
> 
> 
> > What can be done about this is keeping track of number of failed login attempts so lets say the person failed to login after 5 failed attempts and the account can be IP blocked or even locked out for lets say 15 minutes and successful logins will reset the number of failed login attempts.
> 
> This can be done with **Fail2ban** but as stated in their official wiki:
> 
> > Fail2Ban is able to reduce the rate of incorrect authentications attempts however it cannot eliminate the risk that weak authentication presents. Configure services to use only two factor or public/private authentication mechanisms if you really want to protect services.

You are assuming that all users of boxbilling can use Fail2ban... This shouldnt be left to third party software. This should be part of boxbillings software.

**Comment by evrifaessa** [comment]
> This shouldnt be left to third party software. This should be part of boxbillings software.

Agreed.

**Comment by timothygwebb** [comment]
@evrifaessa @rndevuk  @andrewl64  @OstojaOfficial  @DJTerrum  @fordnox 

I have a suggestion if anyone has any time to contribute. 

Update the login script to do a check to the following table INFORMATION_SCHEMA.PLUGINS in the MySQL server on the machine that the BoxBilling is installed on. If the table verifies the CONNECTION_CONTROL_FAILED_LOGIN_ATTEMPTS plugin as active then check logins against the table CONNECTION_CONTROL_FAILED_LOGIN_ATTEMPTS to verify where if greater then number of rows and time stamp deny access. If they plugin does not validate as active then install the plugin.

For the above table to be checked we would have to include in BoxBilling during the install an additional plugin called 

Connection-Control Plugin and CONNECTION_CONTROL_FAILED_LOGIN_ATTEMPTS

Information on the above MySQL plugin can be found below.

SELECT PLUGIN_NAME, PLUGIN_STATUS
       FROM INFORMATION_SCHEMA.PLUGINS
       WHERE PLUGIN_NAME LIKE 'connection%';
+------------------------------------------+---------------+
| PLUGIN_NAME                              | PLUGIN_STATUS |
+------------------------------------------+---------------+
| CONNECTION_CONTROL                       | ACTIVE        |
| CONNECTION_CONTROL_FAILED_LOGIN_ATTEMPTS | ACTIVE        |
+------------------------------------------+---------------+

https://dev.mysql.com/doc/refman/8.0/en/connection-control-installation.html
https://dev.mysql.com/doc/mysql-security-excerpt/5.7/en/connection-control-installation.html
https://dev.mysql.com/doc/refman/8.0/en/information-schema-connection-control-failed-login-attempts-table.html

Please review the above aforementioned website articles and respond. If we all feel that this should be made into a discussion and worked in a project please let me know and I will convert this to a discussion and create the project and work it.

By the way please do your research before posting in an issue our assumptions.
Relying on third parties is not always the best but I do agree why rewrite the wheel when there is a plugin for it.

@DJTerrum  Happy Plugging. :)

**Comment by andrewl64** [comment]
I wasn't really implying that BoxBilling should start using Fail2ban though (but to be fair, I wasn't implying the opposite either lol). I just thought maybe BoxBilling could somehow utilise similar (if not the same) logic and principle that Fail2ban uses when dealing with brute force attacks.

**Comment by BenNottelling** [comment]
Maybe integrate something like this, record by IP address, and once it hits the limit we simply return a 403 forbidden header?
Would slightly increase the size of BoxBilling, but rate limiting on the API is pretty important.
https://github.com/nikolaposa/rate-limit

**Comment by BenNottelling** [comment]
Fact: Boxbilling already has a form of rate limiting implemented. Edit your bb-config file
```rate_span``` : The timespan in seconds
```rate_limit``` : The number of requests allowed in that time span. 
Default numbers are just cranked up a TON

**Comment by BenNottelling** [comment]
@DJTerrum Hi, I'm not sure if you're still around for this, but I've submitted a pull request that should resolve this issue for you!
Make sure to update the config files to include the new options for login API rate limiting.
PR here: https://github.com/boxbilling/boxbilling/pull/911

**Comment by DJTerrum** [comment]
@BenNottelling I am still here, and I appreciate the contribution. I have not been actively responding as this is not really an issue for me anymore, but I left this open for anyone that wanted to provide a public fix, as mentioned in my last response.

If you (or anyone else reading this) is interested in helping me out with updating/replacing the Stripe payment gateway though, I'm still actively looking for help on that and will also pay for the help if required: https://github.com/boxbilling/boxbilling/issues/889
