### ISSUE TITLE
ive made it but it shows issue....

### ISSUE THREAD

**Issue by mtgsquad** [boxbilling/boxbilling#847]
![Image Of Error](https://user-images.githubusercontent.com/75879007/109430486-7fb5d880-7a23-11eb-8386-83255a1ab01d.png)

says i need a table for it...

here is phpMyAdmin for the db:

![imghere](https://user-images.githubusercontent.com/75879007/109430517-a07e2e00-7a23-11eb-8b96-2d87b7142f4c.png)

**Comment by BenNottelling** [comment]
You can clearly see there are no tables in your DB. Why are you installing this way instead of using the installer?

**Comment by BenNottelling** [comment]
@mtgsquad I'm going to close this as it's quite old and you probably gave up or figured it out a long time ago.
I recommend using the installer to create the database and tables as you need, if you need to do it manually for whatever reason these are the templates the installer imports to create everything:
https://github.com/boxbilling/boxbilling/tree/master/src/install/sql
