### ISSUE TITLE
Centova Cast Extension error in BoxBilling 4.22 Beta 1

### ISSUE THREAD

**Issue by emar** [boxbilling/boxbilling#848]
When I click test connection in Centova Cast Extension the popup dialog displays "error"

From bb-data/log/php_error.log

[03-Mar-2021 08:13:32 UTC] PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/site/service.x.com/bb-modules/Servicecentovacast/ccapiclient.php on line 47

**Comment by emar** [comment]
Any plans to fix this extension?

**Comment by evrifaessa** [comment]
> Any plans to fix this extension?

Probably not in our priorities. However, we'd love to see volunteers working on a fix.

**Comment by emar** [comment]
That's a pity, 

I was on a budget and working on a custom billing system with BoxBiling,  just for Centova Cast.
I thought Centova devs created it.. if so, I wouldn't mind asking them about it.

**Comment by 0xcrypto** [comment]
> When I click test connection in Centova Cast Extension the popup dialog displays "error"
> 
> From bb-data/log/php_error.log
> 
> [03-Mar-2021 08:13:32 UTC] PHP Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/site/service.x.com/bb-modules/Servicecentovacast/ccapiclient.php on line 47

This is just a warning on newer versions of PHP.  Maybe I will jump to fix it

**Comment by emar** [comment]
I just tried it with a paypal sandbox buyer, got the order done, 
Can see the order is pending in boxbilling, logged in as admin a set the order as paid.
Then I see Failed Setup message in client area,
Logged in as admin I see: "Centova Cast Server not found"
