### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Dexxa1024** [boxbilling/boxbilling#853]
I brought a custom design for BoxBilling a few years back,  and all the other links work great on the theme.

But when i click on the order link i get an error

ERROR
Unexpected token "name" of value "js" ("end of statement block" expected).

Anyway i can fix this?

The company who did it for me doesnt seem to exist now :-(

**Comment by rndevuk** [comment]
If its a custom design then the person who designed it would need to update it. That being said, if you can send a link to the sourcecode for the design and provide as much info as possible. Then i'm sure someone here would help.

**Comment by Dexxa1024** [comment]
The theme files are here :-) https://drive.google.com/file/d/1xi4wlzF66nFptq0cTUXYMUOmmAeeXo3O/view?usp=sharing    if anyone wants to have a look, befree to use it yourself to if you want to :-)

**Comment by NatarajaVj** [comment]
File removed?

**Comment by Dexxa1024** [comment]
> File removed?

It's still in my google drive?

**Comment by sAco2web** [comment]
Nop. No more files in there .. 

Envoyé de mon iPhone

**Comment by Dexxa1024** [comment]
I just created a new link, hopefully it works this time https://drive.google.com/drive/folders/1xjd6qH6sdJBUYjSdlmLNZj-rp_bpZjB4?usp=sharing

**Comment by sAco2web** [comment]
Yes it’s there now. Just sent access request. 

Envoyé de mon iPhone
