### ISSUE TITLE
Install not possible / No connection to Database

### ISSUE THREAD

**Issue by Yakashimoto** [boxbilling/boxbilling#855]
Hello,

is there any knowing bug on the install ?

Because on the install steps it dont work to go forward after SQL Details has been placed.

Try to use the config file end with:

ERROR
ERROR CODE: 1045
SQLSTATE[HY000] [1045] Access denied for user 'xxxxc'@'127.0.0.1' (using password: YES)

Set BB_DEBUG to FALSE, to hide the message below

Class: "PDOException"

File: "/www/htdocs/xxxxx/boxbill.xxxx.xxx/bb-di.php"

Line: "58"

**Comment by samapraku** [comment]
That is your database setup issue and not boxbilling.

Check the password authentication that you have configured for your database user

**Comment by Yakashimoto** [comment]
Database is correct....as written, the install script also stops WITHOUT any Warning on the SQL Steps (no action after click next step).

**Comment by plz-hlp-me** [comment]
Hi,

@samapraku do you got any solution for this issue? I am also facing the same.

**Comment by plz-hlp-me** [comment]
HI,

@Yakashimoto do you got any solution for this issue? I am also facing the same.

**Comment by BenNottelling** [comment]
@Yakashimoto you say the setup doesn't continue after the SQL setup? Clean the database, ensure you're running at least PHP 7.2, but not PHP 8, and then try again

**Comment by BenNottelling** [comment]
I'm going to close this as we haven't heard anything and I believe this was an issue with PHP8. BoxBilling should now correctly install and work on PHP8, although we haven't done thorough testing
