### ISSUE TITLE
18% on every Product

### ISSUE THREAD

**Issue by RudiBott** [boxbilling/boxbilling#856]
Hello, 
I created a Product and if ill try to buy it, it puts 18% on top. 

For example: i set 2€ and if ill try to buy it, it says 2,36€. 
I set no Tax Rules.

Who do i fix that problem?

Rudi Bott

**Comment by samapraku** [comment]
Turn off Tax support under Tax settings tab in Tax rules configuration

**Comment by evrifaessa** [comment]
Could you inform us why you closed this? Unless it's solved, issues should be kept open. Thanks.

**Comment by RudiBott** [comment]
The issue is solved. thats why i closed it.
