### ISSUE TITLE
Can not klick after Installing

### ISSUE THREAD

**Issue by Stormez1998** [boxbilling/boxbilling#857]
Hay there,

after installing without any problems i was very hyped :D 

Then i clicked to Adminarea and wants to login. But then i realized, that i can not klick anywhere. So the side loads but i get every time back to the main URL.

For Testing, here is my website: www.tz-gaming.com

Thanks for Help and best regrads 

For questions im open here.

**Comment by evrifaessa** [comment]
Provided website is unreachable. Please re-open this issue if you need further help.
