### ISSUE TITLE
Cron execution is failing

### ISSUE THREAD

**Issue by EpicUnknown** [boxbilling/boxbilling#882]
During the cron execution I get the error below:

```
- Welcome to BoxBilling.
Last executed: .Successfully ran the cron jobs.Error #[0] occurred in [/var/www/boxbilling/rb.php] at line [830]: [syntax error, unexpected namespaced name "implements\IteratorAggregate", expecting "{"]
```

It is running on:
```
Linux cerberus 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux
```

Not sure why it's saying successful because it is not successful.

**Comment by evrifaessa** [comment]
You haven't provided your PHP version, but guessing from the error message, it's probably PHP 8.x.
If so, please downgrade your version to something from PHP 7.2 to 7.4 and try again. BoxBilling is not compatible with PHP 8 yet.

**Comment by EpicUnknown** [comment]
You sure are correct... I am running 8.0.3.

I apologize, thank you for the help!! You can close this ticket if you wish (:
