### ISSUE TITLE
Domain can not be transferred

### ISSUE THREAD

**Issue by ijmilton** [boxbilling/boxbilling#89]
This script is really cool. I am coming from WHMCS and am very impressed. 

So far I only seem to be having an issue with the ResellerClub domain module. I followed the steps (got my userid and registered IP's in their control panel) and when choosing domain transfer during the order process, I usually get "Domain can not be transferred" in the pop-up dialog. I occasionally get other messages when trying random domains like "ResellerClub: "rewererw.com is currently available for Registration. You may Register this domain name by placing a Registration request with us." This leads me to believe the module is doing something.

Any suggestions? Thank you for your time.

**Comment by rrkksinha** [comment]
Hi everyone. I try boxbilling and it's really cool. 

I have also getting the same issue **"Domain can not be transferred."** when trying to transfer domain form other service provider with the transfer option available in boxbilling.

https://support-tools.com/?f8748dc9077701ac#3JWJDslcF/jPwvrPEFjPUndx7S+azX37WPRZM5Tdo0M=

https://support-tools.com/?5dc2c08b03cfaecd#G8a9a9/mv70Udhpcrd0uWxV68zNxyTyvyn4tSknkzDE=

Please help me how to solve it...

Thanks in advance...
