### ISSUE TITLE
KB category duplicate

### ISSUE THREAD

**Issue by pexcreative** [boxbilling/boxbilling#890]
https://github.com/boxbilling/boxbilling/commit/17dc286a1f13c67467f11b99f6dc4104f961fba5#diff-17cffd996996e38e435ebd7b6c3c4011ef4497c908e9f6852735dcaaa73f7f34

I only went back as line 376 shows.
Adding: GROUP BY kac.id

**Comment by samapraku** [comment]
Instead of using GROUP BY, a better approach might be using `SELECT DISTINCT`
