### ISSUE TITLE
MOFH

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [boxbilling/boxbilling#891]
Does this work with Myownfreehost

**Comment by DJTerrum** [comment]
https://github.com/boxbilling/boxbilling/releases/tag/v4.22-beta.1

`Added MyOwnFreeHost support`

**Comment by Slddev** [comment]
> https://github.com/boxbilling/boxbilling/releases/tag/v4.22-beta.1
> 
> `Added MyOwnFreeHost support`

Gives the wrong password though.

**Comment by BenNottelling** [comment]
> Gives the wrong password though.

Definitely shouldn't. It's not the user account password, but a separate one that gets created with each hosting account created and then emailed to you

**Comment by BenNottelling** [comment]
MOFH should be supported. If someone confirms there's an issue with the integration, then please submit a new issue
