### ISSUE TITLE
Admin Area doesn't exist

### ISSUE THREAD

**Issue by Slddev** [boxbilling/boxbilling#895]
I tried accessing the admin area with the `/bb-admin` and `index.php?_url=/bb-admin` but both don't work. (gives me a 404 error). Checked the files and no such file named as "bb-admin" was found. Did I make a mistake? How do you guys access your admin area?

**Comment by thegraylan** [comment]
i have been having the same issue, i just found a comment that said to change 'sef_urls' => false, on bb-config.php
and it worked for me, i am using apache

**Comment by Slddev** [comment]
Fixed. Just waited for a few hours and it resolved itself. I'm not sure what happened really...
