### ISSUE TITLE
Page /bb-themes/boxbilling/assets/style.css not found

### ISSUE THREAD

**Issue by BrunnoPrego** [boxbilling/boxbilling#898]
Verifing the bb-data/log/php_error.log I get this message about style.css not found, the file is in assets/css/style.css.
Then, to bypass that error, I maked a link from assets/style.css point to assets/css/style.css

**Comment by notbasetwo** [comment]
@BrunnoPrego What theme are you using in BoxBilling?

I have had a little look and I've found one template which could potentially cause the issue in the boxbilling theme but I don't think it is used anywhere.

**Comment by BenNottelling** [comment]
@notbasetwo if the path is `/bb-themes/boxbilling` then they were using the default BoxBilling theme that is enabled out of the box

**Comment by notbasetwo** [comment]
> 
> 
> @notbasetwo if the path is `/bb-themes/boxbilling` then they were using the default BoxBilling theme that is enabled out of the box

Doh! Didn't read the title. Guess the only thing I can see is the one file, I'll make a PR that should close the issue.
