### ISSUE TITLE
Adding custom java-script to a product page..

### ISSUE THREAD

**Issue by emar** [boxbilling/boxbilling#899]
..

**Comment by kochivai** [comment]
I already did it.
it's simple
if you want to add globally. go to page layout_default.phtml of your selected theme.
you will find {% block js %} there add your js.
 {{ 'bootstrap/js/bootstrap.bundle.min.js' | asset_url | script_tag }}
asset_url means your theme asset folder. locate the file in first section...--> 'bootstrap/js/bootstrap.bundle.min.js'

**Comment by emar** [comment]
Thanks Kochivai,

Might have to give bb a miss as the one extension I was depending on has stopped working,
Probably because of php version.

**Comment by BenNottelling** [comment]
Looks like this issue is taken care of, and a separate one exists for the extension
