### ISSUE TITLE
Does can https?

### ISSUE THREAD

**Issue by sialexsofficial** [boxbilling/boxbilling#908]
my website if using http is safe and controlled, but if using https my website looks like there is no css, how do I redrect to https in boxbilling?

**Comment by BenNottelling** [comment]
Inside your ```bb-config.php``` file, check that the "url" is HTTPS and not HTTP.

**Comment by BenNottelling** [comment]
@sialexsofficial BoxBilling does use HTTS correctly, if you're around we can figure out why your instance isn't loading correctly on it

**Comment by John-S4** [comment]
If you have modified any files then maybe you have a hardcoded link to a http:// file (like a CSS file). 

If the issue is visible on public facing pages, then you could try using https://www.whynopadlock.com/ to see which particular files if any are not being served over HTTPS

**Comment by BenNottelling** [comment]
I'm going to close this since we haven't heard anything.
BoxBilling works without issue over HTTPS, so if you're experiencing issues it's on your end. Would be happy to help identify the problem if you're around, but we haven't heard anything from you
