### ISSUE TITLE
[Bug]: Install fails on PHP 8 directly after creating SQL database

### ISSUE THREAD

**Issue by BenNottelling** [boxbilling/boxbilling#915]
### What happened?

If you install on a webserver using PHP 8, the install create the SQL database and then do nothing. It will never pass that as long as you are on PHP 8.
Created an issue as per: https://github.com/boxbilling/boxbilling/pull/909#issuecomment-893450316

### BoxBilling Version

Current Master Branch

### Additional Notes

I do believe everything works fine on PHP 8 after the install as I was having an issue where my webserver was switching back to PHP 8 for my BB directory even though I had that set as 7.4.
I'm not sure if everything does work, though, I always switched back to 7.4 and never did any attempts to figure out if anything was broken

**Comment by timothygwebb** [comment]
Please append to ticket workflow with screenshots.

Thanks

Timothy Webb Sr.

**Comment by BenNottelling** [comment]
@timothygwebb This is literally all it does
![problem](https://user-images.githubusercontent.com/17304943/128372354-f1aed6a9-ccc7-4b45-a358-32fb74384205.gif)

**Comment by BenNottelling** [comment]
@timothygwebb I just tested and I can confirm the admin table become populated. Showing data because it's random stuff I made up just to test it.
![image](https://user-images.githubusercontent.com/17304943/128470611-cbc3a7ad-0895-4215-8a96-6fd04757acf5.png)

**Comment by BenNottelling** [comment]
Some testing I did:

install.php is missing `BB_PATH_LANGS`
Added: `define('BB_PATH_LANGS',     BB_PATH_ROOT . '/bb-locale');` to install.php
Now will error out with old RedBeanPHP.
Updating RedBeanPHP results in the install seemingly finishing, but then being given an error about `email_template` not being a valid type

**Comment by timothygwebb** [comment]
@BenNottelling  Create or update existing pull request with your branch and I will look into email_template.

**Comment by BenNottelling** [comment]
@timothygwebb Why would I create a PR that leaves something unfinished and will directly conflict with https://github.com/boxbilling/boxbilling/pull/980?

**Comment by timothygwebb** [comment]
@BenNottelling  then post in conversation reference to email_template so I may further assist.

**Comment by BenNottelling** [comment]
I actually fixed this without realizing it. @evrifaessa merged the fix, closing now
