### ISSUE TITLE
Travis-CI Repository Access Update Requires Organization Owner

### ISSUE THREAD

**Issue by timothygwebb** [boxbilling/boxbilling#924]
### What is the idea?

@fordnox 

> Mustafa Ergul (Support)
> 3:45 AM (3 hours ago)
> to me
> ##- Please type your reply above this line -##
> from Travis CI has an update for your ticket, #31168. If you'd like to add additional comments, please reply to this email:
> Mustafa Ergul (Travis CI)
> Aug 6, 2021, 4:45 GMT-3
> Hey Timothy​,
> I have been checking your plan status on your account boxbilling and it seems like there is no plan on this account. With the new pricing model[1], you will need to at least sign up for a Free Plan to be able to trigger builds. Please visit this[2] link and select at least a Free plan.
> I hope this helps, please let us know if you need further assistance, we will be glad to help.
> Sincerely,
> [1] https://docs.travis-ci.com/user/billing-overview/
> [2]https://travis-ci.com/organizations/boxbilling/plan
> --
> Mustafa
> Your Friends @Travis CI
> Test and Deploy with Confidence.
> www.travis-ci.com

### Why would this be beneficial

Merging of pull requests and the passing of status checks.
![image](https://user-images.githubusercontent.com/16106877/128500172-c8f1f9be-2e61-4d26-b67d-f46077e7eef9.png)

**Comment by BenNottelling** [comment]
![image](https://user-images.githubusercontent.com/17304943/128532807-848043f6-5959-45d1-8c4c-75918a344cb4.png)

**Comment by BenNottelling** [comment]
Travis free plan has been enabled and builds are being triggered again

**Comment by timothygwebb** [comment]
Thanks for your help.

Thanks

Timothy Webb Sr.
