### ISSUE TITLE
Update CKEditor, and decide if it should be default

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#939]
### What is the task

Our CKEditor implementation was added 7 years ago and has never been touched since. [/bb-modules/Wysiwyg/assets/ckeditor](https://github.com/boxbilling/boxbilling/tree/master/src/bb-modules/Wysiwyg/assets/ckeditor)

Github's code scanning alerts detected vulnerabilities on this implementation of the old CKEditor version of ours.
We should update it to the newest version found [here](https://ckeditor.com/). It also has a lot of improvements.

**Comment by evrifaessa** [comment]
So, I updated CKEditor 4 to it's latest release. My suggestion is to drop markitUp (another WYSIWYG editor we have added 7 years ago. It was never updated since, and it's latest release was made in 2018). Then, if CKEditor works as expected (first impressions show that it works), we can make the WYSIWYG extension enabled by default.

**Comment by evrifaessa** [comment]
@fordnox @BenNottelling @timothygwebb @John-S4

**Comment by BenNottelling** [comment]
If it's not maintained let's drop it

**Comment by John-S4** [comment]
Makes sense to me, I'm not sure there is any need at all for multiple editors and if one is no longer maintained it should definitely not be kept.
