### ISSUE TITLE
[Bug] CSRF-Protection-PHP blocks me from logging in at all

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#951]
### What happened?

It blocks anything I do. Running on localhost, tried with Firefox and Brave, doesn't let me log in and requests end up being returned with a 403 error.

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

7.4x

**Comment by BenNottelling** [comment]
Do you have cookies and JavaScript enabled?
What browser?

**Comment by evrifaessa** [comment]
> Do you have cookies and JavaScript enabled?
Yeah
> What browser?
Firefox and Brave

Can you do a clean install of master and try to fix? Thanks.
