### ISSUE TITLE
Error Code: Request Error

### ISSUE THREAD

**Issue by ArxStudio** [boxbilling/boxbilling#96]
I'm experiencing this error when trying to login to the admin area.
When I install BoxBilling, I get the email saying my username and password etc,
I've tried going in phpMyAdmin and changing the password but still no luck.

I've looked at the config file, and it's all correct.

The URL for anyone who wants to take a look is:
http://client.arxstudio.co.uk/bb-admin.php/staff/login

I've tried reinstalling it from scratch a few times, but each time I get this error.

Please help :)

**Comment by Deb00** [comment]
I can't log in with right pass and email
