### ISSUE TITLE
[Bug] csrfp-config.php is broken

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#964]
### What happened?

```
Notice: Undefined variable: config in (...)\csrfp-config.php on line 16
Notice: Trying to access array offset on value of type null in (...)\htdocs\csrfp-config.php on line 16
```

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

7.4x

### Additional Notes

* PHP 7.4.22
* URL: http://(...)/bb-admin/staff/login

**Comment by BenNottelling** [comment]
Steps to reproduce? I did a fresh install of BB last night and have never had this issue. Just checked my logs too

**Comment by evrifaessa** [comment]
> Steps to reproduce? I did a fresh install of BB last night and have never had this issue. Just checked my logs too

Just navigate to /bb-admin.

It's about the use of `$config` in this line:
https://github.com/boxbilling/boxbilling/blob/63524613dbfb0d20305e1dee57634552365c2101/src/csrfp-config.php#L16

**Comment by BenNottelling** [comment]
> > Steps to reproduce? I did a fresh install of BB last night and have never had this issue. Just checked my logs too
> 
> Just navigate to /bb-admin.
> 
> It's about the use of `$config` in this line:
> https://github.com/boxbilling/boxbilling/blob/63524613dbfb0d20305e1dee57634552365c2101/src/csrfp-config.php#L16

I did navigate to /bb-admin. No error, everything works fine.
Nothing in the log

**Comment by BenNottelling** [comment]
> So can you tell me where you defined $config in? Because in my installation, it's undefined.

I didn't define it. It's defined here in bb-load before the CSRF protection is loaded in.
https://github.com/boxbilling/boxbilling/blob/master/src/bb-load.php#L258

**Comment by evrifaessa** [comment]
> I didn't define it. It's defined here in bb-load before the CSRF protection is loaded in.
> https://github.com/boxbilling/boxbilling/blob/master/src/bb-load.php#L258

I don't know why my installation thinks it's null. Already tried doing a clean install.

**Comment by BenNottelling** [comment]
> I don't know why my installation thinks it's null. Already tried doing a clean install.

I don't either, that's strange. Can you change the "jsUrl" line to this:
``"jsUrl" => BB_URL .'/bb-library/Security/CSRF-Protector-PHP/js/csrfprotector.js',``
and modify `bb-load.php` so that these lines are below where `BB_URL` is defined?
```
// Initialize CSRFProtector library
csrfProtector::init();
```

**Comment by BenNottelling** [comment]
@evrifaessa Were you able to try that?

**Comment by evrifaessa** [comment]
> @evrifaessa Were you able to try that?

not yet. I'll reinstall my OS this evening, so won't be able to test anything.

**Comment by BenNottelling** [comment]
> not yet. I'll reinstall my OS this evening, so won't be able to test anything.

Copy, let me know when you do

**Comment by evrifaessa** [comment]
> I don't either, that's strange. Can you change the "jsUrl" line to this:
> `"jsUrl" => BB_URL .'/bb-library/Security/CSRF-Protector-PHP/js/csrfprotector.js',`
> and modify `bb-load.php` so that these lines are below where `BB_URL` is defined?
> 
> ```
> // Initialize CSRFProtector library
> csrfProtector::init();
> ```

This worked. I'll create a PR. Thanks.
