### ISSUE TITLE
You are not allowed to login to admin area from IP address:

### ISSUE THREAD

**Issue by Beatdown032** [boxbilling/boxbilling#970]
### What happened?

Hi Everyone,

Hope all is well!

In our Box Billing site we cannot log in to our admin area its getting error see the attached:

Is there anyone who has encountered the same issue? 

Please I need and advice.

 

### BoxBilling Version

v4.21

### What version of PHP are you running?

Something unsupported

### Additional Notes

Additional notes

**Comment by BenNottelling** [comment]
Did you by any chance manually configure allowed IP addresses? Thanks

**Comment by Beatdown032** [comment]
> Did you by any chance manually configure allowed IP addresses? Thanks

Hi BenNottelling, May I know how to do it?

**Comment by evrifaessa** [comment]
@Beatdown032 have you filled this line with something?

https://github.com/boxbilling/boxbilling/blob/42cde7416e899421f01ec72d4a91a399dde708d2/src/bb-config-sample.php#L108

Leave it default if you want every IP to access. If you have any IP added to that array, BB will deny any other IP addresses.

**Comment by BenNottelling** [comment]
@Beatdown032 I saved the IP shown in your screenshot just Incase we need it for anything. I'd recommend you remove it from the issue mostly as a privacy thing for yourself since it has your IP address in it. 

Also, I see you have BB version 4.21 which is pretty old and still based on PHP 5. Neither that version of PHP or BB are maintained for security vulnerabilities, so if you can I would consider using a newer version of BB with PHP 7.2-7.4

These are at least being maintained. Soon we should be releasing a new beta version of BB 4.22 which will have multiple security patches and some bug fixes.

I should still note these are in the beta state and bugs are to be expected, but that's the most up-to-date version we can currently provide

**Comment by Beatdown032** [comment]
> @Beatdown032 I saved the IP shown in your screenshot just Incase we need it for anything. I'd recommend you remove it from the issue mostly as a privacy thing for yourself since it has your IP address in it.
> 
> Also, I see you have BB version 4.21 which is pretty old and still based on PHP 5. Neither that version of PHP or BB are maintained for security vulnerabilities, so if you can I would consider using a newer version of BB with PHP 7.2-7.4
> 
> These are at least being maintained. Soon we should be releasing a new beta version of BB 4.22 which will have multiple security patches and some bug fixes.
> 
> I should still note these are in the beta state and bugs are to be expected, but that's the most up-to-date version we can currently provide

@BenNottelling , Thanks I'm on it..

**Comment by Beatdown032** [comment]
> @Beatdown032 have you filled this line with something?
> 
> https://github.com/boxbilling/boxbilling/blob/42cde7416e899421f01ec72d4a91a399dde708d2/src/bb-config-sample.php#L108
> 
> Leave it default if you want every IP to access. If you have any IP added to that array, BB will deny any other IP addresses.

Hi @evrifaessa, Let me check it.. Thanks

**Comment by Beatdown032** [comment]
Team,

Where should I put the IPs? and how? 
![image](https://user-images.githubusercontent.com/85406541/129324218-fe953c37-e7e5-4432-ab17-6337656d595c.png)

Appologies,

**Comment by BenNottelling** [comment]
Just leave it blank.  That's useful if you want to lock access down to only a specific IP, but for most people their public IP changes all the time so they can't really do it. 

I brought it up because I wanted to make sure you didn't accidentally configure it incorrectly. 

Anyways, it's 1am so I'm off to bed. Will check back when I'm awake

**Comment by evrifaessa** [comment]
> Where should I put the IPs? and how?

This is weird, it supposed to allow logging in from any IP if the allowed_ips array is empty. You don't need to put any IP addresses.

Can you take a backup, then try installing [this version](https://github.com/boxbilling/boxbilling/releases/tag/v4.22-beta.1)? But take a full file + database backup in case you want to go back to your working stable installation. Also, you'll need something between PHP 7.2 and 7.4 to run the newer version. Let's see if this fixes your issue.

**Comment by Beatdown032** [comment]
> Just leave it blank. That's useful if you want to lock access down to only a specific IP, but for most people their public IP changes all the time so they can't really do it.
> 
> I brought it up because I wanted to make sure you didn't accidentally configure it incorrectly.
> 
> Anyways, it's 1am so I'm off to bed. Will check back when I'm awake

Thanks, Man for the time, I'll try to figure it out.

**Comment by Beatdown032** [comment]
> > Where should I put the IPs? and how?
> 
> This is weird, it supposed to allow logging in from any IP if the allowed_ips array is empty. You don't need to put any IP addresses.
> 
> Can you take a backup, then try installing [this version](https://github.com/boxbilling/boxbilling/releases/tag/v4.22-beta.1)? But take a full file + database backup in case you want to go back to your working stable installation. Also, you'll need something between PHP 7.2 and 7.4 to run the newer version. Let's see if this fixes your issue.

HI @evrifaessa How Can I manually upgrade the BB? May I know?

**Comment by evrifaessa** [comment]
> HI @evrifaessa How Can I manually upgrade the BB? May I know?

1. Take a backup of **everything**. Get your SQL dump, backup the whole folder you installed BB in.
2. Upgrade your PHP installation to something between 7.2 and 7.4. I personally would go with 7.4.
3. Delete /bb-vendor /bb-data/cache
4. Download v4.22-beta.1 from [this link](https://github.com/boxbilling/boxbilling/releases/download/v4.22-beta.1/BoxBilling.zip).
5. Copy the content onto your existing installation (overwrite the existing files)
6. Delete the /install folder
6. Navigate to https://(your_domain_here)/bb-update.php
7. You're done.

**Comment by Beatdown032** [comment]
Hi @evrifaessa,

Well done its working now, Ive upgraded the PHP Version to 7.4 and the Latest BB Version...

Last question: May I know how properly configure the "Enabling search engine friendly URL’s" Mine has still /index.php?_url=/bb-admin/staff/login even I have changed the "'sef_urls'  => false," into true
 
![image](https://user-images.githubusercontent.com/85406541/129330989-5db0bbe9-3c59-4ddd-ad6f-cf08acc58aff.png)

Thanks a lot Team.

**Comment by BenNottelling** [comment]
@Beatdown032 I just want to confirm, did you change that in `bb-config.php` or the config sample? You have to make the changes inside `bb-config.php` for the changes to be used

**Comment by Beatdown032** [comment]
> @Beatdown032 I just want to confirm, did you change that in `bb-config.php` or the config sample? You have to make the changes inside `bb-config.php` for the changes to be used

Hi @BenNottelling , What are you talking about?  "Enabling search engine friendly URL’s"?

**Comment by BenNottelling** [comment]
> What are you talking about? "Enabling search engine friendly URL’s"?

Yes, when you install BB it creates a `bb-config.php` file and that's the correct place to make the changes. The other one that comes with BB is just to document all the options and let you know what they do

**Comment by Beatdown032** [comment]
Yes. I have it 
![image](https://user-images.githubusercontent.com/85406541/129381507-0412a4ae-4a20-44e2-a9ec-2c29eea9b0b3.png)

There is a codes that I need to update into the bb-config.php ?

**Comment by BenNottelling** [comment]
@Beatdown032 Yes. Editing anything inside `bb-config-sample.php` won't do anything, so make your changes inside `bb-config.php` instead. Also, don't forget to delete the old .zip of BB so you can save a bit of space ;)

**Comment by Beatdown032** [comment]
Great, thanks for letting me know.

So, May I know what are the codes for "Enabling search engine friendly URL’s"?

Thanks for the @BenNottelling

**Comment by Beatdown032** [comment]
Look at the screenshot:
![image](https://user-images.githubusercontent.com/85406541/129382656-bb1fae5f-978d-407c-a1c3-e8de0df9225a.png)

**Comment by BenNottelling** [comment]
@Beatdown032 just set it to `true` if you want to enable it, or `false` if you want to disable it

**Comment by BenNottelling** [comment]
@Beatdown032 the correct URL should be `/bb-admin/staff/login`

**Comment by Beatdown032** [comment]
I ve tried it but did not work:

![image](https://user-images.githubusercontent.com/85406541/129382919-1a577e02-75dd-4894-9e43-283990628f4a.png)

**Comment by Beatdown032** [comment]
> @Beatdown032 the correct URL should be `/bb-admin/staff/login`

Well done.. its working now.. 

Thanks a lot @BenNottelling

**Comment by Beatdown032** [comment]
![image](https://user-images.githubusercontent.com/85406541/129383251-56d1a907-7da0-4108-aef8-71c3a1baf47f.png)

Thank you team..

**Comment by BenNottelling** [comment]
Awesome, I'll go ahead and close this as well since the original problem was on an unsupported version of BB

**Comment by Beatdown032** [comment]
> Awesome, I'll go ahead and close this as well since the original problem was on an unsupported version of BB

Sure, Thanks
