### ISSUE TITLE
How to remove e-mail branding

### ISSUE THREAD

**Issue by Beatdown032** [boxbilling/boxbilling#972]
### What is the idea?

Hi Everyone,

Quick question: How Can I hide Powered by BoxBilling this is from the client email notification. 

I just upgraded to the new BB version I've there is Powered by BoxBilling in the footer.

![image](https://user-images.githubusercontent.com/85406541/129347713-20510694-b232-4c2f-b4b0-5809eb038100.png)

Thanks,

### Why would this be beneficial

Benefits

**Comment by evrifaessa** [comment]
Hello @Beatdown032. We already removed it 8 months ago. Last beta release (the one that you're using) was made 9 months ago, and any changes made from that point is not included in public releases yet. So you can either wait for us to release a newer version or remove the branding yourself.

See #824 for what you need to do. Basically, you need to remove these 2 lines:
https://github.com/boxbilling/boxbilling/blob/88e9f4114e377eb06f7d071c832f83aca44de521/src/bb-modules/Email/Service.php#L543-L544

Sorry for the inconvenience. All changes we made in the last 9 months are going to be added to the releases soon.

**Comment by Beatdown032** [comment]
> Hello @Beatdown032. We already removed it 8 months ago. Last beta release (the one that you're using) was made 9 months ago, and any changes made from that point is not included in public releases yet. So you can either wait for us to release a newer version or remove the branding yourself.
> 
> See #824 for what you need to do. Basically, you need to remove these 2 lines:
> https://github.com/boxbilling/boxbilling/blob/88e9f4114e377eb06f7d071c832f83aca44de521/src/bb-modules/Email/Service.php#L543-L544
> 
> Sorry for the inconvenience. All changes we made in the last 9 months are going to be added to the releases soon.

Hi @evrifaessa  Thank you so much well explained.. It works..

**Comment by BenNottelling** [comment]
Great, I'm going to close this since it's fixed now.
@Beatdown032 Keep an eye out for a new release soon, it should have some bug fixes and security improvements. We don't have an exact date on it, but I'm hoping it'll be within the next week.
