### ISSUE TITLE
Link for the Website is not working

### ISSUE THREAD

**Issue by alenjohn05** [boxbilling/boxbilling#974]
### What happened?
Hi Everyone,

Hope all is well!

On our Box Billing site, we are getting an error response while clicking the website link down.

Is there anyone who has encountered the same issue?

### BoxBilling Version

Current Master Branch

### What version of PHP are you running?

7.4x

### Additional Notes

Additional notes

**Comment by evrifaessa** [comment]
If this is about #973, it'll be fixed with the merge. If you're talking about another place where the link doesn't work, please re-open this issue. Thanks for your contribution, welcome :)

**Comment by evrifaessa** [comment]
I see you edited your comment, okay. @alenjohn05 

Can you provide additional details? Like the error message?

**Comment by BenNottelling** [comment]
It would also be helpful to know what pages are causing the error message. Is it your entire site or just some specific parts of it?
Thanks

**Comment by BenNottelling** [comment]
@alenjohn05 Just trying to follow up here, what link isn't working?
What error message do you get? Thanks

**Comment by alenjohn05** [comment]
I got to see the website has been updated and it looks nice, and the error
has been resolved and I am happy to see that.

**Comment by evrifaessa** [comment]
Glad to see it's solved. Have a nice day :)
