### ISSUE TITLE
New website discussion thread

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#986]
Hello. I just pushed the new layout of [boxbilling.org](https://boxbilling.org). If you see any bugs or want me to add/change anything, please let me know.

**Comment by notbasetwo** [comment]
Site looks fine, Slack link is broken in footer - but that may be on purpose as there is no public invite link to the workspace.

There is a mention for a call for new contributors but there is a lack of help-wanted issues. Only a module for a niche, proprietary, Shoutcast/Icecast hosting software and a general "we need new contributors issue".

**Comment by evrifaessa** [comment]
> but that may be on purpose as there is no public invite link to the workspace.

Yeah. Let me try finding a link for you.

> I would avoid mentioning it if you don't have a clear entry point for new contributors.

Nice point. I'll see tomorrow what we can do about it.

**Comment by BenNottelling** [comment]
We should also be labeling issues that are good for beginners / first time contributors. 
We also need a working demo

**Comment by notbasetwo** [comment]
> We also need a working demo

You could be cheeky temporarily and use Softaculous' demo stuff. (https://www.softaculous.com/apps/ecommerce/BoxBilling)

**Comment by BenNottelling** [comment]
> You could be cheeky temporarily and use Softaculous' demo stuff. (https://www.softaculous.com/apps/ecommerce/BoxBilling)

I appreciate the suggestion, but we don't currently have a way to update the softaculous version of BB, so it would only work as a stop-gap solution. It's still on version 4.22.1 which is 5 years old which is a problem

**Comment by John-S4** [comment]
It's definitely a big improvement visually, and a nice start. 

There are a couple of things that are a bit odd, like the fact that the height of the carousel changes (and affects the text below it) as it flows through. 

I think the 'copyright' text at the bottom of the footer is too small, since it links to the license file it's pretty important - and the spacing down there is odd too, there's a huge margin below that at the bottom of the screen and not much space between it and the info above. 

I know that it's a bit of a work in progress @evrifaessa so not sure if you would prefer suggestions like this to just be added here or for people to jump into the middle of what you are doing with PRs.

**Comment by evrifaessa** [comment]
> I know that it's a bit of a work in progress @evrifaessa so not sure if you would prefer suggestions like this to just be added here or for people to jump into the middle of what you are doing with PRs.

You can directly create PRs. It's okay with me and it would save time. Thanks for your suggestions :).

**Comment by evrifaessa** [comment]
@John-S4 can you create a PR about the improvements you suggested? Thanks.

**Comment by John-S4** [comment]
@evrifaessa Yes, I will at some point in the near future. I was out sick for a little while and have been super busy with catching up with work this week.

**Comment by evrifaessa** [comment]
> @evrifaessa Yes, I will at some point in the near future. I was out sick for a little while and have been super busy with catching up with work this week.

@John-S4 pinging again, are you available now? thanks.

**Comment by evrifaessa** [comment]
> @evrifaessa I'll take a look tomorrow :)

@John-S4 hey

**Comment by evrifaessa** [comment]
Closed in favor of #1118.

**Comment by Neustradamus** [comment]
Good news about the website!

It was one of my requests a long time ago.

The demo is important.
