### ISSUE TITLE
Mobile app discussion thread

### ISSUE THREAD

**Issue by evrifaessa** [boxbilling/boxbilling#993]
This is a long-term task. Any idea about a potential mobile application is open for discussion under this thread.

**Comment by BenNottelling** [comment]
What purpose would a mobile app have?

**Comment by evrifaessa** [comment]
> What purpose would a mobile app have?

It would make system administrators' jobs easier. Today, many billing systems have mobile apps. I'm not saying that we have to build one, but it would not hurt to have one.

**Comment by notbasetwo** [comment]
I think this is way beyond the current scope of this project, work on a responsive web app first in my opinion.

**Comment by BenNottelling** [comment]
Many mobile apps these days ARE responsive web apps anyways. IMO, ensuring that the admin panel works well on mobile should be enough, anything else is going above and beyond for us

**Comment by notbasetwo** [comment]
> 
> 
> Many mobile apps these days ARE responsive web apps anyways. IMO, ensuring that the admin panel works well on mobile should be enough, anything else is going above and beyond for us

Hard agree. At a push, a responsive web app can be made in to a progressive web app for use as an "app".

**Comment by John-S4** [comment]
Agree with @BenNottelling and @notbasetwo . 

On a personal level as a user, I really prefer to have sites that work properly on mobile than being expected to download a different app for every site/service that I use.
